### ISSUE TITLE
Docker error - no such file or directory

### ISSUE THREAD

**Issue by defensivedepth** [codelibs/fess#1006]
Greetings,

I am trying to use the docker image, but am getting the following error on Win10, Docker 17.03.1

docker run -d -p 8080:8080 --name fess codelibs/fess:latest
Unable to find image 'codelibs/fess:latest' locally
latest: Pulling from codelibs/fess
<snip>
Digest: sha256:bcfc2bbbd593a03a241937a51a25f51ab4be1bbfec585e1eca15568e7094155e
Status: Downloaded newer image for codelibs/fess:latest
b03117c303eefe4ca1968162d211050f53f52ed038213c5a9ea8d0fbbc45b673
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"/opt/fess/bi
n/fess\": stat /opt/fess/bin/fess: no such file or directory".

**Comment by nullpos** [comment]
Hi,

I updated Docker Hub image. Please pull latest image again and try it.

**Comment by defensivedepth** [comment]
Works, thanks!
