### ISSUE TITLE
Disable cache?

### ISSUE THREAD

**Issue by defensivedepth** [codelibs/fess#1007]
Is there a way to disable caching of crawled pages? I am trying to reduce storage requirements for a project, and figured I can minimize storage requirements if I can disable the caching of images, etc.

**Comment by marevol** [comment]
The setting is in fess_config.properties.
To disable a page cache, set false to:

    crawler.document.cache.enabled=false

**Comment by defensivedepth** [comment]
Thanks, much appreciated!
