### ISSUE TITLE
Few questiones about Fess itself

### ISSUE THREAD

**Issue by llluuuyyy123** [codelibs/fess#1010]
Hi sorry to disturb,
I am a beginner user for Fess.I faced a few problem when I was using Fess. 

First:

After I add fess a new crawler website in admin mode.I couldn't get any results back when  I did the search.Do I need to change the default Crawler setting in the Job scheduler? Or i missed any steps when I added the new website in fess?

Second:

I am using the Elasticsearch which build in fess.Am I allow to query this Elasticsearch directly? Because some of the search results seem to different to my own loacl Elasticsearch.

Third:

If I add an external Elasticsearch in the Fess (So two Elasticsearch exist together). When I search one word . Would Fess search both of  ES for me?

Hope Someone can give me some advices thx..!

**Comment by marevol** [comment]
> After I add fess a new crawler website in admin mode.I couldn't get any results back when I did the search

Did you start Default Crawler after adding crawling config?
http://fess.codelibs.org/11.0/admin/scheduler-guide.html

>Am I allow to query this Elasticsearch directly? 

Embedded elasticsearch runs on 9201 port.

> Would Fess search both of ES for me?

If you setup external elasticsearch, embedded elasticsearch in Fess will be disabled. So, you can use only external elasticsearch.
http://fess.codelibs.org/11.0/install/install.html

**Comment by llluuuyyy123** [comment]
Thanks for your rapidly reply.

I did started my default crawler
![image](https://cloud.githubusercontent.com/assets/16218602/25473534/6c42eb08-2b62-11e7-827e-6661220a5181.png)
any ideas?

And I noted that my Fess Properties in System info /config info is happened some error

![image](https://cloud.githubusercontent.com/assets/16218602/25473913/e38be010-2b63-11e7-9f2a-3b512fcef04f.png)

any relative?

**Comment by marevol** [comment]
What are crawling configs?
http://fess.codelibs.org/11.0/admin/webconfig-guide.html
http://fess.codelibs.org/11.0/admin/fileconfig-guide.html

**Comment by llluuuyyy123** [comment]
thanks the problem solved.

One last question about the FESS_DICTIONARY_PATH
Because I am using External elasticsearch cluster after I set the FESS_DICTIONARY_PATH=/var/lib/elasticsearch/config/ in fess.in.sh 
I find out the Dictionary List didn't match with my real file
![image](https://cloud.githubusercontent.com/assets/16218602/25477701/0227428c-2b71-11e7-8125-8b36b26c6e86.png)

![image](https://cloud.githubusercontent.com/assets/16218602/25477744/2d011208-2b71-11e7-9b85-9e7a7adf4757.png)

and if Iset
These two: in  elasticsearch.yml
----------------------------------------------------------------------------------- 
configsync.config_path: /var/lib/elasticsearch/config/node_1
script.engine.groovy.inline.update: on
------------------------------------------------------------------------------------

the dictionary list option will run into an error
any ideas??

**Comment by marevol** [comment]
configsync.config_path: /var/lib/elasticsearch/config

See http://fess.codelibs.org/11.0/install/install.html
