### ISSUE TITLE
How to use fess to recreate index

### ISSUE THREAD

**Issue by ghost** [codelibs/fess#1011]
Hi I read some of the old post.
When I add some filters in my standard_analyzer at fess.json.

I saw some people said you need to  "re-create fess index" or "re-index your fess" then can work
These two is the same meaning??
I don't know how to "re-create fess index"

Or only mean these two processes at below?
1.Re-run Default Crawler.(I only see the sign from active to running)
2.If "Check Last Modified" is true, set it to false before starting crawler.

Please give me some exlaination thanks

**Comment by llluuuyyy123** [comment]
oh ! i am confuse too ! I think @marevol can answer you .
He is the best!

**Comment by marevol** [comment]
> When I add some filters in my standard_analyzer at fess.json.

fess.json is used at first startup time to create fess.yyyymmdd index.

> "re-create fess index" or "re-index your fess" 

They are different.

> 1.Re-run Default Crawler.(I only see the sign from active to running)
> 2.If "Check Last Modified" is true, set it to false before starting crawler.

The above is re-index.
If you want to update words on dictionaries, it's re-index.

To re-create index,
1. Delete fess.yyyymmdd index on dashboard
2. Stop Fess
3. Start Fess
4. A new fess.yyyymmdd index is created automatically

If you want to change analyzer settings, re-create is needed.

**Comment by CodingIsTheBEst** [comment]
thanks for your explicit answers!
You are the man!!!!

**Comment by CodingIsTheBEst** [comment]
Here is another question .
How do I set the crawler data store location to which index?
I want to check the store index because after I do the recreate and re-index, I check the data in my 9201 port at default crawler, I didnt see any data and when I do the search in search bar I  didnt get any searchresult.
Should I do anything beside the re-index??

thx man

**Comment by marevol** [comment]
To check index settings/mappings, see [Dashboad](http://fess.codelibs.org/11.0/admin/dashboard-guide.html).
To check indexed data, see [Admin Search](http://fess.codelibs.org/11.0/admin/searchlist-guide.html).
