### ISSUE TITLE
hash tag 

### ISSUE THREAD

**Issue by MajidSafari** [codelibs/fess#1046]
Fess support hash tag  search? like #news

**Comment by marevol** [comment]
Fess Crawler removes a hash from URL because the content specified by the hash is in a page.
If not ignoring a hash, many duplicated pages will be crawled.

**Comment by MajidSafari** [comment]
that right ,

i say , when search #fess   if in  content #fess exist show in result search ,

now Fess Crawler must every word start by # , index 

so each page some tags , ["#new","#teramp","#usa"]

**Comment by marevol** [comment]
For specific requirement, it's better to add a new field to search it(ex. tags)

To add the new field, 
1) Add mapping to fess/doc.json before setting up Fess
      "tags": {
        "type": "keyword"
      }
2) Add extracting rule to crawler/transformer.xml
                <postConstruct name="addFieldRule">
                        <arg>"tags"</arg>
                        <arg>"...XPath..."</arg>
                </postConstruct>
3) Add it to search fields
query.additional.search.fields=tags
