### ISSUE TITLE
how get LABEL count in json

### ISSUE THREAD

**Issue by MajidSafari** [codelibs/fess#1047]
how get LABEL count result in json result

**Comment by marevol** [comment]
Use facet.field:

     curl "https://search.n2sm.co.jp/json/search/?q=fess&facet.field=label"

facet_field is returned in the response.

**Comment by MajidSafari** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/5099564/25650364/9be16aae-2ff1-11e7-8be9-5b6fadc372e3.png)

**Comment by MajidSafari** [comment]
tanx
