### ISSUE TITLE
Admin API Crawler in Fess 11.1.0

### ISSUE THREAD

**Issue by lethanh603Imlv** [codelibs/fess#1057]
How to create crawler using admin/api in Fess 11.1.0 ?

**Comment by marevol** [comment]
Admin API will be supported in Fess 11.2.

**Comment by lethanh603Imlv** [comment]
hi marevol!

I find api  POST /api/admin/scheduler/{id}/start in source fess.
I was test in postman
http://localhost:8080/api/admin/scheduler/AVxcLXDv_AawDJ2XLzjz/start
and receive response 
{
  "response": {
    "message": "Unauthorized request.",
    "version": "11.2",
    "status": 3
  }
}

Can i use it to start Crawler ?

**Comment by lethanh603Imlv** [comment]
Thanhk you very much.
i will test Admin APIs
I am very expect Fess version 11.2

**Comment by lethanh603Imlv** [comment]
Hi marevol
I tested admin api in the fess 11.2. It worked well.
When will the fess 11.2 be published?

**Comment by marevol** [comment]
I'd like to release it this week...

**Comment by lethanh603Imlv** [comment]
thank you very much.

**Comment by lethanh603Imlv** [comment]
Hi marevol!
i am try get count filetype in api Json search, but i can get count filetype in 1 page.
Example: 
Word - 4
Excel - 3
....
can i count all records by file type in all page?

**Comment by marevol** [comment]
Need more details...

**Comment by lethanh603Imlv** [comment]
Ex:
http://localhost:8080/json/?q=fess&num=20&sort=
	"page_size": 20,
		"page_number": 1,
		"record_count": 44,
		"page_count": 3,
                 ......
page 1 has 5 file word and 2 file excel
page 2 has 6 file word and 1 file excel
page 3 has 1 file word and 3 file excel
i want display sum FILE TYPE
word: 12
excel: 6

**Comment by marevol** [comment]
Try:
```
$ curl "https://search.n2sm.co.jp/json/?q=fess&facet.field=filetype"
...
    "facet_field": [
      {
        "name": "filetype",
        "result": [
          {
            "value": "txt",
            "count": 9
          },
          {
            "value": "pdf",
            "count": 19
          },
          {
            "value": "html",
            "count": 17910
          },
          {
            "value": "others",
            "count": 310
          }
        ]
      }
    ],
...
```

**Comment by lethanh603Imlv** [comment]
thank you very much.

**Comment by lethanh603Imlv** [comment]
hi marevol
i am using fess version 11.2.1
Was labels.search_click_count supported by JSON-response?
