### ISSUE TITLE
GitBucketDataStore: Don't store too large files

### ISSUE THREAD

**Issue by kw-udon** [codelibs/fess#1065]
If a file is larger than 10MB, `org.codelibs.fess.crawler.exception.MaxLengthExceededException` occurs. 

---
Reported by @shiena. ([ref](https://gist.github.com/shiena/9c1a363cda664fc38102e766a67e1b4e))

**Comment by MajidSafari** [comment]
The setting is in app/WEB-INF/classes/crawler/contentLength.xml.

`<property name="defaultMaxLength">10485760</property><!-- 10M -->`

**Comment by kw-udon** [comment]
@MajidSafari Thanks!
