### ISSUE TITLE
Crawling through proxy

### ISSUE THREAD

**Issue by AlexKrivbass** [codelibs/fess#1066]
How can I set the properties for crawling through proxy with basic auth (user:pass)?

**Comment by marevol** [comment]
Could you put the following settings to Config Parameters for Crawling Config?

```
client.proxyHost=hostname
client.proxyPort=1234
client.proxyUsername=username
client.proxyPassword=password
```

http://fess.codelibs.org/11.1/admin/webconfig-guide.html#config-parameters
