### ISSUE TITLE
Documents can't be found in search after several crawls (Question)

### ISSUE THREAD

**Issue by crpgbogor** [codelibs/fess#1069]
I used to be able to find documents using certain queries (X) after some crawls. After a few days and several other crawls, when I insert X, I can no longer find the documents. Will setting remove documents before x-days in "general" tab to -1 help with this issue?

**Comment by marevol** [comment]
> Will setting remove documents before x-days in "general" tab to -1 help with this issue?

Yes, and then re-indexing is needed.

**Comment by crpgbogor** [comment]
Thanks! Would that mean that I need to delete existing indexes first and then start again?

**Comment by marevol** [comment]
To delete docs and start crawler:
1) Type \*:\* on [Search List](http://fess.codelibs.org/11.1/admin/searchlist-guide.html)
2) Click Delete All button
3) Start Crawler on [Scheduler](http://fess.codelibs.org/11.1/admin/scheduler-guide.html)

**Comment by crpgbogor** [comment]
I see..... Just realize that the search list can do this. Very cool! Thanks!
