### ISSUE TITLE
Huge difference between "docs" and "indexed"

### ISSUE THREAD

**Issue by pcolmer** [codelibs/fess#1072]
![image](https://cloud.githubusercontent.com/assets/1979931/26487333/01e17490-41f7-11e7-9e5f-a8feda9b2f5d.png)

Is it normal for there to be such a massive difference between the number of docs (2,744,050 in the screenshot) and the number of indexed files (11,532)?

**Comment by marevol** [comment]
Select "special" checkbox.

**Comment by pcolmer** [comment]
Thank you for this suggestion.

Can you please explain where I can find this checkbox, and what it does? I've searched the documentation and cannot find a mention of it, and I cannot find the checkbox in the web UI.

**Comment by crpgbogor** [comment]
You need to tick the special button marked with asteriks (*), just above the fess.suggest crawler on your screenshot. I also experience this, I don't know if this is normal or not. Currently testing it manually. See also https://github.com/codelibs/fess/issues/673
