### ISSUE TITLE
Crawling debug

### ISSUE THREAD

**Issue by clauded** [codelibs/fess#1073]
Is there a way to have a detailed log of crawling : I'm trying to index a site and tried http://www.mysite.org/.* as well as http://www.mysite.org.* as indexing url but nothing gets indexed (it's a sharepoint site with no robots.txt). 

Note. the actual log file does not help.

**Comment by marevol** [comment]
To change a log level for Crawler, open "Default Crawler" setting on [Scheduler](http://fess.codelibs.org/11.1/admin/scheduler-guide.html) and change .logLevel("info") to .logLevel("debug") in Script.

**Comment by clauded** [comment]
Thanks for the info.
