### ISSUE TITLE
can replace crawling result of 'title' and 'content' fields (with regexp)?

### ISSUE THREAD

**Issue by corselia** [codelibs/fess#1096]
`Fess` is very sexy product, thank you.

by the way, two fields `title` and `content` can be replaced to any word?
because some websites have prefix in `title` and/or `content`.

for example below.

- `<title>NICE TEA SHOP - Lipton</title>`
- `<title>NICE TEA SHOP - Twining</title>`
- `<title>NICE TEA SHOP - Tetley</title>`
- `<title>NICE TEA SHOP - Typhoo</title>`
- `<title>NICE TEA SHOP - Yorkshire Tea</title>`

I wanna remove prefix `NICE TEA SHOP - `.
is it available?

sincerely

**Comment by marevol** [comment]
No.
It will be support in the next release.

**Comment by marevol** [comment]
In Fess 11.2, you can put script settings in [Config Parameters](http://fess.codelibs.org/11.2/admin/webconfig-guide.html#config-parameters).
```
field.value.title=
field.script.title=context.doc.remove("title");title.replace("NICE TEA SHOP - ", "")
```

**Comment by corselia** [comment]
@marevol 
thanks for well answer and great solution!
I expect next release!
