### ISSUE TITLE
how to config language for FESS,

### ISSUE THREAD

**Issue by chuqingsheng** [codelibs/fess#1129]
I have translate the fess_label_en.properties and fess_message_en.properties .put into classes directory. but how to config fess to using the language? please help me

**Comment by marevol** [comment]
Could you try to restart Fess and then access http://localhost:9200/admin/?browser_lang=<YOUR_LANG>(or remove cookies on your browser)?

**Comment by chuqingsheng** [comment]
thank you very much. It is OK. 

I see FESS has user ,role and group function, How to use those function?

**Comment by marevol** [comment]
Fess support Secure Search to display search results matching each user’s permissions.
You can set permissions at crawling settings.
