### ISSUE TITLE
Which version of the SMB protocol suppoted?

### ISSUE THREAD

**Issue by keisinm** [codelibs/fess#1133]
When I try to use it to file server with SMB 1.0 disabled, crawling failed and just logged "could not access".
But change the server setting to SMB 1.0 enabled, it works. 
It is not support SMB 2.0 or is any optional setting required?

**Comment by marevol** [comment]
SMB 2/3 is not supported because jcifs supports only SMB 1.
In the future release, Fess will support it.

**Comment by keisinm** [comment]
Thank you for reply. 
I try to change the settings to SMB 1.
