### ISSUE TITLE
Question : Can I inject the config file into my docker images without having to import them through the GUI.

### ISSUE THREAD

**Issue by acossette1979** [codelibs/fess#1150]
Question : Can I inject the config file into my docker images without having to import them through the GUI.

**Comment by marevol** [comment]
There is no solution at the moment...
We will modify docker-fess.

**Comment by acossette1979** [comment]
If you are considering this are you gonna plan a command line tool to backup and restore the bulk file, or will we be able to inject them directly into a config folder ?

**Comment by marevol** [comment]
It may be to mount /etc/fess to a local directly...

**Comment by acossette1979** [comment]
Do you have an ETA when it will be available ?

**Comment by nullpos** [comment]
Hi @acossette1979 .
I updated docker images. Please update and try these.

Bulk files are saved on Elasticsearch.
If you want to save bulk files, to mount `/var/lib/elasticsearch` to local folder is the simplest way I think.
example:
`$ docker run -d -p 8080:8080 -v $(pwd)/esdata:/var/lib/elasticsearch codelibs/fess:latest`
make sure esdata directory is already created and `owner:group` ID is `1000:1000` (same as elasticsearch user ID in the container).

Config files are on file system.
Q. Can I inject the config file into my docker images without having to import them through the GUI.
A. The one way is using -v option when you run container. 
example:
`$ docker run -d -p 8080:8080 -v /path/to/config/file:/etc/elasticsearch/elasticsearch.yml -v /path/to/config/dir:/etc/fess codelibs/fess:latest`
The other way is clone codelibs/docker-fess repository and create/customize config files.
You can also use `docker cp` command.

**Comment by acossette1979** [comment]
Is it new that config file are in ES. (list below)

Name
.fess_basic_config.bulk
.fess_config.bulk
.fess_user.bulk
system.properties
click_log.csv
favorite_log.csv
search_log.csv
search_field_log.csv
user_info.csv

**Comment by marevol** [comment]
> .fess_config.bulk
> .fess_user.bulk

are in ES.

> system.properties

is in /etc/fess.

> click_log.csv
> favorite_log.csv
> search_log.csv
> search_field_log.csv
> user_info.csv

are search logs in ES.

**Comment by acossette1979** [comment]
But how do I insert it on the first initial load ?

**Comment by fbonin** [comment]
Hi,
I have the same question, I was able to modify the config files but the ones that are in Elastic Search are not loaded during the initial installation. I need to upload them manually through the UI.

Is there a way to make them load when the application starts ?

Regards,
Fred

**Comment by nunofernandes** [comment]
Any idea if we will have the possibility of (using the command line or some other mean) insert Crawling targets?
