### ISSUE TITLE
generate thumbnail not working for file system crawling

### ISSUE THREAD

**Issue by freestyle68** [codelibs/fess#1156]
Fess 11.2.1
Debian 9
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)

Hi,

with Debian 9/8/Ubuntu, generate thumbnail always returns 0 results with file system crawling.
Instead working with web crawling.

Installed:
unoconv xpdf imagemagick fonts-vlgothic libreoffice-common phantomjs

The commandline
_unoconv_
and
_convert_ 
are working.

Also tried enabling Crawler Job but same results.

How can I debug this problem?

Thank you

**Comment by marevol** [comment]
Could you check if the following command works?
```
/usr/share/fess/bin/generate-thumbnail msoffice <MS Office file> <Output Path> 
```

**Comment by freestyle68** [comment]
yes, it generate a low-res multipage pdf.
Tried with .doc, .ppt and .pdf.

**Comment by freestyle68** [comment]
This is not an OS issue, because the same happens with Centos or Doker images (latest tag).

With Centos I installed this:

bzip2 fontconfig freetype freetype-devel fontconfig-devel libstdc++ unoconv libreoffice-headless vlgothic-fonts ImageMagick

**Comment by marevol** [comment]
I'll check and fix it in next release...
