### ISSUE TITLE
How to enable ssl/https (question) 

### ISSUE THREAD

**Issue by crpgbogor** [codelibs/fess#1162]
Hi, how can we enable ssl/https? I red somewhere in the docs that we can enable port 8443 in the conf/server.xml. But, where can we deploy our ssl cert? Thanks!

**Comment by marevol** [comment]
We expect to use Web server, such as Apache, as a reverse proxy to enable ssl.

**Comment by robinComa** [comment]
Hello all, 
I want an end to end security between FESS and elasticsearch.
So the reverse proxy solution is not good for my case.
Have you got a solution?
Do you plan something for next release? 
Thanks,

**Comment by marevol** [comment]
This issue also described a communication between users and Fess.

For Fess<->Elasticsearch and Elasticsearch<->Elasticsearch, I think that it's better to use a closed internal network/devices.
If you need to use SSL/TLS, a solution may be [X-Pack](https://www.elastic.co/guide/en/x-pack/current/ssl-tls.html).

**Comment by robinComa** [comment]
Thanks for answer.
My Elasticsearch cluster is already SSL secured. Now I need to configure FESS to connect to it, but I don't see the SSL settings (certificates, etc...) in FESS. Any idea?

**Comment by marevol** [comment]
TransportClient in Fess may be able to configure SSL/TLS setting, but I cannot try it...

I think that a simple way is: (installing Fess and Elasticserch into the same server)
```
Fess(Host1)<-local(plain)->Elasticsearch(Host1)<-tls->Elasticsearch Cluster(Others)
```
I'm not sure that x-pack uses http/transport with/without ssl/tls at the same time...

**Comment by robinComa** [comment]
Ok, if I fork the project and I find a solution, could I offer a pull request?

**Comment by marevol** [comment]
Of course, any contributions are welcome!

**Comment by Dave-c-Ross** [comment]
Hi @robinComa I'm realy interested about this feature, did you find a way to use an Elastic cluster with X-Pack/SSL and FESS ?

**Comment by acossette1979** [comment]
We have request the commercial version to create a version to support xpack but it is not working with SSL/TLS on the ES transport. I'm looking into it now. @robinComa

**Comment by robinComa** [comment]
Hello @Dave-c-Ross and @acossette1979 
We achieve it on our private repository.
I will do a PR to the official repo next week.
@marevol , Will you be able to merge it if the code is ok?

**Comment by marevol** [comment]
Any PR is welcome, but for dependencies to X-Pack, we will be not able to merge it. X-Pack is not OSS...

**Comment by acossette1979** [comment]
nice perfect.
Thank you very much.

**Comment by robinComa** [comment]
Hello @marevol I propose this PR : 
[https://github.com/codelibs/fess/pull/1610](https://github.com/codelibs/fess/pull/1610)
What do you think about it?

Hope this is your point @acossette1979

**Comment by marevol** [comment]
I removed modifications for CurlHelper because it's supported in fess-xpack.
For X-Pack support with SSL, see https://github.com/codelibs/fess-xpack.
