### ISSUE TITLE
how suggest filter by label

### ISSUE THREAD

**Issue by MajidSafari** [codelibs/fess#1167]
how suggest filter by label ??

suggest?callback=jQuery32108189480920118195_1500216327643&query=fess&fields=_default%2Ctitle&num=20&lang=&_=1500216327644

**Comment by marevol** [comment]
It will be supported in next release.

**Comment by kledung** [comment]
Hi!
I'm trying to filter suggestions based on label but I can't get it to work. 
I'm trying with this url /suggest?query=fre&num=5&fields.label=personal

How is the url supposed to be in order to filter by label?

Best regards
Kristian
