### ISSUE TITLE
How to use System->Access Token->Parameter Name

### ISSUE THREAD

**Issue by rdaemen** [codelibs/fess#1170]
Hi,

Created an access token with "role"-permission for selective search results.
How to use the "Parameter name" (defined as at) in e.g. the javascript example:

    <script>
      (function() {
        var fess = document.createElement('script');
        fess.type = 'text/javascript';
        fess.async = true;
        fess.src = '//<server>/js/ss/fess-ss.min.js';
        fess.charset = 'utf-8';
        fess.setAttribute('id', 'fess-ss');
        fess.setAttribute('at', '<access token>');
        fess.setAttribute('fess-url', '//<server>/json');
        fess.
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(fess, s);
      })();
    </script>
    <fess:search></fess:search>

**Comment by marevol** [comment]
[Parameter Name](http://fess.codelibs.org/11.2/admin/accesstoken-guide.html#parameter-name) is not for passing Access Token.
Fess Site Search script does not support Authorization header at the moment...
It will be supported in next release.
