### ISSUE TITLE
Boosting URL?

### ISSUE THREAD

**Issue by enesser** [codelibs/fess#1171]
I'd like to boost a search result if the query is found in the URL field of the document. I can't seem to get that to work. Fess doesn't seem to search the URL field at all.

Here's what I have in `fess_config.properties`:

```
query.additional.search.fields=url

query.boost.url=0.8
```

In fact, after changing `fess_config.properties`, I'm not sure Fess is indexing documents after a manual request and there's nothing in the error logs.

Any help would be greatly appreciated. Thanks!!

**Comment by marevol** [comment]
url field is searchable one by default.
query.boost.* other than title/content does not exist.
To boost url field, it's like url:"..."^10.
See [Boost Search](http://fess.codelibs.org/11.2/user/search-boost.html).

**Comment by enesser** [comment]
Ah, okay. Thanks. Should I be querying Elastic directly or does Fess' REST API support this somehow? I have tried this and it doesn't seem to work:

```
http://localhost:8080/json/?q=url%3Avalue&num=20&sort=
```

The default search query does not appear to pick up values in URL in the latest release.

**Comment by marevol** [comment]
Fess supports it, and url field is not analyzed field.
Use a wildcard query, such as
```
$ curl "http://search.n2sm.co.jp/json/?q=url%3A%22http%3A%2F%2Ffess.codelibs.org%2F*%22"
```

**Comment by enesser** [comment]
Worked! Thank you so much for your help.
