### ISSUE TITLE
index social network

### ISSUE THREAD

**Issue by nacimgoura** [codelibs/fess#1174]
Hello,
I think this project is really very successful.
I think it would be a good idea to be able to index social networks. For example if I want to index my twitter account, I give my id and I retrieve all the tweets using the official API or not. It will be able to search on the tweets afterwards.
What do you think ?

**Comment by marevol** [comment]
Fess provides [DataStore](http://fess.codelibs.org/11.2/admin/dataconfig-guide.html) to access external data stores.
If creating DataStore class, such as [GitBucketDataStoreImpl](https://github.com/codelibs/fess/blob/master/src/main/java/org/codelibs/fess/ds/impl/GitBucketDataStoreImpl.java), you can index/search documents on other systems.

**Comment by nacimgoura** [comment]
Thank you for your reply!
