### ISSUE TITLE
Thumbnails for images

### ISSUE THREAD

**Issue by freestyle68** [codelibs/fess#1182]
Hi,

I added several other image formats to be thumbnailed.

The added formats are the following:

eps (application/postscript), bmp (image/bmp, image/x-ms-bmp, image/x-windows-bmp), gif (image/gif), png (image/png), ps (application/postscript), psd (image/vnd.adobe.photoshop, image/photoshop, application/x-photoshop, application/photoshop), tiff (image/tiff), jpeg (image/jpeg).

I attach the two modified files

fess_thumbnail.xml
crawler_thumbnail.xml

The images need a single pass to be thumbnaillized, so I inserted under the pdf queue.

Tested for several formats (also multipage tiff) and no problem, except for some ps that give the error:

Error: /rangecheck in --colorimage--

caused by ghostscript.

Please see you if it is the case to add also some formats to app.xml, at least jpeg, as there are a lot of formats (png, bmp, tiff, ...) but this very used is missing.

Thank again

[file added.zip](https://github.com/codelibs/fess/files/1168205/file.added.zip)

**Comment by marevol** [comment]
Thank you for checking them.
I'll add it.
