### ISSUE TITLE
How to use the faceted filter in the json api?

### ISSUE THREAD

**Issue by luisarn** [codelibs/fess#1191]
Hi marevol san,

I would like to retrieve only the HTML file type of the indexed data on the json API. How does the query string looks like?

I'm trying something like this but doesn't work:
?q=somekeyword&facet.field=filetype:[html]

Thanks in advance,
Luís

**Comment by marevol** [comment]
How about using facet.query?
```
curl -XPOST "https://search.n2sm.co.jp/json/?q=fess&facet.query=filetype:html"
```
