### ISSUE TITLE
Avoid Download File in Temp Folder and Open File directly from source server ?

### ISSUE THREAD

**Issue by mon-routeur** [codelibs/fess#1195]
I try to open file directly on IE, i add my server url into "Secured Site" on IE and he refused to open it from source server, the file is donwloaded into temp file and open.
I see the href link is `http://MY_URL/go/?rt=1501163584656&docId=8d0d658da70f4b7a976b50a1e012b73a&queryId=c1ba1c8ef8d641fea8898f73a26bc613&order=2`
And not `file://MY_SERVER/service informatique/gesdoc2/tmp/gardes/Pages-de-Garde-241116-1p.pdf`

How can change this for open file directly from Source Server and avoid download the file in temp folder.

**Comment by marevol** [comment]
To disable Content Proxy, please add search.file.proxy=false to system.properites.

**Comment by mon-routeur** [comment]
I add search.file.proxy=false to system.properties and but not work. He try to open a smb:// link and IE accept only file:// url like SearchDaimon : http://www.searchdaimon.com/documentation/opening_files_from_network_shares_in_firefox/

**Comment by marevol** [comment]
You need to use [Path Mapping](http://fess.codelibs.org/11.2/admin/pathmap-guide.html) to replace smb: with file:.
In this case, View process type is proper.

**Comment by freestyle68** [comment]
Tried with:

Regexp.:	   smb:
Replacement:  file:
Process Type:  Displaying

and it works only with namefiles without spaces.

With spaces the path is translated as

\\win2012\share\name+file.pdf

and I get the error

This page can’t be displayed

Tested with IE 11.

**Comment by freestyle68** [comment]
The problem is solved adding also this path mapping:

```
Regexp.:      \u0020
Replacement:  %20
Process Type: Displaying
```
