### ISSUE TITLE
How get all files by JSON API ?

### ISSUE THREAD

**Issue by boyoyon8** [codelibs/fess#1209]
Is there a way to get "all the results" from the JSON API?

"all the result" are same data as Search results with keyword "\*:\*" on  Administration Search page.
http://fess.codelibs.org/11.2/admin/searchlist-guide.html

**Comment by marevol** [comment]
Try `*`. 
`*` is a match all query.

**Comment by boyoyon8** [comment]
Oh great, Thanks!
