### ISSUE TITLE
In future, administration API Supports ?

### ISSUE THREAD

**Issue by boyoyon8** [codelibs/fess#1210]
In future, administration API Supports ?
I want to manage via API not just searches.

plz consider. :smiley:

**Comment by marevol** [comment]
Fess 11.2 supports Admin API, but there is no public documents at the moment...
FYI: https://github.com/codelibs/fess/issues/1057#issuecomment-305186767

**Comment by boyoyon8** [comment]
Oh my goodness! :sob: 
i hope documented  as soon as possible.... Thanks!

**Comment by boyoyon8** [comment]
sorry, one more question @marevol
Is there a way to create access token via Admin API ?
only create on Access Token page ?

**Comment by marevol** [comment]
> Is there a way to create access token via Admin API ?

Yes.

**Comment by boyoyon8** [comment]
> Is there a way to create access token via Admin API ?
>>Yes.

How do you do that?

**Comment by boyoyon8** [comment]
Sorry, that was self resolved.
thanks for support !
