### ISSUE TITLE
How to get favorite count in fess?

### ISSUE THREAD

**Issue by vanghtc** [codelibs/fess#1212]
Hello marevol,
I am using Fess  version 11.2.1
I want to get favorite_count of each file.
This version have been supported for it?
What should i do to resolve it?
Please help me.

**Comment by marevol** [comment]
Is it https://github.com/codelibs/fess/issues/805#issuecomment-320965906 ?

**Comment by vanghtc** [comment]
Thanks for your answer.
But in my app, I not use original value of "url_link" and it not working.
So can i get it when I change value of  "url_link"?
Or have any Api to update value of favorite count ?

**Comment by marevol** [comment]
I could not understand your problem... need more info...
