### ISSUE TITLE
Possibility to create index per Domain?

### ISSUE THREAD

**Issue by remoblaser** [codelibs/fess#1215]
Hey there!

I'd like to use fess as a crawler for elasticsearch, thus crawling multiple domains. Is there a possibility to tell a Web Crawler in which ES index the data should be saved? e.g. Web crawler for google.com saves Data in index  "google" instead of fess.<date>

**Comment by marevol** [comment]
Index locations in fess_config.properties are as below:
```
index.document.search.index=fess.search
index.document.update.index=fess.update
index.document.suggest.index=fess
index.document.crawler.index=.crawler
index.config.index=.fess_config
index.user.index=.fess_user
index.log.index=fess_log
```

**Comment by remoblaser** [comment]
But i guess i cannot define a seperate index per web crawler?

**Comment by marevol** [comment]
It's to better to launch multiple Fess instances.
If you want to start standalone Fess Crawler, read [CrawlJob](https://github.com/codelibs/fess/blob/master/src/main/java/org/codelibs/fess/job/CrawlJob.java).

**Comment by remoblaser** [comment]
Aight, thank you marevol!
