### ISSUE TITLE
how to use the Admin API without accessing the administration page?

### ISSUE THREAD

**Issue by boyoyon8** [codelibs/fess#1217]
Now, Admin API can not use without an access token. This is also the same as "Access Token Creation API(PUT /admin/api/accesstoken/setting)".
In other words, the first creation of an access token must be done via the administration page?

how to use the Admin API without accessing the administration page ?

**Comment by marevol** [comment]
What do you want to do??
I would like to know the purpose to do that... need more info...

**Comment by boyoyon8** [comment]
Thanks reply.

I would like to set up and run Fess crawl from other systems.
For that, need to get a token from administration page. 
However, if I could get the first token via API, I can automation more process by the program.

**Comment by marevol** [comment]
Admin API cannot be accessed without a token to avoid any security issues.
I think you have 2 solutions:
- Create access_token.bulk to app/WEB-INF/classes/fess_indices/.fess_config before first Fess startup. Tokens will be inserted from access_token.bulk on startup.

or
- Access to elasticsearch directly.

**Comment by boyoyon8** [comment]
> Create access_token.bulk to app/WEB-INF/classes/fess_indices/.fess_config before first Fess startup. > Tokens will be inserted from access_token.bulk on startup.
thanks, I try it.

**Comment by boyoyon8** [comment]
sorry, plz tell me how to write access_token.bulk....

**Comment by marevol** [comment]
See [Elasticsearch Bulk API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html).

**Comment by boyoyon8** [comment]
OK, thanks for many supports !!
