### ISSUE TITLE
Java error when searching using GSA API.

### ISSUE THREAD

**Issue by jdeathe** [codelibs/fess#1222]
I'm not sure of the exact steps to reproduce this issue but in 11.2.2 - if I do a search using the `/gsa/?q={search_query}` URI with any query I expect 1 result for I get the message `java.lang.Double cannot be cast to java.lang.String`.

Using the json API works as expected.

**Comment by marevol** [comment]
I'm not sure, but I fixed in #1223 in order to avoid a cast problem.

**Comment by jdeathe** [comment]
Thank you! I will give 11.3 a go :)
