### ISSUE TITLE
GSA API's XML results (R) items incomplete

### ISSUE THREAD

**Issue by jdeathe** [codelibs/fess#1225]
Fess 11.3

REF: https://www.google.com/support/enterprise/static/gsa/docs/admin/70/gsa_doc_set/xml_reference/results_format.html#1079005

> **R**
> Format/Parent: RES
> Subtags: CRAWLDATE, FS?, HAS, HN?, LANG, MT*, RK, S?, T?, U, UD, UE
> Definition: Encapsulates the details of an individual search result.

Only the `HAS` subtag is included in results; missing `T` (title), `U` (url), `S` (summary), etc.

**Comment by marevol** [comment]
Could you try to modify the following settings to fess_config.properties?
```
query.additional.api.response.fields=T,U,S
```

**Comment by jdeathe** [comment]
@marevol - Thanks! That works as expected now. 

I edited `/etc/fess/fess_config.properties` on my CentOS-7 host. 

Does this get included in any of the configuration files that can be backed up and imported or does it have to be made to the host at install time?

**Comment by marevol** [comment]
> does it have to be made to the host at install time?

Yes. fess_config.properties is not included in backup process.
You need to modify fess_config.properties at install/upgrade time.
