### ISSUE TITLE
How to delete searchList by label

### ISSUE THREAD

**Issue by lethanh603Imlv** [codelibs/fess#1233]
Hi marevol
i was setting label for File system
i want delete data by label
can i use api /api/admin/searchlist/query for delete listsearch by label ?
how i do that ?
thanks you!

**Comment by marevol** [comment]
```
curl -XDELETE -H "Authorization: ...TOKEN..." http://localhost:8080/api/admin/searchlist/query -d '{"q":"label:test"}'
```
