### ISSUE TITLE
Search UI not populating LABEL filter list

### ISSUE THREAD

**Issue by jdeathe** [codelibs/fess#1234]
In Fess 11.3 the search results UI, (e.g. `/search/?q=fess&num=20&sort=`), no longer populates the LABEL list to allow filtering of results. 

The search query works correctly when including the URL parameter `fields.label=<label>` but there's no list of available label filter links.

**Comment by marevol** [comment]
Need more info...
https://search.n2sm.co.jp/search/?q=fess&num=20&sort= works.

**Comment by jdeathe** [comment]
After reducing the number of labels for a test case it worked okay. If I find out how to replicate it I will re-open this but I've removed access to the front-end search UI now anyway.
