### ISSUE TITLE
question regarding SPNEGO/kerberos

### ISSUE THREAD

**Issue by eimperat** [codelibs/fess#1237]
is it possible to use Spnego/kerberos ticket to crawl websites which I have access to?
currently unable to crawl some internal pages even if supplying username/password with the Web Authentication tool provided

**Comment by marevol** [comment]
Not supported.
Fess supports a web page for BASIC/DIGEST/NTLM/FORM authentication.

**Comment by eimperat** [comment]
okay. i noticed that /src/main/java/org/codelibs/fess/mylasta/direction/FessConfig.java has variables for spnego, is it worth trying to modify these and rebuild the project?

**Comment by marevol** [comment]
Fess uses SPNEGO to login to Fess with SSO, not for crawling web sites.
