### ISSUE TITLE
TesseractOCRParser support

### ISSUE THREAD

**Issue by marevol** [codelibs/fess#1238]

**Comment by freestyle68** [comment]
still not working.
My config:

`config.tika.tesseract.config=/usr/share/fess/TesseractOCRConfig.properties
`
and the config is:

```
# Tesseract properties
tesseractPath=/usr/bin/tesseract
language=eng
pageSegMode=1
extractAcroFormContent=true
useNonSequentialParser=false
extractAnnotationText=true
sortByPosition=false
extractUniqueInlineImagesOnly=true
enableAutospace=true
maxFileSizeToOcr=2147483647
minFileSizeToOcr=0
timeout=30
suppressDuplicateOverlappingText=false
#txt or hocr
outputType=txt
preserveInterwordSpacing=false

# properties for image processing
# to enable processing, set enableImageProcessing to 1
enableImageProcessing=1
ImageMagickPath=/usr/bin/convert
density=300
depth=4
colorspace=rgb
filter=triangle
resize=200
```
Nothing strange from log folder.
Please notice that Tika has another config file for pdf, [PDFParser.properties](https://github.com/apache/tika/blob/master/tika-parsers/src/main/resources/org/apache/tika/parser/pdf/PDFParser.properties), that need to be defined on Config Parameters.

Tried with fess-11.4.0-SNAPSHOT.deb and fess-12.0.0-SNAPSHOT.deb.

Thank you

**Comment by marevol** [comment]
We are still working on this issue.

For PDF, Fess does not use Tika to parse it as default.
To use Tika, modify [extractor.xml](https://github.com/codelibs/fess-crawler/blob/fess-crawler-parent-1.4.0/fess-crawler-lasta/src/main/resources/crawler/extractor.xml#L65).

**Comment by marevol** [comment]
11.4.x branch has supported TesseractOCRParser.

**Comment by freestyle68** [comment]
thank you, it works as expected. 
With the config above I can enable/disable ocr per crawler. Default is enabled with tesseract.

**Comment by nam-np** [comment]
Hi, 
I config follow: 
https://news.mynavi.jp/itsearch/article/devsoft/4928

But with PDF, it is not works. Have any update or suggestion, please tell to me.

Thank you.
