### ISSUE TITLE
Some pages show "Redirect to URL" and aren't being indexed

### ISSUE THREAD

**Issue by efridge** [codelibs/fess#1239]
When l look at the fess-crawler.log, I see some pages being indexed correctly with log entries like this:

```
2017-08-22 00:33:41,837 [Crawler-AVvTqFCtri8ZxKbEyVQo-1-9] INFO  Crawling URL: http://uwf.edu/offices/international-affairs/student-involvement/
```
Other pages are being crawled, but immediately have an entry below them with the entry "Redirect to URL", like this:
```
2017-08-22 00:50:25,980 [Crawler-AVvTqFCtri8ZxKbEyVQo-1-9] INFO  Crawling URL: http://uwf.edu/ceps
2017-08-22 00:50:25,983 [Crawler-AVvTqFCtri8ZxKbEyVQo-1-9] INFO  Redirect to URL: http://uwf.edu/ceps
```
I've noticed that the second page isn't being indexed at all.  I've checked the page and I don't see a redirect HTTP code being returned.  I'm curious what this second "Redirect" entry means, and if that has anything to do with it not being indexed.  Thanks!

**Comment by marevol** [comment]
The url is redirected.
```
$ curl -I http://uwf.edu/ceps
HTTP/1.1 301 Moved Permanently
Content-Length: 143
Content-Type: text/html; charset=UTF-8
Location: http://uwf.edu/ceps/
X-Powered-By: ASP.NET
Server: Apache
Date: Tue, 22 Aug 2017 20:46:00 GMT
```

**Comment by efridge** [comment]
You are completely right. I will keep investigating. Thanks for the help.

**Comment by GenxuanHu** [comment]
Hi @marevol  Can I ask how to index the direct page ?
Thanks
Genxuan
