### ISSUE TITLE
question on web crawl and forms authentication

### ISSUE THREAD

**Issue by jfabales** [codelibs/fess#1255]
Hi,

I just want to ask for general guidelines on how to configure a web crawl with forms authentication. How can I determine what URLs to write in the configuration and what parameters I need to configure? I wanted to configure web crawl for a jira site and some forum sites running in nginx and I can't seem to properly configure them. The sites go through several redirects. Is there a way to get the values I need from a network monitor result?

Best regards,
Joseph

**Comment by marevol** [comment]
See [example configurations](http://fess.codelibs.org/11.3/admin/webconfig-guide.html#redmine).
To configure it, I think that you need to have enough HTML/HTTP knowledge.
If you need commercial supports, please contact [support team](http://www.n2sm.net/en/support/fess_support.html).

**Comment by jfabales** [comment]
Thanks for the reply.
I'm still in the testing stage so I cannot really say right now if I need commercial support.
I've already seen the documentation and from there it looks like parameters like token_url, token_name, token_pattern, login_url, login_parameters, etc. are needed to configure web authentication. I guess I just want to know how to get the values needed for those parameters.

**Comment by marevol** [comment]
To configure parameters, you need to check/understand HTML and HTTP(S) requests for the login page.
