### ISSUE TITLE
Elastic Search on Docker throughs error

### ISSUE THREAD

**Issue by INOV8TOR** [codelibs/fess#1258]
Fess cannot start, because ES throughs an error while creating. The issue depends on vm.max_map_count=262144. Which cannot be set by ES. Therefore, the system doesn't start.

This issues happens since V11.2 and V11.3.

**Comment by marevol** [comment]
Please see [Elasticsearch document](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode).
