### ISSUE TITLE
When you did a clawring, + of the filename is converted into the space.

### ISSUE THREAD

**Issue by khama1** [codelibs/fess#1259]
When you did a clawring, + of the filename is converted into the space.

Can you just clawring it?

**Comment by marevol** [comment]
Url-decoded + is a space character.

**Comment by dappyks** [comment]
When crawl documents on FileSystem,url and _id field were containing + after crawl.
But filename and title field of document removed +. Are only these words targeted of Url-decoded?

**Comment by marevol** [comment]
Since filename and title are not in url, url-decoded is not needed.

**Comment by dappyks** [comment]
When crawl documents on FileSystem, is it possible to display + in filename and title?

![image](https://user-images.githubusercontent.com/31941660/30650194-41d4cf26-9e5d-11e7-88d5-41c9c88de417.png)

**Comment by marevol** [comment]
Fixed in #1284

**Comment by dappyks** [comment]
Thanks @marevol
