### ISSUE TITLE
Please tell me how to execute the FESS job from the Linux shell.

### ISSUE THREAD

**Issue by khama1** [codelibs/fess#1260]
Please tell me how to execute the FESS job from the Linux shell.

**Comment by khama1** [comment]
When execute crawling.
Is it possible to execute a crawling job from the shell?

**Comment by marevol** [comment]
Yes.

> You can see executed Java options.

and then run java command with the above options.

**Comment by khama1** [comment]
Is not an API provided for launching the crawler without using the scheduler?

**Comment by marevol** [comment]
Admin API is available, but documents are under construction.

**Comment by khama1** [comment]
What is the name of Admin API.

**Comment by khama1** [comment]
Is the management API released together with the document in a future version?

**Comment by marevol** [comment]
For public API documentation, the schedule is unclear.
If you need it ASAP, please contact [commercial support](http://www.n2sm.net/en/support/fess_support.html).
