### ISSUE TITLE
Exclude certain Parts

### ISSUE THREAD

**Issue by remoblaser** [codelibs/fess#1266]
Hey!

Is it possible to exclude certain parts from the Crawler? Like defining a part of the HTML Code which shouldn't be crawled?

Or can i hide certain HTML Elements by setting them to display: none / removing them with JS if the visitor has the crawler's User Agent?

**Comment by marevol** [comment]
Try to change the following setting in fess_config.properties:
```
crawler.document.html.pruned.tags=noscript,script,style,header,footer,nav,a[rel=nofollow]
```

**Comment by remoblaser** [comment]
Awesome! So this means i could define a div like this?:

crawler.document.html.pruned.tags=div[data-index="noindex"]

**Comment by marevol** [comment]
Remove "

```
div[data-index=noindex]
```

**Comment by remoblaser** [comment]
Awesome! Thank you very much!

**Comment by TkTech** [comment]
Hello @marevol, I was looking for this exact same thing. Where does one find the available options for crawlers? Can this be passed in from the crawler settings instead of globally in the `fess_config.properties`?
