### ISSUE TITLE
Request for whole domain webcrawling option

### ISSUE THREAD

**Issue by flochman** [codelibs/fess#1270]
I would like to request  for whole domain webcrawling option in Fess.

Would you implement option laik this in future versions of Fess?

Thank you very much.

**Comment by marevol** [comment]
Need more info...
What are "whole domain webcrawling option" and "option laik"?

**Comment by flochman** [comment]
I mean feature or functionality that it is possible instead of entering many URLs for webcrawling, enter for example *.jp  or  *.com  and all URLs from that domain will be crawled by Fess.

I was thinking that it is possible to do in administrators menu as an option.

The list of URLs from particular domain is possible obtain by quering the DNS server.

Thanks.

**Comment by marevol** [comment]
I do not think that many users need it...
For specific requirements, we are supporting them in [Commercial Support](http://www.n2sm.net/en/support/fess_support.html).
