### ISSUE TITLE
A few questions with Fess...

### ISSUE THREAD

**Issue by geodawg** [codelibs/fess#1272]
First off, I would like to say that Fess is amazing! It does almost 100% of what I need right out of the box. 

1. The first thing I am interested in is the ability to add a facet search to the application. Is that currently in place and am I missing it? 
2. The second is the ability to add a Label with the value in UTF-8 characters. 
3. Finally, I would like to export some of the data that is crawled. What is the best way to do this. What is the ES end point?

Thanks in advance

**Comment by marevol** [comment]
> Is that currently in place and am I missing it?

Facet is available. See [Demo](https://search.n2sm.co.jp/search/?q=fess).

> The second is the ability to add a Label with the value in UTF-8 characters.

Yes. Fess is i18ned software.

> What is the ES end point?

It depends on installation. See [Installation Guide](http://fess.codelibs.org/11.3/install/index.html).

**Comment by geodawg** [comment]
Thank you! So, Labels are facets? If that is the case, I am still having issues saving a Label if the value of the Label is in Chinese, Korean or Japanese.

**Comment by marevol** [comment]
Try it and then let us know if you have a problem.

**Comment by geodawg** [comment]
When I add chinese characters in to the value field of the labels page (http://localhost:8080/admin/labeltype/) I get the error below.

> 
Value must match "^[a-zA-Z0-9_-| ]+$".

**Comment by marevol** [comment]
Value field is alphabet or numeric characters.

**Comment by geodawg** [comment]
This is what I am putting in the value field of the label type page. 

>阳光和彩虹
>日差しと虹
>햇빛과 무지개

I still get the error above stating that is has to be numbers and letters. Does it have to be in latin text?

**Comment by marevol** [comment]
Value is URL parameter. You cannot use multibyte characters in it. See [doc](http://fess.codelibs.org/11.3/admin/labeltype-guide.html#value).

**Comment by geodawg** [comment]
That makes sense. 

When I convert this 
>日差しと虹
to
>%E6%97%A5%E5%B7%AE%E3%81%97%E3%81%A8%E8%99%B9
I get the same error as well as another one saying that it's too long.
>Size of Value must be between 0 and 20.
>Value must match "^[a-zA-Z0-9_-| ]+$".

**Comment by marevol** [comment]
The Value is like a value of ID...
We do not expect to use multibyte language.
