### ISSUE TITLE
Crawl data merged to search index

### ISSUE THREAD

**Issue by geodawg** [codelibs/fess#1274]
I have ~400k documents in the .crawler index and only ~7k documents in the index that was created yesterday called fess.20170913. Why aren't the two converging in to the main search index (fess.20170913)? What needs to happen for one to go in to the other for use in the search application? I am crawling the web for data and would like to search through all of it locally...

**Comment by marevol** [comment]
.crawler index is a working data to crawl documents. Searchable documents are in fess.YYYYMM index.
