### ISSUE TITLE
used additional field as facet field

### ISSUE THREAD

**Issue by mokkouyou** [codelibs/fess#1276]
I added additional field ,using datastore crawler, and used as facet field but get errors.
Do I need something else for using facet?

#version 
11.3

#api query
http://localhost:8088/json/?q=*&facet.field=addeddfield

#error
IllegalArgumentException[Fielddata is disabled on text fields by default. Set fielddata=true on [addeddfield] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.];

#fess_config.properties
query.additional.response.fields=addeddfield
query.additional.api.response.fields=addeddfield
query.additional.cache.response.fields=addeddfield
query.additional.highlighted.fields=
query.additional.search.fields=addeddfield
query.additional.facet.fields=addeddfield

#created mapping
addeddfield: {
type: "text",
fields: {
keyword: {
type: "keyword",
ignore_above: 256
}
}
},

I think that type should be keyword, but what should I do?

**Comment by mokkouyou** [comment]
sorry 

In this way I did what I wanted to do

//mod
query.additional.facet.fields=addeddfield.keyword

//mod query
http://localhost:8088/json/?q=*&facet.field=addeddfield.keyword

**Comment by mokkouyou** [comment]
should I close this?

**Comment by mokkouyou** [comment]
use facet result in search query
//mod
query.additional.search.fields=addeddfield.keyword

**Comment by marevol** [comment]
To add own field, you need to add a proper elasticsearch mapping before crawling.
Elasticsearch requires fielddata=true for aggregation.

**Comment by mokkouyou** [comment]
OK, I see

thanks
