### ISSUE TITLE
When crawl separate documents on FileSystem,is it possible to set different aliases of fess.update?

### ISSUE THREAD

**Issue by dappyks** [codelibs/fess#1285]
Please let me ask a question.

I want to assign aliases automatically when crawl separate documents on FileSystem.

When crawl separate documents on FileSystem,is it possible to set different aliases of fess.update?
For example, are the plural aliases such as fess.update1 and fess.update2 setable?

When set crawl setting or Scheduler setting,is it possible to assign aliases of separate target?

**Comment by marevol** [comment]
ONE Fess instance uses ONE search/update alias.
To use multiple aliases, multiple Fess instances are needed.

**Comment by dappyks** [comment]
Would you please tell me how to use multiple aliases by multiple Fess instances.
When elasticsearch cluster is used,is it possible to use multiple aliases?

**Comment by marevol** [comment]
See https://github.com/codelibs/fess/issues/1152#issuecomment-313688352

**Comment by dappyks** [comment]
Thanks @marevol

Will you implement the function that can be used with multiple aliases by single Fess instances in the future?

**Comment by marevol** [comment]
Your solution might not be proper...
Why do you want to use plural aliases?
How about using labels?

**Comment by dappyks** [comment]
I want to assign different index automatically when crawl separate documents on FileSystem.
Labels are set for each document.
In the case,Is there a good way to do it?

**Comment by marevol** [comment]
Why do you want to assign different indices?

**Comment by dappyks** [comment]
Because the owner of each crawl data is different.
Should I separate Fess and Elasticsearch together?

**Comment by marevol** [comment]
I think it will work on Role-based search or Virtual Host setting.

For Role-based search, you need to create users, and users have to log in to Fess.
Setting [permissions](http://fess.codelibs.org/11.4/admin/webconfig-guide.html#permissions) in crawling config, search results are filtered by users.

For Virtual Host, you need to assign multiple hosts/IPs to Fess server.
Adding Virtual Host setting to [General](http://fess.codelibs.org/11.4/admin/general-guide.html#virtual-hosts) page and setting [Virtual Hosts](http://fess.codelibs.org/11.4/admin/webconfig-guide.html#virtual-hosts) in crawling config, search results are filtered by accessing url.
