### ISSUE TITLE
Default admin/admin doesn't work on new installation

### ISSUE THREAD

**Issue by WorldWideWebb** [codelibs/fess#1288]
Not sure what I'm doing wrong, but I have a fresh installation, and when trying to hit http://localhost:8080/admin, the admin/admin username/password doesn't work. I get a 401 Unauthorized every time. When I try that on the server using IE, the security prompt tells me:

"The server localhost is asking for your user name and password. The server reports that it is from XDB.

Warning: Your user name and password will be sent using basic auth...."

Also - when I try running fess as a service (I assumed the right way to do this was to right click on the service file in the installation directory, and run as an administrator), the service either doesn't show up in the services list, or is not named something that I can recognize. What am I doing wrong there?

**Comment by marevol** [comment]
I do not think that it's Fess problem.
Stop all other software(ex. Oracle?), and then try it(or install Fess on a clean environment).
