### ISSUE TITLE
fess service on linux

### ISSUE THREAD

**Issue by aschmu** [codelibs/fess#1295]
Hello I'd like to run fess as a service but so far I haven't found any guidelines on how to do it.
The official documentation instructions only address the case where fess has been installed as an rpm package but not with a zip file.
My systemd file is pretty straightforward, with `/fess-xxx/bin/fess -Dfess.port=8081 -Dfess.context.path:/fess/` in the ExecStart field.
Fess seems to be starting for a few seconds (I can access localhost:8081) with the `service start` command but then errors out with the exit code 143 and no server logs anywhere.

Any clue as to what's happening.

**Comment by marevol** [comment]
It's better to use rpm/deb package.
