### ISSUE TITLE
Docker - 404 ?

### ISSUE THREAD

**Issue by defensivedepth** [codelibs/fess#1297]
Just did a  docker run -d -p 8080:8080 --name fess codelibs/fess:latest on a fresh docker instance. When I browse to localhost:8080, I get a 404 error.

Is the docker image in a known good state?

Thanks,

**Comment by marevol** [comment]
Could you check log messages by "docker logs"?

**Comment by marevol** [comment]
and also check [Kernel Settings](https://hub.docker.com/r/codelibs/fess/).

**Comment by defensivedepth** [comment]
Thanks, I missed the issue in the logs... Looks like the container couldn't start because it needed at least 4GB RAM allocated to Docker... Once I did so, it started successfully.
