### ISSUE TITLE
Windows batch script fails in path containing space character

### ISSUE THREAD

**Issue by doct** [codelibs/fess#1299]
When installing Fess in a directory with a path containing a space fess.bat on Windows fails to start.

Issues lies in the setting of JESS_JAVA_OPTS variables in bin\fess.in.bat not correctly quoting values. Values containing ES_HOME and FESS_HOME need to be quoted in assigning them to FESS_JAVA_OPTS.

Corrected code:
`
set FESS_JAVA_OPTS=%FESS_JAVA_OPTS% -Des-foreground=yes
set FESS_JAVA_OPTS=%FESS_JAVA_OPTS% -Dfess.home="%FESS_HOME%"
set FESS_JAVA_OPTS=%FESS_JAVA_OPTS% -Dfess.es.dir="%ES_HOME%"
set FESS_JAVA_OPTS=%FESS_JAVA_OPTS% -Dfess.context.path=/
set FESS_JAVA_OPTS=%FESS_JAVA_OPTS% -Dfess.port=8080
set FESS_JAVA_OPTS=%FESS_JAVA_OPTS% -Dfess.webapp.path="%FESS_HOME%\app"
set FESS_JAVA_OPTS=%FESS_JAVA_OPTS% -Dfess.temp.path="%FESS_HOME%\temp"
set FESS_JAVA_OPTS=%FESS_JAVA_OPTS% -Dfess.log.name=%APP_NAME%
set FESS_JAVA_OPTS=%FESS_JAVA_OPTS% -Dfess.log.path="%FESS_HOME%\logs"
set FESS_JAVA_OPTS=%FESS_JAVA_OPTS% -Dfess.log.level=warn
set FESS_JAVA_OPTS=%FESS_JAVA_OPTS% -Dlasta.env=web
set FESS_JAVA_OPTS=%FESS_JAVA_OPTS% -Dtomcat.config.path=tomcat_config.properties

REM External elasticsearch cluster
REM set FESS_JAVA_OPTS=%FESS_JAVA_OPTS% -Dfess.es.http_address=http://localhost:9200
REM set FESS_JAVA_OPTS=%FESS_JAVA_OPTS% -Dfess.es.transport_addresses=localhost:9300
REM set FESS_JAVA_OPTS=%FESS_JAVA_OPTS% -Dfess.dictionary.path="%ES_HOME%/config/"
`

**Comment by marevol** [comment]
A location containing a space is not supported at the moment.
Pull Request is welcome.
