### ISSUE TITLE
Site search label filter

### ISSUE THREAD

**Issue by arwed** [codelibs/fess#1306]
How do I limit the results of the site search to a certain label?

**Comment by marevol** [comment]
label:VALUE

VALUE is a [label value](http://fess.codelibs.org/11.4/admin/labeltype-guide.html#value).

**Comment by arwed** [comment]
Thanks for the quick answer. Is there a way I can set a label as default?

**Comment by marevol** [comment]
See [Default Label Value](http://fess.codelibs.org/11.4/admin/general-guide.html#default-label-value).

**Comment by arwed** [comment]
Sorry, I meant somewhere in the settings of the site search form:

```
<script>
  (function() {
    var fess = document.createElement('script');
    fess.type = 'text/javascript';
    fess.async = true;
    fess.src = '//<Server Name>/js/ss/fess-ss.min.js';
    fess.charset = 'utf-8';
    fess.setAttribute('id', 'fess-ss');
    fess.setAttribute('fess-url', '//<Server Name>/json');
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(fess, s);
  })();
</script>
<fess:search></fess:search>
```
