### ISSUE TITLE
How to use roles and groups?

### ISSUE THREAD

**Issue by pcolmer** [codelibs/fess#1307]
The documentation doesn't really explain how roles and groups can be used, specifically in regards to controlling what users can do in the admin interface.

For example, if I want someone to be able to look at failed URLs and then search for anchors referencing those URLs, what steps do I need to take, rather than just giving them full admin rights?

Thanks.

**Comment by marevol** [comment]
For admin UI, only "admin" role is to manage administrative operations.
Use case for role/group is to filter search results with proper permissions.
For example, if connecting to Active Directory, users can search only proper contents.

**Comment by pcolmer** [comment]
Oh ... so there isn't any way to restrict what can be done on the admin page?

Thanks for the clarification.
