### ISSUE TITLE
Meta tags - crawling and indexing

### ISSUE THREAD

**Issue by chippinkston** [codelibs/fess#1313]
Is there anyway to update the crawl/index to record data from custom metatags?  We're looking to migrate from a GSA, and were using custom metatags to populate the facets (Labels in Fess).  This is data like Official Release dates, Categories, etc.

**Comment by marevol** [comment]
Yes.
See https://github.com/codelibs/fess/issues/1046#issuecomment-298633416

**Comment by chippinkston** [comment]
That worked perfectly.  Thanks!
