### ISSUE TITLE
How to set up redundant Fess containers

### ISSUE THREAD

**Issue by kujiy** [codelibs/fess#1315]
Hi, thank you for sharing your excellent project. We've used the docker image over a year. It's literally excellent. 

We'd like to make our Fess container redundant. What is the best solution? It will be nice that we can build a master-slave or multi-master system. Reducing duplicated crawl is better also. Does anybody give us a hint?

**Comment by marevol** [comment]
1. Setup/Configure Elasticsearch cluster with plugins (multiple nodes)
2. Setup multiple Fess instance connected to the above Elasticsearch cluster
3. Set a node name to scheduler.target.name in fess_config.properties
4. Edit Scheduled job with [Target](http://fess.codelibs.org/11.4/admin/scheduler-guide.html#target) (Job is executed if Target matches scheduler.target.name)

**Comment by kujiy** [comment]
Hi @marevol ,
Thank you for answering. I should have asked at [docker-fess](https://github.com/codelibs/docker-fess/issues) project. Does the *Target* feature mean Fess has already supported the elastic search cluster? That's awesome. I think it's hard to apply the instruction to the docker entrypoint at this time. Hense we'll just try it manually. I may ask you again during the challenge. Thanks.

**Comment by marevol** [comment]
Fess supports Target feature.

**Comment by yashodhank** [comment]
https://techoverflow.net/2019/03/16/elasticsearch-docker-compose-yml-and-systemd-service-generator/
This tutorial might help someone, though I have yet to test this out.
