### ISSUE TITLE
Configuration for Fess

### ISSUE THREAD

**Issue by dracorp** [codelibs/fess#1316]
Hello
I had installed Fess from zip archive. It worked well. I decided to connect it with standalone Elasticsearch also from zip archive.
But after restarting Fess I lost configuration: crawlers, users, labels, and schedulers.
Where they are kept?
For Fess I've added only below configuration:
```
-D fess.es.http_address=http://localhost:9200
-D fess.es.transport_addresses=localhost:9300
-D fess.dictionary.path="/var/lib/elasticsearch/config
```
  Are there somewhere in fess/es/data/node_1/nodes/0?

**Comment by marevol** [comment]
Configurations are in .fess_config index.

**Comment by dracorp** [comment]
I cannot find any my configurations in fess/app/WEB-INF/classes/fess_indices/.fess_config.  But I've found the new configurations in /var/lib/elasticsearch/data/nodes/0/indices.
I'm using:

* fess-11.4.2
* elastisearch-5.6.3

How I can import previous data from fess/es/data/node_1/nodes/0 to new the location, for standalone elasticsearch?
```
$ du -sh 0
5.6G    0
```

**Comment by marevol** [comment]
Enough knowledge of elasticearch is required...
I think it's better to use [backup/restore](http://fess.codelibs.org/11.4/install/upgrade.html).

**Comment by dracorp** [comment]
Thx, tomorrow I'll try. But why this configuration (crawler, label, account, scheduler etc) is kept in elasticsearch data directory not in .fess_config?

**Comment by marevol** [comment]
> why this configuration (crawler, label, account, scheduler etc) is kept in elasticsearch data directory not in .fess_config?

Fess is scalable system. Using index, Multiple Fess instances are able to share configurations.

**Comment by dracorp** [comment]
It makes sense, thx
