### ISSUE TITLE
Fess search index loses docs

### ISSUE THREAD

**Issue by reversecipher** [codelibs/fess#1318]
Hi,

I have a problem where Fess search index seems to lose its documents after a week. When Fess and crawler are started, the index (fess.YYYMMDD) is created and populated. However, after a week the documents disappear. The crawler is still running but the docs are not populated to the search index.

**Comment by marevol** [comment]
See [Remove Documents Before](http://fess.codelibs.org/11.4/admin/general-guide.html#remove-documents-before).
