### ISSUE TITLE
Acquire PDF thumbnail

### ISSUE THREAD

**Issue by kyo1915** [codelibs/fess#1322]
I am using fess11.4.1.
I want to acquire thumbnails of PDF files with web crawl.
Do I need to set something?

**Comment by marevol** [comment]
PDF thumbnail is supported on Linux.
Installing convert command for ImageMagick, it'll work.

**Comment by kyo1915** [comment]
ImageMagick was installed.

Version: ImageMagick 6.7.7-10 2014-03-06 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2012 ImageMagick Studio LLC
Features: OpenMP

OS uses ubuntu.
Is there anything else you need to install?

**Comment by kyo1915** [comment]
This command created a png file.
`/fess-11.4.1/bin/generate-thumbnail pdf ./test.pdf ./test.png`

I also installed unoconv, libreoffice, vlgothic-fonts, but I will not improve it.
Are there any other points to check?
