### ISSUE TITLE
Qustion: Save entire content

### ISSUE THREAD

**Issue by j8** [codelibs/fess#1328]
Hello,

**First**: 

Amazing project. Thank you for all the nice work!

**Second**:

I'm just exploring it and I have requrerement, the crawler to record the entire conetent of a web page, not just a summary.

So for example, if I query: **_localhost:8080/json?q={searchQuery}_**

I want in the JSON output in the "_**content_description**_" to receive the entire content of a webpage.

Regards

**Comment by marevol** [comment]
content and content_description field does not contain an entire content.
cache field has an original content.

Could you try the following setting in fess_config.properties:

```
query.additional.api.response.fields=cache
```

**Comment by j8** [comment]
I added it, seems it's not making any change?

**Comment by j8** [comment]
@marevol any update on this?

**Comment by marevol** [comment]
Oh, put it as below:

```
query.additional.response.fields=cache
query.additional.api.response.fields=cache
```

**Comment by j8** [comment]
Thank you @marevol! Works.
