### ISSUE TITLE
Question: How do I safely empty /var/lib/fess/thumbnails?

### ISSUE THREAD

**Issue by WorldWideWebb** [codelibs/fess#1335]
What's the best/safe way to clear out /var/lib/fess/thumbnails? Looks like I've got quite a buildup, and I never had the "thumbnail view" option checked in the settings (I assumed this meant that thumbnails wouldn't even be generated, but I guess that's more of a UI option). I tried the thumbnail purger job in the scheduler, but that didn't seem to clear them out.

**Comment by WorldWideWebb** [comment]
Thanks - I had already deactivated the Thumbnail Generator job, but I still have all that space being occupied by what was generated. How do I get rid of those without breaking the application?

**Comment by marevol** [comment]
After disabling the job, run `rm -r /var/lib/fess/thumbnails/*`.
