### ISSUE TITLE
Fatal error on the network layer

### ISSUE THREAD

**Issue by Lmmb74** [codelibs/fess#1336]
Hello, I am trying to setup fess 11.4.2 with standalone elasticsearch 5.6.3. But every time I start fess service, elasticsearch stops with [this](https://hastebin.com/ajuzaquyiy.lua) error log. Help me please.

**Comment by marevol** [comment]
See [Installation Guide](http://fess.codelibs.org/11.4/install/install.html#using-rpm-package).
For elasticsearch plugins, you need to install them with elasticsearch-plugin command.

**Comment by Lmmb74** [comment]
@marevol Thanks :D, I should have done that before.
