### ISSUE TITLE
Approx. maximum number of docs?

### ISSUE THREAD

**Issue by WoSaBeu** [codelibs/fess#1337]
Hello, 

this might be the most common question at all? Up to what limit of docs will a fess-server work with query answer times smaller than 1 sec? ? After doing first tests I'd guess, that this maximum number of docs in ONE index might be limited to approx. 1 million docs? To which number might I push that limit using many indexes (still in one server)? The server has 32 GB of RAM and 4 TB disks. 

Or should I switch from the beginning to ElasticSearch only? The number of indexed docs should be in the end around some 100 millions. Would this be possible with an elasticsearch-based fess-cluster?

If anyone can answer, I would be really very grateful!
Best,
Wolfgang

**Comment by marevol** [comment]
Throughput depends on elasticsearch.
So, for throughput improvement, see elasticsearch documents.
In production, we recommend using Fess with Elasticsearch cluster.
("Embedded Elasticsearch is not recommended for production use." in [Installation Guide](http://fess.codelibs.org/11.4/install/install.html#requirements))
Our customers manage over X0 million documents and they work on Fess with ES cluster.
For more supports, please ask [commercial support](http://www.n2sm.net/en/support/fess_support.html).
