### ISSUE TITLE
Question: How to use "CsvListDataStore"

### ISSUE THREAD

**Issue by stm0209** [codelibs/fess#1340]
Would you tell me "CsvListDataStore"?
For example,setting of "Script" and "Parameter".
I was looking for SampleData,but not found.

Thank you for your cooperation.

**Comment by marevol** [comment]
See [Data Store Config](http://fess.codelibs.org/11.4/admin/dataconfig-guide.html#csvdatastore).

**Comment by marevol** [comment]
Oops, for csvLISTdatastore, you can create sample data by the following script.
https://github.com/codelibs/fess-testdata/blob/master/tools/csvlistdatastore.sh

**Comment by stm0209** [comment]
Thank you very much for your prompt reply.
Sorry,What should I set in an "event_type"? 
Please tell me "SampleCSV Format".

I'm sorry to be so inquisitive.

**Comment by marevol** [comment]
Did you run csvlistdatastore.sh?
It creates csv file.
event_type is modify or delete for an indexing action.

**Comment by stm0209** [comment]
Sorry for replying so late.
I was able to confirm it.Thank you.
