### ISSUE TITLE
Question: How to crawl files from all hierarchy?

### ISSUE THREAD

**Issue by hominhphuong19** [codelibs/fess#1347]
I'm trying to crawl data from File Server. 
However, Fess only crawl files from hierarchy four levels down from the directory I've set.
How to crawl data from all hierarchy?

I've tried to set hierarchy level to crawl as 1000 level down but it doesn't work.
I'm using Fess 11.3.0

**Comment by marevol** [comment]
Fess does not limit it.
Please check fess-crawler.log.
