### ISSUE TITLE
Question:  Does fess have an AJP connector port

### ISSUE THREAD

**Issue by zaryk** [codelibs/fess#1354]
We have used a IIS to tomcat connector for other application.  As far as I know, it connects to tomcat using the AJP connector Port.  Does fess have an AJP connector port?

https://github.com/Bilal-S/iis2tomcat/tree/1.0.36

**Comment by marevol** [comment]
AJP is not supported.
Could you try to use a reverse proxy, such as Application Request Routing?

**Comment by zaryk** [comment]
I am trying that now.  I am running into an issue where the CSS/JS/Images aren't being rewritten, so IIS is looking for them under the main application rather than under Fess.  This may be because Fess href/src don't match the pattern: ^http(s)?://localhost:8080/(.*)   Otherwise, I can see the search page, but doesn't have any styles/scripts/images.

Do you have any suggestions?  Do I have to copy the css/js/images to the main application?

**Comment by zaryk** [comment]
I am able to add additional rules to replace the css/js/images href/source, but have to get through "was loaded over HTTPS, but requested an insecure stylesheet" issue.  Just takes some tweaking and consolidation.  Would be nice if there were some setting in Fess to add the base url so more work wouldn't have to be done after the initial setup of the ARR.

Will close.
---------------------------------------------------------
<rule name="Rewrite Css URLs in Response" preCondition="ResponseIsHtml1">
                <match pattern="/css/" />
                <action type="Rewrite" value="http://localhost:8080/css/" />
            </rule>
<rule name="Rewrite Js URLs in Response" preCondition="ResponseIsHtml1">
                <match pattern="/js/" />
                <action type="Rewrite" value="http://localhost:8080/js/" />
            </rule>
<rule name="Rewrite Image URLs in Response" preCondition="ResponseIsHtml1">
                <match pattern="/images/" />
                <action type="Rewrite" value="http://localhost:8080/images/" />
            </rule>
