### ISSUE TITLE
Set Attribute Label in Site Search 

### ISSUE THREAD

**Issue by RSeptiane** [codelibs/fess#1355]
Hi,

Is it possible to add a label to the site search script as a filter? 
something like fess.setAttribute('label', 'main-website');

I want to filter the search result by the label.  
If it does could you let me know how to do it? 
<script>
  (function() {
    var fess = document.createElement('script');
    fess.type = 'text/javascript';
    fess.async = true;
    fess.src = '//<server>/js/ss/fess-ss.min.js';
    fess.charset = 'utf-8';
    fess.setAttribute('id', 'fess-ss');    
    fess.setAttribute('fess-url', '//<server>/json');
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(fess, s);
  })();
</script>
<fess:search></fess:search>

Thank you

**Comment by marevol** [comment]
Could you try:
```
    fess.setAttribute('fess-url', 'http://search.n2sm.co.jp/json?fields.label=main-website');
```

**Comment by RSeptiane** [comment]
Hi,

Thank you for your answer.
