### ISSUE TITLE
url field search no results

### ISSUE THREAD

**Issue by freestyle68** [codelibs/fess#1356]
Hi,
according to http://fess.codelibs.org/11.4/user/search-field.html 
the search 

`url:"*youtube*" `

on 

http://search.n2sm.co.jp/search/?q=url%3A%22*youtube*%22&num=20&sort=

should have some results, as seen for example with this search:

http://search.n2sm.co.jp/search/?q=demo&ex_q=label%3areddit&sdh=&

There is something to enable on fess to make this field searchable?

Thank you

**Comment by marevol** [comment]
For searching with a partial matching in url, inurl is supported.

```
inurl:youtube
```

**Comment by freestyle68** [comment]
Yes, I tested it and produces reliable results, not to forget the query is case sensitive.

The query url:*path* instead not give predictable results, for example it happens the query

`url:*select1*`

give me zero results and

`url:*elect1* `

instead give me some results where the path contain select1 (but not all).

But not so much important at this point with the inurl operator.

Many thanks for the help
