### ISSUE TITLE
How to add tika fields?

### ISSUE THREAD

**Issue by freestyle68** [codelibs/fess#1357]
Hi,
how to add tika fields to fess? For example
`meta:author`
or
`Author`  ?

They are not supported fields as seen in https://github.com/codelibs/fess/blob/master/src/main/java/org/codelibs/fess/helper/QueryHelper.java

Adding 
```
"meta:author": {
"type": "keyword"
},
```
to doc.json

and

`index.field.meta:author=author`   (or` index.field.meta\:author=author` ?)

to fess_config.properties is not enough to see the field in elasticsearch.

**Comment by marevol** [comment]
For an additional field, to search on it:
```
query.additional.search.fields=author
```
and, to display it on a search result:
```
query.additional.response.fields=author
```
in fess_config.properties.

**Comment by freestyle68** [comment]
yes, but the field must be inserted on elasticsearch at crawling time:

in fact also with mapping

```
"author": {
"type": "keyword"
},
```

on doc.json and
```
query.additional.search.fields=author
query.additional.response.fields=author
```
the field author is not visible on elasticsearch. There is a way to collect this info?

**Comment by marevol** [comment]
> index.field.meta:author=author (orindex.field.meta\:author=author ?)

Ah, it is not correct.
Could you try to modify the following setting in fess_config.properties?

```
crawler.metadata.name.mapping=\
title=title:string\n\
Title=title:string\n\
meta:last-author=author:string\n\
Author=author:string
```

**Comment by freestyle68** [comment]
Perfect, It works and elasticsearch mapping is not needed, because fess put this:

```
"author": {
        "type": "text",
        "fields": {
          "keyword": {
            "ignore_above": 256,
            "type": "keyword"
          }
        }
      },
```
Thank you so much!
