### ISSUE TITLE
Question: Site Search not taking into account Path Mapping

### ISSUE THREAD

**Issue by zaryk** [codelibs/fess#1358]
I am using FileSystem Index.  Path Mapping works when searching from admin and Fess Search Page, but Path Mapping doesn't seem to work from Site Search.  Are there any configurations that need to be setup to allow this?

This is what works from admin:

Regexp. 
file:/E:/Websites/test.site.gov/Attachments/orders 

Replacement
https://test.site.gov/Attachments/Order

EDIT:
Also, when clicking a link on Fess Search Page it should be a url to this path: 

- test.site.gov/Attachments/Order/785EECCE-D...

but the link takes me to 

- **https://test.site.gov/go/?rt=1511752151219&docId=b3b4af63edaf449db27089e8bf66e3b7&queryId=f8a052a1ace64821969f73606f06738e&order=1**

As mentioned in another post, this link should include **/fts/go** instead.  When I manually add this to the url, it takes me to the http url, which isn't open to the public.  If I add https, then it takes me to the correct location.  It looks like the correct url is changed to the **/go/** url after clicking the url.

**Comment by marevol** [comment]
/go link is an expected behavior to log a click action.
I think that rewriting Location response header is failed in your reverse proxy setting.

**Comment by zaryk** [comment]
I will take a look, but the Location Response Header shouldn't affect the Path Mapping.  At least for admin and Fess search page, this works.  But doesn't work for the Site Search Javascript.

**Comment by marevol** [comment]
The response of /go returns url replaced by Path Mapping at Location response header.

**Comment by zaryk** [comment]
But, does /go/ handle what shows in the list, before clicking it?

![image](https://user-images.githubusercontent.com/593015/33285274-ce67e336-d37f-11e7-9245-cc2e27f80e3a.png)

**Comment by marevol** [comment]
What is Process Type of Path Mapping?

**Comment by zaryk** [comment]
Displaying.

**Comment by zaryk** [comment]
Will this require a rebuild of fess, or is there something I can quickly change?

**Comment by marevol** [comment]
This needs to modify FSS JS, not Fess.
To generate a new JS file:

1. Clone https://github.com/codelibs/fess-site-search.git
2. Replace with site_path in ./fss/11.4/src/templates/fess-result.hbs 
3. Run on Docker: https://github.com/codelibs/fess-site-search#run-on-docker
4. Generate JS file

**Comment by zaryk** [comment]
docker doesn't install on my machine for some reason, or it is just taking too long.  Any idea when this can be done in your timeline of things?

**Comment by zaryk** [comment]
I noticed the issue has been closed, but FSS Generator doesn't seem to have the fix yet.

Can this section of the js be changed without changing anything else, and what would it need to be changed to?

`<cite>'+u((p=null!=(p=r.site||(null!=n?n.site:n))?p:f,typeof p===c?p.call(l,{name:"site",hash:{},data:o}):p))+"</cite>`

**Comment by marevol** [comment]
Not released yet...

**Comment by marevol** [comment]
Released.

**Comment by zaryk** [comment]
Hey, 

The actual url is still pointing to the local path.

![image](https://user-images.githubusercontent.com/593015/34403070-d939eaa0-eb73-11e7-80f2-390b2d8811d3.png)
