### ISSUE TITLE
Index pdf metadata

### ISSUE THREAD

**Issue by vitorcoxta** [codelibs/fess#1360]
I have Fess indexing a website, which have some PDFs. I'm seeing that Fess is not indexing those PDF metadata, namely its modified date. Is there a way to configure Fess to index this kind of metadata?

**Comment by marevol** [comment]
See #1357.
You need to set a metadata name to crawler.metadata.name.mapping.

**Comment by vitorcoxta** [comment]
This is exactly what I needed. Just to be written here, all I had to do to get the modification and the creation date from PDFs was to change the `crawler.metadata.name.mapping` on the file fess_config.properties as follows:

    crawler.metadata.name.mapping=\
    title=title:string\n\
    Title=title:string\n\
    meta:modDate=modDate:string\n\
    ModDate=modDate:string\n\
    meta:creationDate=creationDate:string\n\
    CreationDate=creationDate:string\n\

Thanks for the help!
