### ISSUE TITLE
Can't enable Desktop Search function on fess 11.x

### ISSUE THREAD

**Issue by naoto80** [codelibs/fess#1372]
about "Desktop Search Function" descrived here ->> ["The desktop search settings"]( http://fess.codelibs.org/8.0/config/desktop-search.html?highlight=desktop%20search
) is still working?

And let me know this function detail.
If I turned on this function, the link of serach result are point to share folder's file?
The system will not work as contents proxy?

**Comment by marevol** [comment]
Desktop Search was removed.

**Comment by naoto80** [comment]
Ok, So "File System search" still work as contents proxy?
Or that function was also removed?

**Comment by marevol** [comment]
Content Proxy is available.

**Comment by naoto80** [comment]
OK Thanks!
