### ISSUE TITLE
redundant UI

### ISSUE THREAD

**Issue by eimperat** [codelibs/fess#1373]
I'd like to have multiple servers run the fess UI, in case one happens to go down. It was easy to have them all point at the same elastic cluster, but the settings on the Admin page are not shared between hosts. Is there a good way to keep these in sync? (i.e. have all Fess instances know the same crawl schedule)

**Comment by marevol** [comment]
> have all Fess instances know the same crawl schedule

To select Fess instance which runs by a specific job, 

1. Set scheduler.target.name in fess_config.properties (ex. scheduler.target.name=SERVER1)
2. Set the target name(ex. SERVER1) to [Target](http://fess.codelibs.org/11.4/admin/scheduler-guide.html#target)
