### ISSUE TITLE
Question: Additional Content for Search Term

### ISSUE THREAD

**Issue by matzesa** [codelibs/fess#1374]
I try to add additional content to the index of html docs that can be searched/found via
`https://fess.example.com/json?q=SEARCH_TERM`

I tried to add an additional field to the fess-index in ES. The field is filled correctly during crawling. But the field will not be searched with fess. Direct search in ES works (`/fess.20171204/doc/_search?q=SEARCH_TERM`) and finds all elements with SEARCH_TERM in the additional field. It seems that only the `content` and `title` field will be searched in fess. (`https://fess.example.com/json?q=FIELD_NAME:SEARCH_TERM` works, but is no alternative)

Or is it possible to add special/additional content to the `content` field in ES during crawling?

**Comment by marevol** [comment]
See [copy_to](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/copy-to.html).
For example, to copy the additional content to "content" field, the mapping is:
```
        "FIELD_NAME": {
          "type": "text",
          "copy_to": "content" 
        },
```

**Comment by matzesa** [comment]
Thank you for your help. Works very well.
