### ISSUE TITLE
java.lang.NoSuchMethodError errors on office docs

### ISSUE THREAD

**Issue by freestyle68** [codelibs/fess#1375]
Hi, starting from 11.4 version (11.3 is ok) I get a lot of java.lang.NoSuchMethodError errors on office docs.

Tried with deb version and also zip.

I attach a log and also two problematic files, thank you.

[logs.txt](https://github.com/codelibs/fess/files/1535950/logs.txt)
[files.zip](https://github.com/codelibs/fess/files/1535951/files.zip)

**Comment by marevol** [comment]
Thank you for the info.
Fixed in https://github.com/codelibs/fess-crawler/commit/f14a912c9d03407248fa38c498ef6b016d4ffefc
It will be fixed in a next release.
