### ISSUE TITLE
fess.search index not following doc.json

### ISSUE THREAD

**Issue by freestyle68** [codelibs/fess#1383]
Hi,

If I change

/usr/share/fess/app/WEB-INF/classes/fess_indices/fess/doc.json

then delete fess.search index and restart fess, the new index does not take the new mappings, as I can see from 

Dashboard --> fess.search --> show mapping

There is a way to change this?

**Comment by marevol** [comment]
1. Change doc.json
2. Start Reindex with Update Aliases at [Upgrade](http://fess.codelibs.org/11.4/admin/upgrade-guide.html) page
3. Check the new index
4. Delete the old index

**Comment by freestyle68** [comment]
Tested and working.
 Thank you very much!
