### ISSUE TITLE
Some issue with crawler path in macos

### ISSUE THREAD

**Issue by PakanAngel** [codelibs/fess#1385]
Hi,
 I did setup a file system crawler on my mac so it has to crawl a specific folder but it does't work. Have checked the log but realized it cannot find the given folder path. What is the correct folder path syntax to a mac folder by setting up a file system crawler. 
Can anybody help me please?

**Comment by marevol** [comment]
What is the crawling config setting you created?

**Comment by PakanAngel** [comment]
This is a snapshot of my file scrawler 
I left the remaining properties as default and how can I set the node that I want to add these docs to.
![screen shot 1396-09-27 at 13 37 15](https://user-images.githubusercontent.com/26673019/34106501-bee79846-e3f8-11e7-9e37-16580d0033f0.png)

**Comment by marevol** [comment]
- Is the directory permission correct?
- Did you check fess-crawler.log?

**Comment by PakanAngel** [comment]
What are the preferred permissions for a folder to get crawled by the crawler? 
These are the permission for my repo folder
drwxr-xr-x   admin   272 Dec 16 19:43 text-repository

**Comment by marevol** [comment]
The user which launched Fess needs to be able to access it.

**Comment by PakanAngel** [comment]
It is. The user is an admin user. I thought I might have some syntax error by entering the paths. 
How can I force a crawler to recrawl a folder immidiately?
