### ISSUE TITLE
PC error after running FESS >6 hours 

### ISSUE THREAD

**Issue by tetracilin** [codelibs/fess#1386]
#I got WINDOWS error: 

> The IO operation at logical block address b6ff for Disk 2 (PDO name: \Device\00000034) was retried

FESS.bat will not response and I will lose all previous crawled data.

Screen of the system event log: 
![image](https://user-images.githubusercontent.com/25259933/34098777-0e3e6fb6-e410-11e7-98d9-24479c8a7b93.png)

thank you for helping

**Comment by marevol** [comment]
I do not think that it's Fess issue and it's better to check your hardware and OS.
https://answers.microsoft.com/en-us/windows/forum/windows_8-hardware/the-io-operation-at-logical-block-address-for-disk/23c32152-c2a6-4c6d-b229-95dc1470231a?auth=1
