### ISSUE TITLE
how to add new facet field?

### ISSUE THREAD

**Issue by AllenHan5** [codelibs/fess#1387]
Hello all

I followed the approach described in the question below, but it did not work.
   #1276 

Specifically, I modified the entry in fess_config.properties with the following:
    query.additional.facet.fields=mimetype
or 
    query.additional.facet.fields=mimetype.keyword
Both did not work.

Anything else I have missed?

When I tested with Searchkit (http://www.searchkit.co/), I was able to see mimetype as facet field, which led me to believe the backend support from ES should be enough.

Any tips/guidance?
Thanks

**Comment by AllenHan5** [comment]
Any one has an idea about the issue?  THanks

**Comment by shradhatx** [comment]
Have you tried adding to fess_config.properties -
query.additional.facet.fields=mimetype.keyword
query.additional.search.fields=mimetype.keyword
