### ISSUE TITLE
How to configure fess for binding to a standalone elastic search server on mac

### ISSUE THREAD

**Issue by PakanAngel** [codelibs/fess#1393]
Hi, 
I am running a standalone server on background on my mac. I need that my fess server can connect to it and create and make all the changes to the standalone elasticsearch instance.
There are some explanation regarding to this need but none of them are detailed. I have added 2 environment variables on my mac so that fess can connect to 'http://localhost:9200' but now when I go to localhost:8080 get just a blank screen instead of fess UI.
Why is that, I am sure that my standalone elastic search server is running.
Please can anybody tell me exactly how to configure fess so it can connect to my standalone elastic search server on mac. 
Please in details and step by step.

**Comment by marevol** [comment]
Did you check log files? and also see [Network Settings](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/modules-network.html).

**Comment by PakanAngel** [comment]
i am sure that elastic-search is running on my localhost on port 9200. is there any extra configuration needed for binding fess to standalone elastic-search running instance?
Actually my elastic-search instance is fresh and has no data yet, but I expect that I can see its node in fess UI even if it has no indices. 
Which logs should I check, elastic-search or fess logs?

**Comment by marevol** [comment]
Both.

**Comment by PakanAngel** [comment]
Thnx  wil check both of them. But may its because I'm using elasticsearch 6.1.0 and fess11.4.4. 
Could this be the reason?

**Comment by marevol** [comment]
Fess 11 does not support Elasticsearch 6, and Fess 12 will work with it.
