### ISSUE TITLE
More Like This Query

### ISSUE THREAD

**Issue by anatomo** [codelibs/fess#1395]
I'd like to use "More Like This" query.
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-mlt-query.html

I found this information.
http://www.chazine.com/archives/3199

I add "mlt.field=content_ja" to search.jsp.
But, It doesn't work.
[search.jsp.txt](https://github.com/codelibs/fess/files/1585513/search.jsp.txt)

Is this setting wrong?
Could you please give any example or advise?

**Comment by marevol** [comment]
Not supported from 10.

**Comment by anatomo** [comment]
OK. I'll try to check source code...
Are you planning to support in the future?

**Comment by marevol** [comment]
No plan. Any contributions are welcome.
