### ISSUE TITLE
Search result is not shown for public search

### ISSUE THREAD

**Issue by PakanAngel** [codelibs/fess#1396]
Hi, 
I just setup Elasaticsearch with Fess on Centos 7 env. I've defined several crawlers for indexing some websites which are working properly. When I search in admin panel for some specific keywords can browse the those search results very well but when I am searching the same keywords as guest on public search page, no search results is shown. How can I let my customers search through the main search page without any issue? Am I missing any configurations after the installation?
Please help

**Comment by marevol** [comment]
What is your crawling configuration?
Did you change [Permission](http://fess.codelibs.org/11.4/admin/webconfig-guide.html#permissions)?

**Comment by PakanAngel** [comment]
Thnx for your quick response. It was my own fault just excluded guest role from admin user.
