### ISSUE TITLE
How can I delete all indexed docs from a specific crawler?

### ISSUE THREAD

**Issue by PakanAngel** [codelibs/fess#1397]
I just setup a crawler and it worked well. But as I reviewed the crawl info, realized there are some unwanted indexed files like .css and some other website links and .php files which I had to exclude in my crawler settings. Now I need to delete all indexed docs from a specific crawler and reconfigure the crawler and let it recrawl the website. How can I do this?

**Comment by marevol** [comment]
You can delete documents from index by a query at [Admin Search](http://fess.codelibs.org/11.4/admin/searchlist-guide.html) page.

**Comment by PakanAngel** [comment]
Yes I think in this page I can just delete docs one by one but I am looking for a command so I can delete all docs crawled by a crawler at once.

**Comment by marevol** [comment]
There is Delete All by Query button at the bottom of the page.

**Comment by PakanAngel** [comment]
Oh, yes thank you.
