### ISSUE TITLE
What is the right regexp to exclude indexing files like .jpg .css .php in a whole domain?

### ISSUE THREAD

**Issue by PakanAngel** [codelibs/fess#1401]
I cannot find a clear regexp to exclude indexing files from a whole domain
e.g.:  
URL: http://example.com
includde URls: http://example.com/.*
Exludeed URls for crawling: http://example.com/.*/*.jpg

**Comment by marevol** [comment]
```
(?i).*(css|js|jpeg|jpg|gif|png|bmp|wmv|exe|mp4)
```
For php, it contains request parameters. 
```
.*php\?.*
```

**Comment by PakanAngel** [comment]
Thnx a lot @marevol . Another question is how can I exclude an entire URL which contains a specific word? Words like category or tag
e.g.:
http://www.example.org/category/65354/discussion
What would be the correct regexp to exclude category from the above URL?

**Comment by marevol** [comment]
```
.*category.*
```
This is Java Regular Expression.
