### ISSUE TITLE
Plugins for elasticsearch 6.1.1

### ISSUE THREAD

**Issue by markcamos** [codelibs/fess#1419]
Do I use the same elasticsearch plugins (below) with Fess 12 and elasticsearch 6.1.1 or do these need to change:
/usr/share/elasticsearch/bin/elasticsearch-plugin install org.codelibs:elasticsearch-analysis-fess:5.6.2
/usr/share/elasticsearch/bin/elasticsearch-plugin install org.codelibs:elasticsearch-analysis-ja:5.6.1
/usr/share/elasticsearch/bin/elasticsearch-plugin install org.codelibs:elasticsearch-analysis-synonym:5.6.1
/usr/share/elasticsearch/bin/elasticsearch-plugin install org.codelibs:elasticsearch-configsync:5.6.1
/usr/share/elasticsearch/bin/elasticsearch-plugin install org.codelibs:elasticsearch-dataformat:5.6.1
/usr/share/elasticsearch/bin/elasticsearch-plugin install org.codelibs:elasticsearch-langfield:5.6.1
/usr/share/elasticsearch/bin/elasticsearch-plugin install org.codelibs:elasticsearch-minhash:5.6.1

**Comment by marevol** [comment]
Elasticsearch I/F does not have backward compatible.
See [Installation Guide](http://fess.codelibs.org/12.0/install/install.html).
