### ISSUE TITLE
Crawling & Threads....

### ISSUE THREAD

**Issue by looper976** [codelibs/fess#1420]
I am looking at crawling 100+ sites per crawler configuration. If I set threads = 20, does the crawler work sequentially through the list of sites, finishing one site before going to the next, or will it allocate those 20 threads to multiple sites concurrently?

Related, is there a way to view the current queue of URLs to be crawled? I see the crawling log, but it does not appear to show this very clearly.

**Comment by marevol** [comment]
The number of threads for Crawler is [Simultaneous Crawler Config](http://fess.codelibs.org/12.0/admin/general-guide.html#simultaneous-crawler-config) x [The number of Thread](http://fess.codelibs.org/12.0/admin/webconfig-guide.html#the-number-of-thread).

No UI for checking url queue.
