### ISSUE TITLE
FESS with Ldap

### ISSUE THREAD

**Issue by rishikumarshaw** [codelibs/fess#1422]
Please suggest steps to implement LDAP integration for Authentication in FESS 11.4.4. We are trying to implement in Win server 2012 R2.

**Comment by marevol** [comment]
See [LDAP Configuration](http://fess.codelibs.org/12.0/admin/general-guide.html#ldap-configuration).

**Comment by rishikumarshaw** [comment]
Thank you @marevol . One issue, how can we bind authentication with AD group, and check if user trying to login belongs to AD group. And secondly, how to provide admin role to all user from AD group. Please suggest.

**Comment by rishikumarshaw** [comment]
Dear @marevol is there any way we can provide Admin role to AD security group members.

**Comment by marevol** [comment]
Try to add users/groups to
```
authentication.admin.users=admin
authentication.admin.roles=admin
```
in fess_config.properties.
