### ISSUE TITLE
extract eml attachments

### ISSUE THREAD

**Issue by arengore** [codelibs/fess#1423]
Hello,

Thanks for the nice project, surely the more complete opensource enterprise search software.
But looks like Fess doesn't extract eml attachments as I tried with a few files.

Maybe I'm missing something or it's unsupported?

If this is the case, is it possible to add this features like other opensource search engines?

Cheers

**Comment by marevol** [comment]
For eml, Fess Crawler does not support attachments at the moment. Could you give me .eml file with attachments as a sample file?

The source code for Fess Crawler is [here](https://github.com/codelibs/fess-crawler). .eml extractor is [EmlExtractor](https://github.com/codelibs/fess-crawler/blob/master/fess-crawler/src/main/java/org/codelibs/fess/crawler/extractor/impl/EmlExtractor.java).

**Comment by arengore** [comment]
Oh well, here is a sample.

I really appreciate your help.

[Exkursion.eml.zip](https://github.com/codelibs/fess/files/1609308/Exkursion.eml.zip)

**Comment by marevol** [comment]
Thank you for the info.
Fixed. eml attachment will be supported in next release.

**Comment by arengore** [comment]
Thanks for your help @marevol!
