### ISSUE TITLE
Admin API - Create Scheduler bug

### ISSUE THREAD

**Issue by defensivedepth** [codelibs/fess#1424]
I have been working with 11.4.6 & 12.0 with these docs: 
http://fess.codelibs.org/11.4/lastadoc-fess.html#.api.admin.scheduler.setting::put_d_setting

I am able to create a web crawler as well as a scheduler - however, the scheduled job gets created with Crawler Job & Status disabled, and I cannot start the crawler through the Admin API with it disabled. No matter how I try and create the scheduler job, it never enables it.

Here is what I am sending to create the job: 

`{"name":"Scheduler-Test","target":"all","script_type":"groovy","script_data":"return container.getComponent(\"crawlJob\").logLevel(\"info\").sessionId(\"KGbJzGABNFb2ZLGNJe-H\").webConfigIds([\"KGbJzGABNFb2ZLGNJe-H\"] as String[]).fileConfigIds([] as String[]).dataConfigIds([] as String[]).jobExecutor(executor).execute();","crawler":"true","job_logging":"true","available":"true","sort_order":0}`

This results in the following scheduler job being created:

![screen shot 2018-01-06 at 2 15 15 pm](https://user-images.githubusercontent.com/954732/34643093-5185a13c-f2ec-11e7-808c-93e15b0938ea.png)

Is this a known issue?

Thanks

**Comment by marevol** [comment]
Replace with "on" as below:

    ..."crawler":"on","job_logging":"on","available":"on"...

Boolean will be supported in a next release.

**Comment by defensivedepth** [comment]
Perfect, that works, thanks. I tried "enable" as well.. Didn't think to try "on" .

Thanks again
