### ISSUE TITLE
Optimize index or any other operation on index failed with 406

### ISSUE THREAD

**Issue by rhayun** [codelibs/fess#1426]
Hi
i am using fess latest version 12.0 with Elasticsearch 6.1.1

when i try to do anything with index in the dashboard i get failed with this message

Content-Type header [application/x-www-form-urlencoded] is not supported

i believe its something with elasticsearch version 6 but cant find how to fix it
will appreciate your help

thanks

**Comment by marevol** [comment]
Fess uses forked kopf. The source code is [fess-6.0](https://github.com/codelibs/elasticsearch-kopf/tree/fess-6.0) branch.
Any contributions are welcome.
