### ISSUE TITLE
How to set the number of characters before and after the hit word in the search result?

### ISSUE THREAD

**Issue by JiroSato** [codelibs/fess#1427]
Hi!
Please tell me how to set the number of characters before and after the hit word in the search result?

**Comment by marevol** [comment]
Highlight settings are as below in fess_config.properties.

```
query.highlight.fragment.size=50
query.highlight.number.of.fragments=5
```

For more details, see [Highlighting](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html).

**Comment by JiroSato** [comment]
Thank you @marevol ^^
