### ISSUE TITLE
The authority information of the AD / LDAP group is not reflected in the search results

### ISSUE THREAD

**Issue by shiro-note** [codelibs/fess#1428]
I am trying to divid search results by Active Directory.
I am able to log in with AD.

However, the search result by the group of AD linked to the logged-in user is not reflected.

The file crawl is done normally, and I checked [System Info] > [Search] > file[Update] > [role], and the group role of the AD set in the shared folder was reflected correctly.
If the user name is specified directly in the file access permission and the user logs in, the search result will be displayed.

When I tried it in another environment, I linked the AD group and reflected the information on the search result, but I can not clarify the cause.

Could you suggest possible causes and remedies?
I need your help.

**Comment by maki-note** [comment]
I solved this problem on my own.
I referred to the following https://ja.osdn.net/projects/fess/forums/18580/38229/.

It seems that the group was nested within the group, so it was not reflected in the search result.
Are you planning to deal with this issue in the future?

**Comment by marevol** [comment]
We will fix it in a future release.

**Comment by maki-note** [comment]
Thank you for your reply.
I expect it.
