### ISSUE TITLE
Dashboard Rest UI - Error:  Content-Type header

### ISSUE THREAD

**Issue by defensivedepth** [codelibs/fess#1429]
Using FESS 12.0 with included ES. When I run a POST request from the Dashboard Rest UI, I get the following error: 

`{
  "error": "Content-Type header [application/x-www-form-urlencoded] is not supported",
  "status": 406
}`

This appears to be related to how ES 6 changes Content-Type checking:

https://www.elastic.co/blog/strict-content-type-checking-for-elasticsearch-rest-requests

**Comment by marevol** [comment]
Fixed in #1426.

**Comment by defensivedepth** [comment]
Thanks!
