### ISSUE TITLE
Label usage question

### ISSUE THREAD

**Issue by rhayun** [codelibs/fess#1434]
Hello,

First wonderful work on this project

i have one domain with multiple subdomains
i created one web crawler like this:

```
URLs: http://www.mywebsite.com/
Included URLs For Crawling: http?s://www.mywebsite.com/.*
Excluded URLs For Crawling: 
  .*/admin/.*
  https?://sub.mywebsite.com/.*
  etc...
```

Also i created some labels - for example
```
Name: Label1
Value: label1
Included Paths: https?://www.mywebsite.com/games/.*
```

```
Name: Label2
Value: label2
Included Paths: https?://www.mywebsite.com/software/.*
```

now i start crawling and i can see results but its not labeled
like i see results like this
https://www.mywebsite.com/games/game1
and its not get the label: Label1

now i try to understand how to work properly with labels... should i select the label in the web crawling form also? or its enough to create the label with the settings..

when i add multiple labels into the web crawling form the results show the labels but each label store the same result

can you please light my way with this?

thanks

**Comment by marevol** [comment]
For the configuration, it looks good to me.
Disabling [Incremental crawling](http://fess.codelibs.org/12.0/admin/general-guide.html#check-last-modified), could you try it again?
If incremental crawling is enabled and an indexed page is not updated, labels information are also not updated.

**Comment by rhayun** [comment]
i unchecked "Check Last Modified" and its look.. will keep testing this

thanks
