### ISSUE TITLE
HTTP ERROR 404

### ISSUE THREAD

**Issue by iny** [codelibs/fess#1436]
Hello there,

I am experiencing such an error.

"HTTP ERROR 404" [Fess log](https://gist.github.com/ilkiny/ea957d0d8df9c79c6a392f3b50eefe20) 

Stay with love. @marevol

**Comment by marevol** [comment]
Need more info...
Could you provide steps to reproduce it?

**Comment by ilkiny** [comment]
Have you e-mailed? You can connect to the computer.

2018-01-13 14:55 GMT+03:00 Shinsuke Sugaya <notifications@github.com>:

**Comment by marevol** [comment]
I'd like to reproduce it in MY environment.
For others, see [Commercial Support](http://www.n2sm.net/en/support/fess_support.html).

**Comment by ilkiny** [comment]
So, what is the information I need to forward to you? @marevol

**Comment by ilkiny** [comment]
[Installation](http://fess.codelibs.org/12.0/install/install.html) 
I applied the steps one by one, it looks normal when I look at the service fess status report

Loaded: loaded (/usr/lib/systemd/system/fess.service; enabled; vendor preset:
Active: active (running) since Sat 2018-01-13 15:01:42 +03; 20 min ago

**Comment by marevol** [comment]
Did you install a rpm package? but your fess.log does not look like for rpm installation.

**Comment by ilkiny** [comment]
No, I manually installed it as "zip". @marevol

**Comment by marevol** [comment]
> Loaded: loaded (/usr/lib/systemd/system/fess.service; enabled; vendor preset:

What does it means??

For zip package, just run ./bin/fess

**Comment by marevol** [comment]
```
(Install Java 8 or 9 and then...)
$ wget https://github.com/codelibs/fess/releases/download/fess-12.0.0/fess-12.0.0.zip
$ unzip fess-12.0.0.zip
$ cd fess-12.0.0
$ ./bin/fess
```
That's it.
For zip package, systemd is not used.

**Comment by ilkiny** [comment]
I'm following the "./bin/fess" step but there is no response. @marevol

**Comment by marevol** [comment]
> there is no response.

Need more details...

**Comment by ilkiny** [comment]
I do not get an answer when I enter "./bin/fess" on SSH. And I get an error when I connect to localhost:8080 from the internet.

**Comment by marevol** [comment]
>  I get an error

Need more details...
Did you check log files?

**Comment by ilkiny** [comment]
Yep, you can look at it.

[Fess.log](https://gist.github.com/ilkiny/29efb1da48bb922616a307bfb0736d37)
[server_o.log](https://gist.github.com/ilkiny/2d5e86dfba319c179d0d7250fbfe572a)

**Comment by marevol** [comment]
> Caused by: org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{11hZc3jlQyWrwxH9bprcdQ}{localhost}{127.0.0.1:9300}]

Did you change configurations? For zip package, 9301 port should be used.

I think that it's better to try [this](https://github.com/codelibs/fess/issues/1436#issuecomment-357433628) on a clean environment...

**Comment by ilkiny** [comment]
The file I have configured [fess.in.sh](https://gist.github.com/ilkiny/d69a6fad6208409106dfdfbfedb4eeed)

**Comment by marevol** [comment]
Did zip package work by [this steps](https://github.com/codelibs/fess/issues/1436#issuecomment-357433628) without any changes?

**Comment by ilkiny** [comment]
Nope. @marevol

**Comment by ilkiny** [comment]
What should I do? @marevol

**Comment by ilkiny** [comment]
I installed the Windows server again, and I get the same error. @marevol

**Comment by marevol** [comment]
1. Create /tmp/test.sh on Ubuntu as below:
```
#!/bin/bash

cd /tmp
pkill java
rm -rf fess-12.0.0*
wget https://github.com/codelibs/fess/releases/download/fess-12.0.0/fess-12.0.0.zip
unzip fess-12.0.0.zip
cd fess-12.0.0
./bin/fess &
sleep 60
curl localhost:9201
curl localhost:8080
cat logs/*.log
pkill java
```

2. Run
```
bash -x /tmp/test.sh 2>&1 | tee /tmp/test.log
```

3. Check /tmp/test.log

**Comment by iny** [comment]
The problem has been solved.

The "JAVA_HOME" settings have been configured.
