### ISSUE TITLE
Doc boost if title contains / start with term

### ISSUE THREAD

**Issue by rhayun** [codelibs/fess#1438]
Hello

can you please help me to figure how to doc boost if title contain lets say the word "Home"
so its contains the word "Home" i want it to be above all the results in deepest depth

thanks

**Comment by rhayun** [comment]
Is this will work?

`title.trim().toLowerCase()​​​​​​​​​​​​​​​​​​​​​​​​​​​.startsWith("home")​​​​​ || title.trim().toLowerCase().startsWith("welcome")​`

then boost with 100?

**Comment by marevol** [comment]
Yes.
If you have a problem, check fess.log.

**Comment by fanjinfei** [comment]
Is it possible to boost at query time?  
https://www.elastic.co/guide/en/elasticsearch/reference/5.6/mapping-boost.html suggests to boost at query time instead of at indexing time.

**Comment by marevol** [comment]
`WORD^BOOST_VALUE`
ex. Fess^10
