### ISSUE TITLE
Canonical issue when there is more then one canonical tag

### ISSUE THREAD

**Issue by rhayun** [codelibs/fess#1440]
Hi there

i notice an issue when there is more then one canonical tag
for some reason my website (CMS) added by mistake two canonical tags and this is cause the crawler to skip it and not index

any help will be welcome

thanks

**Comment by rhayun** [comment]
its something like that:

Crawling URL: http://www.example.com/resources

CANONICAL: http://www.example.com/resources -> http://www.example.com/resources http://www.example.com/resources

INFO  Processing no docs (Doc:{access 1ms, cleanup 8ms}, Mem:{used 171MB, heap 243MB, max 494MB})

its just skip it
no crawling

**Comment by rhayun** [comment]
maybe its happen only when there is more then one canonical tag or if the canonical is relative URL and not full

**Comment by rhayun** [comment]
The solution is grab always the first one by doing this:
`crawler.document.html.canonical.xpath=//LINK[@rel='canonical'][1]/@href`

**Comment by marevol** [comment]
Fixed. Thanks!
