### ISSUE TITLE
Specify/Change Admin password from Docker run option or tomcat .xml file?

### ISSUE THREAD

**Issue by yuatasia** [codelibs/fess#1443]
Hi, Im new to FESS-on-docker and wonder how i can easily specify/change 
the Admin login password as a docker run option?
something like 
$docker run -e ADMIN_PASSWORD="my_new_password" codelibs/fess
would be very helpful.

the official document says, the authentication system relies on tomcat but
I couldn't find the "$TOMCAT_HOME/conf/tomcat-users.xml" file anywhere, either.

so, are there any ways to specify/change the user/password combination using commands?

**Comment by marevol** [comment]
No options.
Any contributions are welcome.

> I couldn't find the "$TOMCAT_HOME/conf/tomcat-users.xml" file anywhere, either.

It's information for old Fess(before Fess 10).

**Comment by nunofernandes** [comment]
Also interested on this....
