### ISSUE TITLE
the default [crawl target URL] and [search target URL] behavior?

### ISSUE THREAD

**Issue by yuatasia** [codelibs/fess#1444]
in the Web Crawling settings page,
when only the [URL] section has been specified with 
[Included URLs For Crawling] and [Included URLs For Indexing] left empty
what's gonna be the default behavior of the crawling and searching?
Would it be the same as specified as "http://abc.net/*"?

URL:http://abc.net/
Included URLs For Crawling:
Included URLs For Indexing:

**Comment by marevol** [comment]
It depends on your requirement.

Included URLs For Crawling -> URLs are crawled and indexed.
Included URLs For Indexing -> URLs are crawled, but are not indexed.
