### ISSUE TITLE
search result links doesn't open up

### ISSUE THREAD

**Issue by yuatasia** [codelibs/fess#1445]
another issue(?) with displaying search results.

after successfully crawling local file system 'file:/opt/fess-11.1.1/', (fess' its own config files)
i could see the returned search results with file names and clickable links.
however, unlike web crawling results where I can click the file link and open up to see the contents,
nothing happens clicking those file-system crawled files.

what might be wrong here?

**Comment by marevol** [comment]
Did you check log files?
