### ISSUE TITLE
search filetype:"txt" returns .bat .MD .yml .scss .policy ...

### ISSUE THREAD

**Issue by yuatasia** [codelibs/fess#1446]
where is the logic(code) defining a file type in fess system?
I want the search results to be precise that only files with the specified extension be returned.
(.txt files in this case)
also want to enable like filetype:"bat" but have no clue how to add that.
anyone?

**Comment by marevol** [comment]
See [app.xml](https://github.com/codelibs/fess/blob/master/src/main/resources/app.xml).
