### ISSUE TITLE
Remove urls from index

### ISSUE THREAD

**Issue by hottwerk** [codelibs/fess#1447]
Is it possible to remove already crawled urls from a index based on a regex? 
lets say: delete all .\*id_categorie=2.\* 

Or maybe filter them when search display?

**Comment by marevol** [comment]
You can remove it on [Admin Search](http://fess.codelibs.org/12.0/admin/searchlist-guide.html) page.

**Comment by hottwerk** [comment]
Yes, but is it possible to search url's based on regex? If so could you give a small example?

**Comment by marevol** [comment]
```
url:"http://fess.codelibs.org/*"
```

**Comment by marevol** [comment]
> url:"http://fess.codelibs.org/1*/install/*" doesn't work. 

It will be supported in a next release.

> how to escape characters in the search string?

`\*`

**Comment by marevol** [comment]
>> url:"http://fess.codelibs.org/1*/install/*" doesn't work.
>
> It will be supported in a next release.

Oops, it's not correct...
url:"..." is a phrase query with supporting a prefix query.
To use prefix/wildcard query, the query is:
```
url:http\:\/\/fess.codelibs.org\/*\/12.0\/*
```

**Comment by hottwerk** [comment]
That seems to work...better. Not totally like I would expect but now I can figure it out now.
Thank you!
