### ISSUE TITLE
HTTP error 404 - No webpage was found for web address

### ISSUE THREAD

**Issue by ArthurBV** [codelibs/fess#1448]
Hello,
Recently I've been working with Fess, I installed everything using RPM on an amazon server and it was working well without any issues. 
I had to stop both services (elasticsearch and fess) for a while and once I restarted them for some reason the error 404 began to pop out.
I'm currently using fess 12.0.0, I have uninstalled (using rpm and deleting the folders) and reinstalled everything again, even tried using the version 11.4 but the same error keeps appearing. The only workaround I've found is to use the .zip and run ./bin/fess, but I need to run it as a service. Any idea what might be causing this error?

Thanks in advance

**Comment by marevol** [comment]
Did you check log files?

> the error 404 began to pop out.

Is it on a dashboard page? Dashboard page accesses to Fess periodically even if Fess stops.

**Comment by ArthurBV** [comment]
I ended up creating a new instance and everything is working perfectly, thanks anyway.
Another question, does Fess work on port 80? I checked "fess_config.properties" under  etc/fess but I didn't find the line to change the port, I can see it is using port 8080 on the dashboard though. If possible can you direct me how to change it to said port? Thanks

**Comment by marevol** [comment]
See /usr/share/fess/bin/fess.in.sh.
