### ISSUE TITLE
Bug / Improvement - jqeury does not support .error

### ISSUE THREAD

**Issue by hottwerk** [codelibs/fess#1451]
I found that in fess 12.0 the thumnails didn't show (althoug they where on the server). Debugging gave a javascript error while loading so bootstrap could not finish its job.
The error: the .error() method is deprecated and not supported in jquery anymore.

Solution, I changed:

.\fess-12.0.0\app\js\search.js :  

       .error(function(       TO    .on('error', function(

That did the job and now thumbs are shown again.

**Comment by marevol** [comment]
Thanks. Fixed.
