### ISSUE TITLE
Page Not Found - Check the url

### ISSUE THREAD

**Issue by defensivedepth** [codelibs/fess#1452]
New FESS 12.0 + separate ES 6.1.1 install.

On the front-end search UI, clicking on any result leads to a FESS page that says:

Page Not Found
Check the url. 
<part of the target URL here>

I don't see anything relevant in the logs. Any ideas on what the issue is?

**Comment by marevol** [comment]
Could you check fess.log after changing a log level to debug?
The log level is in fess.in.[sh|bat].
```
FESS_JAVA_OPTS="$FESS_JAVA_OPTS -Dfess.log.level=warn"
```

**Comment by defensivedepth** [comment]
Thanks, that pointed me to the IIS reverse proxy we are using. Still troubleshooting, but it appears there is some trickery happening with the URL rewrite settings that is causing this.
