### ISSUE TITLE
Database connection

### ISSUE THREAD

**Issue by iny** [codelibs/fess#1468]
Hello there,

Details on the document are inadequate, do you have any information on how to do it? @marevol

**Comment by iny** [comment]
Can we also add the suggestion to the database? @marevol

**Comment by marevol** [comment]
See [DatabaseDataStore](http://fess.codelibs.org/12.0/admin/dataconfig-guide.html#databasedatastore).

**Comment by iny** [comment]
Should this be like this?

![1pm](https://user-images.githubusercontent.com/24559998/35512225-00314ac6-0510-11e8-9069-9630de51385f.png)

**Comment by iny** [comment]
Could you help me?

**Comment by marevol** [comment]
What is a problem?

**Comment by iny** [comment]
Is the screen image correct? Data is not entering the database. @marevol

**Comment by marevol** [comment]
Try it! Fess is Open Source Software. 
If you need supports, please contact [Commercial Support](http://www.n2sm.net/en/support/fess_support.html).

**Comment by iny** [comment]
Hello again,

How is the data stored? If it is stored, is it possible to convert it to sql? I tried it in many ways but it did not.
- I did not get a result from Github and I read your documents. If I think many people are facing the same problem.


Can you help me? At least tell them where the data is stored.

**Comment by iny** [comment]
In order to buy support packages, I need to know how it works. @marevol

**Comment by marevol** [comment]
Data Store Crawling adds data in database into fess index.
Using Data Store Crawling, knowledge of SQL is required.

**Comment by iny** [comment]
![Example](https://user-images.githubusercontent.com/24559998/35512225-00314ac6-0510-11e8-9069-9630de51385f.png) What's wrong here? He does not write data at all.

**Comment by marevol** [comment]
Is MySQL available? Did you put jar file to Fess?

**Comment by iny** [comment]
Yes, I did it as you wrote it on the document.

**Comment by marevol** [comment]
Need more info about all steps you did in order to reproduce it.
Your problem is unclear for me... 
Did you check log files? Did you check if MySQL works with SQL?

**Comment by iny** [comment]
Should I send you something else? @marevol

**Comment by marevol** [comment]
> Did you check log files? Did you check if MySQL works with SQL?

**Comment by iny** [comment]
![3423](https://user-images.githubusercontent.com/24559998/35782889-60cee474-0a10-11e8-9e64-99234bfb523d.png)

When I create Data Crawler, these are SQL logs.

But he is not doing any writing. "I can forward server information" @marevol

**Comment by josempolm** [comment]
Is the problem solved? I have the same problem. @iny @marevol

**Comment by iny** [comment]
Not yet, I'm waiting for reply. @josempolm

**Comment by marevol** [comment]
Did you check if mysql command connected to MySQL server?

**Comment by iny** [comment]
Yeah, I checked, but I did not understand what the problem was.

**Comment by marevol** [comment]
1. For Default Crawler, change a log level to "debug" at Admin Scheduler page
1. Start Default Crawler job
1. Check fess-crawler.log

**Comment by iny** [comment]
[fess-crawler.log](https://gist.github.com/iny/78a8846f772da8d49797fde4d012c7e6) I followed the steps you said.

**Comment by marevol** [comment]
> Caused by: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver

You did not put jar file. See [JDBC Driver](http://fess.codelibs.org/12.0/admin/dataconfig-guide.html#jdbc-driver).

**Comment by iny** [comment]
![48956730](https://user-images.githubusercontent.com/24559998/35822205-804e45d6-0abc-11e8-9b1a-df138dec6609.png) I've already put it in place.

**Comment by marevol** [comment]
Need more info...
Did you check log files?

**Comment by iny** [comment]
Yes, I've shared the most up to date with you.

**Comment by marevol** [comment]
> Caused by: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver

It means that jar file for mysql was not found.

**Comment by iny** [comment]
Yes, but I replaced the file.

**Comment by iny** [comment]
Any progress?

**Comment by marevol** [comment]
>  jar file for mysql was not found.

Check log files and MySQL jar file.

**Comment by iny** [comment]
As I said, I already checked.

**Comment by marevol** [comment]
> Caused by: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver

If MySQL jar file is found in Fess, the above exception will be disappeared.

**Comment by iny** [comment]
I have already uploaded the files I did as you said, do I send the server information?

**Comment by iny** [comment]
[jar file](https://user-images.githubusercontent.com/24559998/35822205-804e45d6-0abc-11e8-9b1a-df138dec6609.png) Could you please look? I have placed files.

**Comment by iny** [comment]
![d1553289](https://user-images.githubusercontent.com/24559998/35887533-a00a94d0-0ba5-11e8-91cb-b63086ef23d4.png) These job log data records.

**Comment by iny** [comment]
Incidentally, there is a sample output in Search results coming from sql.


- Are we not able to overwrite the indexes we searched over in SQL?

**Comment by iny** [comment]
![r536](https://user-images.githubusercontent.com/24559998/35887810-8d4e8a4e-0ba6-11e8-8f49-8066a62871fb.png) As an example we have added

**Comment by iny** [comment]
[This](https://github.com/codelibs/fess/blob/81be3de0381fb78e6596303a3b520e8c3d1f7d3d/src/main/config/mysql/fess.ddl) is it disabled?

**Comment by marevol** [comment]
Deprecated.
Data Store Crawling is for crawling database or other data sources.

**Comment by iny** [comment]
> This is it disabled? Can you tell me where I can change the database settings?

How can I bring it back?

**Comment by marevol** [comment]
I think you mixed the following:
1. Store Fess configuration into DB
2. Crawl data in DB and then store them into Fess index

For 1, old Fess (1.x-9x) saved configuration to DB, and the schema is fess.dll. Old Fess is EOLed. Fess 10.x- does not use DB to store configurations.

2 is Data Store Crawling.

**Comment by iny** [comment]
>Crawl data in DB and then store them into Fess index

Can I add scanned data to the DB?

**Comment by marevol** [comment]
All data are in elasticsearch.
You can get them from elasticsearch, and then feel free to use them...

**Comment by iny** [comment]
Thank you very much.

**Comment by iny** [comment]
I could not find anything, can you help?

**Comment by iny** [comment]
Comment and Close
