### ISSUE TITLE
documents show up in /admin/search but not search

### ISSUE THREAD

**Issue by markcamos** [codelibs/fess#1471]
When I search in the admin console (System Info/Search) I see several dozen results

http://devel-fess/admin/searchlist/?lastaflute.action.TRANSACTION_TOKEN=...&q=optispray&search=Search

When I do a search using http://devel-fess/search/?q=Optispray&num=20&sort=

I get none.

Why the difference?

**Comment by markcamos** [comment]
Yes, to both questions above. 

When I tried it this morning they both return the same result.

What would have caused them to be different yesterday and the same today?

**Comment by marevol** [comment]
See [Permission](http://fess.codelibs.org/12.0/admin/webconfig-guide.html#permissions).

**Comment by markcamos** [comment]
Rguest is apparently allowed to access the results - according to http://devel-fess/admin/searchlist/

Is it necessary to specify role in the query for http://devel-fess/search?
