### ISSUE TITLE
Can I use basic authentication with fess ?

### ISSUE THREAD

**Issue by tknao** [codelibs/fess#1482]
Can I use basic authentication with fess system?

I would like to use basic authentication with fess UI, but I can not find tomcat-users.xml.

I use a reverse proxy with apache 2.4 (ProxyPass  http://127.0.0.1:8080/).

Is there a way to use basic authentication?

**Comment by marevol** [comment]
No. It's better to set Basic authentication to Apache server.

**Comment by tknao** [comment]
Thank you for your comment.
I will set it up with Apache server.

**Comment by tknao** [comment]
I set set Basic authentication to Apache server.
  <Location /fess >
                ProxyPass http://127.0.0.1:8080/ 
                ProxyPassReverse  http://127.0.0.1:8080/
                 AuthType Basic
                 AuthUserFile "/etc/apache2/.htpasswd"
                 AuthName "Member Certification"
                 Require valid-user
   </Location>

When I used google chrome,The authentication dialog box is displayed many times.
( Firefox  and MS edge, safari has no problem.)

Details;
When entering search form and suggesting function works.
When search button is pushed.

Are these google chrome bugs?
I would be grateful if you would have solution.
