### ISSUE TITLE
Crawling wikipedia?

### ISSUE THREAD

**Issue by ArthurBV** [codelibs/fess#1490]
Hello,

Is it possible to crawl wikipedia using the fess crawler? I have reduced the boost and interval time since wikipedia has some restrictions. But I haven't been able to crawl their sites (only the main page is crawled and indexed)

Thanks!

**Comment by marevol** [comment]
Need more info... ex. what is your crawling configs?

**Comment by ArthurBV** [comment]
Here is the configuration: 
![image](https://user-images.githubusercontent.com/35460692/36035904-59310516-0d86-11e8-82a9-57b4cdb65476.png)
I tried putting on "Included URLs For Crawling": https://es.wikipedia.org/wiki/.* but it didn't work either.

Also I created this job to schedule the crawling:

![image](https://user-images.githubusercontent.com/35460692/36036163-1ea3c6d0-0d87-11e8-81f2-12ec96a46f13.png)

**Comment by marevol** [comment]
Interval time is too long.
I tried it and wikipedia pages were indexed.

**Comment by ArthurBV** [comment]
What interval time are you using?

**Comment by marevol** [comment]
To check it in my environment, settings are:
```
URL: https://es.wikipedia.org/wiki/
Include URL: https://es.wikipedia.org/wiki/.*
Interval time: 1000
Max Access Count: 10
```

**Comment by ArthurBV** [comment]
Thanks a lot, everything appears to be working correctly.
