### ISSUE TITLE
Convert data to sql

### ISSUE THREAD

**Issue by josempolm** [codelibs/fess#1492]
Hello,

How can I convert searched data to sql?

**Comment by marevol** [comment]
You can access data in fess.search index to elasticsearch.
[Elasticsearch SQL](https://github.com/NLPchina/elasticsearch-sql) might work.

**Comment by josempolm** [comment]
[Data Store](https://fess.codelibs.org/12.0/admin/dataconfig-guide.html#databasedatastore) Does not work?

**Comment by marevol** [comment]
Data Store Crawling crawls data in DB and stores them into Fess index.

**Comment by josempolm** [comment]
What do we need to do to transfer the scanned data to the database? Will such a feature come?

**Comment by marevol** [comment]
See [elasticsearch reference](https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html).

**Comment by josempolm** [comment]
How can I use my Kibana? In connection with Fess.


- Can I also transfer mysql data on the kibana?

**Comment by marevol** [comment]
It's better to ask Kibana community.

**Comment by josempolm** [comment]
Does all data reside on elasticsearch, Does database support come in the future?

**Comment by marevol** [comment]
Why does Fess support data export to database?
Did you check elasticsearch features?

**Comment by josempolm** [comment]
Yes I did, but I do not understand, we need to transfer it to the database for the school to be distributed as data sharing.

**Comment by marevol** [comment]
If you need more supports, please contact [Commercial Support](https://www.n2sm.net/en/support/fess_support.html).
