### ISSUE TITLE
Can I add data for additional field using datastore crawl after file crawl?

### ISSUE THREAD

**Issue by JiroSato** [codelibs/fess#1495]
Hi!
Can I add data for additional field using datastore crawl after file crawl?
I would like to integrate the results of data store crawl and data store crawl.

https://qiita.com/chocomaro/items/32f822ac64f37cdebb08

**Comment by marevol** [comment]
No. DataStore Crawling cannot merge with File System Crawling, but you can invoke CrawlerClient to access other documents in DataStore Crawling.

**Comment by JiroSato** [comment]
Thank you for your reply.

I'd appreciate it if you give me more information about DataStore Crawling.
I referred to [this page](https://fess.codelibs.org/12.0/admin/dataconfig-guide.html#databasedatastore), but I couldn't find enough information to understand how to invoke CrawlerClient.

I would like to use text extraction of FileCrawl.
