### ISSUE TITLE
JSON Search: Disable highlighting

### ISSUE THREAD

**Issue by defensivedepth** [codelibs/fess#1502]
FESS 12.01 on Windows Server 2012 R2.

I checked the docs, but I don't see a way to disable the highlight params on JSON search? 

I don't want the  `<strong><\/strong>` tags included in the JSON results.

Thanks,

**Comment by marevol** [comment]
Add the following property tags in app/WEB-INF/classes/app.xml:

```
...
        <component name="viewHelper" class="org.codelibs.fess.helper.ViewHelper">
                <property name="highlightTagPre">""</property>
                <property name="highlightTagPost">""</property>
                <postConstruct name="addFacetQueryView">
...
```

**Comment by defensivedepth** [comment]
Great, thanks!
