### ISSUE TITLE
FTP supported or not?

### ISSUE THREAD

**Issue by draganpodvezanec** [codelibs/fess#1503]
Hi,

Just trying fess 12, and I don't see FTP support, but I see that

https://github.com/codelibs/fess/issues/493

Is closed. So, is FTP supported or not?

Best regards.

**Comment by marevol** [comment]
FTP is supported in File System Crawling.

**Comment by draganpodvezanec** [comment]
Hi. 

Thank you for answer. 

I'm trying to crawl local FTP server on LAN which has no authentication (anonymous allowed, I can browse it in any web browser without authentication).

When I try to run a job, I see in crawler log:

2018-02-14 09:59:23,218 [WebFsCrawler] INFO  Target Path: ftp://10.40.62.1/
2018-02-14 09:59:23,418 [Crawler-phtwk2EB7Fs2Bzh0IzrQ-1-1] INFO  Crawling URL: ftp://10.40.62.1/
2018-02-14 09:59:23,742 [Crawler-phtwk2EB7Fs2Bzh0IzrQ-1-1] INFO  Failed FTP request: 530 Please login with USER and PASS

I try also to create "anonymous" user with "guest" password, and use

{user}anonymous  in permissions

But I get the same error. Do you have an idea how can I crawl anonymous FTP?

**Comment by marevol** [comment]
See [File Authentication](https://fess.codelibs.org/12.0/admin/fileauth-guide.html), not users and permissions.

**Comment by draganpodvezanec** [comment]
Thank you, it works fine now.
