### ISSUE TITLE
Remove out of date results

### ISSUE THREAD

**Issue by defensivedepth** [codelibs/fess#1511]
ES 6.1.1 + FESS 12.01 on Windows Server 2012 R2.

I crawled a website a month ago - some of the FESS results from this crawl are now 404s. 

I re-crawled this same website this week, with a new web crawler config - new results were added to FESS for the website, but the FESS results from the first crawl that are now 404s were not removed from FESS. 

How do I configure FESS to remove results that are no longer relevant / found on the site?

Here are my crawler settings:

![image](https://user-images.githubusercontent.com/954732/36315772-7f99cfdc-1306-11e8-881b-93c3bf46affd.png)

**Comment by marevol** [comment]
"Remove Documents Before 360 Days" means "Remove expired(removed) documents 360 days later".
So, they will be removed 360 days later.
If you remove them now, you need to do that manually because they are not updated even if starting re-crawl.

**Comment by defensivedepth** [comment]
Ah, ok. I was under the impression that "Remove Documents Before 360 Days" meant that FESS will delete the document from the index in 360 days, no matter if it was still valid or not.

Thanks, this makes more sense now.
