### ISSUE TITLE
how to reset login password!?

### ISSUE THREAD

**Issue by yuatasia** [codelibs/fess#1520]
hi,
I've forgot my login ID/password and can't log into my fess server.
how can I a reset my password or add a new admin/admin to my fess?
thanks!

**Comment by marevol** [comment]
```
curl -XPOST "localhost:9201/.fess_user.user/user/YWRtaW4=" -d '
{"password":"8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918","surname":"admin","roles":["YWRtaW4=","Z3Vlc3Q="],"name":"admin"}
'
```
For Fess 11, the index is ".fess_user".

**Comment by josempolm** [comment]
What is the index link for scanned links?
