### ISSUE TITLE
Question: How to force showing file names instead of file title tag in search results page?

### ISSUE THREAD

**Issue by PakanAngel** [codelibs/fess#1521]
I have realized that some results links are different than the original file name. It looks like the result page is  showing the file title tag instead of the original file name. 
1- Does fess record the file name or it just capture the file title tag?
2- If the file name is scanned and recorded in indices, how can I force the result page to show the file name instead of the file title tag?
3- If not, how can I change automatically all the file's title tag in a specific folder to their own file names?

**Comment by marevol** [comment]
You can edit JSP file on [Page Design](https://fess.codelibs.org/12.1/admin/design-guide.html) and use ${doc.filename}.

**Comment by PakanAngel** [comment]
Can you please show me where in the .jsp file do I have to put the ${doc.filename}?

**Comment by marevol** [comment]
searchResults.jsp

**Comment by PakanAngel** [comment]
Thanks but where in this statement do i have to put ${doc.filename}?
Cannot find the right place for it.
Should I replace it with ${doc.url_link} or ${doc.doc_id}?


I guess this where it's drawing the title of each found file

```
<h3 class="title ellipsis media-heading">
								<a class="link" href="${doc.url_link}" data-uri="${doc.url_link}"
									data-id="${doc.doc_id}" data-order="${s.index}">${f:h(doc.content_title)}</a>
							</h3>

```
Can you correct the a element based of my request? Please

**Comment by PakanAngel** [comment]
Thank you found it. 
The correct <a> element's properties would be:
```
<h3 class="title ellipsis media-heading">
	<a class="link" href="${doc.url_link}" data-uri="${doc.url_link}"
	data-id="${doc.doc_id}" data-order="${s.index}">${f:h(doc.filename)}</a>
</h3>
```
How can I check that if the current media is a web file or a local file?
I want to arrange things so that when the media is a web file its title tag should be displayed and when it is a local file than its file name, instead of document contet_title.
