### ISSUE TITLE
Question : fess_config.properties change default location.

### ISSUE THREAD

**Issue by acossette1979** [codelibs/fess#1522]
Hi,
Is there a way to make fess look into another location for this fess_config.properties file ?
I'm running it in kubernetes, and I would like to create a configmaps for this file and expose it in another directory.  I try a symlink but it's not working.

**Comment by marevol** [comment]
Try to change FESS_CONF_PATH in /etc/sysconfig/fess.

**Comment by acossette1979** [comment]
It works for fess_config.properties, but not for fess*.bulk 
Is there a way to force fess to import it into ES at startup ?

**Comment by marevol** [comment]
This question is for location of fess_config.properties.
Mixing questions is not good...
