### ISSUE TITLE
Question: What is to be set to dedicate fess to a specific language?

### ISSUE THREAD

**Issue by PakanAngel** [codelibs/fess#1523]
I have read all questions regarding the term "language".
I am still not able to figure out how the language properties should be set and changed for a specific language. 
It looks like there is mapping list for some languages, do I have to activate them or they are all activated by default. It doesn't look they are all activated cause the mapping has no effect.
Some more helps and description about language settings would be appreciated.

**Comment by PakanAngel** [comment]
Character mapping or word mapping does not work for me. 
How should I enable it?

**Comment by marevol** [comment]
See [langfield plugin](https://github.com/codelibs/elasticsearch-langfield).
