### ISSUE TITLE
Install plugins for ES 6.2.1 offline

### ISSUE THREAD

**Issue by goldenivan** [codelibs/fess#1532]
Hi everyone,

I am trying to install ES with Fess v12.1.0. I am behind a proxy and can't download from internet. When I have to install plugins for ES, like this : 

/usr/share/elasticsearch/bin/elasticsearch-plugin install org.codelibs:elasticsearch-analysis-fess:6.2.1

It's not working. So, I checked how to execute an offline install. For example, I downloaded the zip-file for dataformat from this page : https://github.com/codelibs/elasticsearch-dataformat/releases

Then, I used this command : 

sudo /usr/share/elasticsearch/bin/elasticsearch-plugin install file:///MyPath/elasticsearch-analysis-fess-elasticsearch-analysis-fess-6.2.1.zip

1. The name is doubled, I don't know why
2. The zip release is the git repo

==> How can I get the zip file to install plugins for ES ?

**Comment by marevol** [comment]
The simple way is:

1. Download and unzip elasticsearch ZIP file in your local machine
2. To download plugins, run elasticsearch-plugin commands
3. Copy plugins directory to elasticsearch in your server

> The zip release is the git repo

The zip file is not a plugin file. ES plugins are in Maven Central.

**Comment by goldenivan** [comment]
Hi, I downloaded all plugins from the Maven Central : https://repo1.maven.org/maven2/org/codelibs/

I Then installed all plugins listed in the documentation. For some plugins, I've got some warning : 

Warning : plugin requires additional permissions

1. elasticsearch-analysis-fess-6.2.1.zip
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission getClassLoader
* java.lang.reflect.ReflectPermission suppressAccessChecks


2. elasticsearch-analysis-ja-6.2.1.zip
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission getClassLoader
* java.lang.reflect.ReflectPermission suppressAccessChecks

3. elasticsearch-configsync-6.2.1.zip
* java.io.FilePermission <<ALL FILES>> read,write

4. elasticsearch-dataformat-6.2.1.zip
* java.lang.RuntimePermission getClassLoader

5. elasticsearch-langfield-6.2.1.zip
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission getClassLoader
* java.lang.reflect.ReflectPermission suppressAccessChecks

elasticsearch-analysis-synonym and elasticsearch-minhash have no troubles.

Are these warnings a problem?

**Comment by marevol** [comment]
It's not a problem. These plugins need permissions.

**Comment by goldenivan** [comment]
This solution worked for me, I close this issue.
