### ISSUE TITLE
Crawler does not work correctly. org.lastaflute.di.core.factory.dixml.exception.DiXmlParseFailureException

### ISSUE THREAD

**Issue by rporange** [codelibs/fess#1533]
Hello,

First, thank you for FESS, it's a great software!
I'm a new user and I'm testing the latest zip (FESS 12.1.0) on Ubuntu 16.04 with IBM Java8 (bug report details at the end).
Installation seems alright as I can access the admin dashboard (1 node, 44 indices, ...).

My first test is to setup a new File System crawler through the Wizard and launch it manually from the Job Scheduler as suggested in the documentation.
But it has stopped almost instantly.
From the logs, I have found this strange output:

```
2018-02-27 17:22:18,339 [main] INFO  ...Reading     lastaflute_assist.xml
2018-02-27 17:22:18,347 [main] INFO  ...Reading       lastaflute_director.xml
2018-02-27 17:22:18,444 [main] ERROR Crawler does not work correctly.
org.lastaflute.di.core.factory.dixml.exception.DiXmlParseFailureException: Look! Read the message below.
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
Failed to parse the dependency XML.

[Dependency XML]
lastaflute_director.xml included by lastaflute_assist.xml
* * * * * * * * * */
	at org.lastaflute.di.core.factory.dixml.DiXmlLaContainerBuilder.throwDependencyXmlParseFailureException(DiXmlLaContainerBuilder.java:92) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.core.factory.dixml.DiXmlLaContainerBuilder.parse(DiXmlLaContainerBuilder.java:79) ~[lasta-di-0.7.5.jar:?]
```

Here the content of ./app/WEB-INF/classes/lastaflute_director.xml

```
<!DOCTYPE components PUBLIC "-//DBFLUTE//DTD LastaDi 1.0//EN"
	"http://dbflute.org/meta/lastadi10.dtd">
<components>
	<component name="assistantDirector" class="org.codelibs.fess.mylasta.direction.FessFwAssistantDirector"/>
	<component name="fessConfig" class="org.codelibs.fess.mylasta.direction.FessConfig$SimpleImpl"/>
</components>
```
Seems ok with xmllint and vanilla from lastest sources.

I have tried to understand what's is going on but so far I have not any trail.

Best

Here the Properties for Bug Report:
```
file.separator=/
file.encoding=UTF-8
java.runtime.version=8.0.5.0 - pxa6480sr5-20170905_01(SR5)
java.vm.info=JRE 1.8.0 Linux amd64-64 Compressed References 20170901_363591 (JIT enabled, AOT enabled)
J9VM - d56eb84
JIT  - tr.open_20170901_140853_d56eb84
OMR  - b033a01
java.vm.name=IBM J9 VM
java.vm.vendor=IBM Corporation
java.vm.version=2.9
os.arch=amd64
os.name=Linux
os.version=4.4.0-22-generic
user.country=US
user.language=en
user.timezone=Europe/Paris
```

**Comment by marevol** [comment]
Could you put all stacktraces from logs?

**Comment by rporange** [comment]
Hello,

Certainly. Below the lastest log files:

[fess.log](https://github.com/codelibs/fess/files/1767005/fess.log)
[fess-crawler.log](https://github.com/codelibs/fess/files/1767006/fess-crawler.log)
[server_0.log](https://github.com/codelibs/fess/files/1767009/server_0.log)

Embedded ES is responding:
curl http://localhost:9201
{
  "name" : "Node 1",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "f54xzTfPQ4Sch2oJfUGHNA",
  "version" : {
    "number" : "6.2.1",
    "build_hash" : "7299dc3",
    "build_date" : "2018-02-07T19:34:26.990113Z",
    "build_snapshot" : false,
    "lucene_version" : "7.2.1",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}

Best

**Comment by marevol** [comment]
Thanks. Reproduced. Fess does not seem to work on J9.

**Comment by marevol** [comment]
To run on J9, a workaround is:

```
cp -r lib/classes/javax app/WEB-INF/env/crawler/resources/
cp -r lib/classes/javax app/WEB-INF/env/thumbnail/resources/
cp -r lib/classes/javax app/WEB-INF/env/suggest/resources/
```

**Comment by rporange** [comment]
Hello,

Thank you for the workaround. I will test it ASAP.

FESS is working perfectly so far (including a test crawl) with openjdk-8-jre but not with openjdk-9-jre.

Best
