### ISSUE TITLE
crawler.document.html.pruned.tags properties does not support "-" ?

### ISSUE THREAD

**Issue by Vincent-Dej** [codelibs/fess#1534]
Hi,

When i configure /etc/fess/fess_config.properties to set crawler.document.html.pruned.tags with value "...,div[class=custom-footer]", the "content" value is null for indexed page.

If i remove "div[class=custom-footer]", the content is correct.

Does the pruned.tags param allow "-" in his string ?

Thanks a lot

(Fess 11.3.3 / ES 5.6.4)

**Comment by marevol** [comment]
I'll fix it in a next release.

**Comment by Vincent-Dej** [comment]
thanks a lot !
