### ISSUE TITLE
Unable to index the content of page 2 and next

### ISSUE THREAD

**Issue by Vincent-Dej** [codelibs/fess#1542]
Hello,

I want to crawl a forum. When i crawl a topic with multiple pages, Fess indexed only the "content" of the first page.
Title and url are good for pages 1,2,3, ... , but content and cache have always the value of the first page. 

I have set "crawler.document.html.canonical.xpath=" (null) in /etc/fess/fess_config.properties.

I'm using Fess 11.4.9 and ES 5.6.4

Thanks, 
Vincent

**Comment by marevol** [comment]
Did you check if HTML of the first page contains links for next pages by curl command or the like?

**Comment by Vincent-Dej** [comment]
yes it is.

Example : 
For page 1; title="My example"; content="The text of my example"
For page 2; title="My example - page 2"; content="The text of my example in page 2"
For page 3; title="My example - page 3"; content="The text of my example in page 3"

Fess crawl :
For page 1; title="My example"; content="The text of my example"
For page 2; title="My example - page 2"; content="The text of my example"
For page 3; title="My example - page 3"; content="The text of my example"

Fess found, crawled and indexe all the  pages, but the content is always the same : The first page content

**Comment by marevol** [comment]
I think that the site returns the same content.
It might works if changing UA in crawling config.
If it does not work, it's better to ask system administrator for the site.

**Comment by Vincent-Dej** [comment]
I change UA in Fess by my Firefox UA.
Cache value is up to date, thanks !
