### ISSUE TITLE
Integration in other websites

### ISSUE THREAD

**Issue by goldenivan** [codelibs/fess#1551]
Hi everyone,

Is there a way to integrate the search results into another website ? For example, I've got some Drupal websites. Which one can be named **www1.drupal.com**. The virtual host associated with it in Fess would be named **www1**. 

I would like to display search results from this website, especially from the virtual host **www1** directly in the website **www1.drupal.com**.

Thank you in advance for your answers.

**Comment by marevol** [comment]
How about using [Fess Site Search (FSS)](https://fss-generator.codelibs.org/)?
FSS is like alternatives to Google Site Search (GSS) by using Fess.

**Comment by goldenivan** [comment]
It was a perfect solution for us !
