### ISSUE TITLE
cannot delete index from dashboard

### ISSUE THREAD

**Issue by freestyle68** [codelibs/fess#1552]
Hi,

Fess 12.1.1 (zip version).
When I try to delete an index from Kopf interface I get the error: 
```
"error": "Content-Type header [text/plain;charset=UTF-8] is not supported",
  "status": 406
```

With Fess 11.4.10 no problem.

Thank you

**Comment by marevol** [comment]
Fixed in https://github.com/codelibs/elasticsearch-kopf/tree/fess-6.0
It'll be fixed in a next release.

**Comment by freestyle68** [comment]
It works, thank you!
