### ISSUE TITLE
results per page unexpected reset

### ISSUE THREAD

**Issue by freestyle68** [codelibs/fess#1554]
Hi,

with the new version there is an unexpected behavior:

when I set for example 20 results per page and then I click on a file type filter, the number reset to 10.

Instead, the sort and languages filters on search options remains unchanged after selecting a file type (correctly).
Why this discrepancy?

**Comment by marevol** [comment]
I could not reproduce it...

**Comment by marevol** [comment]
I could not reproduce it in my local environment, but I improved session handling in #1566.

**Comment by freestyle68** [comment]
This solved, now the fronted behavior is much improved.

Thank you!
