### ISSUE TITLE
Json Output Settings

### ISSUE THREAD

**Issue by iny** [codelibs/fess#1555]
Hello,

There are places I do not want to show at the Json outlet, how do I set it up?

- Also, are there character limits in texts?
- Is there a key to show all the search?

**Comment by marevol** [comment]
You can add fields in fess_config.properties
```
query.additional.api.response.fields=
```
To specify fields to display, add setApiResponseFields in app.xml.
```
	<component name="queryHelper" class="org.codelibs.fess.helper.QueryHelper">
		<property name="defaultFacetInfo">facetInfo</property>
		<postConstruct name="addHighlightField">
			<arg>"title"</arg>
		</postConstruct>
		<postConstruct name="addHighlightField">
			<arg>"content"</arg>
		</postConstruct>
		<postConstruct name="setApiResponseFields">
			<arg>["title", "content", ...snip...]</arg>
		</postConstruct>
	</component>
```
> are there character limits in texts?

No option.

> Is there a key to show all the search?

To enable scroll search, set true in fess_config.properties:

```
api.search.scroll=true
```
and then access to `localhost:8080/json/scroll?q=*`.

**Comment by iny** [comment]
Can we add all the fields here in json output?

![asdasd](https://user-images.githubusercontent.com/24559998/37538599-2b462972-2962-11e8-9e26-f29a21533d1c.PNG)

**Comment by iny** [comment]
>query.additional.api.response.fields=lang
>query.additional.api.response.fields=content
Like this?

**Comment by marevol** [comment]
Try it!

**Comment by iny** [comment]
Thank you for your answers.
