### ISSUE TITLE
How to change built-in ES ports 9201/9301?

### ISSUE THREAD

**Issue by rustyx** [codelibs/fess#1557]
I already have another (incompatible) ES instance running on ports 9201/9301.

How do I change Fess configuration to use the built-in ES instance, but on different ports?

**Comment by marevol** [comment]
Why do you need to change ports for embedded elasticsearch?

> Embedded Elasticsearch is not recommended for production use.

See [Installation Guide](https://fess.codelibs.org/12.1/install/install.html).

**Comment by rustyx** [comment]
Because I can't get it to work with ES 6.2.2, getting an error: `Incorrect HTTP method for uri [/_configsync/wait?status=green] and method [GET], allowed: [POST]`

Is ES 6.2 supported?

**Comment by marevol** [comment]
Yes, it's supported.
Did you check log files?

**Comment by rustyx** [comment]
Here are the logs

```
java.lang.IllegalArgumentException: Rejecting mapping update to [.fess_config] as the final mapping would have more than 1 type: [access_token, bad_word]
java.lang.IllegalArgumentException: Rejecting mapping update to [.fess_config] as the final mapping would have more than 1 type: [access_token, boost_document_rule]
. . .
```

[fess.log](https://github.com/codelibs/fess/files/1808685/fess.log)
[server_0.log](https://github.com/codelibs/fess/files/1808686/server_0.log)
[elasticsearch.log](https://github.com/codelibs/fess/files/1808687/elasticsearch.log)

In fess.in.bat:
```
set FESS_JAVA_OPTS=%FESS_JAVA_OPTS% -Dfess.es.http_address=http://localhost:9206
set FESS_JAVA_OPTS=%FESS_JAVA_OPTS% -Dfess.es.transport_addresses=localhost:9306
set FESS_JAVA_OPTS=%FESS_JAVA_OPTS% -Dfess.dictionary.path=C:/dev/elasticsearch-6.2.2/config/
```

In elasticsearch.yml:
```
http.port: 9206
transport.tcp.port: 9306
configsync.config_path: C:/dev/elasticsearch-6.2.2/config
```

**Comment by marevol** [comment]
Fess 11 does not support Elasticsearch 6.
See [Installation Guide](https://fess.codelibs.org/12.1/install/install.html) and install a proper Fess version.

**Comment by rustyx** [comment]
Even after upgrading to Fess 12.1 it didn't work.
I think the path in the documentation is incorrect:
`set FESS_PARAMS=%FESS_PARAMS% -Dfess.dictionary.path="c:/<elasticsearch-<version>/data/"`
Should be:
`set FESS_PARAMS=%FESS_PARAMS% -Dfess.dictionary.path="c:/<elasticsearch-<version>/config/"`
After changing that it seems to work.

**Comment by marevol** [comment]
It's better to install it to a clean enviroment, and then check a log file.

**Comment by rustyx** [comment]
It's working now but the [documentation for Windows install](https://fess.codelibs.org/12.1/install/install.html) is incorrect, pls check my previous message.
Change `c:/<elasticsearch-<version>/data/` -> `c:/<elasticsearch-<version>/config/`
