### ISSUE TITLE
Index file name

### ISSUE THREAD

**Issue by Orenvi** [codelibs/fess#1563]
Hi,
I index file system, but there is a file that I cannot find in the search because they cannot be index.
for example: if the file name is "test.pdf" and I am searching for the "test", I don't find it.
How do I make sure it will find also the files name and showing it to me.

**Comment by marevol** [comment]
Try `filename:test*`.

**Comment by Orenvi** [comment]
No:
Your search - filename:test*. - did not match any document

**Comment by Orenvi** [comment]
I have found the file, but as you can see the name was renamed:

![image](https://user-images.githubusercontent.com/37143902/37404950-fe1006e8-279b-11e8-9cb4-b4204f14a46f.png)

**Comment by marevol** [comment]
It's a title which comes from a title in meta data of PDF, not a filename.
If you want to display a filename, modify JSP file in [Page Design](https://fess.codelibs.org/12.1/admin/design-guide.html).

**Comment by Orenvi** [comment]
Can you show me how? what file name?
and what I write in the file?
Sorry )-:

**Comment by marevol** [comment]
searchResults.jsp

**Comment by Orenvi** [comment]
what do I write in the file? or replace?
I do not know java.

**Comment by Orenvi** [comment]
Help....

**Comment by marevol** [comment]
I will be able to support Fess, but I have no time to support Java and JSP...
If you need supports, please contact [Commercial Support](https://www.n2sm.net/en/support/fess_support.html).
