### ISSUE TITLE
Autosuggest very rare words

### ISSUE THREAD

**Issue by freestyle68** [codelibs/fess#1567]
Hi,

very rare words aren't suggested. There is a way to set the minimum occurrence of a word to be suggested and eventually set this minimum to one?

**Comment by marevol** [comment]
In fess_config.properties:
```
suggest.min.hit.count=1
```

**Comment by freestyle68** [comment]
It does't happen in my environment: if I try also in http://search.n2sm.co.jp  with "regular" or "mapping" or "administration" why these words aren't suggested?

**Comment by marevol** [comment]
Did you run Suggester job?

**Comment by freestyle68** [comment]
Of course.

To have a reproducible environment try to index the attached pdf on zip package: why the terms "kozinski", "silverman", "Pregerson" aren't suggested? The are existing on docs!

[samples.zip](https://github.com/codelibs/fess/files/1827286/samples.zip)

**Comment by marevol** [comment]
The following parameters limit the number of documents to process it. To use all documents, change them in fess_config.properties:
```
suggest.update.contents.limit.num.percentage=100%
suggest.update.contents.limit.num=-1
```

**Comment by freestyle68** [comment]
Before your tip: 6228 docs from suggest index.
After: 6349 docs.

But still missing some terms (the same of the last message and others).

**Comment by marevol** [comment]
Documents which contain over 50000 characters are ignored.
In a next release, the limit will be changed. #1576

**Comment by freestyle68** [comment]
Still problem with some documents. For example the following terms aren't suggested in attached samples:

bower, cirillo, richter, sussex, bunn, derek, interdependency, etc

My config:

suggest.update.contents.limit.num.percentage=100%
suggest.update.contents.limit.num=-1
suggest.update.contents.limit.doc.size=500000000

My Fess version:  https://github.com/codelibs/fess/tree/1aa6da600ca9a7ecd5f4aeb335d8210b542286c1

[test suggest.zip](https://github.com/codelibs/fess/files/1866722/test.suggest.zip)

**Comment by freestyle68** [comment]
For example the attached doc 064452.pdf has 28000 words only, but suggest don't happen for words after two-thirds of the document. It seems the setting

`suggest.update.contents.limit.doc.size=500000000`

is not picked by Fess.

**Comment by marevol** [comment]
The cause might be suggest_analyzer.json.

```
      "limit_token_count_filter": {
        "type": "limit",
        "max_token_count": 10000
      },
```

**Comment by freestyle68** [comment]
It works perfectly!

Thank you @marevol
