### ISSUE TITLE
URL normalization

### ISSUE THREAD

**Issue by pointan** [codelibs/fess#1572]
Hello there,

is there a way to normalize URLs, so that the same URL (just with minimal differences) doesn't appear twice in the search results,. The image below shows such an example, where the crawler found the same page (one time with www and one time without).

![grafik](https://user-images.githubusercontent.com/7925259/37701298-b0be2a16-2cee-11e8-81a5-171259f4e2b3.png)

Thanks in advance.

Best regards.

**Comment by marevol** [comment]
Use [Path Mapping](https://fess.codelibs.org/12.1/admin/pathmap-guide.html).

**Comment by pointan** [comment]
Thank you for your quick response, I'll give it a try.

**Comment by zackhorvath** [comment]
@pointan did you happen to find a solution to this?

**Comment by pointan** [comment]
Oh, sry totally forgot to close the ticket. Path Mapping did the job
