### ISSUE TITLE
Document refresh period

### ISSUE THREAD

**Issue by rustyx** [codelibs/fess#1573]
Is there a setting to control how often a document needs to be re-crawled (in case there is no Expires header)?

**Comment by marevol** [comment]
No settings, but you can control [Schedule](https://fess.codelibs.org/12.1/admin/scheduler-guide.html#schedule) and create crawling configs.

> in case there is no Expires header

Fess does not use Expires header.

**Comment by rustyx** [comment]
Does it mean that all the URLs are retrieved every time the schedule is started?

**Comment by marevol** [comment]
It depends on your requirement...
If you have many updated urls, you can also use CsvListDataStore in [Data Store Crawling](https://fess.codelibs.org/12.1/admin/dataconfig-guide.html#handler-name).
CsvListDataStore crawls urls by using CSV file which contains urls.
The sample script which creates test data is [csvlistdatastore.sh](https://github.com/codelibs/fess-testdata/blob/master/tools/csvlistdatastore.sh).

**Comment by rustyx** [comment]
Ok, so the Web Crawler has no such setting. Clear, thanks.
