### ISSUE TITLE
Debug fess in EclipseIDE

### ISSUE THREAD

**Issue by rodrigobml** [codelibs/fess#1575]
I want to debug the fess project connected in my elasticsearch cluster, is it possible?

**Comment by marevol** [comment]
I think it works if adding the following options as JVM options in Eclipse.
```
-Dfess.es.http_address=http://localhost:9200 -Dfess.es.transport_addresses=localhost:9300 -Dfess.dictionary.path=...(ex. /var/lib/elasticsearch/config/)
```
