### ISSUE TITLE
Question : Crawling target https website using an a self signed certificate

### ISSUE THREAD

**Issue by acossette1979** [codelibs/fess#1578]
Hi,
Can I configure fess where the target site is using an a self signed certificate? Is there a parameter  I can enter in the config parameter of that site ?
Thanks

**Comment by marevol** [comment]
No settings. It will be fixed in a next release.
https://github.com/codelibs/fess-crawler/commit/1e5b3202ab25662e682702254c77f9d9228a0e58

**Comment by acossette1979** [comment]
Hi @marevol, do you have an ETA for this fix ?
Thanks

**Comment by etlweather** [comment]
If anyone arrives here for an answer - see https://discuss.codelibs.org/t/how-to-crawl-site-with-self-signed-cert/1495/3 where you can find the answer.
