### ISSUE TITLE
AutoComplete Json API

### ISSUE THREAD

**Issue by josempolm** [codelibs/fess#1584]
Hello,

And another question that I would like to ask is, does not it show up when I put "*" in AutoComplete, is there a way?

> Like this ; localhost:8080/json/scroll?q=*

**Comment by marevol** [comment]
Try to add `\*` to [Bad Word](https://fess.codelibs.org/12.1/admin/badword-guide.html).

**Comment by josempolm** [comment]
I want to see all the text at the json exit.


`        {
          "text": "fess n2sm",
          "tags": [
            "fess"
          ]
        },`

**Comment by marevol** [comment]
We have no plan to provide scroll search for suggest index, but you can use elasticsearch api directly to do that.

**Comment by josempolm** [comment]
Appears in Json api, But not in scroll api. 

-What could be the reason for this? I have to do something different. 

>query.additional.api.response.fields=content
query.additional.api.response.fields=cache

**Comment by marevol** [comment]
Is it about Suggest API?
This issue is for Suggest API.
