### ISSUE TITLE
How to import CSV instead of /admin/searchlist/createnew/

### ISSUE THREAD

**Issue by jyo2035** [codelibs/fess#1585]
Thank you for developing!

I have CSV files including url, title, timestamp, etc...
Do you have any ideas How to do bulk import?
Can I use Embulk?
(instead of http://FESS-SERVER-URL/admin/searchlist/createnew/)

**Comment by marevol** [comment]
See [CsvDataStore](https://fess.codelibs.org/12.1/admin/dataconfig-guide.html#csvdatastore).

**Comment by jyo2035** [comment]
Thank you!
I'll try.
