### ISSUE TITLE
Similar results limit

### ISSUE THREAD

**Issue by jfabales** [codelibs/fess#1593]
Hi Fess team,

I've enabled similar results on our Fess instance and when we get similar results of over 100 (could go to thousands), nothing happens when trying to collapse the similar results, it works for similar results of <100.
So I'm wondering if there's some sort of limit and if it can be changed?
Is that the similar_docs_hash container and doesn't it have a max value of 1000?

Thanks in advance.

**Comment by jfabales** [comment]
Hmm why then search results with more than 100 similar results don't collapse? Does it need time to build the list of similar results?

**Comment by marevol** [comment]
Is it #1595?

**Comment by jfabales** [comment]
Hi @marevol,
I'm afraid not, it only solves browsing through Next/Previous pages which is good, but not what I reported. 
What I observed is this, if you get a result with thousands of similar results, and hover over the Similar Results (5.5k) link, and look at the lower left corner of the browser to see the actual link, you'll get this: 
/search/?q=search+term&ex_q=&sdh=
No value for String sdh
Normally you'll get something like this: 
/search/?q=search+term&ex_q=&sdh=%24H4sIAAAAAAAAAEWMgQkAMAzCXjL_P7e1zToRlCAm5ArKHRkDVtmGcNRDi9tB0v_I0gcrD0jzreeAAAAA
Could it be that you're hitting the String length limit for sdh?

**Comment by marevol** [comment]
If disabling [Similar Result Collapsed](https://fess.codelibs.org/12.1/admin/general-guide.html#similar-result-collapsed), an indexed value for sdh will be empty.
If you have an empty `sdh` value, you need to remove indexed documents and then crawl/index them again.

**Comment by jfabales** [comment]
This is resolved by re-indexing the docs. thanks.
