### ISSUE TITLE
Default userAgent

### ISSUE THREAD

**Issue by wancode** [codelibs/fess#1597]
Hello there,

Previously I could change it via "app.xml". It does not change after the update.

**Comment by marevol** [comment]
See [User Agent](https://fess.codelibs.org/12.1/admin/webconfig-guide.html#user-agent).

**Comment by wancode** [comment]
Do I have to change it every time?

**Comment by wancode** [comment]
Is there a way to change the default value?

**Comment by wancode** [comment]
Any progress?

**Comment by marevol** [comment]
Need more info...

**Comment by wancode** [comment]
Is there a way to change the default value? For userAgent.

![q1](https://user-images.githubusercontent.com/38166045/40400687-f5ae4c30-5e4b-11e8-835b-055fccb4d98c.PNG)

**Comment by marevol** [comment]
Set `crawling.user.agent` to system.properties.
