### ISSUE TITLE
Is it possible to separate search results by folder (content path) ?

### ISSUE THREAD

**Issue by noffin** [codelibs/fess#1604]
Hello, 

In #1543 "Virtual Host" setting solve the separate search site.
I'd like to have different search result pages like below. Is it possible ?
www.fessurl.com for Site X
www.fessurl.com/aaa   for Site A

**Comment by marevol** [comment]
Virtual Host feature processes a request header.
To use other values as a key, you need to modify [VirtualHostHelper](https://github.com/codelibs/fess/blob/master/src/main/java/org/codelibs/fess/helper/VirtualHostHelper.java).
