### ISSUE TITLE
Question: Using FESS as a search-engine for Wordpress

### ISSUE THREAD

**Issue by remoblaser** [codelibs/fess#1608]
Hey there!

Currently we're using FESS as a Crawler to crawl the Wordpress websites of our customers, thus creating a more reliable search functionality.
Behind FESS we have one elasticsearch engine which holds all the data.
The problem we currently have is, if we update a configuration, we have to delete all the indexes to reindex the website, whose config has been changed.
Is there a way around this?

We've thought about multiple solutions:

- Possibility to have a elasticsearch server per website, thus running FESS on one server and each elasticsearch service per website on a different server. Then we would only need to purge one elasticsearch server index
- Is there a way to delete a index associated with a crawler or label?
- Different approaches? Are we going too far or is FESS not the solution we're looking for?

Thank you for your time!

**Comment by marevol** [comment]
Virtual Host is available for using multiple websites.
