### ISSUE TITLE
if any issues with adding new web app filter?

### ISSUE THREAD

**Issue by AllenHan5** [codelibs/fess#1609]
Hello

I wanted to implement a new authentication mechanism, say SAML. 
From the possible solution I found from the Internet, it seemed adding a web app filter is a general way to go. Is there any implication if I add a filter to existing FESS web.xml?

Any guide about it?
Thanks

**Comment by marevol** [comment]
See [web.xml](https://github.com/codelibs/fess/blob/master/src/main/webapp/WEB-INF/web.xml) for Fess.
