### ISSUE TITLE
Value and weight research element

### ISSUE THREAD

**Issue by goldenivan** [codelibs/fess#1611]
Hi,

As the title say, what is the value and weight research element ? I would like to know how Fess manage the SEO.

Thank you in advance for your answer.

**Comment by marevol** [comment]
Fess uses BM25.
See [Similarity module](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/index-modules-similarity.html) in Elasticsearch documents.

**Comment by riceming** [comment]
Can we config the weight?

**Comment by marevol** [comment]
You can change app/WEB-INF/classes/fess_indices/fess.json and then run [Reindex](https://fess.codelibs.org/12.1/admin/upgrade-guide.html#reindex) with Update Aliases.
