### ISSUE TITLE
is this a bug with FessSearchAction::redirectToRoot()?

### ISSUE THREAD

**Issue by AllenHan5** [codelibs/fess#1616]
Hello

I noticed during redirect, the name of FESS web app (i.e. the context path) was added to the target url. After I made changes as following, the issue was resolved:
```
protected HtmlResponse redirectToRoot() {
        final String contextPath = request.getServletContext().getContextPath();
        // return newHtmlResponseAsRediect(StringUtil.isBlank(contextPath) ? "/" : contextPath);
        return newHtmlResponseAsRediect("/");
    }
```

Is it a potential bug, or I should find a different way to address the issue I had?
Thanks

**Comment by marevol** [comment]
Thanks! Fixed in #1620.
