### ISSUE TITLE
Scroll API Settings

### ISSUE THREAD

**Issue by wancode** [codelibs/fess#1625]
Hello there,

I added it like this but it does not show why?

>query.additional.scroll.response.fields=score
>query.additional.scroll.response.fields=result__score

Example; #1555

**Comment by marevol** [comment]
Did you enable `api.search.scroll` in fess_config.properties?
`query.additional.scroll.response.fields` is a comma separated values, such as `aaa1,aaa2`.

**Comment by wancode** [comment]
This is the json output.

>http://localhost:8080/json/?q=a > "score":32.24106


Scroll "score" does not output.

>localhost:8080/json/scroll?q=*

>query.additional.api.response.fields=lang,content,score,result__score	
query.additional.scroll.response.fields=lang,content,score,result__score

**Comment by wancode** [comment]
Does anybody know why?

**Comment by marevol** [comment]
score is not an index field.
It will be added in a next release. Fixed in #1628.

**Comment by wancode** [comment]
Thank you.

**Comment by wancode** [comment]
Why does the score on Json and Scroll differ?


Ex;
>"score":62.935604 
>"score":18.00

**Comment by wancode** [comment]
Any progress?

**Comment by marevol** [comment]
If you need a quick response, please contact [Commercial Support](https://www.n2sm.net/en/support/fess_support.html).
