### ISSUE TITLE
Quesiton: Add label to documents

### ISSUE THREAD

**Issue by chuqingsheng** [codelibs/fess#1626]
How to add multiple labels to a documents?  and those labels are searchable.  
For example, when user get search results page. user can add some labels to douments list in search results. so next time, user can search by those labels.
Have any idea to implement this function?

**Comment by marevol** [comment]
For search conditions, labels in facets are not in HTTP session by default.
To add labels into HTTP session as search conditions, you need to modify source code.

**Comment by chuqingsheng** [comment]
thank you!
I mean how users can tag the document directly on the search results web page, and later he can search the document through tags.

Can we get this function if we become Gold Professional Support?

**Comment by marevol** [comment]
For specific requirements, it will be supported by [Commercial Support](https://www.n2sm.net/en/support/fess_support.html).

**Comment by chuqingsheng** [comment]
Thank you. I will contact with Commercial Support.
