### ISSUE TITLE
update label problem

### ISSUE THREAD

**Issue by chuqingsheng** [codelibs/fess#1627]
When I update document labels(add a new label :label1)  at admin search  list edit page. Then I search by this label with label:label1. It does work, but this label doesn't display in the search option Labels box. How to display new label in search options?

**Comment by marevol** [comment]
Label information is cached.
Config Reloader in [Scheduler](https://fess.codelibs.org/12.1/admin/scheduler-guide.html) reloads configurations.

**Comment by chuqingsheng** [comment]
I have start the Config Reloader. but doesn't work.
I add label at document update page. please see below picture.
![image](https://user-images.githubusercontent.com/29627257/39297667-aff1ed9e-4976-11e8-833e-f1e1d99d4ec4.png)

**Comment by marevol** [comment]
I see.
A label in a search condition is a label name, and one in a document is a label value.
So, to display it in a search condition, you need to add it in [Label](https://fess.codelibs.org/12.1/admin/labeltype-guide.html).

**Comment by chuqingsheng** [comment]
Can I display label values at right of  every search result item? how can I do?  add html code in searchResults.jsp? please give me some suggestion. thank you.

**Comment by chuqingsheng** [comment]
In searchResults.jsp , the doc haven't label field. how to modify source code to add label field output searchresults.jsp?

**Comment by nkampel** [comment]
Hello,
iam also trying to display the Labels for individual docs in the searchresults. I tryed modifying the searchresults.jsp with no luck.
I would appreciate any suggestions to help me solve this issue.
