### ISSUE TITLE
Imposible to crawling repositories files when using metadata ?

### ISSUE THREAD

**Issue by budiangga95** [codelibs/fess#1635]
Great work and special thanks with your fess search engine @marevol !!! 
I have problem about the fess search performance to crawling a website **using metadata scheme** like Dspace or Eprints (Institutional Repository). 

In this case, the pdf file extension and the bibliography descriptions cannot to crawling using FESS 12.1.

For example in here : 
![dspace](https://user-images.githubusercontent.com/19369333/39541787-eef18f6e-4e70-11e8-8ecb-6c1a9049bacc.png)

can you help me crawling this sites and get the result page with pdf document?

thanks...

**Comment by marevol** [comment]
Try to add `client.robotsTxtEnabled=false` to [Config Parameters](https://fess.codelibs.org/12.1/admin/webconfig-guide.html#config-parameters).
