### ISSUE TITLE
it takes time to open files after clicking search result(filesystem)

### ISSUE THREAD

**Issue by hillxrem** [codelibs/fess#1651]
When I use FESS for my laptop , just about 1sec is needed to open files after
clicking search result , but for a fileserver(contains >200,000 files), it takes about 10-15sec to open.(after clicking link like this <http://FESSserver/go?rt=1234567890&docld=12345678abcde.... >)
Is there any way to speedup this thing ? 
I can open files as admin from system information page quickly by clicking link like <<file:/fileserver/file..>>
 , but I want to share FESS with other people.

**Comment by marevol** [comment]
Is your PC spec good enough?
It's better to check fess.log by debug level.

Content Proxy is a feature to proxy a file access by Fess and is enabled by default.
To disable it, set search.file.proxy to false in system.properties:
```
search.file.proxy=false
```
However, you may not be able to open files from `file://...` for a browser security policy.
It's not a problem on Fess...

**Comment by hillxrem** [comment]
Thank you @marevol , and I’ve added <search.file.proxy=false> to ./etc/fess/system.properties. But , in search result page, FESS(12.1.2 ,dockerCE18.03.1 on CentOS7) links files still like <<http://FESSserver/go?rt=...>> and redirects to <<smb://fileserver/????????/???????>>.
“????????/???????” is literally “????????/???????” in my browser ,and probably it is originally a filename or foldername spelled in Chinese character.(Of course , this link doesn't work.)
Is there any properties to be set in order to use <<file://>> in search result ? 

And I've also checked fess.log and found a process in trouble like this.(Before adding search.file.proxy=false)

> 2018-05-17 08:35:10,682 [http-nio-8080-exec-10] DEBUG Creating SmbFile: smb://fileserver/filename
> 2018-05-17 08:35:10,733 [http-nio-8080-exec-10] DEBUG Processing SmbFile: smb://fileserver/filename
> 2018-05-17 08:35:39,852 [CoreLib-TimeoutManager] DEBUG Updating scheduled jobs. time:1526546109821
> 2018-05-17 08:35:50,810 [http-nio-8080-exec-10] DEBUG java.net.UnknownHostException: Domain name of fileserver
> 2018-05-17 08:35:50,811 [http-nio-8080-exec-10] DEBUG 	at jcifs.UniAddress.getAllByName(UniAddress.java:315)
> 2018-05-17 08:35:50,811 [http-nio-8080-exec-10] DEBUG 	at jcifs.UniAddress.getByName(UniAddress.java:245)

Any user of CentOS( runs FESS) can't access  our fileserver without  some specific username(domain user) and password , and these are set in filecrawl in FESS(username differs in each filecrawl). Is this the reason for this matter? If so , why can I open files finally...?
