### ISSUE TITLE
Popular Word Response is 0 word

### ISSUE THREAD

**Issue by HidenobuNaruse** [codelibs/fess#1654]
To Reproduce.
1.Popular Word Response is Enabled
2.To 10 times search (guest user)
3."http://[hostname]/json?type=popularword" access

{"response":{"version":12.1,"status":0,"result":[]}}

**Comment by marevol** [comment]
> 2.To 10 times search (guest user)

Try it 1 minute later after a previous search.

**Comment by HidenobuNaruse** [comment]
@marevol

**Comment by HidenobuNaruse** [comment]
@marevol

**Comment by HidenobuNaruse** [comment]
@marevol

**Comment by HidenobuNaruse** [comment]
@marevol 

> 2.To 10 times search (guest user)
> Try it 1 minute later after a previous search.

I waited for a few minutes, but I did not get a response.
Is there any other way to respond?

**Comment by marevol** [comment]
Did you run [Suggest Indexer](https://fess.codelibs.org/12.1/admin/scheduler-guide.html)?

**Comment by HidenobuNaruse** [comment]
@marevol 
After executing Suggest Indexer, previous search. 
but I did not get a response.

**Comment by iladrero** [comment]
Same bug here. No popular words displayed. Checked general setting, and tried all the above.
Running fess-12.3.0
