### ISSUE TITLE
Need to change URL context

### ISSUE THREAD

**Issue by wireless00** [codelibs/fess#1655]
I need to change the URL base context to something like http://my-awsome-server/fess/ to get to FESS instead of http://my-awsome-server.

**Comment by marevol** [comment]
You can use apache or nginx to rewrite a path.

**Comment by wireless00** [comment]
I can rewrite /fess to the fess server, however, FESS context is /, so it redirect me to / where I have another application...

**Comment by marevol** [comment]
Do you use apache or nginx?

**Comment by wireless00** [comment]
We use it in OpenShift. (Behind a route) The ''Proxy'' is HAProxy.

**Comment by marevol** [comment]
You need to rewrite Location header.

**Comment by wireless00** [comment]
Is that Tomcat that run FESS.... If so, where is the config and could I add a blck like this...

`<subsystem xmlns="urn:jboss:domain:undertow:3.1">
  <buffer-cache name="default"/>
  <server name="default-server">
      <http-listener name="default" socket-binding="http" redirect-socket="https"/>
      <host name="default-host" alias="localhost">
          <location name="/" handler="welcome-content"/>
          <filter-ref name="server-header"/>
          <filter-ref name="x-powered-by-header"/>
      </host>
  </server>
  ...
</subsystem>`

**Comment by marevol** [comment]
It's not a plain Tomcat... You cannot add it.

**Comment by wireless00** [comment]
OpenShfit HAProxy does forward HTTP headers "X-Forwarded-For, X-Forwarded-Proto and X-Forwarded-Port", so I don't get why I should change anything in our proxy. Also, we might be in a situation where there no possiblity to change the PROXY config if it's in a share environment like OpenShift as a service (PAAS). 

It would be interesting to have FESS deal with such behaviour as this could be a issue for other peoples running FESS in a container under OpenShift using HAProxy in front of it (This is their default setup/behaviour) (OpenShift ROUTES).

May I suggest a variable to enable such a behaviour or a config to change FESS context ?

**Comment by wireless00** [comment]
I notice this parameter in fess.in.sh

-Dfess.context.path=/

Changes to /fess

Fix my issue...

**Comment by wireless00** [comment]
My pleasure ;-)
