### ISSUE TITLE
Couple of questions with LDAP and SSO

### ISSUE THREAD

**Issue by jfabales** [codelibs/fess#1661]
Hi Fess team,

I would like to ask first if SSO with LDAP on Linux is available with FESS.
I could connect and authenticate with our LDAP server but now I want to configure SSO.
I tried this configuration but it didn't work.
**Admin/general page:** (this works with manual authentication)
```
LDAP url: ldap://ldap.company.com:389
base DN: dc=company,dc=com
bind DB: ldapbind
password: ****
User DN: %s@company.com
Account filter: (&(objectClass=user)(sAMAccountName=%s))
memberOf attribute: memberOf
```
**fess_config.properties**
```
ldap.admin.provider.url=ldap\://ldap.company.com\:389
ldap.admin.security.principal=CN\=ldapbind,OU\=ServiceAccounts,DC\=company,DC\=com
ldap.admin.security.credentials=*****
```

Also, I want to make groups from LDAP/AD as Fess administrators, is that possible? I tried these configurations but all didn't work.
```
authentication.admin.users=2group_name
authentication.admin.roles=admin

authentication.admin.users={group}group_name
authentication.admin.roles=admin

authentication.admin.users=1user_name
authentication.admin.roles=admin

authentication.admin.users={user}user_name
authentication.admin.roles=admin
```

Thanks in advance

**Comment by marevol** [comment]
If you need docs for SSO configuration, please contact [Commercial support](https://www.n2sm.net/en/support/fess_support.html).
There is no docs on OSS.

`authentication.admin.roles` is comma separated value.
You can check roles in audit.log

**Comment by jfabales** [comment]
Hi,

We don't have roles setup in our LDAP and no roles are being detected in audit.log, can't I also point roles to OU=Group,DC=company,DC=com? 
We're still in the testing stage of the capabilities and features of FESS and not sure if we want to have commercial support yet, that's why any help would be appreciated.

**Comment by marevol** [comment]
Your settings for [Account Filter](https://fess.codelibs.org/12.1/admin/general-guide.html#account-filter) or [memberOf](https://fess.codelibs.org/12.1/admin/general-guide.html#memberof-attribute) might not be correct.

**Comment by jfabales** [comment]
No we really don't have roles setup on our AD.
I tried to configure the `role.filter` and `role.base.dn` properties with the same values for `group.filter` and `group.base.dn` but still couldn't detect any roles.

**Comment by jfabales** [comment]
Created OU=Roles and added a role, changed the role.filter and was able to see the role in audit.log already.
LDAP user can access the admin page now but you have to change the URL to /admin, the `Administration` link is not showing in the User Profile dropdown menu.

Also I'm getting a Page not found error when accessing the Dashboard using the LDAP account.

**Comment by biligee** [comment]
I wanted to use "fess_roles" and "fess_groups" instead of the default "Role" and "Group".

Does the following settings are correct?
ldap.admin.role.base.dn=ou\=fess_roles,dc\=test,dc\=com
ldap.admin.group.base.dn=ou\=fess_groups,dc\=test,dc\=com

However, audit.log shows the "cn="s of  "Role" and "Group" only. I can't list the "cn="s of "fess_roles" and "fess_groups". 
I also tried with "ldap.group.name.with.underscores=true" with no success.

**Comment by biligee** [comment]
> I wanted to use "fess_roles" and "fess_groups" instead of the default "Role" and "Group".
> 
> Does the following settings are correct?
> ldap.admin.role.base.dn=ou=fess_roles,dc=test,dc=com
> ldap.admin.group.base.dn=ou=fess_groups,dc=test,dc=com
> 
> However, audit.log shows the "cn="s of "Role" and "Group" only. I can't list the "cn="s of "fess_roles" and "fess_groups".
> I also tried with "ldap.group.name.with.underscores=true" with no success.
Oh...,
ldap.admin.role.base.dn=ou=fess_roles,dc=test,dc=com
ldap.admin.group.base.dn=ou=fess_groups,dc=test,dc=com seems used for administrating LDAP.
So, I tried without "admin" with nit success:
ldap.role.base.dn=ou=fess_roles,dc=test,dc=com
ldap.group.base.dn=ou=fess_groups,dc=test,dc=com
