### ISSUE TITLE
search for file- and directorynames

### ISSUE THREAD

**Issue by rocky-galveston** [codelibs/fess#1667]
hi all,

i'm crawling some samba-shares per smb://-urls. 

searching for the content of files works perfectly, but if i search for file- or directorynames, this doesn't give any results. ich tried the search with title:- and url:-fields.

thanks in advance

rocky

**Comment by marevol** [comment]
Directories are not indexed.

**Comment by rocky-galveston** [comment]
thanks for your answer.

but what about filenames? this also doesn't work.

**Comment by marevol** [comment]
https://search.n2sm.co.jp/search/?q=filename%3Atest.html
