### ISSUE TITLE
Job Scheduler ignoring expression

### ISSUE THREAD

**Issue by bhdzllr** [codelibs/fess#1670]
Hello,

i have 14 different Web Crawlers and each of them uses a separate label. Also each crawler has a scheduler where I want to define different times to run the crawler, because it seems that running every crawler at the same time leads to too high workload for the server (RAM, CPU).

But, no matter what crontab expression I use, every crawler starts after every hour.

I have tried the following expressions, among others:

Run ervery 5th minute
*/5 * * * *

Run at hours 00:00, 03:00, 06:00, 09:00, ...
0 0,3,6,9,12,15,18,21 * * *

It seems the changed value is not loaded into the scheduling engine.

My Fess Version is 12.1.1
I use the codelibs/docker-fess Dockerfile

Thank you.

**Comment by marevol** [comment]
Did you check log files?

**Comment by bhdzllr** [comment]
Thank you for your fast reply.

Log files did not have any information about this.
After different approaches I restarted the docker container and now it works.
