### ISSUE TITLE
http://hostname/fess/fess/ is called after login with setting fess.context.path=/fess/

### ISSUE THREAD

**Issue by mschibata** [codelibs/fess#1674]
Hello friends,

I use Fess 11.3.3.
Now I am trying to map http://hostname/fess as application root with using Apache reverse proxy.
Then I set fess.context.path=/fess/ in /usr/share/fess/bin/fess.in.sh.
And httpd reverse proxy setting I made like...

        ProxyPass / http://localhost:8080/
        ProxyPassReverse / http://localhost:8080/

So everything is OK except just after login.
With login, fess page wants to move into http://hostname/fess/fess and retruens error page with message  /fess/fess cannot be found.

I think another settings are lacked but I cannot found.
If anyone knows information around this.

Please tell me.

**Comment by marevol** [comment]
Changing fess.context.path is not supported officially... Because we do not do testing for it.
