### ISSUE TITLE
Search failed in datastore

### ISSUE THREAD

**Issue by luigigf49** [codelibs/fess#1676]
Hi all,
I have configured the crawling for some folders and search works correctly.
Then I added the crawling of an Oracle table called CO_CLIFO:

PARAMETER
driver = oracle.jdbc.OracleDriver
url = jdbc: oracle: thin: @localhost: 1521: ORA9ZV
username = "AZ09"
password = "AZ09"
sql = select * from CO_CLIFO

SCRIPT
name = cliforagi1
address = clifoindir
location = clifolocal

Crawling of datastore ends succesfully.

I then tried to do a search in different ways (CORRIDONIA is the name of a city in the clifolocal field):

- CORRIDONIA
or:
- location: CORRIDONIA

but I find only some documents contained in the folders and no reference to the records of the CO_CLIFO table.

Many thanks
Luigi

**Comment by marevol** [comment]
A type of `location` field is [geo_point](https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-point.html).
See [doc.json](https://github.com/codelibs/fess/blob/fess-12.1.3/src/main/resources/fess_indices/fess/doc.json#L559).

**Comment by luigigf49** [comment]
Hi marevol,
Thank you for your help but I still have problems (certainly due to my lack of knowledge of the instrument).
Now my script is:
content = clifolocal
digest = clifolocal
My searches however do not work.
Is there a way to see the contents of the indexes that were created for the datastore by the crawler?

Many thanks
Luigi

**Comment by marevol** [comment]
See [Admin Search](https://fess.codelibs.org/12.1/admin/searchlist-guide.html).

**Comment by luigigf49** [comment]
Already tried without success.

**Comment by marevol** [comment]
Are these values indexed? 
Did you check log files?
Need more info...

**Comment by luigigf49** [comment]
Hi marevol,
this is a sample message generated by the datastore crawler:

ID | 3W3mtWMB4hOHaSFZhk0j
-- | --
select * from CO_CLIFO:1360
L1-HsmMByoyqlpSzApha-1
org.codelibs.fess.exception.DataStoreException
org.codelibs.fess.exception.DataStoreException: url is null. dataMap={expires=Sun Jun 03 12:57:43 CEST 2018, role=[Rguest], config_id=DL1-HsmMByoyqlpSzApha, created=Thu May 31 12:57:45 CEST 2018, segment=L1-HsmMByoyqlpSzApha, boost=9.9999998E17, mimetype=application/datastore, label=[]}at org.codelibs.fess.ds.impl.IndexUpdateCallbackImpl.store(IndexUpdateCallbackImpl.java:69)at org.codelibs.fess.ds.impl.DatabaseDataStoreImpl.storeData(DatabaseDataStoreImpl.java:122)at org.codelibs.fess.ds.impl.AbstractDataStoreImpl.store(AbstractDataStoreImpl.java:106)at org.codelibs.fess.helper.DataIndexHelper$DataCrawlingThread.process(DataIndexHelper.java:236)at org.codelibs.fess.helper.DataIndexHelper$DataCrawlingThread.run(DataIndexHelper.java:222)
1
1527765173794

**Comment by marevol** [comment]
?

**Comment by luigigf49** [comment]
Hi marevol,
on the page 'Failure URL' for each record to crawl (1360 records/1360 messages) there is a message like this:
org.codelibs.fess.exception.DataStoreException: url is null. dataMap={expires=Sun Jun 03 16:10:23 CEST 2018, role=[Rguest], config_id=DL1-

Many thanks

**Comment by luigigf49** [comment]
Hi marevol,

attached a document that contains some information about my problem.

Many thanks

[DataStoreCrawlingProblem.zip](https://github.com/codelibs/fess/files/2059060/DataStoreCrawlingProblem.zip)

**Comment by luigigf49** [comment]
Hi marevol,
thanks to your help I have made some progress and now I have no more problems like 'Failure URL'.
However, the database search does not work yet.
In the file 'fess-crawler.log' I noticed some error reports that I reported in the attached document.

Many thanks
Luigi
[DataStoreCrawlingProblem_2.zip](https://github.com/codelibs/fess/files/2061224/DataStoreCrawlingProblem_2.zip)

**Comment by marevol** [comment]
> MissingPropertyException: No such property: cliforagi1 for class: Script1

cliforagi1 column does not exist in a result of `sql`.

**Comment by luigigf49** [comment]
But cliforagi1, clifoindir etc. are all columns of table CO_CLIFO and sql command is 'slq * from CO_CLIFO'

**Comment by luigigf49** [comment]
Default Crawler or Crawler that I defined for my DataStore ?

**Comment by marevol** [comment]
need more info such as fess-crawler.log...

**Comment by luigigf49** [comment]
Attached some documents.
[Logs_2018_06_01.zip](https://github.com/codelibs/fess/files/2064174/Logs_2018_06_01.zip)

**Comment by luigigf49** [comment]
Another document with screenshots.
[DataStoreCrawlingProblem_3.zip](https://github.com/codelibs/fess/files/2064200/DataStoreCrawlingProblem_3.zip)

**Comment by marevol** [comment]
1. Replace with attached classes
2. Restart Fess and start crawler
3. Check fess-crawler.log with debug level
You can check values at `params:` line.


[dsdb.zip](https://github.com/codelibs/fess/files/2064242/dsdb.zip)

**Comment by luigigf49** [comment]
Excuse me,
inside your zip tree folders is : 
![image](https://user-images.githubusercontent.com/25151076/40865624-8fe27eca-65f9-11e8-96ea-844f511e0957.png)

while installation has this structure:

![image](https://user-images.githubusercontent.com/25151076/40865662-c47796ca-65f9-11e8-95b6-bcab88dfcfe8.png)

you should tell me which or which folders to copy from your zip and to which folders of my installation.

Thanks for your patience
Luigi

**Comment by luigigf49** [comment]
Ok. Done.
I'll try.

Thanks

**Comment by luigigf49** [comment]
Hi marevol,
attached a document that explains my configuration for crawler with a new simple table and resulting fess-crawler.log.

Thanks
Luigi
[DataStoreCrawlingProblem_4.zip](https://github.com/codelibs/fess/files/2064870/DataStoreCrawlingProblem_4.zip)
[fess-crawler.zip](https://github.com/codelibs/fess/files/2064871/fess-crawler.zip)

**Comment by luigigf49** [comment]
Hi marevol,
I think I understood where the problem was.
I modified the script of the simple DOC table with which I had made the previous attempt using uppercase for field names and now the attempt is successful and my 4 records of the DOC table are visible in the searches.
Unlike MySql, Oracle evidently returns names only in uppercase.
Now I will test with my CO_CLIFO table after modifying its script.
I will keep you informed of the result of my tests.
In the meantime, I thank you for your help.

Luigi

**Comment by luigigf49** [comment]
Hi marevol,

tests with a  more complex Oracle table were succesful.
I hope that my experience can be of help to others
As the principle of Occam states: when to solve a problem there are many possible hypotheses, it is preferable to choose the simplest one.

Thank you again
Luigi
