### ISSUE TITLE
Add Target URL for related content configuration in admin

### ISSUE THREAD

**Issue by kishoreghattu** [codelibs/fess#1679]
Hi @marevol ,

  Please add Target URL field for related content configuration in admin along with Term, Content, Display Order and Virtual Host fields.

Also really appreciate all your efforts with FESS as a true enterprise search engine. 

Thanks
Rama

**Comment by marevol** [comment]
How do you want to use it in related content?

**Comment by kishoreghattu** [comment]
Hi @marevol,
 
Thanks again for quick response. Our site has requested being able to display links to content for specific search terms consistently.  In order to make it possible and to keep those looking and behaving the same, being able to pull the URLs out from the main content body into its own field like Target URL will be helpful so that it can be displayed and styled separately.

I think this separation of URLs and content will help the community and other users too.

Thanks again
Rama

**Comment by marevol** [comment]
Hmm, it's still unclear to me...
In related content, you can use HTML tags and also edit JSP files for search result pages.
Why do you need separated urls??

**Comment by kishoreghattu** [comment]
Hi @marevol,

Our users have over 100 different related content items.  In order to ensure the same behavior across all of the items and minimize the potential for user error.  Breaking the links out into a dedicated field allows for this separation and more closely mimics the KeyMatch behavior of a Google Search Appliance.

Thanks
Rama

**Comment by marevol** [comment]
Did you try [KeyMatch](https://fess.codelibs.org/12.1/admin/keymatch-guide.html)?
