### ISSUE TITLE
Can Fess indicate link of path for Explorer on search result ?

### ISSUE THREAD

**Issue by makiyama-shinji** [codelibs/fess#1689]
Hello!

We using Fess10.0.3 on Windows2012R2.
The main purpose is a File server document search.

The search result indicate the path of file://～ + file name normally,
but we have a request that link of path for Explorer instead of it.
Or in addition to it.

The version up to recently version or paid support be a solution ?

**Comment by marevol** [comment]
Fess 10 is EOLed. See [EOL](https://fess.codelibs.org/eol.html).
If you need any support, please contact [Commercial Support](https://www.n2sm.net/en/support/fess_support.html).

**Comment by makiyama-shinji** [comment]
I know what you say.
We can use recently version, so can recently version indicate link of path for Explorer on search result ?

**Comment by marevol** [comment]
You can edit JSP file at [Page Design](https://fess.codelibs.org/12.1/admin/design-guide.html) page.

**Comment by makiyama-shinji** [comment]
Thanks !
Show me a fee of Commercial Support.
By getting Commercial Support, we can get it on Fess 10 ?

**Comment by makiyama-shinji** [comment]
I resolved by myself.
Adding to searchResults.jsp.

<c:set var="filename">
"${f:h(fn:split(doc.urlLink,"/")[fn:length(fn:split(doc.urlLink,"/"))-1])}"
</c:set>
<c:set var="fullpath_name" value="${fn:substring(doc.urlLink, 0, fn:length(doc.urlLink) - fn:length(filename) + 2)}" />
<a href="${fullpath_name}"> (Open Folder)  </a>
						<div class="description">${doc.contentDescription}</div>

**Comment by makiyama-shinji** [comment]
But, it can open Explorer by only IE. not Chrome.
