### ISSUE TITLE
System Error after searching

### ISSUE THREAD

**Issue by tobebe1990** [codelibs/fess#1692]
I get "System Error" message everytime I search something on a search page (localhost:8080) and also when I click session ID in crawling information.

Could you please tell me where to look in the logs to find what are causing these problems?

Thank you in advance.

**Comment by marevol** [comment]
Check ...Exception in log files.

**Comment by tobebe1990** [comment]
Got it. Thank you for your time!
I still couldn't find what was causing this problem but I don't get "System Error" anymore.
Maybe it has something to do with searching while crawling...
