### ISSUE TITLE
DEMO site parameters

### ISSUE THREAD

**Issue by luigigf49** [codelibs/fess#1694]
Hi marevol,

a good help for me would be to know how the label / facet configurations were set in the parameters of the DEMO site.
Screenshots of how the parameters were defined would be enough to be able to continue faster with my tests.

Many thanks
Luigi

**Comment by marevol** [comment]
1. Add a label with Name and Value at [Label](https://fess.codelibs.org/12.1/admin/labeltype-guide.html) page
2. Set the label at [Web Configuration](https://fess.codelibs.org/12.1/admin/webconfig-guide.html) page

That's it.

**Comment by luigigf49** [comment]
Ok.

Many thanks
