### ISSUE TITLE
Variable for only path to taget file

### ISSUE THREAD

**Issue by makiyama-shinji** [codelibs/fess#1698]
Hi,

I crawl file system and search results show links to href="${doc.urlLink}".
Are there any variable for only path to target file ?

**Comment by marevol** [comment]
`doc.filename` is available.

**Comment by makiyama-shinji** [comment]
Thank you for your support.
Do you mean I can use "${doc.filename}" instead of "${doc.urlLink}" ?

<h3 class="title ellipsis">
	<a class="link" href="${doc.filename}" data-uri="${doc.filename}"
		data-id="${doc.doc_id}" data-order="${s.index}">${f:h(doc.contentTitle)}</a>
</h3>

It does not work...
How can I use "${doc.filename}" ?

**Comment by makiyama-shinji** [comment]
a class="link" href="${doc.filename}" data-uri="${doc.filename}"
		data-id="${doc.doc_id}" data-order="${s.index}">${f:h(doc.contentTitle)}</a
