### ISSUE TITLE
Search result and labels

### ISSUE THREAD

**Issue by luigigf49** [codelibs/fess#1701]
Hi all,

Fess demo shows documents obtained from search profiles and also possible labels with their frequencies.
Documentation about JSON API explains clearly how to use labels but I don't found how to obtain labels and number for each labels together documents found.

Many thanks

**Comment by marevol** [comment]
See `facet.field` and `facet.query` in [Search API](https://fess.codelibs.org/12.1/api/api-search.html).

**Comment by luigigf49** [comment]
Perfect !

Thanx
