### ISSUE TITLE
AWS-S3 as a file crawl target.

### ISSUE THREAD

**Issue by nabedge** [codelibs/fess#1714]
I will be happy if FESS file crawler supports AWS-S3.

like this.
```
file:/home/share
smb://server/share
s3://foo-bar-bucket/baz
```
https://fess.codelibs.org/ja/12.1/admin/fileconfig-guide.html

**Comment by marevol** [comment]
Okay, I'll do that when I have time...

**Comment by marevol** [comment]
Fixed in [fess-ds-s3](https://github.com/codelibs/fess-ds-s3).
