### ISSUE TITLE
Re-crawl - boost reset

### ISSUE THREAD

**Issue by charles-pinkston** [codelibs/fess#1715]
When re-crawling a site, manual edits to a specific document's 'boost' value are being reset to the default of `1.0`.

**Comment by marevol** [comment]
An indexed document are overwritten by recrawling it.

**Comment by jeiholzer** [comment]
I think I see our problem. Hopefully I am understanding. So FESS keeps track of boosts separate from the search engine. Do you know if it keeps a whole different set of data or if it copies the current metadata from the search engine before it over writes it?

How does it handle click tracking? We are losing our click tracking data, Is there a place for FESS to keep that?

**Comment by marevol** [comment]
See [search.js](https://github.com/codelibs/fess/blob/fess-12.1.4/src/main/webapp/js/search.js#L38).
