### ISSUE TITLE
Config optimisations and tweaks for speed.

### ISSUE THREAD

**Issue by Quardah** [codelibs/fess#1716]
Hi folks.

I have been using the software for a while now but due to the large size of its reach the performances are acceptable at most. Our infra is terribly large therefore every tips, trick and tweak is welcome to help us speed up the process.

Please let me know if you have any performance tweaks for FESS configuration thanks.

**Comment by marevol** [comment]
Performance tuning depends on where is a bottleneck. 
Fess has a lot of settings, and examples are as below:

- Change [the number of threads and interval time](https://fess.codelibs.org/12.1/admin/fileconfig-guide.html#the-number-of-thread)
- Change [Simultaneous Crawler Config](https://fess.codelibs.org/12.1/admin/general-guide.html#simultaneous-crawler-config)
- Change [mappings](https://github.com/codelibs/fess/blob/fess-12.1.3/src/main/resources/fess_indices/fess/doc.json) (ex. change analyzers, replace langstring,...)
- Change the number of shards for [fess](https://github.com/codelibs/fess/blob/fess-12.1.3/src/main/resources/fess_config.properties#L214) and .crawler indices
- Change [queue parameters](https://github.com/codelibs/fess/blob/fess-12.1.3/src/main/resources/fess_config.properties#L207-L208) for indexer
- Change [term sizes](https://github.com/codelibs/fess/blob/fess-12.1.3/src/main/resources/fess_config.properties#L155-L157)
- Disable [document cache](https://github.com/codelibs/fess/blob/fess-12.1.3/src/main/resources/fess_config.properties#L193)
...
