### ISSUE TITLE
Create Automatically Access Token

### ISSUE THREAD

**Issue by PhuongHaNguyen** [codelibs/fess#1720]
Hi Marevol ! 
I want create automatically Access Token. I was create file access_token.bulk then use Postman test API http://localhost:8080/api/admin/general then result return as "Unauthorized request". 

Please help me, how to create access token by file access_token.bulk.

**Comment by marevol** [comment]
bulk file is imported when .fess_config.* index is created.
It's one time process.

**Comment by PhuongHaNguyen** [comment]
Thank's so much for reply me.
But i don't understand you more in detail.
