### ISSUE TITLE
What type of link (anchor or button) will click by fess to web crawl?

### ISSUE THREAD

**Issue by kanekot** [codelibs/fess#1728]
Hi.
I'm very new to fess.it's fantastic app.

What type of link (anchor or button) will click by fess to web crawl?
I'm tring to crawl my a few redmine site.
Should I exclude any url pattern to avoid delete or updating my tickets or dmsf file and redmine settings.

**Comment by marevol** [comment]
Fess follows links in [transformer_basic.xml](https://github.com/codelibs/fess-crawler/blob/fess-crawler-parent-2.1.3/fess-crawler-lasta/src/main/resources/crawler/transformer_basic.xml#L54-L75).

**Comment by kanekot** [comment]
thank you so much.
and every url will request by get method?

and my note...
issue journal delete -> using put method -> ok(must be)
issue delete using delete method -> ok(must be)
issue update using submit form  -> ok
dmsf file delete -> using get method -> ng
and may more...

should be including determinate urls to crowling and indexing. like /issues/.*

**Comment by marevol** [comment]
It's GET request.

**Comment by kanekot** [comment]
Thank you!
