### ISSUE TITLE
Upgrade fro 12.1.3 to 12.1.4

### ISSUE THREAD

**Issue by luigigf49** [codelibs/fess#1729]
Hi all,
I would like to upgrade my version from 12.1.3 to 12.1.4 which are within two different folders.
I have created the backups of the 12.1.3 configuration files as indicated in the link https://fess.codelibs.org/12.1/admin/backup-guide.html
Now I would like to migrate my configurations (at least those contained in the fess_basic_config and fess_user files) into the new version.
The functionality of UPGRADE indicated in the link http: //localhost:8080/admin/upgrade/ does not seem to help me since it does not know which version I want to migrate from ('**Version from**' does not contain any choice because,I guess,  it can not know where the old version's folder is).
Surely I could not interpret the indications of the documentation.

Many thanks
Luigi

**Comment by marevol** [comment]
12.1.x are compatible versions. 
You do not need to backup/restore configurations,
but since some settings are added, you need to update fess_config.properties.

**Comment by luigigf49** [comment]
Hi marevol,
in this case what is the correct update procedure?
I tried to roughly copy the contents of folder 12.1.4 in folder 12.1.3 but I do not think I did something very beautiful.
Should I first save some files from the 12.1.3 folder and then bring them back to the updated folder?
fess.bat starts regularly but 8080 is not reachable.
Attached two log files.

Many thanks

[server_0.log](https://github.com/codelibs/fess/files/2150381/server_0.log)
[fess.log](https://github.com/codelibs/fess/files/2150382/fess.log)

**Comment by marevol** [comment]
Do you use Elasticsearch cluster? 
Embedded Elasticsearch is not recommended for production use.
https://fess.codelibs.org/12.1/install/install.html#requirements

To upgrade 12.1.4 from 12.1.3 if using Elasticsearch cluster,
1. Install Fess 12.1.4
2. Merge config files, such as fess_config.properties

That's all.

**Comment by marevol** [comment]
Fess 12.1 does not support Elasticsearch 6.3.

**Comment by luigigf49** [comment]
Hi marevol,
What are the files that contain the definitions of General configuration, jobs, labels, files and datastore crawlers?

**Comment by marevol** [comment]
system.properties or .fess_config.* indices.

**Comment by luigigf49** [comment]
Perfect.
I copied **system.properties** and **indices** and now 12.1.4 works.

Many thanks
Luigi
