### ISSUE TITLE
Datastore crawling error

### ISSUE THREAD

**Issue by luigigf49** [codelibs/fess#1735]
Hi marevol,
I migrated from 12.1.3 to 12.1.4 including configuration files. 
File system crawling work well while datastore files report 'DataStoreException' errors'
[fess-crawler.log](https://github.com/codelibs/fess/files/2156713/fess-crawler.log)

I attach a log that maybe can give some indications.

Many thanks
Luigi

**Comment by marevol** [comment]
> Caused by: java.lang.ClassNotFoundException: oracle.jdbc.OracleDriver

You need to put Oracle JDBC jar file to app/WEB-INF/crawler/lib.

**Comment by luigigf49** [comment]
Now it works !

Many thanks
Luigi
