### ISSUE TITLE
Content_description length

### ISSUE THREAD

**Issue by luigigf49** [codelibs/fess#1736]
Hi marevol,

I found length definitions for some fields in fess_config.properties but nothing for Content_description.
Is it possible to define its length ?

Many thanks
Luigi

**Comment by marevol** [comment]
To do that, you need to modify [Transformer](https://github.com/codelibs/fess/tree/master/src/main/java/org/codelibs/fess/crawler/transformer) classes.

**Comment by luigigf49** [comment]
Ok.
Many thanks
