### ISSUE TITLE
Too many records for pagination

### ISSUE THREAD

**Issue by luigigf49** [codelibs/fess#1743]
Hi marevol,
when results are above 10.000 records pagination fails and the error message is:

**QueryPhaseExecutionException[Result window is too large, from + size must be less than or equal to: [10000] but was [16000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.]; }{[z3wbKR-jQhWRaXdcJnNaDg][fess.20180525][1]:** 

How can I change '_**index.max_result_window**_' ?

Many thanks
Luigi

**Comment by marevol** [comment]
See [Index Modules](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html).
It's elasticsearch setting, but it's better to avoid a deep scrolling without scroll api.

**Comment by luigigf49** [comment]
Ok.

Thanx
Luigi
