### ISSUE TITLE
Default crawler

### ISSUE THREAD

**Issue by luigigf49** [codelibs/fess#1748]
Hi marevol,

Default Crawler has the task to run all the crawlers that have been defined and scheduled (also those without a specific timing) ?

Thanks
Luigi

**Comment by marevol** [comment]
Yes. Fess controls the number of crawling settings by [Simultaneous Crawler Config](https://fess.codelibs.org/12.1/admin/general-guide.html#simultaneous-crawler-config).

**Comment by luigigf49** [comment]
Very good.

Many thanks
Luigi
