### ISSUE TITLE
Accent insensitive terms

### ISSUE THREAD

**Issue by EyadA** [codelibs/fess#1771]
Hi there,

Is it possible to return results with Ascii folding? Example, GSA allows you to search for hopital and hôpital or securitaire and sécuritaire and you would get the same results. 

ElasticSearch has an asciifolding filter:https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-asciifolding-tokenfilter.html but I am unsure how I can apply it. Any suggestions?

**Comment by marevol** [comment]
You can edit app/WEB-INF/classes/fess_indices/fess/doc.json and then start reindexing on [Upgrade](https://fess.codelibs.org/12.1/admin/upgrade-guide.html) page.

**Comment by EyadA** [comment]
Perfect, that did it!

**Comment by rafael844** [comment]
Im newbie in elastcsearch and fess, could someone tell me how to introduce this code in doc.json ?
Im also trying to put accents in the search and show same results as described above.
