### ISSUE TITLE
XSS Vulnerability

### ISSUE THREAD

**Issue by jb8893** [codelibs/fess#1782]
I noticed a cross-site scripting vulnerability during a security scan in the query parameter of the go function. You can trigger it by making a GET request like the following:

https://localhost/go/?rt=1532455559505&docId=031758aa0e8e417c9033c7259bd463da%3Cscript%3Ealert%284387%29%3C%2Fscript%3E&queryId=3ae8b8b2db574a5c950bc4abdbddb268&order=9&hash=%23search%3D%25221234%2522

Is there any fixes for this?

**Comment by marevol** [comment]
Fixed in #1786.
