### ISSUE TITLE
how set just html index

### ISSUE THREAD

**Issue by MajidSafari** [codelibs/fess#1791]
how set just html index ?

**Comment by marevol** [comment]
Need more info...

**Comment by MajidSafari** [comment]
some time css and js index in fess

**Comment by MajidSafari** [comment]
![screenshot 6](https://user-images.githubusercontent.com/5099564/43354756-0d57cdbc-9267-11e8-8595-d6121b13f6ee.png)

**Comment by marevol** [comment]
To exclude css files, put `.*\.css` to [Excluded URLs For Crawling](https://fess.codelibs.org/12.1/admin/webconfig-guide.html#excluded-urls-for-crawling).
