### ISSUE TITLE
Sitemap Trailing Slash - Not Found Exception

### ISSUE THREAD

**Issue by jb8893** [codelibs/fess#1806]
When the sitemap.xml file is being crawled, it gets a trailing slash appended to the end which results in a 404 error.  Is there a fix for this besides using a rewrite rule for slashes?

Thanks!

**Comment by marevol** [comment]
Could you provide an example of sitemap.xml to reproduce it?

**Comment by jb8893** [comment]
https://njcourts.gov/sitemap.xml

**Comment by jb8893** [comment]
http://njcourts.gov/sitemap.xml/ was appearing in the failure URL.  However that was not the issue that was causing the problem.  The sitemap was using http://www.example.com, instead of http://example.com.  I added it to the "Included URLs for Crawling" and the problem has been fixed.  However I am still not sure why it was appearing in the Failure URL List with a slash appended to it.

Thanks again for your help!

**Comment by marevol** [comment]
It do not think it's a problem about sitemap... The links might be in your site.
You can use [Path Mapping](https://fess.codelibs.org/12.2/admin/pathmap-guide.html) to replace `xml/` with `xml`.
To normalize a hostname, see [Duplicate Host](https://fess.codelibs.org/12.2/admin/duplicatehost-guide.html).
