### ISSUE TITLE
How to use sorting option in JSON API?

### ISSUE THREAD

**Issue by riceming** [codelibs/fess#1808]
I want to sort document by their date with JSON API, but I can't find it in documentation.  

Can anyone tell me how to do that?  or is it implemented yet?

**Comment by marevol** [comment]
Try sort parameter as below:

https://search.n2sm.co.jp/json/search?q=test&num=10&sort=last_modified.desc

**Comment by riceming** [comment]
great, thanks
And please also add this to the document
https://fess.codelibs.org/12.2/api/api-search.html
