### ISSUE TITLE
Popular words are not displayed.

### ISSUE THREAD

**Issue by gonpchan** [codelibs/fess#1813]
Popular words are not displayed in the following environments.
* WindowsServer2012R2
* fess-12.2.0
* elasticsearch-6.3.2

The executed operations are as follows. It is the same situation as #1654 .
1. Popular Word Response is Enabled.
1. Search more than 10 times at 1 minute intervals
1. Run  Suggest Indexer.

The result of curl is as follows.
<pre>{"response":{"version":12.2,"status":0,"result":[]}}</pre>

**Comment by gonpchan** [comment]
Thank you for your reply immediately.
However, There was no change even if executed.
I am confirmed to operate in the following environment.
* fess-12.1.4
* elasticsearch-6.2.4

Please let me know if there is something to investigate.

**Comment by iladrero** [comment]
Same issue, config reloader won't solve it, any ideas?
fess.version=12.3.0

**Comment by julianopcardoso** [comment]
Same thing with me.

**Comment by gonpchan** [comment]
I do not know whether it has changed, but it did not matter with fess-12.2.3.

**Comment by duynqvn** [comment]
I have the same issue in both of fess-12.1.4 and fess-12.2.3.
Any suggestions?

**Comment by marevol** [comment]
Is it reproduced in the latest Fess 12.4?

**Comment by duynqvn** [comment]
It is reproduced in the Fess-12.4.3 too.
Is there any attention points when we produce popular words?

Best regards,

**Comment by marevol** [comment]
> 2. Search more than 10 times at 1 minute intervals

You need to access a new session(remove cookies).

**Comment by duynqvn** [comment]
Thank you for your reply.
It worked. The popular word is displayed with fess-12.2.3 and higher version now.
Best regards,
