### ISSUE TITLE
"Cache" link does not display on mobile

### ISSUE THREAD

**Issue by boredwookie** [codelibs/fess#1816]
I would like to let my users leverage the 'Cache' link on their mobile devices. Is there a way to configure the mobile template to display this? In my testing today with Android devices I did not see the link appear. Not afraid to dig into the code if necessary, just want to make sure I'm not missing a straight-forward configuration setting.

**Comment by marevol** [comment]
Since cache page is not mobile friendly, the link is not displayed.
To put Cache link, you can edit searchResult.jsp on [Design page](https://fess.codelibs.org/12.2/admin/design-guide.html).

**Comment by boredwookie** [comment]
Ah, I think I get it now! Thank you. :)
