### ISSUE TITLE
Index DOC(X)/WORD metadata

### ISSUE THREAD

**Issue by bhdzllr** [codelibs/fess#1821]
Referring to Issue #1360 I try to add modification date meta data for Word-Documents.

As mentioned in Issue #1360 I added the configuration to fess_config.properties and now I have "modDate" meta data for PDFs but not for Word-Documents.

```
crawler.metadata.name.mapping=\
title=title:string\n\
Title=title:string\n\
meta:modDate=modDate:string\n\
ModDate=modDate:string\n\
meta:creationDate=creationDate:string\n\
CreationDate=creationDate:string\n\
```

So I tried adding `Last-Modified=modDate:string\n\` as follows:

```
crawler.metadata.name.mapping=\
title=title:string\n\
Title=title:string\n\
meta:modDate=modDate:string\n\
ModDate=modDate:string\n\
Last-Modified=modDate:string\n\
meta:creationDate=creationDate:string\n\
CreationDate=creationDate:string\n\
```

But still no modification date for Word-Documents. How can i configure Fess to index this meta-data?
Information about Office meta data: https://www.tutorialspoint.com/tika/tika_extracting_ms_office_files.htm

**Comment by marevol** [comment]
You can check extracted metadata by debug level logging.
See https://github.com/codelibs/fess/issues/1073#issuecomment-304397187

**Comment by bhdzllr** [comment]
Thank you for the information with the debug level logging.

I found the field "modified" as meta-data for Word-Documents in the log file, so my declaration looks as follows:

```
crawler.metadata.name.mapping=\
title=title:string\n\
Title=title:string\n\
meta:modDate=modDate:string\n\
ModDate=modDate:string\n\
modified=modDate:string\n\
meta:creationDate=creationDate:string\n\
CreationDate=creationDate:string\n\
```

It works. However "Last-Modified" is also a property but it doesn't work. Maybe because of the hypen?
