### ISSUE TITLE
Enabling SSL in FESS

### ISSUE THREAD

**Issue by ECJansen** [codelibs/fess#1829]
I'm looking to enable SSL in FESS for the search page.
Where is the server.xml file located ?  It's not in the app/WEB-INF/conf directory.
Is there any documentation on enabling SSL ?

Thanks,
Eric

**Comment by marevol** [comment]
https://github.com/codelibs/fess/issues/1162#issuecomment-315202848

**Comment by ECJansen** [comment]
I assume that FESS is using Apache as part of the FESS package,
but where are the Apache configuration files within FESS ?
Where is the server.xml file located ?

Thanks,
Eric

**Comment by marevol** [comment]
It's not correct.
For example,
1. Install Apache
2. Install Fess
3. Configure Apache's files, such as httpd.conf, to use as a reverse proxy

**Comment by ECJansen** [comment]
Ah.  Will do.  Thanks !

**Comment by julianopcardoso** [comment]
I need to configure SSL/https in Fess.
For example https://<SERVER>:443/search and https://<SERVER>:443/admin .

How I do it?
