### ISSUE TITLE
Can I override "click_count" when crawl ?

### ISSUE THREAD

**Issue by kaleid-scope** [codelibs/fess#1831]
I am trying to overwrite "click_count" when crawling CMS (Joomla) data from mysql.

Specifically, when I output search results in API, I want the result to be output in descending order of "hits".
("hits" is the number of articles viewed in Joomla)

I set "click_count=hits" to "script" in the crawler setting but it was not overwritten. 

I think that I should also invalidate counting the number of clicks of the search result of FESS.
Is it possible to realize this?

**Comment by marevol** [comment]
Fess manages `click_count` and `favorite_count`.
So, it's better to use other own field after adding it.

**Comment by kaleid-scope** [comment]
Thank you for your reply.

Then, I investigated how to add fields from the past issues.
#1357 

Is the procedure as follows? ( When adding a field named "hits" )
1.  Edit doc.json (path:app/WEB-INF/classes/fess_indices/fess/doc.json)
```
"hits": {
"type": "keyword"
},
```
2.  Edit fess_config.properties (path: /etc/fess/fess_config.properties )
```
index.field.hits=hits
query.additional.response.fields=hits
query.additional.search.fields=hits
query.additional.sort.fields=hits
```
(Is it also necessary to set up the following comments?https://github.com/codelibs/fess/issues/1357#issuecomment-347333794 )

3. Restart FESS

（The version of FESS is 12.1.)
