### ISSUE TITLE
LANG of the environment variable property of FESS's system information becomes US.UTF-8 instead of ja-JP.UTF-8

### ISSUE THREAD

**Issue by ajinotatakii** [codelibs/fess#1832]
In the property of the environment variable of system information, **"LANG = en_US.UTF - 8"** is displayed, but what is the cause of this?

FESS is running as a Docker container on CentOS 7.5. (Image source is FROM openjdk: 8-jre)
At build time, locale is set in Dockerfile as follows.

_RUN_ echo "ja_JP.UTF - 8 UTF - 8" >> /etc/locale.gen && \
_locale-gen_ && \
_update-locale_ LANG = ja_JP.UTF-8 && \
_echo_ "export LANG = ja _ JP.UTF - 8" >> /etc/profile.d/lang.sh

When entering the container with docker exec -it fess / bin / bash, **LANG = ja-JP.UTF-8** is set.

**Comment by marevol** [comment]
Fess and Elasticsearch run on en_US.UTF-8.
It should not be changed.

**Comment by ajinotatakii** [comment]
THX for your answer.
Because Japanese path and filename can not be crawled, I thought that the system environment variable LANG = en_US.UTF-8 is caused, but it is another cause.
It is confirmed that the file name is UTF - 8.
