### ISSUE TITLE
FESS Rest APIs for Crawling and Scheduler

### ISSUE THREAD

**Issue by farooqsheikhpk** [codelibs/fess#1833]
Hi @marevol 

https://fess.codelibs.org/12.3/api/api-search.html

I am unable to see FESS Rest APIs for Crawling and Scheduler. is it implemented? 

If Yes, Please share the documentation or Swagger Docs for review. 

If No? Please share your future plan related to it. 

Thanks in advance for all your cooperation.

**Comment by marevol** [comment]
See https://github.com/codelibs/fess/issues/1057#issuecomment-305186767 and [lastadoc-fess.html](https://fess.codelibs.org/lastadoc-fess.html).
