### ISSUE TITLE
curl4j appears to leave behind a lot of curl4j-*.tmp files

### ISSUE THREAD

**Issue by burple6** [codelibs/fess#1840]
My fess installation produces a large number of curl4j-*.tmp files in the /var/tmp/fess directory that never get cleaned up. I suspect that the tmp files are only being cleaned up when there is an exception, and not under normal circumstances.

**Comment by marevol** [comment]
I'll fix it in next release. thanks.

**Comment by hellonico** [comment]
got stuck into this one too, so we created a cron job to delete those files.
Any settings around to avoid this ?

**Comment by marevol** [comment]
This problem has been fixed.
Do you use the latest version?
