### ISSUE TITLE
Exclude files and only allowed doc, pdf files in fess

### ISSUE THREAD

**Issue by minhtienhcmus** [codelibs/fess#1842]
I want to setup [Excluded Paths For Crawling] in file system of fess.
I want to Exclude files and only allowed doc, pdf files in fess  by ((\\.|\/)(?!pdf|doc).*$)
but not working !!!
I need to know what to do!!!!!
thank!!

**Comment by marevol** [comment]
Use "[Excluded URLs For Indexing](https://fess.codelibs.org/12.3/admin/webconfig-guide.html#excluded-urls-for-indexing)", not "Excluded URLs For Crawling".
