### ISSUE TITLE
WARN cluster:configsync/flush in elasticsearch

### ISSUE THREAD

**Issue by freestyle68** [codelibs/fess#1843]
Hello,

Java Oracle 8
Fess 12.3 release
Elasticsearch 6.4.1

I'm receiving a lot of this warning on elasticsearch.log:

`[WARN ][o.e.t.TransportService   ] [Luv8G7b] invalid action name [cluster:configsync/flush] must start with one of: [cluster:admin, indices:data/read, indices:monitor, indices:data/write, internal:, indices:internal, cluster:monitor, cluster:internal, indices:admin]`

can this alert slow the crawling process?

Thank you

**Comment by marevol** [comment]
Did elasticsearch 6.4.0 work?

**Comment by freestyle68** [comment]
yes, now using 6.4.1. Now I see the message only on elasticsearch boot.

**Comment by marevol** [comment]
Released Fess 12.3.1 compiled with Elasticsearch 6.4.1.

**Comment by freestyle68** [comment]
I continue to see now, but this is not cause if  any issue apparently.

Thank you
