### ISSUE TITLE
IndexUpdater info

### ISSUE THREAD

**Issue by freestyle68** [codelibs/fess#1845]
Hi,

Fess last commit (yesterday), Java 10 and elasticsearch 6.4.1.

It happens the performance of a smb crawling are progressively degrading, after 130000 docs becoming very slow. In this case I see similar logs on fess-crawler.log and the crawling stop with low CPU usage and low IO throughput, so this is not a hardware resource problem. I have tuned garbage collector but with litte success.

```
2018-09-23 11:56:31,190 [IndexUpdater] INFO  Sent 10 docs (Doc:{process 80ms, send 1309ms, size 4MB}, Mem:{used 1GB, heap 8GB, max 8GB})
2018-09-23 11:56:31,194 [IndexUpdater] INFO  Processing no docs (Doc:{access 4ms, cleanup 35ms}, Mem:{used 1GB, heap 8GB, max 8GB})
```
What this messages mean?

Thank you

**Comment by marevol** [comment]
You need to set proper settings(# of shards, heap size,...) for your environment.

> 2018-09-23 11:56:31,190 [IndexUpdater] INFO  Sent 10 docs (Doc:{process 80ms, send 1309ms, size 4MB}, Mem:{used 1GB, heap 8GB, max 8GB})

Fess sent 10 docs to fess.YYYYMMDD index in elasticsearch.
For details, see [IndexUpdater](https://github.com/codelibs/fess/blob/master/src/main/java/org/codelibs/fess/indexer/IndexUpdater.java).
If you need more support, please contact [Commercial Support](https://www.n2sm.net/en/support/fess_support.html).
