### ISSUE TITLE
Multiple Label Apply instead of selected one

### ISSUE THREAD

**Issue by farooqsheikhpk** [codelibs/fess#1846]
@marevol
In my web crawling configuration. I just mention to apply one label but FESS server auto apply all other 
labels? Why? System is not matching label include paths though. Is it a known bug? Kindly explain.

I am using fess-12.3.0.

**Comment by marevol** [comment]
I think that you selected [Labels](https://fess.codelibs.org/12.3/admin/webconfig-guide.html#labels) in web config.
If you did that, remove them.

**Comment by farooqsheikhpk** [comment]
@marevol 
> I think that you selected Labels in web config.
Yes, I selected only one label during web config for crawler. 

>If you did that, remove them.
If i remove them how can i apply only selected label for this crawler configuration.

**Comment by marevol** [comment]
See [Included Paths](https://fess.codelibs.org/12.3/admin/labeltype-guide.html#included-paths).

**Comment by farooqsheikhpk** [comment]
@marevol 

Thanks for your quick reply. Much Appreciated. 

I think i didn't explain my scenario well.  Let me re-phrase it. 

Question:
I have n labels where Included/Excluded Path are properly set in each label configuration. 
It is possible some of labels have common include path. 
Now I want to apply Only One Label for a Web Crawler? I have selected one particular label in Web Crawler configuration but it looks FESS ignore it during crawling and apply all label configurations.

Kindly guide restrict crawler to use only selected labels and ignore others. 

Thanks in advance for all your cooperation.

**Comment by farooqsheikhpk** [comment]
Thanks @marevol . I got my answer in the code. 

If label is selected in web config. i will added by default and other match labels will also apply. 

`
// label: labelType
        final Set<String> labelTypeSet = new HashSet<>();
        for (final String labelType : crawlingConfig.getLabelTypeValues()) {
            labelTypeSet.add(labelType);
        }
        labelTypeSet.addAll(labelTypeHelper.getMatchedLabelValueSet(url));
`
