### ISSUE TITLE
Web authentication

### ISSUE THREAD

**Issue by iladrero** [codelibs/fess#1848]
Anybody has a working sample/template for authentication settings on Web Auth page? Trying to access RESTful web with login page with no results, already tried [documentation sample](http://fess.codelibs.org/11.3/admin/webconfig-guide.html#redmine) with no success.

**Comment by marevol** [comment]
> RESTful web with login page

It's not supported.

**Comment by buithehien1991** [comment]
Dear @marevol 

Could you please provide search API with authentication ?
for example: http://localhost:8080/search/?q=test&username=admin&password=admin 

I want each user can be search on each site. If you have another way, please tell me. 

Thank you so much for your answer
