### ISSUE TITLE
Labels in  alphabetical order

### ISSUE THREAD

**Issue by freestyle68** [codelibs/fess#1849]
Hello,

with Fess 12.3.1 I cannot put labels in alphabetical order while in Fess 11.4 it was possible putting a progressive number on "value" field on label definition.

Tried also with Display Order but no differences.

Thank you

**Comment by marevol** [comment]
Try to change sort in app.xml.
```
        <component name="facetInfo" class="org.codelibs.fess.entity.FacetInfo">
                <property name="sort">"term"</property>
```

**Comment by freestyle68** [comment]
Yes, this works.

Thank you very much
