### ISSUE TITLE
404 error after restart

### ISSUE THREAD

**Issue by khiraku** [codelibs/fess#1850]
Hello,
I have a problem restarting fess correctly.
I've installed Fess 12.1.0 using RPM and everything was working well.
But after closing the services I tried to restart them but they did not work anymore.

Thanks in advance.
[fess.log](https://github.com/codelibs/fess/files/2427246/fess.log)
[server_0.log](https://github.com/codelibs/fess/files/2427247/server_0.log)

**Comment by marevol** [comment]
Did you check elasticsearch.log?

> Caused by: NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{IkZ1pk9mTnOLWgry9fM1Aw}{localhost}{127.0.0.1:9300}]]

Elasticsearch does not work.

**Comment by khiraku** [comment]
Thank you for your reply.
This is my elasticsearch.log.

[elasticsearch.log](https://github.com/codelibs/fess/files/2432302/elasticsearch.log)

Thank you.

**Comment by khiraku** [comment]
Thank you for the response.

I've installed fess on testing environment and production environment.
On both environment, they did not work after restart.
These are logs of testing environment.

[fess.log](https://github.com/codelibs/fess/files/2432403/fess.log)
[server_0.log](https://github.com/codelibs/fess/files/2432404/server_0.log)
[elasticsearch.log](https://github.com/codelibs/fess/files/2432405/elasticsearch.log)

It seems they don't say about network problem.

Acttually, I tried to access elasticsearch(servername:9200) over web browser, only on production environment.

Thanks in advance.

**Comment by marevol** [comment]
Did you change elasticsearch.yml?
I do not think it might be correct configurations.

**Comment by khiraku** [comment]
Exactly.
I changed elasticsearch.yml to check if elasticseach works.
After retoring settings, the sytem works correctly.
Thank you very much.
