### ISSUE TITLE
Fess crawler  lost(missing) files 

### ISSUE THREAD

**Issue by minhtienhcmus** [codelibs/fess#1857]
Currently I use fess version 12.1
When I crawler, some files are crawled but not displayed when searching.
I saw [fess-crawler.log] but did not see anything
I do not know why
Can you help me explain this problem?
Thank you so much!!!

Below is a file not found when searching:
2018-10-04 02:50:49,872 [Crawler-PXtyPmYBBoKKj0VBTaDL-1-2] INFO  Crawling URL: smb://192.168.1.62/Test/Testproject/構築_5/営業/構築_4/20171115_集計リスト.xlsx

file [fess-crawler.log]:
[fess-crawler.log](https://github.com/codelibs/fess/files/2449261/fess-crawler.log)

**Comment by marevol** [comment]
You can check indexed content in [Admin Search page](https://fess.codelibs.org/12.3/admin/searchlist-guide.html).

**Comment by minhtienhcmus** [comment]
I had check in Admin Search page but Fess crawler also missing files

**Comment by marevol** [comment]
You can check debug logs if changing logLevel to debug for Default Crawler in Scheduler.
