### ISSUE TITLE
fess search engine

### ISSUE THREAD

**Issue by logeshwaris** [codelibs/fess#1858]
I integrated fess 12.3 with external elasticsearch 6.4 for my custom search application. I tried crawling  the html page and index the content in elasticsearch.  I see that the indexed content,digest is empty in elasticsearch. Only few fields like title,anchor,content_length are getting indexed.

fess_config.properties has **crawler.document.html.content.xpath=//BODY** by default but still its not indexing.
How can this be done? How do i tell fess /elasticsearch to index the html content so that fess search engine can search the appropriate content from indexed data?

**Comment by marevol** [comment]
I think that your installation was failed or the site does not contain a content.
You can check it by curl command:
```
curl http://...
```
