### ISSUE TITLE
What word was search and by who ?

### ISSUE THREAD

**Issue by buithehien1991** [codelibs/fess#1866]
Dear @marevol 

Did you have the way to know what word was search and by who?

Please let me know how to do it. 

Again, Thank you so much.

**Comment by marevol** [comment]
See [Search Log](https://fess.codelibs.org/12.3/admin/searchlog-guide.html).
It's added in 12.2.

**Comment by buithehien1991** [comment]
Thank you so much for your answer. I used 12.1.4. So I will try 12.2.
