### ISSUE TITLE
How can I dive into windows shortcut(folder) while constructing index.

### ISSUE THREAD

**Issue by amsiat2** [codelibs/fess#1868]
I am using Fess-12.3.2. I set the Fess to crawl on fileserver(my pc). I have one shortcut in the target folder. After index construction, I checked fess-crawler.log and confirmed that the target folder was crawled.(as shown below.)
 
2018-10-14 07:07:32,802 [Crawler-20181014070625-1-1] INFO  Crawling URL:     file:/e:/%E3%82%B9%E3%82%AD%E3%83%A3%E3%83%B3%E3%83%87%E3%83%BC%E3%82%BF/short.lnk

But no index was constructed. I confirmed that number of docs was 0 shown on dashbord.
How can I get index.

**Comment by marevol** [comment]
What is your file crawling config?

**Comment by amsiat2** [comment]
My config is like this.
![default](https://user-images.githubusercontent.com/44135037/46917422-107dec00-d002-11e8-882d-00237fdf7f4c.PNG)

**Comment by marevol** [comment]
Did you logout from admin?

**Comment by amsiat2** [comment]
No. I usually stay login as admin to excute ![image](https://user-images.githubusercontent.com/44135037/46947367-9313b380-d0b5-11e8-8cc1-4502def11770.png)/"start now" in the job scheduler page.
I tried "logout from admin" and use "47 18 15 * *" as "schedule", but there was no change in the situation.

**Comment by amsiat2** [comment]
I examed \*:\* and got a reply like below.
I expected that file contained in the my_document are listed.
![default](https://user-images.githubusercontent.com/44135037/47010940-6f1aa580-d17b-11e8-986f-f366a26493f3.PNG)

**Comment by amsiat2** [comment]
I am not willing to close.

**Comment by amsiat2** [comment]
I examed *:* and got a reply like below.
I expected that file contained in the my_document are listed.
![default](https://user-images.githubusercontent.com/44135037/47020854-38ea1f80-d195-11e8-9464-875a1777c23e.PNG)

**Comment by marevol** [comment]
Windows shortcut is just a file...

**Comment by amsiat2** [comment]
I understand. Thank you.
