### ISSUE TITLE
Are there any way to get more than 100 search result?

### ISSUE THREAD

**Issue by amsiat2** [codelibs/fess#1871]
I woud like to copy&paste or download  all the search result by one operation.

**Comment by marevol** [comment]
See https://github.com/codelibs/fess/issues/1555#issuecomment-373029044

**Comment by amsiat2** [comment]
I accessed to localhost:8080/json/scroll?q=* and got a text file, but the text seems to be garbled shown as below. Are there another setting to show 2-byte code correctly.
![default](https://user-images.githubusercontent.com/44135037/47118446-3a553e00-d2a2-11e8-8cd7-cf91a1d61588.PNG)

**Comment by marevol** [comment]
It's unicode escape, not  garbled one.

**Comment by amsiat2** [comment]
Dose Fess have decoder? Or decoding is end users task?

**Comment by marevol** [comment]
Fess does not provide a decoder.

**Comment by amsiat2** [comment]
Thank you.
