### ISSUE TITLE
Search files with spaces by filename field 

### ISSUE THREAD

**Issue by jay-cyrb** [codelibs/fess#1878]
I have 2 files: 'мой_документ.doc' and 'мой документ.doc'. Both of them are indexed. Then I search by
filename:"мой_документ.doc"
I get results which contains link to my_document.doc .
But if I search by
filename:"мой документ.doc"
search result page is empty!
Why FESS can't found file 'мой документ.doc' ? Maybe this problem with the space in filename?

**Comment by marevol** [comment]
duplicated.
