### ISSUE TITLE
Search files with spaces by filename field

### ISSUE THREAD

**Issue by jay-cyrb** [codelibs/fess#1879]
I have 2 files: 'мой_документ.doc' and 'мой документ.doc'. Both of them are indexed. Then I search by
filename:"мой_документ.doc"
I get results which contains link to my_document.doc .
But if I search by
filename:"мой документ.doc"
search result page is empty!
Why FESS can't found file 'мой документ.doc' ? Maybe this problem with the space in filename?

**Comment by marevol** [comment]
You can check indexed documents at [Admin Search](https://fess.codelibs.org/12.3/admin/searchlist-guide.html) page.

**Comment by jay-cyrb** [comment]
I try search this file at Admin Search by '*' query and find it. But I still can't find it with query
filename:"мой документ.doc"
Result page:
По запросу - filename:&#034;мой документ.doc&#034; - совпадений не найдено.

**Comment by marevol** [comment]
`filename:"мой документ.doc"` is a phrase query.
Could you try `filename:мой\ документ.doc`?

**Comment by jay-cyrb** [comment]
I try filename:мой\ документ.doc and get same result, i.e. nothing was found.
