### ISSUE TITLE
Search by url field (russian symbols)

### ISSUE THREAD

**Issue by jay-cyrb** [codelibs/fess#1881]
I have a file /home/плагины/file1.txt . Fess crawl it.
I try search this file
url:*плагины*
and get 0 result
But then I search
url:*file1*
I get link to this file. Why I can't search by field url with query which contain russian symbols?

field url of file1.txt :
file:/home/%D0%9F%D0%BB%D0%B0%D0%B3%D0%B8%D0%BD%D1%8B/file1.txt

**Comment by marevol** [comment]
For `file:`, characters other than ascii are url-encoded.
