### ISSUE TITLE
Path mapping dose not work as I expected.

### ISSUE THREAD

**Issue by amsiat2** [codelibs/fess#1885]
I set the Fess as below.
![default](https://user-images.githubusercontent.com/44135037/47602189-0bfbff00-da16-11e8-91df-98b401f18827.PNG)
And I got the search result as below. I think the under lined part "href=/go/.." is something wrong. 
How can I get "http://test.." as I set up.
![default](https://user-images.githubusercontent.com/44135037/47602200-61d0a700-da16-11e8-9c8b-55f8fa479298.png)

**Comment by marevol** [comment]
You can check a field value of `url` in [Admin Search](https://fess.codelibs.org/12.3/admin/searchlist-guide.html) page.
I think it's url-encoded.

**Comment by amsiat2** [comment]
I checked Admin Search, and the result is as below. How can I replace "file:/E:/.." to "http://.."?
![default](https://user-images.githubusercontent.com/44135037/47602533-62b80780-da1b-11e8-83b2-c94929636f7f.png)

**Comment by marevol** [comment]
Did you check `url` field?
It's not included in these screenshots.

**Comment by amsiat2** [comment]
I stopped using 2Byte-Char with "Regexp" and "Replacement"
Then I got the result as below. Am I going right way? 
![default](https://user-images.githubusercontent.com/44135037/47651295-2543ad80-dbc6-11e8-9002-4c1d09a9c216.PNG)

**Comment by amsiat2** [comment]
I copied the 2 lines in the admin_search_list.jsp shown as below on to the 3 lines in the  searchResult.asp. And then it worked. Is this a right way to solve my broblem?

admin_searchlist.jsp:
<h3 class="title">
	<a href="${doc.url_link}">${doc.content_title}</a>
searchResult.asp:
<h3 class="title text-truncate">
	<a class="link" href="${doc.url_link}" data-uri="${doc.url_link}"
		data-id="${doc.doc_id}" data-order="${s.index}">${doc.content_title}</a>

**Comment by marevol** [comment]
What is your problem?
I need more details...
