### ISSUE TITLE
Is Fuzzy enabled?

### ISSUE THREAD

**Issue by SoloRobo** [codelibs/fess#1887]
In the docs it refers to fuzzy search, the default being ~0.5.

https://fess.codelibs.org/12.3/user/search-fuzzy.html

I am not seeing this in my results, setting ~0.5 in a search query works.

I saw this change and wondered if it was having an effect:

https://github.com/codelibs/fess/issues/277

Is the default fuzzy level configurable for simple search queries? I haven't been able to find it.

I am using Fess 12.3.2, ElasticSearch 6.4.2

**Comment by marevol** [comment]
It works.
https://search.n2sm.co.jp/search/?q=avator
https://search.n2sm.co.jp/search/?q=avator~0.8

**Comment by SoloRobo** [comment]
Thank you for your response.

My reading of the documentation implies that the default setting on a query is ~0.5

https://fess.codelibs.org/12.3/user/search-fuzzy.html
"If no fuzzy value, the default is 0.5."

I would assume this would mean this on all queries:

https://search.n2sm.co.jp/search/?q=avator+~0.5

I must be misunderstanding the doc.

Since it appears to not be configurable, I will approach this differently.

Thank you for your amazing work!
