### ISSUE TITLE
Indexing Meta Tags

### ISSUE THREAD

**Issue by zackhorvath** [codelibs/fess#1893]
Hey everyone,

I have a collection of html pages that have meta tags such as `<meta name="template" content="news"/>` that I am trying to index in ElasticSearch. I've tried a few different settings that others have mentioned in their issues but have become stuck.

So far, I have been able to create a "template" text-type field in ElasticSearch, but have not been able to populate it with any data. Here's what I've done so far...

1. Edited **doc.json** in **/usr/share/fess/app/WEB-INF/classes/fess_indices/fess/doc.json**:
`"template": {
  "type": "text"
},`
2. Added the following to **/etc/fess/fess_config.properties**:
`index.field.template=template
index.admin.long.fields=template
query.additional.response.fields=template
query.additional.api.response.fields=template
query.additional.scroll.response.fields=template
query.additional.cache.response.fields=template
query.additional.search.fields=template
query.additional.sort.fields=template
crawler.metadata.name.mapping=\
title=title:string\n\
Title=title:string\n\
meta:modDate=modDate:string\n\
ModDate=modDate:string\n\
modified=modDate:string\n\
meta:creationDate=creationDate:string\n\
CreationDate=creationDate:string\n\
Template=template:string`
3. Modified **transformer.xml** in **/usr/share/fess/app/WEB-INF/classes/crawler**:
`		<postConstruct name="addFieldRule">
			<arg>"template"</arg>
			<arg>"//META[@ property =\"template\"]/@content"</arg>
		</postConstruct>
`
4. Added the following Config Parameter to the Web Crawl config:
`field.xpath.template=//META[@property='template']/@content`

I have also tried using doc type "keyword", and reloading the index using Maintenance > ReIndex

Thanks!

**Comment by marevol** [comment]
3 is not needed.
XPath is `//META[@name='template']/@content`, not `//META[@property='template']/@content`
You can check more details in debug logs.

**Comment by zackhorvath** [comment]
Ah! Duh! Of course. Arigato Gozaimasu!

I pulled the snippet from https://github.com/codelibs/fess/issues/1634 but forgot to update the meta params for my use. Thanks for the advice on debug logs too!
