### ISSUE TITLE
Create user when login with LDAP/SSO

### ISSUE THREAD

**Issue by buithehien1991** [codelibs/fess#1899]
Dear @marevol 

Can we create user account when login with LDAP?
If we can. Please add option on setting page: Enable Auto Registering users if they do not exist
If we can't. Please tell me some description (class, flow) to modify current source code to create user. 

I saw at LdapManager.java has method createLdapUser(final String username, final Hashtable<String, String> env)

Thank you so much for your help.

**Comment by marevol** [comment]
> Can we create user account when login with LDAP?

LDAP user does not have to create a user in Fess, so Fess does not create it.
However, configuring `ldap.admin.enabled=true` and `ldap.admin.*` settings, Fess manages user information in Fess Admin pages.

**Comment by buithehien1991** [comment]
Dear @marevol 

I have already configuring ldap.admin.enabled=true and ldap.admin.* settings. But I can't see list ldap user on User admin page. When I click on admin or created user, more user information (such as: Employee Number, Telephone Number, Home Phone, ....)

How I can see ldap user on User page to config role and group. 

Thank you and best regards,
Bui The Hien

**Comment by buithehien1991** [comment]
I changed LdapManager source code to can map Role with LDAP User
