### ISSUE TITLE
How do I create an Access Token to use the Fess Delete Api

### ISSUE THREAD

**Issue by akopcz2** [codelibs/fess#1902]
I am unable to find the Access Token configuration under the Crawler tab in the sidebar. 
I am using fess 12.3.2
 Is there a config setting that I need to enable for this to be visible?

**Comment by akopcz2** [comment]
> Access Token page is in System tab.

Thank you!

**Comment by akopcz2** [comment]
curl -X "DELETE" -H "Authorization: ttjtBzxjeGhsoZxb1oD99EAtU1T8p0NFyqe5j7K8lnd5wp4BTyLeAsyq6QgC" -H "docId: ca276adc0622413fa45f5ce861d0a365" http://localhost:8080/admin/searchlist/delete

Would this be the correct way to send the delete action to FESS?

**Comment by marevol** [comment]
See https://fess.codelibs.org/lastadoc-fess.html#.api.admin.searchlist.doc._b_id_e_::delete_d_doc

**Comment by akopcz2** [comment]
> See https://fess.codelibs.org/lastadoc-fess.html#.api.admin.searchlist.doc._b_id_e_::delete_d_doc

Thank you Marevol! Seems I was missing one very important piece in all of this.
 Creating the  "admin-api" token with the role of {role}admin-api. 
I was originally using a token named admin with role of admin.
