### ISSUE TITLE
Is there any way to obscure the tomcat version in error pages with FESS?

### ISSUE THREAD

**Issue by burple6** [codelibs/fess#1903]
Is there any way to obscure the tomcat version in error pages with FESS?

**Comment by marevol** [comment]
What is a step to reproduce it?
Basically, Tomcat error pages do not show up.

**Comment by burple6** [comment]
telnet IP_obscured 8080
Trying IP_obscured...
Connected to IP_obscured
Escape character is '^]'.
GET / HTTP/1.1

HTTP/1.1 400
Content-Type: text/html;charset=utf-8
Content-Language: en
Content-Length: 1127
Date: Fri, 16 Nov 2018 13:02:33 GMT
Connection: close

<!doctype html><html lang="en"><head><title>HTTP Status 400 â Bad Request</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 â Bad Request</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Description</b> The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).</p><hr class="line" /><h3>Apache Tomcat/9.0.11</h3></body></html>Connection closed by foreign host.
