### ISSUE TITLE
Does Path Mapping replace the link destination from local PC to remote server?

### ISSUE THREAD

**Issue by amsiat2** [codelibs/fess#1904]
I backuped my data from a remote windows server to a local windows PC. And builded an index on the PC. And then, I have tested with settings as below, but I could only get some errors, or link jump to the local. Is it possible to replace the links from the local to the remote?  

RegEXP file:/c:/backup
Replacement  file(or smb)://xxxx/target

**Comment by marevol** [comment]
Yes.

**Comment by amsiat2** [comment]
Is it possible to do by using Fess's GUI?

**Comment by amsiat2** [comment]
I confirmed it is possible.
Thank you.
