### ISSUE TITLE
Spaces converted in + sign on filename

### ISSUE THREAD

**Issue by freestyle68** [codelibs/fess#1907]
Hi,

with Fess 12.3.2, with smb crawling, when a file with spaces on filename is saved, spaces are converted in + sign.
For example "**file name.txt**" is saved as "**file+name.txt**".

There is a path mapping to save the file correctly?

**Comment by marevol** [comment]
Need more info...

**Comment by freestyle68** [comment]
fess-12.4.0-SNAPSHOT.zip last commit, Debian 9, filesystem crawler with path:

`smb://192.168.3.210/test/`

The fileserver is Windows 2016, but same results for example with Samba.
In this share there is a file named

`test file.txt`

On search interface, when I search and find this file, if I click on it for downloading, this file is saved on desktop with filename:

`test+file.txt`

This happens with chrome and IE for ex., on Windows and Linux as OS client.

**Comment by marevol** [comment]
Thanks. Fixed in #1910.

**Comment by freestyle68** [comment]
Fine. Thank you very much.
