### ISSUE TITLE
Thumbnail generator heap full

### ISSUE THREAD

**Issue by freestyle68** [codelibs/fess#1913]
Hi,

very often, after a few thousands files, on smb shares Thumbnail Generator crashes.
It happen alway when jvm memory heap is always full (96% and above tipically) in the log below.
I receive this messages on fess-thumbnail.log:

`2018-11-23 12:00:09,017 [CoreLib-TimeoutManager] INFO  [SYSTEM MONITOR] {"os":{"memory":{"physical":{"free":2210758656,"total":33741037568},"swap_space":{"free":8433692672,"total":8433692672}},"cpu":{"percent":7},"load_averages":[1.16, 1.09, 0.85]},"process":{"file_descriptor":{"open":374,"max":65535},"cpu":{"percent":0,"total":89070},"virtual_memory":{"total":10572828672}},"jvm":{"memory":{"heap":{"used":480247808,"committed":1073741824,"max":1073741824,"percent":44},"non_heap":{"used":120457136,"committed":129220608}},"pools":{"mapped":{"count":0,"used":0,"capacity":0},"direct":{"count":46,"used":169889793,"capacity":169889792}},"gc":{"young":{"count":10,"time":316},"old":{"count":0,"time":0}},"threads":{"count":83,"peak":98},"classes":{"loaded":13249,"total_loaded":13249,"unloaded":0},"uptime":427921},"elasticsearch":null,"timestamp":1542996009017}`

and when on 

`jvm":{"memory":{"heap ...`

the "percent" is near 100% the Thumbnail Generator crashes after a few thumbnails.
I tried to increase -Xmx128m on fess_config.properties in jvm.thumbnail.options section but without success.
And, after changing Xmx, I get always 

`max":1073741824,"
`

on 

`jvm":{"memory":{"heap" ....
`

section.
There is a way to increase max heap on this process given that fess_config.properties has no influence?

Thank you

**Comment by marevol** [comment]
In the future release, I fixed in #1921.
The workaround may be to set the following setting to 1 in fess_config.properties. 
```
page.thumbnail.queue.max.fetch.size=1
```

**Comment by marevol** [comment]
Fixed. The thumbnail generator used options for suggest...

**Comment by freestyle68** [comment]
Thank you! 
Lower memory footprint in crawler and thumbnail jobs, and also thumbnail generator does not stop anymore.
