### ISSUE TITLE
 More than 100 labels are not displayed on the search result page

### ISSUE THREAD

**Issue by okato** [codelibs/fess#1919]
When many labels are set, the number of labels more than 100 in the search results, but not all are displayed.
How do we get all the labels to be displayed?

**Comment by marevol** [comment]
`size` is in app.xml.
```
	<component name="facetInfo" class="org.codelibs.fess.entity.FacetInfo">
		<property name="sort">"count.desc"</property>
		<property name="size">100</property>
```

**Comment by okato** [comment]
Thank you for your reply very quickly.
I try it, and it worked successfully.
