### ISSUE TITLE
fields.label parameter appears as highlight

### ISSUE THREAD

**Issue by SoloRobo** [codelibs/fess#1923]
See JSON response:

// http://<fess host>:8080/json/?q=policy&fields.label=com&num=10&start=

{
  "response": {
    "version": 12.4,
    "status": 0,
    "q": "policy",
    "query_id": "389d8a092f7842bca54b69de79f6a836",
    "exec_time": 0.05,
    "query_time": 27,
    "page_size": 10,
    "page_number": 1,
    "record_count": 40,
    "page_count": 4,
    "highlight_params": "&hq=com&hq=policy",
    "next_page": true,
    "prev_page": false,
    "start_record_number": 1,
    "end_record_number": 10,
    "page_numbers": [
...
...
...

**Comment by marevol** [comment]
All terms for a query are highlighted.
