### ISSUE TITLE
How does Fess set userSessionId

### ISSUE THREAD

**Issue by MajidSafari** [codelibs/fess#1925]
https://github.com/codelibs/fess/blob/3187fcb7760895bc5b7505b189f129fc8982e725/src/main/java/org/codelibs/fess/app/web/go/GoAction.java#L92

how set userSessionId  custom by

**Comment by marevol** [comment]
See [UserInfoHelper](https://github.com/codelibs/fess/blob/3187fcb7760895bc5b7505b189f129fc8982e725/src/main/java/org/codelibs/fess/helper/UserInfoHelper.java).

**Comment by MajidSafari** [comment]
i use fess by proxy ( that make by me , C# )  now i want save click in fess

but when get http://localhost:1082/?go=t&rt=d84e986fc37547bdb85d0b6c5add4690&docId=392954f05a8c4dafa902e3373933fe51&queryId=d84e986fc37547bdb85d0b6c5add4690&order=21

userSessionId  is null , and not store click , ...

**Comment by MajidSafari** [comment]
http://localhost/go=t&rt=aadde8f4c4bb45c8b9b24596725fccc7&docId=f8fc61b6f5da47b98fbf76b8b84c453c&queryId=aadde8f4c4bb45c8b9b24596725fccc7&order=0&userCode=545645646


i add userCode parameter but Viewed  not +1

**Comment by marevol** [comment]
> go=t

I think that it's invalid url.

**Comment by MajidSafari** [comment]
tnx
