### ISSUE TITLE
Fess Main page title

### ISSUE THREAD

**Issue by AliAAziz** [codelibs/fess#1930]
I would like to change the title of Fess main page and also add link for back to previous page

**Comment by marevol** [comment]
You can edit JSP file in [Design](https://fess.codelibs.org/12.4/admin/design-guide.html) page.

**Comment by AliAAziz** [comment]
I change the text in \fess-12.2.3\app\WEB-INF\classes\fess_label.properties but it doesn't reflect the changes.
is there any other place to modify these text.
