### ISSUE TITLE
Crawler ID

### ISSUE THREAD

**Issue by Anders-Bergqvist** [codelibs/fess#1931]
Is there a way to make a search (via search api) that only shows results from a specific crawler ID?

**Comment by marevol** [comment]
What is the crawler ID?
Is it `segment` or `config_id`?

**Comment by Anders-Bergqvist** [comment]
Im thinking this ID:

![image](https://user-images.githubusercontent.com/45240300/50005596-30eb0800-ffab-11e8-8d4c-5d568089d4bd.png)

**Comment by marevol** [comment]
You can use `config_id` which contains `W_` as a prefix.

**Comment by Anders-Bergqvist** [comment]
I've tried:
`/json/?q=tomato&w_config_id:Kk19nWcBl7pLpXFKcN5E`

and It does not work. What do I do wrong?

**Comment by marevol** [comment]
> /json/?q=tomato&w_config_id:Kk19nWcBl7pLpXFKcN5E

The above query is invalid.
It may be `q=tomato+w_config_id:Kk19nWcBl7pLpXFKcN5E`, and also see [query.additional.search.fields](https://github.com/codelibs/fess/issues?q=query.additional.search.fields) in fess_config.properties.

**Comment by Anders-Bergqvist** [comment]
Aha, so in fess_config.properties
`query.additional.search.fields=config_id`

and in doc.json
```
"config_id": {
   "type": "keyword"
}
```
