### ISSUE TITLE
Escaping spaces in SMB shares

### ISSUE THREAD

**Issue by biffbaxter** [codelibs/fess#1934]
I cannot seem to escape a space in an SMB share for the file crawler. I am aware of the escape codes for web URLs..but SMB does not seem to work the same....

Example: smb://filepath/name with space/
Ends up in the logs as 
smb://filepath/name+with+space/

I have tried single quotes, double quotes, \ (backslash), and %20 all with no change...How do I crawl SMB shares with spaces as that is quite common in the Windows world unfortunately. I am working with fess 12.3.3

**Comment by marevol** [comment]
Is it the same as #1910?

**Comment by biffbaxter** [comment]
I dont know, I do not believe so, but potentially related?..I figured they were two different issues as one was downloading files and the other was trying to crawl and SMB share and how that treats spaces in the share when enumerating the share,

**Comment by marevol** [comment]
Did you set `smb://hostname/name with space/` to URL in FileSystem Crawling Config?
The above setting works in our test environment.
