### ISSUE TITLE
score in JSON results?

### ISSUE THREAD

**Issue by SoloRobo** [codelibs/fess#1937]
I can see "boost" in the JSON results, but I am unable to see "score" even though I can sort using sort=score and sort=score.desc

It would be helpful to see score to get a better idea of the weighting of results.

I can see them in the Admin :: System Info > Search section.

**Comment by marevol** [comment]
Try it in fess_config.properties:
```
query.additional.api.response.fields=score
```

**Comment by SoloRobo** [comment]
I can confirm this works in Fess 12.4.1

Thank you for the answer
