### ISSUE TITLE
Custom Job for Specific Crawler

### ISSUE THREAD

**Issue by jb8893** [codelibs/fess#1938]
I am attempting to create a custom job that will run every 20 minutes and check a specific dailysitemap.xml.  I created the new custom crawler, but I am unsure of how to target it using a newly created scheduled job.  Would the target be the name of the crawler or is that not how it works?

Thanks!

![crawler](https://user-images.githubusercontent.com/689432/50166348-e6bc9c00-02b4-11e9-97b5-cdd20fb769d6.PNG)
![job](https://user-images.githubusercontent.com/689432/50166350-e6bc9c00-02b4-11e9-8437-750b6bc37aad.PNG)

**Comment by marevol** [comment]
Did you check fess-crawler.log?

**Comment by marevol** [comment]
You need to remove a value of `Target`, and also `Script` may not be correct.
If you want to create a job for the web crawling config, you can create it on a details page of the crawling config.
