### ISSUE TITLE
Debian build is missing files after installation

### ISSUE THREAD

**Issue by caugner** [codelibs/fess#1939]
```terminal
$ wget https://github.com/codelibs/fess/releases/download/fess-12.4.1/fess-12.4.1.deb
...

$ dpkg -i fess-12.4.1.deb
...

$ ls -ls /usr/share/fess/lib/classes/org/codelibs/fess
total 8
8 -rw-r--r-- 1 fess fess 4688 Dec 16 08:00 FessBoot.class
```

Both the `deb` and the `zip` file contain `FessBoot$CustomErrorReportValve.class` in that folder, but these files are somehow not properly installed. (**Update**: The `zip` file has the file in both folders, just not the `deb` file.)

See also: #1936 and https://github.com/codelibs/docker-fess/issues/13

```
$ dpkg-deb -c fess-12.4.1.deb | grep FessBoot
-rwxr-xr-x fess/fess       531 2018-12-16 08:00 ./usr/share/fess/app/WEB-INF/classes/org/codelibs/fess/FessBoot$CustomErrorReportValve.class
-rwxr-xr-x fess/fess      4688 2018-12-16 08:00 ./usr/share/fess/app/WEB-INF/classes/org/codelibs/fess/FessBoot.class
-rw-r--r-- fess/fess      4688 2018-12-16 08:00 .//usr/share/fess/lib/classes/org/codelibs/fess/FessBoot.class
```

I guess these lines don't copy the anonymous class properly:

https://github.com/codelibs/fess/blob/690789bb85c3543576fe382ef5b4fce884ed7dd1/src/main/assemblies/common-bin.xml#L62-L67

**Comment by marevol** [comment]
Thanks. I'll fix and release it.

**Comment by caugner** [comment]
@marevol. Thanks! Actually, the problem seems to lay here:

https://github.com/codelibs/fess/blob/56b928c1ab4c83d1118c484d8bef99f73cf803a2/pom.xml#L498-L507

**Comment by caugner** [comment]
@marevol See #1940.

**Comment by caugner** [comment]
Verified fixed in latest snapshot.
