### ISSUE TITLE
Fess suggest indexes not merging

### ISSUE THREAD

**Issue by freestyle68** [codelibs/fess#1945]
Hi,

Fess 13 snapshot https://github.com/codelibs/fess/tree/e94b8a335aeaa1cf2308dd087769d10b6d7db322

Why every suggest indexer job create a new index instead of usual merging? Is this expected?

Thank you

![no index merging](https://user-images.githubusercontent.com/6328807/50237973-874ab300-03be-11e9-89c1-c885c23fbf8a.png)

**Comment by marevol** [comment]
Thanks. It'll be fixed before Fess 13 release.
