### ISSUE TITLE
Does Fess support googleoff-googleon or similar?

### ISSUE THREAD

**Issue by Anders-Bergqvist** [codelibs/fess#1954]
Hi!
For the GSA you could use `<!--googleoff: all-->Text<!--googleon: all>` to tell the crawler not to index parts of a page. Is that supported in Fess, or are there othe tags you could use similar?

I've read #767 and #666 but I can't see if it has been implemented?

**Comment by marevol** [comment]
Fess supports googeoff/googleon.

**Comment by Anders-Bergqvist** [comment]
Excellent!
