### ISSUE TITLE
porting from dev server to production server

### ISSUE THREAD

**Issue by markcamos** [codelibs/fess#1957]
We've been making changes to a development version of fess and would like to port these changes to a "production" version. What's involved in duplicating what we've done in devel to production?

**Comment by marevol** [comment]
[Upgrade](https://fess.codelibs.org/12.4/install/upgrade.html) page provides information about config files.
For indices in elasticsearch, you can use [snapshot/restore](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html) to copy them to a production server.
