### ISSUE TITLE
Default sort value

### ISSUE THREAD

**Issue by kledung** [codelibs/fess#1961]
We have set "score.desc" as Default Sort Value under General configuration. 

![sort](https://user-images.githubusercontent.com/37445873/51028158-02a11e00-1593-11e9-8033-3cf385ff7439.png)

Is the search result then sorted by score.desc when I use the json search api or do I have to add sort=score.desc in my search string anyway?

myurl/json/?q=test&num=10&start=0&sort=score.desc

**Comment by marevol** [comment]
If you do not set `sort` request parameter, a value of `Default Sort Value` is used.
