### ISSUE TITLE
fess 12.3.3 : smb:// not working

### ISSUE THREAD

**Issue by minhtienhcmus** [codelibs/fess#1962]
Currently, I am using fess 12.3.3. I want Excluded Paths For Crawling by "smb: //192.168.1.62/Test/Testproject/ 構築 _2 / AA / 構築 / *", but get jcifs.smb.SmbException error. However, when I use fess 12.1 it works fine. I think there is some way to config on fess 12.3 but I don't know how. 
Can you help me?.
Thank you very much!!!!
error message:
![capture](https://user-images.githubusercontent.com/43460402/51154589-e9f07b00-18a6-11e9-90cc-165f55054215.PNG)
crawler file:
![capture1](https://user-images.githubusercontent.com/43460402/51154653-38057e80-18a7-11e9-9634-8914546a6ac1.PNG)

**Comment by marevol** [comment]
I could not reproduce it. It's better to check configurations about an authentication.

**Comment by minhtienhcmus** [comment]
Thank you for replying soon!!.
So, in order that smb: // on fess 12.3.3  can work, we have to configure about an authentication , right?
Thank you very much!!!!
