### ISSUE TITLE
Virtual host function

### ISSUE THREAD

**Issue by Anders-Bergqvist** [codelibs/fess#1968]
Hi!
I am trying to separate key matches and related content between a public page and our intranet using virtual host settings. I followed the instruction in #1543 but I can't get it to work.

We are crawling one public site and one intranet:
```
https://www.abc.se
https://intranet.abc.se
```

I've set Virtual Hosts settings in General:
```
Host:www.abc.se=www
Host:intranet.abc.se=intranet
```
I have two Web Crawling Configs with Virtual Hosts settings at Crawling Config:
```
www
intranet
```
In Crawling Information I can see the values for virtual host correct on the pages eg `www` on pages from public page and `intranet` on pages from the intranet.

The **problem** is that when I put the value (www or intranet) in the virtual host field on a term in `Related Content` it does not show up in the result. If the virtual host field is empty it shows. I get the same result in both our own search page (via api) and on the built in Fess-search page.

Is it some other setting or something else that I've missed or have I misunderstood this function completely?

**Comment by marevol** [comment]
I have no time to reproduce it now...
If you need a quick solution, please contact [Commercial Support](https://www.n2sm.net/en/support/fess_support.html).

**Comment by Anders-Bergqvist** [comment]
@burple6 Any thoughts on this? I've used your expertise to get the Related Content going. Have you used Virtual Hosts to steer the matches to fire in specific contexts? I want to separate key matches and Related Content for the Intranet and the public site.

**Comment by marevol** [comment]
Our team could not reproduce the problem.
It seems to work correctly.

**Comment by Anders-Bergqvist** [comment]
It does not work for me! Is there a way to find whats wrong?
