### ISSUE TITLE
Crawling JSON-LD Websites

### ISSUE THREAD

**Issue by cityofaikensc** [codelibs/fess#1969]
I have been trying to crawl the following website(https://library.municode.com/sc/aiken/codes/zoning_ordinance?nodeId=ZONING_ORDINANCE--GENERAL_PROVISIONS) without any success as it appears that the website is generating the main content using XHR requests and JSON-LD data (application/ld+json). Is it even possible for Fess to crawl these types of websites?

**Comment by marevol** [comment]
It might work if installing jar file of [fess-crawler-webdriver](https://github.com/codelibs/fess-crawler/tree/master/fess-crawler-webdriver) and configuring [client.xml](https://github.com/codelibs/fess-crawler/blob/fess-crawler-parent-2.4.4/fess-crawler-lasta/src/main/resources/crawler/client.xml), but we support this feature in only [Commercial Support](https://www.n2sm.net/en/support/fess_support.html) at the moment.
IMO, it's better to access a data source directly by using a data store crawling.
