### ISSUE TITLE
Ingest Pipeline

### ISSUE THREAD

**Issue by zackhorvath** [codelibs/fess#1970]
Hello,

Is it possible to configure Fess to write to an ingest pipeline? https://www.elastic.co/guide/en/elasticsearch/reference/master/ingest.html

I took a look at #1402, and ended up going OP's route of a custom analyzer, but we would like to do processing using native Elastic tooling. We also have tags we would like to write to an array that are comma delimited.

**Comment by marevol** [comment]
Ingest pipeline is not supported at the moment...
It may be supported in a future release.
