### ISSUE TITLE
How do I get google Chrome to open html files directly instead of downloading?

### ISSUE THREAD

**Issue by bksliu** [codelibs/fess#1973]
File Crawling Configuration
Paths  |  file:////192.168.0.149/fileserver/

after searching on google browser, the **html file** will need to download instead of open directly as pdf file., how to fix this?? is there anything be config in Path Mapping??

thanks

**Comment by marevol** [comment]
See https://github.com/codelibs/fess/issues/1651#issuecomment-389654553

**Comment by bksliu** [comment]
thanks
