### ISSUE TITLE
No results for crawling a page of links

### ISSUE THREAD

**Issue by DuncanFranklin** [codelibs/fess#1974]
I am a novice to Fess, the developer who set it up as our web search left and hasn't been replaced.

One of the crawls we do is for events and the events are crawled and labelled as events if they appear on https://www.soas.ac.uk/util/eventscrawler but none of the events listed on this page are showing up. Any help would be gratefully received. 

We exclude .*events.* from indexing and crawling in the main website crawl, this would cover all event items on the site, the settings for the events crawl are:

URLs | https://www.soas.ac.uk/util/eventscrawler

Included URLs For Crawling | https://www.soas.ac.uk/.*

Excluded URLs For Crawling |
.*\.mp3.*\.min\.css.*.*\.css.*\.css.*.*\.js.*\.jpg.*\.jpeg.*\.JPEG.*\.JPG.*\.png.*\.xml.*\.rss.*\-rss\-.*.*\.json.*\.ico.*\.zip

Included URLs For Indexing | 
 
Excluded URLs For Indexing | https://www.soas.ac.uk/util/eventscrawler.*\.mp3.*\.min\.css.*.*\.css.*\.css.*.*\.js.*\.jpg.*\.jpeg.*\.JPEG.*\.JPG.*\.png.*\.xml.*\.rss.*\-rss\-.*.*\.json.*\.ico.*\.zip
 
Config Parameters | 

Depth | 1
 
Max Access Count | 

User Agent | Mozilla/5.0 (compatible; Fess +SOAS Events)

The number of Thread | 8

Interval time | 1000 ms

Boost  | 1.0

Permissions | {role}guest

Virtual Hosts | 
 
Label | Events SOAS Website

Status | Enabled

**Comment by marevol** [comment]
Check fess-crawler.log.

**Comment by DuncanFranklin** [comment]
Searching for event in the fess-crawler.log I found these lines

2019-01-22 04:00:07,008 [WebFsCrawler] INFO  Excluded URL: .*events.*
2019-01-22 04:00:07,456 [WebFsCrawler] INFO  Target URL: https://www.soas.ac.uk/util/eventscrawler
2019-01-22 04:00:07,458 [WebFsCrawler] INFO  Excluded URL from failures: \Qhttps://www.soas.ac.uk/util/eventscrawler\E

Do you know what might be wrong?

**Comment by marevol** [comment]
Remove logs in [Failure URL](https://fess.codelibs.org/12.4/admin/failureurl-guide.html).

**Comment by DuncanFranklin** [comment]
I deleted the logs in Failure URL.

The error for this page says


ID | mCQ_fmgBl8hq3_2dl26o
-- | --
URL | https://www.soas.ac.uk/util/eventscrawler

Thread name | Crawler-20190124040000-19-7

Type | org.codelibs.fess.crawler.exception.MaxLengthExceededException

Log | org.codelibs.fess.crawler.exception.MaxLengthExceededException: The content length (2643693 byte) is over 2621440 byte. The url is https://www.soas.ac.uk/util/eventscrawler
at org.codelibs.fess.crawler.client.http.HcHttpClient.processHttpMethod(HcHttpClient.java:765)
at org.codelibs.fess.crawler.client.http.HcHttpClient.doHttpMethod(HcHttpClient.java:623)
at org.codelibs.fess.crawler.client.http.HcHttpClient.doGet(HcHttpClient.java:582)
at org.codelibs.fess.crawler.client.AbstractCrawlerClient.execute(AbstractCrawlerClient.java:142)
at org.codelibs.fess.crawler.client.FaultTolerantClient.execute(FaultTolerantClient.java:67)
at org.codelibs.fess.crawler.CrawlerThread.run(CrawlerThread.java:164)
at java.lang.Thread.run(Thread.java:745)

Error Count | 1

Last Access | 1548306323368

What should I do next?

**Comment by marevol** [comment]
> The content length (2643693 byte) is over 2621440 byte. 

The size of the crawled file is too large.
To change the upper bound, you can modify it in [contentlength.xml](https://github.com/codelibs/fess/blob/fess-12.4.3/src/main/resources/crawler/contentlength.xml#L12).

**Comment by marevol** [comment]
See https://stackoverflow.com/questions/41677198/result-window-is-too-large-from-size-must-be-less-than-or-equal-to-10000-b
