### ISSUE TITLE
label exclusion rule did not work

### ISSUE THREAD

**Issue by AllenHan5** [codelibs/fess#1975]
Hello all

I am facing an issue where the label exclusion rule seemed not working. Here is my config:

Name: my_warranty
Value: my_warranty
Included Paths:  http://www.mycorp.com/my-warranty/.*
Excluded Paths: http://www.mycorp.com/my-warranty/policy.html

But somehow the page, http://www.mycorp.com/my-warranty/policy.html was marked with label my_warranty.  

Anything I was missing?
Thanks
Allen

**Comment by marevol** [comment]
Did you check fess-crawler.log?
