### ISSUE TITLE
api get status crawling of fess

### ISSUE THREAD

**Issue by minhtienhcmus** [codelibs/fess#1976]
Hi !
Currently, I want to Get  " status crawling" on fess by api . But I don't know which API to use.
Can you help me?.
Thank you very much!!!!
![capturdfdfde](https://user-images.githubusercontent.com/43460402/51518938-12054e80-1e52-11e9-8f79-27fcfec133d6.PNG)

**Comment by marevol** [comment]
See [API doc](https://fess.codelibs.org/lastadoc-fess.html#.api.admin.scheduler.::index) and check [questions](https://github.com/codelibs/fess/issues?q=is%3Aissue+label%3Aquestion) in Issues.

**Comment by minhtienhcmus** [comment]
I found it.
Thank you very much!...
