### ISSUE TITLE
Custom web page parsing

### ISSUE THREAD

**Issue by HeBuDuMkA-83** [codelibs/fess#1977]
Hello
Is there is a way to implement custom web page content parsing? I want to add some logic in that class, where Fess engine already got page content or DOM tree and want to place it into ElasticSearch storage. So I will determine which part of content will sent to storage depending of site url, for example.

**Comment by marevol** [comment]
See [org.codelibs.fess.crawler.transfomer](https://github.com/codelibs/fess/tree/master/src/main/java/org/codelibs/fess/crawler/transformer) and [fess-crawler](https://github.com/codelibs/fess-crawler).
