### ISSUE TITLE
Created date issue

### ISSUE THREAD

**Issue by julianopcardoso** [codelibs/fess#1979]
Hi, I am new in Fess, so I have a doubt about the created date that appears in results. I noticed that is the index´s created date not of the document/page. 
I think is more interessant appeats the document´s created date, how can I do it?
The last modified date is correct.

Thanks in advance.

**Comment by marevol** [comment]
I could not reproduce it.
Could you provide steps to do it in my environment?

**Comment by julianopcardoso** [comment]
I simply crawled some wiki pages.
Look below doc.created is the index´s created data not the of the document (url).
<c:if
							test="${doc.created!=null && doc.created!=''}">
							<c:set var="hasInfo" value="true" />
							<la:message key="labels.	" />
							<fmt:formatDate value="${fe:parseDate(doc.created)}"
								type="BOTH" pattern="yyyy-MM-dd HH:mm" />

**Comment by marevol** [comment]
`doc.last_modified`

**Comment by julianopcardoso** [comment]
Ok. But I want the creation date meanwhile doc.created display the index date.

**Comment by marevol** [comment]
The **specification** of Fess is as below:
- `created`: registered date in index
- `last_modified`: last modified(web crawling) or file timestamp(file crawling)
- `timestamp`: `last_modified` or `created`(if `last_modified` is null)

You cannot change them.

**Comment by julianopcardoso** [comment]
OK. I understood it. 
Thanks.
