### ISSUE TITLE
Default Analyzer?

### ISSUE THREAD

**Issue by julianopcardoso** [codelibs/fess#1980]
Wich is the default analyzer?
I would like to use pt-br in my searches.
Now the searches are ignoring the stopwords for example.

**Comment by marevol** [comment]
See [standard_analyzer](https://github.com/codelibs/fess/blob/fess-12.4.3/src/main/resources/fess_indices/fess.json#L1128), but [portuguese_analyzer](https://github.com/codelibs/fess/blob/fess-12.4.3/src/main/resources/fess_indices/fess.json#L1128) is used if detecting a proper language for a document.
