### ISSUE TITLE
Search No Results (ADUser)

### ISSUE THREAD

**Issue by hakomori** [codelibs/fess#1989]
hi
fess version 12.4.2 is used in conjunction with Active Directory. 
The crawling target is the file system. 

As a user belonging to the AD Administrators group 
If you login to fess and perform a search, 
All files are displayed in search results, 
As a user not belonging to any other Administrators group 
If you login to fess and perform a search, 
The search result will be 0 cases. 

Since crawling is registered in SMB format, 
I think that the access right will be reflected as it is, 
What is the cause?

**Comment by marevol** [comment]
You can check ACL info.
For an user, see audit.log.
For a file, check role field in [Admin Search](https://fess.codelibs.org/12.4/admin/searchlist-guide.html) page.

**Comment by hakomori** [comment]
dear marevol 

Thank you for your reply. 
I confirmed audit.log. 
The Permissions of an this AD user ,
It was the same as the AD group to which the AD user belongs. 
Of course it was possible to access from Windows explorer. 
but,The search result will be 0 cases. 

I logged into fess with an administrator account, 
I also confirmed the Admin Search screen. 
You answer in the previous question, "Roll Field" 
Maybe I should specify the fess role for AD users too ? 
In the current configuration, neither user nor role has been created. 
I thought that role was unnecessary in order to acquire SMB type access authority, 
Is it different? 

Please tell me what other information should be presented. 
I'm sorry, thank you.

**Comment by marevol** [comment]
If a crawling configuration is correct, permissions will be stored to `role` field.
You can check fess-crawler.log with debug logging if you have a problem.

**Comment by hakomori** [comment]
Problem solved
Thank you
