### ISSUE TITLE
How to recover admin role deletion

### ISSUE THREAD

**Issue by mschibata** [codelibs/fess#1990]
I did a very stupid thing.

I logged out of Fess after I erroneously deleted the admin role.
It is troubled that i can not enter the management screen even after logging in as admin afterwards.
Please let me know how I can recover, if there is a way.

Fess version is 11.3 on CentOS7.

Regards,

**Comment by marevol** [comment]
See #921

**Comment by mschibata** [comment]
Yes.
I overwrote /usr/share/fess/app/WEB-INF/classes/fess_indeices/.fess_user/user.bulk directly via Webmin.
I can login 'admin' as account but cannot login 'admin' as role.
I cannot enter admin dashboard etc.

**Comment by mschibata** [comment]
Thanks.
It works.
But i succeeded to post on localhost:9200.
its correct?
