### ISSUE TITLE
Highlightning in Digest

### ISSUE THREAD

**Issue by Anders-Bergqvist** [codelibs/fess#1993]
How to get highlightning <strong></strong> in `Digest` instead of `content_description`? I want to use Digest but the highlightning appears only in Content_description.

**Comment by marevol** [comment]
It may be the following setting in fess_config.properties:
```
query.additional.highlighted.fields=
```
I'm not sure it works...

**Comment by dmpatel3445** [comment]
> How to get highlightning in `Digest` instead of `content_description`? I want to use Digest but the highlightning appears only in Content_description.

@Anders-Bergqvist Have you managed to get this working? I would like to do the same thing so wondering if you have found a solution. Thanks :)

**Comment by Anders-Bergqvist** [comment]
@dmpatel3445 Unfortunately I did not get that to work and gave up. I'm still interested in a way to get it work tough!

**Comment by dmpatel3445** [comment]
@Anders-Bergqvist Thanks for getting back to me. Will let you know if I can get it working.

**Comment by rhayun** [comment]
Hello,
i am interesting in this feature as well
when i change the `query.highlight.content.description.fields=digest,hl_content` so the digest is first its not highlighted - there is no hl_digest field like in content (hl_content)

any help?
