### ISSUE TITLE
Overwrite last_modified with another metadata

### ISSUE THREAD

**Issue by arengore** [codelibs/fess#1996]
I'm indexing several msg email files, I want to overwrite file last_modified with email date, so i picked the field "Last-Save-Date" calling it dmodified:

```
crawler.metadata.name.mapping=\
title=title:string\n\
Title=title:string\n\
Last-Save-Date=dmodified:string\n\

query.additional.response.fields=dmodified
query.additional.search.fields=dmodified
```

The field is picked by crawler and I can see it on ES.
On crawler Config Parameters I entered
doc.last_modified=doc.dmodified

but last_modified don't change it's value.

Where I'm wrong?

**Comment by marevol** [comment]
> doc.last_modified=doc.dmodified

? The above setting does not exist...

It may work if `Last-Save-Date` is ISO 8601 format and replacing `dmodified` with `last_modified`.

**Comment by arengore** [comment]
no way, the metadata are ingested from elasticsearch and then becomes unmodifiable. 

So, I'm using a bash script to change files timestamp.

**Comment by freestyle68** [comment]
Hello all, I have seen last commit introduced:

Last-Save-Date=last_modified:date\n\
Last-Modified=last_modified:date\n\

With mgs files it works very well, and I want to thank you for this.

With other files timestamp wins over Last-Save-Date (I attach an example pdf). I expected the opposite.

The logic behind commit #2019 is: if Last-Save-Date or Last-Modified are present they should win over file timestamp? In this case shouldn't be working also with other files?

[069858.pdf](https://github.com/codelibs/fess/files/2866015/069858.pdf)

**Comment by freestyle68** [comment]
Hello,

I have seen you commit #2019, I have tested it with msg file and also with pdfs.

With msg the Last-Save-Date wins over file timestamp, but with pdf the winning is always file timestamp.

Shouldn't be Last-Save-Date be winning always if present?

I attach a sample pdf with timestamp winning.

[069858.pdf](https://github.com/codelibs/fess/files/2866038/069858.pdf)

**Comment by marevol** [comment]
It's not for PDF.
