### ISSUE TITLE
Getting Authenticaded Windows User 

### ISSUE THREAD

**Issue by julianopcardoso** [codelibs/fess#1997]
If I configure LDAP/AD authentication with SSO will everybody have access to admin page?

I just wanna log searches of the user´s machine (LDAP authenticaded). Not guest user but LDAP User.

**Comment by marevol** [comment]
User information is in fess_log.user_info index.

**Comment by julianopcardoso** [comment]
Ok. I got it.
But I need to get the user from machine and save it in fess_log.user_info.

**Comment by marevol** [comment]
What is the user from machine?
I think a username is stored.

**Comment by julianopcardoso** [comment]
Is the user logged in machine (echo %username%).

**Comment by marevol** [comment]
Hmm, Fess is not a client application...
