### ISSUE TITLE
Does updating "Excluded URLs For Crawling" updates already crawled documents?

### ISSUE THREAD

**Issue by svalo** [codelibs/fess#1999]
Hello, I have a question as per title. 
I realized I miswrote a regexp in the "Excluded URLs For Crawling" and updated it, does this change the already indexed documents or should I do something to apply the new regexp?

Thanks

**Comment by marevol** [comment]
It's used at crawling time.
You need to start a crawler again.

**Comment by svalo** [comment]
Thanks @marevol
