### ISSUE TITLE
Proper crawler setup

### ISSUE THREAD

**Issue by abolotnov** [codelibs/fess#2001]
If I want to crawl only `*.example.com` (both `http` and `https`) and want to exclude images, js files, css files - what should my crawler setup look like?

I tried many combinations but I either get external sites crawled or only `http` and not `https` and looks like excluded urls are overwritten by included so I managed to keep crawler to stick with the domain more or less but can't make it ignore unwanted files.

My setup looks like this:

![image](https://user-images.githubusercontent.com/535448/52105494-f241f900-25bc-11e9-98e2-4d07012a68da.png)

Thank you!

**Comment by marevol** [comment]
Did you check fess-crawler.log?

**Comment by abolotnov** [comment]
What should I be looking for? I think the config works as expected but I can't figure how to:

- Limit the crawler to collect *.example.com - right now based on my config it will only collect www.example.com
- Exclude the unwanted filetypes - these files still get indexed

**Comment by marevol** [comment]
> Exclude the unwanted filetypes - these files still get indexed

1 line is 1 regex.

**Comment by abolotnov** [comment]
I will break them into multiple lines. Is there a way to limit crawling to *.example.com so www.example.com and more.example.com both get indexed?

**Comment by marevol** [comment]
`https?://.*\.example\.com/.*`
It's Java regex.
