### ISSUE TITLE
Hi , how i can ParsiAnalyzer for elastic

### ISSUE THREAD

**Issue by MajidSafari** [codelibs/fess#2004]
how i can  install ParsiAnalyzer for elastic and use in fess for Persian lang?

https://github.com/NarimanN2/ParsiAnalyzer

**Comment by marevol** [comment]
To use it in Fess, modify [fess.json](https://github.com/codelibs/fess/blob/fess-12.4.3/src/main/resources/fess_indices/fess.json).
