### ISSUE TITLE
Labels: bug with spaces in path

### ISSUE THREAD

**Issue by freestyle68** [codelibs/fess#2010]
Hi,

commit https://github.com/codelibs/fess/tree/0542685f071f8826136612a046613d7a3a16f7ba

labels are not effective when path contains spaces.

How to reproduce:

File Crawling
          Path:  file:/dir/path with spaces/

Label
         Included Paths:  file:/dir/path with spaces/.*

Thank you

**Comment by marevol** [comment]
For `file:`, you need to encode it. ex. `file:/dir/path%20with%20spaces/`

**Comment by freestyle68** [comment]
ok thank you
