### ISSUE TITLE
Query search log without "suffixes"

### ISSUE THREAD

**Issue by markcamos** [codelibs/fess#2014]
Is there a way to query the "Search Log" such that it does not return anything but the actual search term?

When I extract data, it includes things like "content_length...", "timestamp", etc. Can I extract just the "search string" without those terms?

Is there a way to do this using the elasticsearch database? I would like to be able to produce a weekly report of top search terms.

**Comment by marevol** [comment]
Search logs are stored in fess_log.* indices.

**Comment by markcamos** [comment]
Thank you - can you recommend a good query tool to access these logs?

**Comment by marevol** [comment]
Kibana
