### ISSUE TITLE
Search Guard Authentication

### ISSUE THREAD

**Issue by julianopcardoso** [codelibs/fess#2016]
Hi, 
I will start to use Search Guard integrated with Elasticsearch and Kibana.
How do I configure Fess to access Elasticsearch passing by Search Guard Authentication?

I saw the Fess X-Pack but I dont use X-Pack.

Thanks.

**Comment by marevol** [comment]
At the moment, we have no plan to support Search Guard on our OSS works.
If you need a support to do that, please contact [Commercial Support](https://www.n2sm.net/en/support/fess_support.html).
