### ISSUE TITLE
 why synonym not working in persian_analyzer ?

### ISSUE THREAD

**Issue by MajidSafari** [codelibs/fess#2017]
why synonym not working in persian_analyzer ??

![1](https://user-images.githubusercontent.com/5099564/52710954-db7ca880-2fa5-11e9-9cb4-c56304c1db44.JPG)
![2](https://user-images.githubusercontent.com/5099564/52710955-db7ca880-2fa5-11e9-8944-84135c28d669.JPG)
![3](https://user-images.githubusercontent.com/5099564/52710956-dc153f00-2fa5-11e9-9605-4274966156cb.JPG)

**Comment by marevol** [comment]
See [fess.json](https://github.com/codelibs/fess/blob/fess-12.5.0/src/main/resources/fess_indices/fess.json#L997-L1008).
persian_analyzer does not have a synonym filter.

**Comment by MajidSafari** [comment]
i add to synonym filter to persian_analyzer in fess.json , how reindex Fess.search ?

**Comment by MajidSafari** [comment]
![image](https://user-images.githubusercontent.com/5099564/52715633-27354f00-2fb2-11e9-9301-57334247ec6d.png)

**Comment by marevol** [comment]
Did you check log files?
