### ISSUE TITLE
set default for Fuzzy in fess

### ISSUE THREAD

**Issue by MajidSafari** [codelibs/fess#2023]
hi @marevol 

how can set Fuzzy default for fess ?

**Comment by marevol** [comment]
more details...

**Comment by MajidSafari** [comment]
my problem is same people  type wrong  word and fess no result return ,

now , i think if Fuzzy set , !!!

**Comment by marevol** [comment]
See [Fuzzy Query Syntax](https://lucene.apache.org/core/2_9_4/queryparsersyntax.html#Fuzzy%20Searches).

**Comment by MajidSafari** [comment]
this like  "jakarta apache"~10 work in fess ?

**Comment by marevol** [comment]
Proximity search works.
These queries depend on terms tokenized by analyzers.
