### ISSUE TITLE
Library for interacting with Fess?

### ISSUE THREAD

**Issue by jhult** [codelibs/fess#2029]
I am planning to use Fess to index files and then run search queries. Is there a library (such as a Maven artifact) I can use to do this? Or should I use a [JSON parser library](https://stackoverflow.com/questions/41928803/how-to-parse-json-in-kotlin) with the [Fess API](https://fess.codelibs.org/12.5/api/api-search.html) to accomplish this?

**Comment by marevol** [comment]
Fess does not provide a client library to parse JSON for Fess API. 
> should I use a [JSON parser library](https://stackoverflow.com/questions/41928803/how-to-parse-json-in-kotlin) with the [Fess API](https://fess.codelibs.org/12.5/api/api-search.html) to accomplish this?

Yes.
