### ISSUE TITLE
Crawling Error: java.lang.NullPointerException

### ISSUE THREAD

**Issue by julianopcardoso** [codelibs/fess#2030]
Failure URL Details

**ID:** lgXKKWkBxcdxvI8b9bAf
**URL:** https://intranet3.corp.com.br/bus/link/home.html
**Thread Name:** Crawler-ttDHFmkBQItnzQEGSGJi-1-2
**Type:** java.lang.NullPointerException
**Log:** java.lang.NullPointerException
at org.codelibs.fess.crawler.transformer.FessXpathTransformer.pruneNode(FessXpathTransformer.java:657)
at org.codelibs.fess.crawler.transformer.FessXpathTransformer.storeData(FessXpathTransformer.java:178)
at org.codelibs.fess.crawler.transformer.impl.HtmlTransformer.transform(HtmlTransformer.java:120)
at org.codelibs.fess.crawler.processor.impl.DefaultResponseProcessor.process(DefaultResponseProcessor.java:77)
at org.codelibs.fess.crawler.CrawlerThread.processResponse(CrawlerThread.java:330)
at org.codelibs.fess.crawler.FessCrawlerThread.processResponse(FessCrawlerThread.java:240)
at org.codelibs.fess.crawler.CrawlerThread.run(CrawlerThread.java:176)
at java.base/java.lang.Thread.run(Thread.java:834)
**Error Count:** 3
**Last Access:** 1551186678758

**Comment by marevol** [comment]
What Fess version did you use?

**Comment by julianopcardoso** [comment]
It is 12.5.0.
