### ISSUE TITLE
Javascript Support

### ISSUE THREAD

**Issue by julianopcardoso** [codelibs/fess#2031]
Does Fess support dynamic pages? Javascript support.

**Comment by marevol** [comment]
It might work if installing jar file of [fess-crawler-webdriver](https://github.com/codelibs/fess-crawler/tree/master/fess-crawler-webdriver) and configuring [client.xml](https://github.com/codelibs/fess-crawler/blob/fess-crawler-parent-2.4.4/fess-crawler-lasta/src/main/resources/crawler/client.xml), but we support this feature in only [Commercial Support](https://www.n2sm.net/en/support/fess_support.html) at the moment...

**Comment by julianopcardoso** [comment]
What is the configurantion I have to do in client.xml?

**Comment by julianopcardoso** [comment]
Hi, 
I configured the Chromedriver to crawl javascript pages but the Jobs aren´t killing the Chrome processes after the crawl. When finish itself or stopping,
This is consuming all the RAM.

I think it is a Fess problem.
