### ISSUE TITLE
クロールの設定画面にラベルが表示されない

### ISSUE THREAD

**Issue by Hikaru-Shibuya** [codelibs/fess#2033]
下記のサイトを参考にし、ファイルクロールやウェブクロールの設定画面でラベルを設定しようとしましたが、ラベルが表示されませんでした。
https://fess.codelibs.org/ja/12.5/admin/fileconfig-guide.html
https://fess.codelibs.org/ja/12.5/admin/webconfig-guide.html

過去のバージョンでは表示されていたようで、12.4.0を境にソースの修正がなされていることは確認できましたが、何故、画面上非表示としたか、理由がわかりませんでした。
https://github.com/codelibs/fess/issues/1854
https://github.com/codelibs/fess/commit/21f697c08ce021421f9d9db958bc1b1801a46327

ラベル機能自体に何か問題があって非表示とされているのであれば、どのような問題かをご教授頂きたいです。また、問題が無いようであればラベル機能を利用したいと考えており、どのようにすればよいかご回答いただければと思います。

よろしくお願い致します。

**Comment by marevol** [comment]
Japanese is not supported.

**Comment by toshiki1408** [comment]
I agree with the questioner.
