### ISSUE TITLE
Labels are not displayed on crawl setting screen

### ISSUE THREAD

**Issue by Hikaru-Shibuya** [codelibs/fess#2034]
I tried to set a label on the setting screen of file crawl and web crawl with reference to the site below, but the label was not displayed.
https://fess.codelibs.org/ja/12.5/admin/fileconfig-guide.html
https://fess.codelibs.org/ja/12.5/admin/webconfig-guide.html

It was displayed in the past version, and it was confirmed that the source was corrected at 12.4.0.
However, I did not understand why I did not hide the label from the screen.
https://github.com/codelibs/fess/issues/1854
https://github.com/codelibs/fess/commit/21f697c08ce021421f9d9db958bc1b1801a46327

If there is something wrong with the label function itself and it is being hidden, I would like to teach you what kind of problem is.
Also, if there seems to be no problem, I'd like to use the label function, and I hope to answer how to do it.

Thank you.

**Comment by marevol** [comment]
Docs will be updated.
See [Included paths](https://fess.codelibs.org/12.5/admin/labeltype-guide.html#included-paths).

**Comment by Hikaru-Shibuya** [comment]
Thank you for answering.

According to the manual set the label path.
However, labels are not created if Japanese or spaces are included in the path.
I set this up.

'Included Paths'
####folder name is "SybaseASE"
file:/C:/FESS/98_manual/
file:/C:/FESS/98_manual/SybaseASE/
file:/C:/FESS/98_manual/SybaseASE/.*
Searchable

####folder name is "Sybase ASE"
file:/C:/FESS/98_manual/
file:/C:/FESS/98_manual/Sybase ASE/
file:/C:/FESS/98_manual/Sybase ASE/.*
or
file:/C:/FESS/98_manual/
file:/C:/FESS/98_manual/Sybase\sASE/
file:/C:/FESS/98_manual/Sybase\sASE/.*
or
file:/C:/FESS/98_manual/
file:/C:/FESS/98_manual/Sybase\\sASE/
file:/C:/FESS/98_manual/Sybase\\sASE/.*
Can not search

####folder name is "SybaseASEマニュアル"
file:/C:/FESS/98_manual/
file:/C:/FESS/98_manual/SybaseASEマニュアル/
file:/C:/FESS/98_manual/SybaseASEマニュアル/.*
or
file:/C:/FESS/98_manual/
#DISABLE_URL_ENCODE
file:/C:/FESS/98_manual/SybaseASEマニュアル/
#DISABLE_URL_ENCODE
file:/C:/FESS/98_manual/SybaseASEマニュアル/.*
Can not search

I solved it by setting the 12.3.5 version from the crawler screen.

**Comment by marevol** [comment]
For crawled urls, see fess-crawler.log.

**Comment by Hikaru-Shibuya** [comment]
OK

I close this issue.
