### ISSUE TITLE
config elasticsearch with hosts

### ISSUE THREAD

**Issue by ewul** [codelibs/fess#2041]
Thank for your project.
Can I config elasticsearch hosts in fess.in.sh?
According to install guide, I can change ES_HTTP_URL=http://192.168.0.100:9200 to point to only one node of my elasticsearch cluster.
Can I config this with hosts which point my ES cluster nodes. When one node going down, Fess can communicate with other nodes.

Thanks again.

**Comment by marevol** [comment]
A multi endpoint is not supported.
We recommend to put LB between Fess and Elasticsearch.

**Comment by ewul** [comment]
Is there any plan to add multi endpoint configuration OR aggregation LB (such as HAProxy) in Fess in future?

**Comment by marevol** [comment]
We have no plan...
