### ISSUE TITLE
Protwords - not working

### ISSUE THREAD

**Issue by jhult** [codelibs/fess#2047]
I would like to search on a term such as "Networking" and not have Fess stem. So, this search term would not return "Networks" or "Network".

I have added "Networking" to en/protwords.txt.

However, if I search for "Networking" or "Networks" or "Network", I always get the same results.

I have deleted all documents and re-crawled. I have also tried closing the index and re-opening it.

I may have this configured wrong. Any assistance would be appreciated.

**Comment by jhult** [comment]
1. Navigate to: Dashboard > More > Analysis > Analyze by Analyzer
2. Enter the following:
2a. Index name: fess.20190313
2b. Analyzer name: english_analyzer
2c. Text to analyze: Networking

![image](https://user-images.githubusercontent.com/9849069/54381906-41bc2000-4665-11e9-87c5-f0a53a34728e.png)

**Comment by jhult** [comment]
If I switch to a different language, it shows it stemming. 
![image](https://user-images.githubusercontent.com/9849069/54382474-71b7f300-4666-11e9-9a0b-3dde1eed47e4.png)

English looks correct in the dashboard but searches don't seem to work.

**Comment by marevol** [comment]
english_analyzer uses [possessive_english](http://lucene.apache.org/core/4_9_0/analyzers-common/org/apache/lucene/analysis/en/EnglishPossessiveFilter.html).
To change it, you need to modify fess.json and recreate fess index.

**Comment by jhult** [comment]
The steps I took to re-create the Fess index, are as follows based upon [this](https://github.com/codelibs/fess/issues/1011#issuecomment-298005767):

1. Delete fess.yyyymmdd index on dashboard
2. Stop Fess
3. Start Fess
4. A new fess.yyyymmdd index is created automatically

**Comment by jhult** [comment]
I edited /usr/share/fess/app/WEB-INF/classes/fess_indices/fess.json at. It was originally:
```
"english_analyzer": {
  "type": "custom",
  "tokenizer": "standard",
  "filter": [
    "truncate20_filter",
    "lowercase",
    "english_keywords",
    "english_override",
    "possessive_stemmer_en_filter"
  ]
},
```
I removed this line: `possessive_stemmer_en_filter`

I then re-recreated the Fess index (based on the above steps). However, it is still not working...

Any other ideas?

**Comment by jhult** [comment]
`/var/lib/elasticsearch/config/en/protwords.txt` contains "Networking"

**Comment by jhult** [comment]
I suppose I should mention I am running a search as follows:

> /search/?num=10&sort=&q="Networking"

**Comment by marevol** [comment]
Fess is a hybrid index with standard_analyzer and language_analyzer.
So, you need to also check standard_analyzer.
