### ISSUE TITLE
Restoring from Elasticsearch snapshot created on different platform

### ISSUE THREAD

**Issue by hilt86** [codelibs/fess#2050]
Thanks for creating FESS!

I am having a problem restoring a snapshot that I took on a Windows based FESS install to an Elasticsearch cluster running on Kubernetes. When I look at the index settings there are a heap of mapping_path settings that point to C:\FESSData\blah\config so when I try restore the index I receive a 

`NoSuchFileException[/usr/share/elasticsearch/config/C:/FESSData/blah/config/mapping.txt` error. This is because the mapping_path is stored in the index instead of a configurable location.

If I add these files to the image then in the future if I want to change platform again I will be in the same situation...is there a better way to provide Elasticsearch with these mappings? I'm using Kubernetes and want to use plan Elasticsearch to isolate that component from FESS which is why I am not using the FESS image.

ps. I have installed all the required plugins as per https://fess.codelibs.org/12.3/install/install.html

**Comment by marevol** [comment]
There is no solution at the moment...
You need to put dictionary files to the same directory.

**Comment by hilt86** [comment]
ok but I should be able to create the index beforehand and update the settings via a PUT indexname/_settings right?

**Comment by marevol** [comment]
probably yes.

**Comment by hilt86** [comment]
Updating the settings doesn't work as when I restore the snapshot it overwrites the settings. There doesn't seem to be a way to restore an index without settings but managed to mirror the directory structure (including the C:/ bit) so I got it working. 

Going forward are their plans to address this in a more platform neutral way?

**Comment by marevol** [comment]
Modifying fess.json, you can change a path of dictionaries to a relative one before creating fess index.

**Comment by hilt86** [comment]
Thanks @marevol. As per the [documentation](https://fess.codelibs.org/12.3/install/install.html), to use an existing elasticsearch cluster I need to install elasticsearch on the FESS server / container even though I only plan to use the FESS webapp on that system?

Is it correct to assume that fess.json should reside on the FESS system and not the Elasticsearch system?

**Comment by marevol** [comment]
fess.json is in Fess server.
