### ISSUE TITLE
popular words API returning no records

### ISSUE THREAD

**Issue by markcamos** [codelibs/fess#2051]
fess version 12.4
config reloader running */10 * * * *

https://fess-devel.owenscorning.com/json/?type=popularword returns:
{"response":{"version":12.4,"status":0,"result":[]}}

I've been searching for the same term every couple of minutes for days. The search shows up in the search log, but not popular words.

Any ideas on what to check?

**Comment by marevol** [comment]
See https://github.com/codelibs/fess/issues/1813#issuecomment-458126751

**Comment by markcamos** [comment]
There is nothing in 1813 that I haven't already tried. 

I think we just won't be using this feature.
