### ISSUE TITLE
Showing the pages starting from the 1001th page

### ISSUE THREAD

**Issue by biligee** [codelibs/fess#2052]
I can't browse search results using &pn=1001&num=10. Is there any setting that should I increase that limit?

**Comment by marevol** [comment]
The setting is in fess_config.properties:
```
query.max.search.result.offset=100000
```
and also `index.max_result_window` is a setting in elasticsearch.

**Comment by biligee** [comment]
Found index level settings on node level configuration.

Since elasticsearch 5.x index level settings can NOT be set on the nodes.
configuration like the elasticsearch.yaml, in system properties or command line.
arguments.In order to upgrade all indices the settings must be updated via the.
/${index}/_settings API. Unless all settings are dynamic all indices must be closed.
in order to apply the upgradeIndices created in the future should use index templates.
to set default values..

Please ensure all required values are updated on all indices by executing:.

curl -XPUT 'http://localhost:9200/_all/_settings?preserve_existing=true' -d '{
  "index.max_result_window" : "300000"
}'
*************************************************************************************
