### ISSUE TITLE
Display inconsistent with fixed labels

### ISSUE THREAD

**Issue by freestyle68** [codelibs/fess#2057]
Hello,

doing a search with fixed label like this

![image](https://user-images.githubusercontent.com/6328807/54649166-7129bd00-4aa9-11e9-9aef-fac964c0b244.png)

produces this result:

![image](https://user-images.githubusercontent.com/6328807/54649215-93233f80-4aa9-11e9-9087-905b742d4a38.png)

and so it seems that the query is "api Fess".

Shouldn't be highlighted that Fess is a label, moving the displayed label a bit to the right or changing it color?

**Comment by marevol** [comment]
The current specification is to display a value of Label as a search word, but it might be changed in a future release.
