### ISSUE TITLE
Keep data forever - issue #1287 - Part 2

### ISSUE THREAD

**Issue by julianopcardoso** [codelibs/fess#2067]
A question about keeping data: I would like keep my data (modified or not) and removing from index only **excluded documents** from base, How do I must configure it?

Actually I have this configuration, but I lost all data, for the first time after one month, even tough crawler running everyday at 10p.m.:
**Check Last Modified:** Enabled
**Remove Documents Before:** 3 Day(s)

**Comment by marevol** [comment]
> Remove Documents Before: 3 Day(s)

-1 is that documents are not expired.
