### ISSUE TITLE
How to set the path of CSVfile in DataStore Crawler  

### ISSUE THREAD

**Issue by mizunokou520** [codelibs/fess#2080]
I am trying DataStore on windows system and refering https://fess.codelibs.org/12.4/admin/dataconfig-guide.html#csvdatastore.

Could someone teache me as following
1. "directories=/home/CSV"  where is the absolute path?
2. if I want to use "files" in specify file on windows ,should I use "file:/" befor my path (ex. files=file:/c:/temp/test.csv)

**Comment by marevol** [comment]
> "directories=/home/CSV" where is the absolute path?

Yes

> 2. should I use "file:/" befor my path (ex. files=file:/c:/temp/test.csv)

I think it works with both cases.

**Comment by mizunokou520** [comment]
Thnak you for answer
I tried both ways to set up DataStore but it dosen't work.

Here is my setting
----parameter------ 
 files="file:/C:/temp/test.csv"
fileEncoding="UTF-8"
----script------ 
url=cell13
host=
site=cell13
title=cell1
content=cell6
cache=cell1
digest=cell1
anchor=
contentLength=cell1.length()
lastModified=@jp.sf.fess.taglib.FessFunctions@formatDate(new java.util.Date(@System@currentTimeMillis()))

Have i made a mistake in this setting?

**Comment by marevol** [comment]
Information you referred is old.
See [Data Store Configuration](https://fess.codelibs.org/12.6/admin/dataconfig-guide.html#id4).

**Comment by mizunokou520** [comment]
Thank you for answer
I referred the link that you gave, and re-try as fallow.
but still dosen't work.
Here is my setting

----Handler Name------
CSV   << I just only have CSV option in option-list , there is no "CsvDataStore" that I can choose.
----parameter------
directories=file:/d:/fess-12.6.0/app/home/john/csv
fileEncoding=UTF-8
 ----script------
url="http://localhost/" + cell1
host="localhost"
site="localhost"
title=cell2
content=cell3
cache=cell3
digest=cell3
anchor=
content_length=cell3.length()
last_modified=new java.util.Date()

Did I miss something?

**Comment by marevol** [comment]
Did you check fess-crawler.log?

**Comment by mizunokou520** [comment]
here is my fess-crawler.lob message

2019-04-24 07:15:47,883 [20190424071536-2] INFO  directories=file:/d:/fess-12.6.0/app/home/john/csv
2019-04-24 07:15:47,883 [20190424071536-2] WARN  file:/d:/fess-12.6.0/app/home/john/csv is not a directory.
2019-04-24 07:15:47,883 [20190424071536-2] WARN  No CSV file.

**Comment by marevol** [comment]
> 2019-04-24 07:15:47,883 [20190424071536-2] WARN file:/d:/fess-12.6.0/app/home/john/csv is not a directory.

You need to fix the above.

**Comment by mizunokou520** [comment]
Thank you for answer
I fixed the directory to be "d:/fess-12.6.0/app/home/john/csv"
And got log message as fallow
But I still can not got accurate search result (notthing hit)
"test.csv" is example from fess website

2019-04-24 12:43:00,215 [20190424124248-2] INFO  directories=d:/fess-12.6.0/app/home/john/csv
2019-04-24 12:43:00,218 [20190424124248-2] INFO  Loading d:\fess-12.6.0\app\home\john\csv\test.csv

**Comment by marevol** [comment]
It's better to change a log level to debug, and then you can check details in fess-crawler.log.

**Comment by mizunokou520** [comment]
Sorry for late and Thank's for your answer.
I put the CSV file or folder under FESS_HOME root then it work.
Thank you
