### ISSUE TITLE
A few questions with Fess

### ISSUE THREAD

**Issue by yuuiki** [codelibs/fess#2091]
Hi sorry to disturb,
I am a beginner user for Fess. I have a question about fess.

I index some arabic document and I can search it in fess. I wonder if FESS has the function of  recognize language automatically , and then call the corresponding language processor finally put it in the corresponding index？

**Comment by marevol** [comment]
See https://github.com/codelibs/elasticsearch-langfield, but this feature will be changed in Fess 13.

**Comment by yuuiki** [comment]
OK, I got it, thank you very much
