### ISSUE TITLE
Similar Result Collapsed

### ISSUE THREAD

**Issue by dvlop** [codelibs/fess#2092]
I talk about fees 12.4 version.

When I turn on the "Similar Result Collapsed" option, as a result of the search, I see only one answer.

This does not group result by domain name.

**Comment by marevol** [comment]
Similar Result Collapsed groups results by content, not domain.

**Comment by dvlop** [comment]
Content is title & description or only description?
Maybe i have option configure "Similar Result Collapsed" per site ?
<img width="693" alt="Screen Shot 2019-04-18 at 13 18 32" src="https://user-images.githubusercontent.com/1873578/56354557-be01d000-61dc-11e9-8198-7814bc65fb73.png">

**Comment by marevol** [comment]
Content means `content` field.
This option is for an entire index.

**Comment by biligee** [comment]
I always see a single result, when I activate the "Similar Result Collapsed" option. Perhaps, it is due to my misconfiguration.
