### ISSUE TITLE
Crawling PDF/DOC/XLS with Fess Web Crawler + Chromedriver

### ISSUE THREAD

**Issue by julianopcardoso** [codelibs/fess#2093]
Hi! I am trying to crawl PDF/DOC/XLS with Fess WebCrawler with Chromedriver (Selenium) but doesnt work. 
I can crawl html with no problem, included pages with javascript.

Could you help me with this issue?

Thanks!

**Comment by marevol** [comment]
We hava no plan to support it in OSS at the moment as mentioned in #2031.
If you need supports, please contact [Commercial Support](https://www.n2sm.net/en/support/fess_support.html).
