### ISSUE TITLE
Paths with spaces exclusion in SMB

### ISSUE THREAD

**Issue by freestyle68** [codelibs/fess#2094]
Hi,

File Crawling Configuration

Paths:  `smb://192.168.10.20/path/`
Excluded Paths For Crawling:    `.*path excluded.*`

but not picking.

Also tried with 

```
.*/path excluded/.*
.*\/path excluded\/.*
.*/path%20excluded/.*
/path excluded/
```

Instead the exclusions

`.*path.*`

or

`.*excluded.*`

give no problem.

How to exclude paths with spaces?

Thank you

**Comment by marevol** [comment]
It may be `+` or `%20`.
You can check it in fess-crawler.log.

**Comment by freestyle68** [comment]
Paths:	smb://localhost/path/

Tried with
Excluded Paths For Crawling: 

```
.*/path+excluded/.*
 /path%20excluded/
 /path+excluded/
.*/path excluded/.*
.*\/path excluded\/.*
.*/path%20excluded/.*
/path excluded/
 smb://localhost/path/path excluded/
 smb://localhost/path/path+excluded/
 smb://localhost/path/path excluded/.*
 smb://localhost/path/path+excluded/.*
 smb://localhost/path/path%20excluded/.*
```

None of these are working.


fess-crawler.log:  `Crawling URL: smb://localhost/path/path excluded/1.pdf`

**Comment by marevol** [comment]
A space character is encoded by default.
To avoid it, you can put `#DISABLE_URL_ENCODE`.

Excluded Paths For Crawling:
```
#DISABLE_URL_ENCODE
.*path excluded.*
```

**Comment by freestyle68** [comment]
Yes it works.

Thank you very much.
