### ISSUE TITLE
Where to disable JarScanning?

### ISSUE THREAD

**Issue by jfabales** [codelibs/fess#2095]
Hello FESS team,

I find that starting FESS server takes a really long time nowadays and that's because tomcat takes a really long time doing jar scanning. Some suggestions recommend skipping jar files in the `catalina.properties` file or in `conf/context.xml` which I couldn't find. Could you help me guys?

Here are the last lines in `server_0.log`
```
Apr 24, 2019 5:13:27 AM org.apache.jasper.servlet.TldScanner scanJars
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
```

Thanks!

**Comment by marevol** [comment]
There is no option at the moment.
I asked an author of the library to add a solution for this issue.

**Comment by jfabales** [comment]
Adding this line to `fess.in.sh` actually works but I found that it wasn't the reason why the took too long to start

```
JAVA_OPTS="$JAVA_OPTS -Dtomcat.util.scan.StandardJarScanFilter.jarsToSkip=*.jar"
```
It's related to CreateSecureRandom when running inside a container but I also discovered that recreating the container solved the problem. I also mounted the `/dev/urandom` of the host to the container and hopefully it helps.
