### ISSUE TITLE
Crawling versus Indexing Filter

### ISSUE THREAD

**Issue by dankoh** [codelibs/fess#2099]
Hi, 

can you please define the difference between the indexing and crawling excluded path option? 

`.*\/_general\/.*\.(?i)(pdf|txt|rtf|docx|doc|xlsx|xlsm|xltx|xltm|xls|pptx|pptm|ppt|potx|potm|ppam|ppsx|ppsm|sldx|msg|eml|mpp|htm|html)`

Adding this regex to the crawling option does not check subdirectories of general at all, adding the regex to the excluded paths for indexing works though but creates a huge amount of unneccesarily crawled files.

**Comment by marevol** [comment]
`Excluded URLs For Crawling` does not crawl and index URLs.
`Excluded URLs For Indexing` does not index URLs, but crawls them.
