### ISSUE TITLE
Get list of running jobs

### ISSUE THREAD

**Issue by defensivedepth** [codelibs/fess#2100]
I am looking through the [Admin API docs](https://fess.codelibs.org/12.0/lastadoc-fess.html#top) and trying to find a way to query FESS for currently running jobs.

Is this possible?

**Comment by marevol** [comment]
Could you check [/api/admin/scheduler/setting/{id}](https://fess.codelibs.org/lastadoc-fess.html#.api.admin.scheduler.setting._b_id_e_::get_d_setting)?

**Comment by defensivedepth** [comment]
Hmmm, let me try that.

I have tried setting `Simultaneous Crawler Config` to 3, but it does not appear to be limiting jobs that start web crawlers.

What does this setting do?

**Comment by marevol** [comment]
Simultaneous Crawler Config is not the number of jobs.
It's the number of crawler configs(threads) running in one crawler job.

**Comment by defensivedepth** [comment]
Thanks - 

Looks like this will work for my purposes:

https://fess.codelibs.org/lastadoc-fess.html#.api.admin.joblog.logs::logs
