### ISSUE TITLE
Escaping Special Characters

### ISSUE THREAD

**Issue by freestyle68** [codelibs/fess#2110]
Hi,

using Elasticsearch special character

`+ - && || ! ( ) { } [ ] ^ " ~ * ? : \`

Fess give the message: The given query is invalid.

For the standard user it's too frustrating to insert the query between double quotes or insert the escape before.

Have you considered to escape this characters on Fess?

Thank you

**Comment by marevol** [comment]
Since some of them are a query operator, Fess cannot decide whether it should be escaped.
So it's difficult to do that... but any idea is welcome.

**Comment by freestyle68** [comment]
By far the more frequently used are` / ` or   `: `   as date separators.

Are also these query operators?

**Comment by marevol** [comment]
/ is not an operator.
A solution might be to send an escaped query again if InvalidQueryException occurs...

**Comment by freestyle68** [comment]
my question was too much broad: forget `:` that is an operator and focus on `/` only:

a query like

`2/20/2015`

give error, so the user must insert an escape before / or make the query

`"2/20/2015"`

It would be easier for the standard user insert the query simply as

`2/20/2015`
