### ISSUE TITLE
org.elasticsearch.indices.IndexClosedException

### ISSUE THREAD

**Issue by hilt86** [codelibs/fess#2112]
Every so often I encounter an issue (using Fess 12.3) where the index that fess uses will get closed and we will get this error : 

`org.elasticsearch.indices.IndexClosedException: closed`

This usually happens when indexing and while the fix is relatively simple (to re-open the index) I would rather find the root cause of the issue than providing a workaround by scripting starting an index.

Any idea what is causing this or how it can be prevented?

**Comment by hilt86** [comment]
Running in docker...yes I have an error on 6 May but the last line from the ES container is on the 4 May. Regardless I would imagine that if anything closed an index it would be fess rather than ES itself right?

**Comment by marevol** [comment]
In Fess, only [Maintenance](https://fess.codelibs.org/13.0/admin/maintenance-guide.html) page closes/opens fess.yyyymmdd index.
So, Fess basically does not send `close` request.
