### ISSUE TITLE
allinurl problem

### ISSUE THREAD

**Issue by freestyle68** [codelibs/fess#2113]
Hi,

go to

`https://search.n2sm.co.jp/`

pick advanced search:

All these words: user
Terms appearing: in the url of the page

and I have 1202 results with this query:

`allinurl: user`

Now I want to make a query with this filter, so search become:

`allinurl: user tweet 
`

for example, but I have zero results even if the word tweet is present:

![allinurl](https://user-images.githubusercontent.com/6328807/57367718-d042ae80-7189-11e9-859e-775c524a803d.png)

Now I modify the query in

`inurl: user tweet 
`

and I have 875 results.

So, I think you should change advanced search from allinurl to inurl, or fix the allinurl.

Thank you

**Comment by marevol** [comment]
`allinurl: user tweet` means that `url` contains both `user` and `tweet`.
So, it works correctly.
If you want to search `tweet` in `content`, it's `allinurl: user content:tweet`.
