### ISSUE TITLE
plz split number of alfa

### ISSUE THREAD

**Issue by MajidSafari** [codelibs/fess#2114]
hi 

when search 13fess search result different when 13 fess

?

**Comment by marevol** [comment]
You need to configure [fess.json](https://github.com/codelibs/fess/blob/master/src/main/resources/fess_indices/fess.json) to edit analyzers.
To do that, knowledge about elasticsearch is required.
If you need any support, please contact [Commercial Support](https://www.n2sm.net/en/support/fess_support.html).
