### ISSUE TITLE
How to force fess search result to show only PDF at the initial display? 

### ISSUE THREAD

**Issue by MeMeLwin** [codelibs/fess#2121]
Hello,

I have two questions about Fess!
1.How to erase fess cache in version fess-12.4.3?
2.Is it possible to show only PDF file at the initial display of the search result page without choosing PDF file type to display?(初期表示にPDFだけの検索結果表示は可能ですか？可能なら設定は何ですか。)

Me Me

**Comment by marevol** [comment]
> 1.How to erase fess cache in version fess-12.4.3?

What is "fess cache"?

> 2.Is it possible to show only PDF file at the initial display of the search result page without choosing PDF file type to display?

I'm not sure about your requirement...
For examples, using JavaScript, you can redirect a top page to `https://yourserver/search/?q=filetype%3Apdf`.

**Comment by MeMeLwin** [comment]
Thank you for your reply...
1. About "Fess Cache", I meant I don't want previous crawl result is showing in search result page.
2. What I try to do is to crawl every file types but show only PDF file at the initial display of the search result. When I reset, display all file types as usual.

**Comment by marevol** [comment]
If you want to delete all indexed documents, you can delete them at [Admin Search](https://fess.codelibs.org/13.0/admin/searchlist-guide.html) page or call [Admin API](https://fess.codelibs.org/lastadoc-fess.html#.api.admin.searchlist.query::delete_d_query) before the new crawling.

You can modify index.jsp for a top page.

**Comment by MeMeLwin** [comment]
Now I can delete all indexed documents at Admin Search.
As for modifying .jsp, it's a bit confusing. I think I have to modify SearchResult.jsp , not index.jsp ! Any idea? 
Thank you...

**Comment by marevol** [comment]
It depends on your requirement... You can edit jsp files for search pages.

**Comment by MeMeLwin** [comment]
Noted ... 
Thank You...
