### ISSUE TITLE
NoSuchFileException occurs in plugin-descriptor.properties installation of elasticsearch.

### ISSUE THREAD

**Issue by YKUser** [codelibs/fess#2128]
https://fess.codelibs.org/ja/12.6/install/install.html

I followed the installation instructions to install fess 12.6 in an offline environment.

When trying to download and install the plug-in as a zip, the following error occurred:

>/usr/share/elasticsearch/bin/elasticsearch-plugin install file:///home/elasticsearch/elasticsearch-analysis-fess-6.6.x.zip
>-> Downloading file:///home/elasticsearch/elasticsearch-configsync-6.6.x.zip
>[=================================================] 100%??
>Exception in thread "main" java.nio.file.NoSuchFileException: /usr/share/elasticsearch/plugins/.installing-7947128891262951635/plugin-descriptor.properties
>        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
>        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
>        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
>        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
>        at java.nio.file.Files.newByteChannel(Files.java:361)
>        at java.nio.file.Files.newByteChannel(Files.java:407)
>        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
>        at java.nio.file.Files.newInputStream(Files.java:152)
>        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:162)
>        at org.elasticsearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:714)
>        at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:793)
>        at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:776)
>        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:231)
>        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:216)
>        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
>        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
>        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
>        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
>        at org.elasticsearch.cli.Command.main(Command.java:90)
>        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)

How Can I solve it?

**Comment by marevol** [comment]
I think downloaded zip file is broken.
It is better to check if zip file is correct.

**Comment by YKUser** [comment]
@marevol Thank you for your reply

I confirmed it with the following command, but it does not seem to be a problem.
>unzip -t elasticsearch-analysis-fess-6.6.x.zip
>
>Archive:  elasticsearch-analysis-fess-6.6.x.zip
>425edb12eb249bf795f620ca9f776d5788c6a94e
>    testing: elasticsearch-analysis-fess-6.6.x/   OK
>    testing: elasticsearch-analysis-fess-6.6.x/.gitignore   OK
>    testing: elasticsearch-analysis-fess-6.6.x/.travis.yml   OK
>    testing: elasticsearch-analysis-fess-6.6.x/LICENSE   OK
>    testing: elasticsearch-analysis-fess-6.6.x/README.md   OK
>    testing: elasticsearch-analysis-fess-6.6.x/pom.xml   OK
>    testing: elasticsearch-analysis-fess-6.6.x/src/   OK
>    testing: elasticsearch-analysis-fess-6.6.x/src/main/   OK
>    testing: elasticsearch-analysis-fess-6.6.x/src/main/assemblies/   OK
>    testing: elasticsearch-analysis-fess-6.6.x/src/main/assemblies/plugin.xml   OK
>    testing: elasticsearch-analysis-fess-6.6.x/src/main/java/   OK
>    testing: elasticsearch-analysis-fess-6.6.x/src/main/java/org/   OK
>    testing: elasticsearch-analysis-fess-6.6.x/src/main/java/org/codelibs/   OK
>    testing: elasticsearch-analysis-fess-6.6.x/src/main/java/org/codelibs/elasticsearch/   OK
>    testing: elasticsearch-analysis-fess-6.6.x/src/main/java/org/codelibs/elasticsearch/fess/   OK
>    testing: elasticsearch-analysis-fess-6.6.x/src/main/java/org/codelibs/elasticsearch/fess/FessAnalysisPlugin.java   OK
>    testing: elasticsearch-analysis-fess-6.6.x/src/main/java/org/codelibs/elasticsearch/fess/analysis/   OK
>    testing: elasticsearch-analysis-fess-6.6.x/src/main/java/org/codelibs/elasticsearch/fess/analysis/EmptyTokenizer.java   OK
>    testing: elasticsearch-analysis-fess-6.6.x/src/main/java/org/codelibs/elasticsearch/fess/index/   OK
>    testing: elasticsearch-analysis-fess-6.6.x/src/main/java/org/codelibs/elasticsearch/fess/index/analysis/   OK
>    testing: elasticsearch-analysis-fess-6.6.x/src/main/java/org/codelibs/elasticsearch/fess/index/analysis/ChineseTokenizerFactory.java   OK
>    testing: elasticsearch-analysis-fess-6.6.x/src/main/java/org/codelibs/elasticsearch/fess/index/analysis/JapaneseBaseFormFilterFactory.java   OK
>    testing: elasticsearch-analysis-fess-6.6.x/src/main/java/org/codelibs/elasticsearch/fess/index/analysis/JapaneseIterationMarkCharFilterFactory.java   OK
>    testing: elasticsearch-analysis-fess-6.6.x/src/main/java/org/codelibs/elasticsearch/fess/index/analysis/JapaneseKatakanaStemmerFactory.java   OK
>    testing: elasticsearch-analysis-fess-6.6.x/src/main/java/org/codelibs/elasticsearch/fess/index/analysis/JapanesePartOfSpeechFilterFactory.java   OK
>    testing: elasticsearch-analysis-fess-6.6.x/src/main/java/org/codelibs/elasticsearch/fess/index/analysis/JapaneseReadingFormFilterFactory.java   OK
>    testing: elasticsearch-analysis-fess-6.6.x/src/main/java/org/codelibs/elasticsearch/fess/index/analysis/JapaneseTokenizerFactory.java   OK
>    testing: elasticsearch-analysis-fess-6.6.x/src/main/java/org/codelibs/elasticsearch/fess/index/analysis/KoreanTokenizerFactory.java   OK
>    testing: elasticsearch-analysis-fess-6.6.x/src/main/java/org/codelibs/elasticsearch/fess/index/analysis/ReloadableJapaneseTokenizerFactory.java   OK
>    testing: elasticsearch-analysis-fess-6.6.x/src/main/java/org/codelibs/elasticsearch/fess/index/analysis/TraditionalChineseConvertCharFilterFactory.java   OK
>    testing: elasticsearch-analysis-fess-6.6.x/src/main/java/org/codelibs/elasticsearch/fess/index/analysis/VietnameseTokenizerFactory.java   OK
>    testing: elasticsearch-analysis-fess-6.6.x/src/main/java/org/codelibs/elasticsearch/fess/service/   OK
>    testing: elasticsearch-analysis-fess-6.6.x/src/main/java/org/codelibs/elasticsearch/fess/service/FessAnalysisService.java   OK
>    testing: elasticsearch-analysis-fess-6.6.x/src/main/plugin-metadata/   OK
>    testing: elasticsearch-analysis-fess-6.6.x/src/main/plugin-metadata/plugin-descriptor.properties   OK
>    testing: elasticsearch-analysis-fess-6.6.x/src/main/plugin-metadata/plugin-security.policy   OK
>    testing: elasticsearch-analysis-fess-6.6.x/src/test/   OK
>    testing: elasticsearch-analysis-fess-6.6.x/src/test/java/   OK
>    testing: elasticsearch-analysis-fess-6.6.x/src/test/java/org/   OK
>    testing: elasticsearch-analysis-fess-6.6.x/src/test/java/org/codelibs/   OK
>    testing: elasticsearch-analysis-fess-6.6.x/src/test/java/org/codelibs/elasticsearch/   OK
>    testing: elasticsearch-analysis-fess-6.6.x/src/test/java/org/codelibs/elasticsearch/fess/   OK
>    testing: elasticsearch-analysis-fess-6.6.x/src/test/java/org/codelibs/elasticsearch/fess/FessAnalysisPluginTest.java   OK
>No errors detected in compressed data of elasticsearch-analysis-fess-6.6.x.zip.

I downloaded several times, but the installation results were all the same.

**Comment by marevol** [comment]
It's not a zip plugin, and Fess 12.6 supports only version 6.7.x for plugins. 
See [README](https://github.com/codelibs/elasticsearch-analysis-fess#version).

**Comment by YKUser** [comment]
I downloaded and installed the correct zip file.
Thanks for your help.

**Comment by alizorlu** [comment]
same problem occurred to me. the source of the problem is 'logstash'
the solution is as follows,
In the Elastich directory > I removed the following folders under the "modules" folder.
-"fb_apache"
-"net_flow"
-"readme.md"

can it be tried?
