### ISSUE TITLE
No results shown after the 2nd or 3rd page.

### ISSUE THREAD

**Issue by eltonkent** [codelibs/fess#2129]
I'm seeing an issue with paginated results. My search query has 60 results but the page does not scroll beyond page 3 (30 results).
<img width="284" alt="Screen Shot 2019-05-25 at 10 03 09 AM" src="https://user-images.githubusercontent.com/5461482/58370420-5e31cf80-7ed4-11e9-9c7f-8b011592856a.png">
<img width="428" alt="Screen Shot 2019-05-25 at 10 03 05 AM" src="https://user-images.githubusercontent.com/5461482/58370421-5e31cf80-7ed4-11e9-9408-64a49a73ca1c.png">

**Comment by marevol** [comment]
Try to disable [Similar Result Collapsed](https://fess.codelibs.org/13.0/admin/general-guide.html#similar-result-collapsed).
