### ISSUE TITLE
Suddenly date label is not showing reselts

### ISSUE THREAD

**Issue by biligee** [codelibs/fess#2131]
My date label suddenly stopped to work. 期間: 該当なし. What could be the cause? I have tried to customize and change a few things in the label localization files.

**Comment by marevol** [comment]
Could you provide the detail to reproduce it?

**Comment by biligee** [comment]
Thank you for your reply. It seems some labels are shown partially and 期間 is not shown at all when crawler(perhaps heavy) is running behind. Once crawler(indexer) finished, I can see 期間. This is just my observation. Sorry, I didn't have time to collect enough evidence.

**Comment by biligee** [comment]
When I search using * to display all the records, 期間 is not shown.

**Comment by marevol** [comment]
I could not reproduce it...

**Comment by biligee** [comment]
Thank you for your reply. It is not such an important matter. My 30K index is showing it, but another 52K index is not. 

Anyway, I will close it.
