### ISSUE TITLE
Exclude (.html) file type in Web Crawling

### ISSUE THREAD

**Issue by MeMeLwin** [codelibs/fess#2132]
Hi,

I was wondering how to exclude certain file types in Web Crawling?
I try the below setting in Excluded URLs For Crawling and it didn't work .

http://xx.x.xx.xxx/Test/doc/.*\.html 

What is the setting for excluding (.html) file and where should I put that setting?
In Excluded URLs For Crawling (or) Excluded URLs For Indexing ?

Thank You.

**Comment by marevol** [comment]
Try `.*\.html`.
