### ISSUE TITLE
Description of the search results become hidden if thumbnail is missing

### ISSUE THREAD

**Issue by biligee** [codelibs/fess#2133]
In the search results, "description" is hidden if thumbnail is missing or /images/blank.png.
`<div class="body" style="display: none;"></div>`
How do I display "description" always?

**Comment by biligee** [comment]
For a while, I removed "display:none;" from search.js.  Needs a better solution.

**Comment by marevol** [comment]
Did you modify jsp files?

**Comment by biligee** [comment]
> Did you modify jsp files?

Yes. But I also tried default page.

**Comment by marevol** [comment]
I think you need to also modify [search.js](https://github.com/codelibs/fess/blob/fess-13.0.1/src/main/webapp/js/search.js#L249-L252).
