### ISSUE TITLE
Fess: No search result with Elasticsearch 

### ISSUE THREAD

**Issue by vikasruhela** [codelibs/fess#2140]
I am using fess 13.1 with elasticsearch 7.1.1. I am able to create the connection and i can see the elasticsearch indices in Fess Admin Dashboard. However, whenever i search something on fess it shows no results. 
Please let me know any steps to make the search possible. I have installed all the required plugins.
![Screenshot from 2019-06-06 12-59-56](https://user-images.githubusercontent.com/37119022/59014720-e744f100-885a-11e9-933d-38bcb4fabbd1.png)
![Screenshot from 2019-06-06 13-01-34](https://user-images.githubusercontent.com/37119022/59014744-ef9d2c00-885a-11e9-9660-e830ebd20fe0.png)

**Comment by marevol** [comment]
Did you check log files?

**Comment by vikasruhela** [comment]
I am not getting any error in fess-crawler.log.

**Comment by marevol** [comment]
How many indexed documents are there in fess.yyyymmdd index?

**Comment by vikasruhela** [comment]
Zero. 
![Screenshot from 2019-06-06 15-09-14](https://user-images.githubusercontent.com/37119022/59023190-d8ffd080-886c-11e9-955e-340ced153321.png)

**Comment by marevol** [comment]
Is your crawling configuration correct?
