### ISSUE TITLE
Error: No write index is defined for alias

### ISSUE THREAD

**Issue by shwetazilpe** [codelibs/fess#2141]
Hi,
When I click on start button in Maintenance submenu, I can see a new index with name fess.yyyyMMddHHmm gets created and update and search alias also being updated. 
But when I start crawler next time, I get the below error-
java.lang.IllegalArgumentException: no write index is defined for alias [fess.update]. The write index may be explicitly disabled using is_write_index=false or the alias points to multiple indices without one being designated as a write index.

After checking all the indices, I noticed there were 2 indexes with name fess.yyyyMMddHHmm and fess.yyyyMMdd, both with search and update alias.
I Just wanted to know that does the crawler creates new index if it does not finds the index in format "fess.yyyyMMdd"?
Thanks in Advance!

**Comment by marevol** [comment]
Please remove fess.update and fess.search alias from the old fess index.

**Comment by shwetazilpe** [comment]
I did it, but every time I click Maintenance menu and then start crawler, issue came again. It would be really helpful if I got to know any code location in fess or fess-crawler where this index is being created during crawling so that i can try debugging it?

**Comment by marevol** [comment]
See [AdminMaintenanceAction](https://github.com/codelibs/fess/blob/master/src/main/java/org/codelibs/fess/app/web/admin/maintenance/AdminMaintenanceAction.java).

**Comment by shwetazilpe** [comment]
Okay. I'll try this. Thank You!
