### ISSUE TITLE
Facebook and twitter profile, posts, tweets, comments etc.

### ISSUE THREAD

**Issue by yashodhank** [codelibs/fess#2146]
Thank you for awesome software!

I have few twitter and facebook accounts to follow for its comments.
Right now I have added in include url as follows:
```
https://twitter.com/username/.*
https://facebook.com/username/.*
https://facebook.com/pagename/.*
```
But only user page got indexed nothing else is showing up in search results.
What config do I have to use? What I am missing here.

Please help, Thank you

**Comment by marevol** [comment]
A html page generated by JavaScript is not supported by default.
