### ISSUE TITLE
to show Additional Word in Suggestion

### ISSUE THREAD

**Issue by biligee** [codelibs/fess#2148]
How to show 追加ワード in キーワードサジェスト?  I have tried to add 全文検索 with yomi both in katagana and hiragana like ぜんぶんけんさく and ゼンブンケンサク. When I start typing ぜん,  全文検索 is not showing in suggestion.

**Comment by biligee** [comment]
I also tried /search/suggest?query=ぜん

**Comment by biligee** [comment]
It seems I need to run Suggest Indexer job.

**Comment by marevol** [comment]
Yes, you need to do that.
