### ISSUE TITLE
Crawing does not work (CrawlingAccessException occured)

### ISSUE THREAD

**Issue by daisyheads-love** [codelibs/fess#2149]
I am trying to crawler a file system, but its not working. "jcifs.CIFSException" is occured. 
Fess version is fess-12.6.2 and fess server OS is win10.
attach files are my setting, Failure URL and fess-crawl.log(debug mode).

Please let me know how to solve this error.
[Uploading file crawl setting.txt…]()
[Uploading failure URL.txt…]()
[Uploading fecc-craler.log…]()

**Comment by marevol** [comment]
fess-crawler.log is not attached.

**Comment by daisyheads-love** [comment]
Sorry!
Reattached Crawling setting , Failure URL and fess-crawl.log. 

[file crawl setting.txt](https://github.com/codelibs/fess/files/3308386/file.crawl.setting.txt)
[failure URL.txt](https://github.com/codelibs/fess/files/3308390/failure.URL.txt)
[fess-craler.log](https://github.com/codelibs/fess/files/3308391/fess-craler.log)

**Comment by marevol** [comment]
Try to replace `smb1://...` with `smb://...` in the crawling configuration.

**Comment by daisyheads-love** [comment]
Thank you for your reply.
I changed the crawling configuration to your reply, and I tried again.
The crawl works well !!

Does this definition(“smb1://”) means SMB1 protocol?
Please let me know reason why use this definition.
