### ISSUE TITLE
java heap size

### ISSUE THREAD

**Issue by rafael844** [codelibs/fess#2152]
Im trying to increase heap size to 10GB, but it shows me only 1GB
```
# JVM options
jvm.crawler.options=\
-Djava.awt.headless=true\n\
-Dfile.encoding=UTF-8\n\
-Djna.nosys=true\n\
-Djdk.io.permissionsUseCanonicalPath=true\n\
-server\n\
-Xmx10g\n\
-XX:MaxMetaspaceSize=128m\n\
-XX:CompressedClassSpaceSize=32m\n\
-XX:-UseGCOverheadLimit\n\
```
But the Dashboard only shows me 1GB
![dash](https://user-images.githubusercontent.com/31928478/59924001-19ce1c80-940b-11e9-810a-d031c30881ee.png)
Is there other place to increase it?

**Comment by marevol** [comment]
The setting is for a crawler, not a web app.
It's in fess.in.bat, but the web app of Fess does not consume a heap memory.
So, installing elasticsearch separately, you need to configure it on elasticsearch.
