### ISSUE TITLE
How to get crawling info via curl

### ISSUE THREAD

**Issue by ECJansen** [codelibs/fess#2153]
I see that one should be able to perform curl requests against the admin api.  I set up an access token (#1057).  When I do:
curl -v -i -H "Authorization:ACCESS_TOKEN" http://localhost:8080/api/admin/crawlinginfo
it returns: /error/notfound/?url=%2Fapi%2Fadmin%2Fcrawlinginfo%2F

What am I missing ?

Thanks

**Comment by marevol** [comment]
It's better to check if the token is valid.

**Comment by ECJansen** [comment]
I added an admin-api role:
![image](https://user-images.githubusercontent.com/42979109/60115967-fae1ca00-972b-11e9-821c-3c0bbfe3e6b4.png)
and created an access token:
![image](https://user-images.githubusercontent.com/42979109/60116039-21076a00-972c-11e9-909c-304076e11f19.png)
When I do the curl, I get:
![image](https://user-images.githubusercontent.com/42979109/60116143-557b2600-972c-11e9-9369-734a7d142bde.png)
Am I not setting up the access token correctly ?  If not, how to set up correctly ?
Thanks

**Comment by ECJansen** [comment]
So having made the changes for the new role and access token, when I login to the admin console, I get a search screen and no dashboard.  Selecting Administration from the dropdown leaves me at the search screen.  Selecting Logout does indeed log me out and leave me at the login screen.  How can I correct this ?
![image](https://user-images.githubusercontent.com/42979109/60122186-8877e680-9739-11e9-9992-783dc96c17ee.png)

Thanks

**Comment by marevol** [comment]
The endpoint is wrong.
See https://fess.codelibs.org/lastadoc-fess.html#.api.admin.crawlinginfo.logs::logs

**Comment by marevol** [comment]
> How can I correct this ?

It's not reproduced and better to restore jsp files.
