### ISSUE TITLE
Fess Search

### ISSUE THREAD

**Issue by MeMeLwin** [codelibs/fess#2158]
Is it possible to display .mp4 file in Result Page in Fess when searching?
In my case, when I search for .mp4 files, the result did not show the .mp4 file.
Any setting to be done to display .mp4 files in search result page?

**Comment by marevol** [comment]
A filename is stored to filename field by default.

**Comment by MeMeLwin** [comment]
My mp4 file is too large. MaxLengthException occured. That's why I can't find mp4 files.
Modified the contextlength.xml and problem solved! Thank You.
