### ISSUE TITLE
Crawling web pages without encoding information.

### ISSUE THREAD

**Issue by biligee** [codelibs/fess#2159]
How do I crawl web pages that didn't explicitly specify the encoding and text is encoded in shift-jis

**Comment by marevol** [comment]
The default encoding is UTF-8.

**Comment by biligee** [comment]
Yes. UTF-8 websites can be crawled. I guess, there are tons of websites that have <META content="text/html; charset=shift_jis" http-equiv=Content-Type>. How do I crawl them.
