### ISSUE TITLE
Unable to index PDF, Word or Excel files

### ISSUE THREAD

**Issue by erbouchard** [codelibs/fess#2164]
I'm trying to figure out. My HTML pages are indexed properly but none of PDF, Word or Excel files.

Using version 12.6.

**Crawling parameters**

```
URLs
http://host/NPG/

Included URL For Crawling
http://host/NPG/.*

Excluded URLs For Crawling
.(?i).*(css|js|jpeg|jpg|gif|png|bmp|wmv|exe|mp4)

Included URLs For Indexing
http://host/NPG/.*

Excluded URLs For Indexing
(empty)
```

**Questions**

1. Is this supposed to index those documents (references in `<a href="...">...</a>`) by default?

2. Or do I have to configure something?

Thanks

**Comment by marevol** [comment]
> Is this supposed to index those documents (references in <a href="...">...</a>) by default?

Yes.

> Or do I have to configure something?

See fess-crawler.log.

**Comment by erbouchard** [comment]
Here's my fess-clawler.log for today. No trace of any of those files.

[fess-crawler.log](https://github.com/codelibs/fess/files/3363269/fess-crawler.log)

**Comment by marevol** [comment]
Which page is PDF file linked?
