### ISSUE TITLE
label paths

### ISSUE THREAD

**Issue by rafael844** [codelibs/fess#2174]
Hi, is there a way to label paths as a folder tree? For example, I search an article and it was found in:
www.reddit.com/r/youtube/
www.reddit.com/r/ThisAmericanLife/
www.reddit.com/r/ 
www.reddit.com/user/SecondEpsilon/

The Label shows "reddit", then I click on it, and it shows 
```
reedit
   |-r
   |-user
```

When I click on user:
```
reedit
   |-r
   |-user
      |-SecondEpsilon
```
... and so on... And while I click on the disired label it does automatically the filtering and shows to user.

**Comment by marevol** [comment]
No.
Label does not have a hierarchy.

**Comment by rafael844** [comment]
It would be nice to have this feature in a future release. Specially for intranet searches.

**Comment by rafael844** [comment]
> 
> 
> No.
> Label does not have a hierarchy.

Is there any way to to this?

**Comment by marevol** [comment]
Adding a custom field with [path hierarchy tokenizer](https://www.elastic.co/guide/en/elasticsearch/reference/6.3/analysis-pathhierarchy-tokenizer.html) is proper for your requirement.
If you need more supports, please contact [Commercial Support](https://www.n2sm.net/en/support/fess_support.html).
