### ISSUE TITLE
Docker Kibana instructions

### ISSUE THREAD

**Issue by pcolmer** [codelibs/fess#2181]
https://github.com/codelibs/docker-fess says to use this command to use Kibana with Fess:

    docker run -d -e ELASTICSEARCH_URL=http://localhost:9200 \
        --name kibana kibana:latest

However, that doesn't work - `kibana:latest` isn't a valid container reference.

I've tried using `docker.elastic.co/kibana/kibana:7.2.0` as that matches the ES version number but I'm getting the error "Cannot connect to the Elasticsearch cluster currently configured for Kibana". The message goes on to say "To use the full set of free features in this distribution of Kibana, please update Elasticsearch to the default distribution".

Do you know how to resolve this? I've also posted at https://discuss.elastic.co/t/docker-kibana-cannot-connect-to-the-elasticsearch-cluster-currently-configured-for-kibana/190961 about this but I'm not sure if the root cause of the problem is how the fess container is being built with ES inside it (compared with how Elastic build their ES container).

Thanks.

**Comment by marevol** [comment]
Fixed [docker-compose.yml](https://github.com/codelibs/docker-fess/blob/master/compose/docker-compose.yml), but fess_log.json in [Kibana config](https://github.com/codelibs/fess/tree/master/src/main/assemblies/extension/kibana) does not work.

**Comment by pcolmer** [comment]
Thank you for the changes to `docker-compose.yml`.

- If `fess_log.json` does not work, does that mean there is no value (at the moment) in using Kibana to monitor fess? Will you/are you able to fix the problem(s)?

- https://github.com/codelibs/docker-fess/blob/master/README.md says that running fess with persistent data/config requires volume mounts to /opt/fess and /var/lib/elasticsearch. However, `docker-compose.yml` seems to be hinting that the data directory is /usr/share/elasticsearch/data and is being mounted from the current directory?

- Both es01 and es02 have a volume mount to /usr/share/elasticsearch/config/dictionary and all three containers define `FESS_DICTIONARY_PATH` to the same location. However, fess01 doesn't have a volume mount so does that mean that the fess reference is ephemeral rather than persisted on the host?

**Comment by pcolmer** [comment]
One small point that may be worth making on the Kibana documentation is that it isn't possible to create an Index Pattern for "fess_log*" until fess has actually been used. The ES indices don't seem to exist for Kibana until they have some documents in them. That had me scratching my head for quite some time trying to figure out why I couldn't get past that point.

**Comment by marevol** [comment]
Docs for Kibana is still old. It'll be updated...
The new docker-compose.yml uses an elasticsearch image based on elastic.co, not Fess.
In fess01, FESS_DICTIONARY_PATH is just a setting to specify a dictionary path in es nodes.

**Comment by pcolmer** [comment]
Thank you.
