### ISSUE TITLE
Thumbnail generation in Ubuntu

### ISSUE THREAD

**Issue by biligee** [codelibs/fess#2187]
I can generate thumbnails in CentOS by installing  unoconv libreoffice-headless vlgothic-fonts ImageMagick. 

However, I can't generate thumbnails of PDF and MS Office files. Image files such as BMP, JPG is OK. I have installed Libreoffice, Imagemagick and convert command is running in terminal. What am I missing?  

BTW, There is no English manual for https://fess.codelibs.org/ja/13.2/config/thumbnail.html

Thank you in advance.

**Comment by marevol** [comment]
Did you check fess-*.log files?
It's better to check these commands in PATH environment.
Fess generates images by [generate-thumbnail](https://github.com/codelibs/fess/blob/master/src/main/assemblies/files/generate-thumbnail).
