### ISSUE TITLE
Unable to add label to crawl configuration of datastore

### ISSUE THREAD

**Issue by seki19** [codelibs/fess#2193]
I want to add a label for crawling a data store, but the form for adding a label is not displayed on the crawl setting screen.

I have created two labels.

centos7
fess 13.1

**Comment by marevol** [comment]
Label is label field.
You can put `label=["aaa", "bbb", "ccc"]` to [Script](https://fess.codelibs.org/13.2/admin/dataconfig-guide.html#script).

**Comment by seki19** [comment]
Thank you for your response！
