### ISSUE TITLE
Only 10 facets result returned

### ISSUE THREAD

**Issue by GenxuanHu** [codelibs/fess#2196]
In my testing of fess, I created several facet field by content hierachy with property content_cateogry. 

So for the page like /level1/level2/products.html, I will set content_category as 
level1%7C%7Clevel2 ( %7C is the encoded | )

for the level1 I have 5 pages and level2 I have 10 pages for each in total. 
By this way, I should have facets result contains 5 x 10 = 50.
But when I do the search like q=*&facet.field=content_category,
I can just get 10 facet_field results instead of all of those 50 results. the same facets works like.

[{"name": "content_category","result": [{"value": "products%7C%7CIP%20Products","count": 72},{"value": "products%7C%7CAccessories","count": 30},{"value": "newsroom%7C%7Clatest-news","count": 17},{"value": "newsroom%7C%7Csuccess-stories","count": 15},{"value": "products%7C%7CITS%20Products","count": 11},{"value": "products%7C%7CTurbo%20HD%20Products","count": 11},{"value": "Solutions%7C%7CIP","count": 9},{"value": "products%7C%7CAccess%20Control%20Products","count": 9},{"value": "products%7C%7CAlarm%20Products","count": 7},{"value": "products%7C%7CVideo%20Intercom%20Products","count": 7}]}]

Is there any place to change it to allow me show those 50 facets results ?

**Comment by marevol** [comment]
Did you try `facet.size`?
See [JSON API](https://fess.codelibs.org/13.2/user/json-response.html).

**Comment by GenxuanHu** [comment]
I see, Sorry to missed the JSON API. Works perfectly. thanks a lot.

Thanks
Genxuan
