### ISSUE TITLE
404 After Service Restart

### ISSUE THREAD

**Issue by jb8893** [codelibs/fess#2198]
After trying to restart our FESS / Elasticsearch service we are currently receiving a 404 error.  The solution has been working fine for 6 months with no changes.

We tried clearing configsync using:
`service fess stop;
curl -XDELETE http://localhost:9200/.configsync;
service elasticsearch restart;
service fess start`

**Fess**: 12.3.0
**Elasticsearch**: 6.3.2

[internal-search.log](https://github.com/codelibs/fess/files/3457717/internal-search.log)

**Comment by marevol** [comment]
Fess 12.3 does not support Elasticsearch 6.3.
See [Download](https://fess.codelibs.org/downloads.html) page.

**Comment by jb8893** [comment]
Issue resolved.  The problem was caused when trying to use a OR query in the Key Match.  Removed and everything is working as intended now.  Thank you!
