### ISSUE TITLE
Correct File System Label path using windows shared folder

### ISSUE THREAD

**Issue by Conmariin** [codelibs/fess#2199]
Hi,
I'm using Ver. 12.4 of fess.
I'm crawling a pdf archive on another windows-server in a windows shared folder. With crawling all works fine but you have no search hits when you choose a label in the search options. Without choosing a label you're getting hits. So I think the label included path is wrong. I'm taking the url from the fess-crawler.log for included path: INFO  Crawling URL: **file:////se_rver2/PDF-Archive/ressortone/2001/** 
So, can anybody help me out getting the correct label path for a windows shared folder?
Thanks!

Besides the labeling to a webside with a http-URL works fine.

Best regards
Conmariin

**Comment by marevol** [comment]
What is your setting for the label?

**Comment by Conmariin** [comment]
Name -> Ressortone
Value -> ressortone
Included Paths -> file:////se_rver2/PDF-Archive/ressortone/

**Comment by marevol** [comment]
`file:////se_rver2/PDF-Archive/ressortone/.*`
file:////se_rver2/PDF-Archive/ressortone/ is not indexed because of a folder.

**Comment by Conmariin** [comment]
That was the solution! Thank you! :)
For al who want to crawl windows shared folder:

Crawler -> FileSystem: Path -> file:////se_rver2/PDF-Archive/

Crawler -> Label: Included Paths -> file:////se_rver2/PDF-Archive/ressortone/.*
