### ISSUE TITLE
Web authentication SSO

### ISSUE THREAD

**Issue by panyaue** [codelibs/fess#2204]
Hi!
please teach me how to Use Web Session SSO(Session Id Save to cookie).

current Web authentication Parameters Settings.
It doesn't work.
↓
login_method=POST
login_url=[login page url]
login_parameters=USER=${username}&PASSWORD=${password}

**Comment by marevol** [comment]
It depends on your web site.
See [Crawling Protected Site](https://fess.codelibs.org/13.2/admin/webconfig-guide.html#crawling-protected-site).
If you need more supports, please contact [Commercial Support](https://www.n2sm.net/en/support/fess_support.html).

**Comment by panyaue** [comment]
Thank you marevol san.
The site you taught me has already been checked.
But Sample Parameters is Token Pattern.
In the same way Session Pattern Can Authenticate?
Or do you need to deal with request headers?

**Comment by panyaue** [comment]
It was a certificate issue, not an authentication issue.
Thank you.

**Comment by panyaue** [comment]
It was a certificate issue, not an authentication issue.
 Thank you.
