### ISSUE TITLE
Crawling a large number of SMB files will slow down when fess is running in docker container

### ISSUE THREAD

**Issue by sutra806** [codelibs/fess#2214]
I am trying to crawl many smb files in Fess 13.2 in docker container.
After crawling about 1000 or more files, crawl speed becomes very slow.

When "The number of thread" is large or "Interval time" is short in the crawl setting, it is often occurs.

I crawl with the log level set to debug, the following log is output to fess-crawler.log, and then the crawler thread blocks for about 1 to 3 minutes.

- DEBUG Closing FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

**Comment by marevol** [comment]
Did you check CPU&Memory resource on crawling?
You need to set proper values for "The number of thread" and "Interval time".

**Comment by sutra806** [comment]
Yes, I've not restricted cpu and memory resource on docker, and not changed JVM option of fess and crawler from the default settings.
I've tried to crawl in same setting on Windows zip distribution of fess, it's not slows down.

**Comment by sutra806** [comment]
I've tried the rpm version of fess 13.2(without docker), the problem does not resolved. Do you have any solutions?

**Comment by marevol** [comment]
Could you provide the debug logs?

**Comment by sutra806** [comment]
[fess-crawler.log](https://github.com/codelibs/fess/files/3628952/fess-crawler.log)
Here is an extracted crawl log file (some information is masked.)

**Comment by marevol** [comment]
Is it reproduced if replacing `smb://` with `smb1://`?

**Comment by sutra806** [comment]
It is not reproduced!

**Comment by sutra806** [comment]
Could I get any workaround to crawl SMB2 files?

**Comment by sutra806** [comment]
Did you have any plans to improve this issues?

**Comment by marevol** [comment]
For smb2 feature, we merge it from [jcifs-ng](https://github.com/AgNO3/jcifs-ng) to our [jcifs](https://github.com/codelibs/jcifs).
So, if it's fixed in jcifs-ng, it will be fixed in Fess.

**Comment by sutra806** [comment]
It makes me happy by upgrading jcifs to 2.1.13. Thanks!
