### ISSUE TITLE
gitbucket datastore crawler with {role}admin permission do not work

### ISSUE THREAD

**Issue by o-matsuo** [codelibs/fess#2215]
i use 
 fess: 13.2.0
 elasticsearch: 7.2.0
 gitbucket: 4.32.0
 gitbucket-fess-plugins: 2.13-1.5.0

i setuped datastore crawler
------------------------------------------
名前	gitbucket_crawler
ハンドラ名	GitBucket
パラメータ	url=http://localhost:8089/gitbucket/
                        token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
スクリプト	
ブースト値	1.0
パーミッション	{role}admin
仮想ホスト	
状態	有効
説明	
------------------------------------------

i search data in gitbucket-repo-data when i do not login.
but i can search gitbucket-repo-data.
( my permission is guest mode)

i hope that i can not search gitbucket-repo-data when i do not login.

**Comment by marevol** [comment]
For fess-ds-gitbucket, permission info seems to come from [gitbucket setting](https://github.com/codelibs/fess-ds-gitbucket/blob/master/src/main/java/org/codelibs/fess/ds/gitbucket/GitBucketDataStore.java#L261-L275), not the configuration.

**Comment by o-matsuo** [comment]
Thank you very much.
I understood that the plug-in cannot set permissions on the FESS side
