### ISSUE TITLE
jcifs.smb.SmbException indexing files smb

### ISSUE THREAD

**Issue by rafael844** [codelibs/fess#2218]
Im having problems with authentication, all folders and files are in the same place, I put they there at the same time and with the same permissions. But its not indexing all. I have about 11.000 files, but it only indexes 300, then I have to run it again and it indexes another few files, its almost in 1000, but i have to run the scheduler many times, and its not indexing all. Im using windows fess 13.1.1.
one file log:

> 
>  Type:  jcifs.smb.SmbException
> 
> org.codelibs.fess.crawler.exception.CrawlingAccessException: Cannot get owner of the file: smb://10.200.51.131/sged/12818/id_10976_Ofício n.º 260-2018.pdf	at org.codelibs.fess.crawler.client.smb.SmbClient.getResponseData(SmbClient.java:228)	at org.codelibs.fess.crawler.client.smb.SmbClient.processRequest(SmbClient.java:162)	at org.codelibs.fess.crawler.client.smb.SmbClient.doHead(SmbClient.java:394)	at org.codelibs.fess.crawler.client.AbstractCrawlerClient.execute(AbstractCrawlerClient.java:144)	at org.codelibs.fess.crawler.FessCrawlerThread.isContentUpdated(FessCrawlerThread.java:85)	at org.codelibs.fess.crawler.CrawlerThread.run(CrawlerThread.java:155)	at java.base/java.lang.Thread.run(Thread.java:834)Caused by: jcifs.smb.SmbException: 0xC0000128	at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1457)	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1568)	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1023)	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1539)	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:409)	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:469)	at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:400)	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:315)	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:295)	at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130)	at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:117)	at jcifs.smb.SmbFile.withOpen(SmbFile.java:1747)	at jcifs.smb.SmbFile.withOpen(SmbFile.java:1716)	at jcifs.smb.SmbFile.withOpen(SmbFile.java:1710)	at jcifs.smb.SmbFile.querySecurity(SmbFile.java:2226)	at jcifs.smb.SmbFile.getOwnerUser(SmbFile.java:2275)	at jcifs.smb.SmbFile.getOwnerUser(SmbFile.java:2268)	at org.codelibs.fess.crawler.client.smb.SmbClient.getResponseData(SmbClient.java:222)	... 6 more
> 
> 
>

**Comment by marevol** [comment]
Could you try `smb1://`, not `smb://`?

**Comment by rafael844** [comment]
Yes it worked.

Thank you.

**Comment by Lavini281** [comment]
Hi !

Sorry to comment on this closed issue but I am having the exact same problem and I can't use SMBv1. While Tracing I have seen the error Code `0xC0000128``sent from the SMB host. From the microsoft [documentation](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-cifs/8f11e0f3-d545-46cc-97e6-f00569e3e1bc), it looks like it stands for "STATUS_FILE_CLOSED". I tried to use only one thread in case it was a threading issue but it is still appearing. Do you have any idea on this ?

Thank you in advance
