### ISSUE TITLE
indexing MaxLengthExceededException

### ISSUE THREAD

**Issue by rafael844** [codelibs/fess#2224]
We have MaxLength with 200MB, and in few documents we are getting org.codelibs.fess.crawler.exception.MaxLengthExceededException.
1 - Is there a way to indexing this documents? not crawl, just do they searchable by file name.

2 -  We set Remove Documents Before to -1, so its not deleted after few days, but its not deleted from index if we delete it from storage. Is there a way to do fess crawl they again only if the are changed or delete from index if the dont exists anymore?

**Comment by marevol** [comment]
> Is there a way to indexing this documents? 

See https://github.com/codelibs/fess/issues/929#issuecomment-286734962

> Is there a way to do fess crawl they again only if the are changed or delete from index if the dont exists anymore?

No. -1 means not to delete indexed documents.

**Comment by rafael844** [comment]
I set this  variable already, but its not beeing indexed. I set it to 200MB but if the PDF has 300 MB it can not be founded in the search. I dont want it to crawl all its text, just be able to find it by its name.pdf.
