### ISSUE TITLE
Data store libraries are not loaded by Fess

### ISSUE THREAD

**Issue by Yanagi-fixstars** [codelibs/fess#2225]
I tried add data store library (JIRA) following repository's instruction on Fess 13.0 in Ubuntu 18.04.
Specifically, I did commands below:

```
$ cd  /usr/share/fess/app/WEB-INF/lib/
$ sudo wget  wget http://central.maven.org/maven2/org/codelibs/fess/fess-ds-atlassian/13.3.0/fess-ds-atlassian-13.3.0.jar
$ sudo chmod 755 fess-ds-atlassian-13.3.0.jar
$ sudo chown fess:fess fess-ds-atlassian-13.3.0.jar
$ sudo systemctl restart fess.service
```

After that, I tried to make crawler in data store crawling configuration and confirmed the library was not shown in `Handler name`.
I solved this problem by downgrading 12.1.

**Comment by marevol** [comment]
Fess 13.0 supports only fess-ds-atlassian-13.0.x.jar.
To install fess-ds-atlassian-13.3.x.jar, you need to use Fess 13.3.x.

**Comment by Yanagi-fixstars** [comment]
@marevol Oops, this is a typo. I used Fess 13.3.0.
I found that fess plugins are installed by `admin/plugin/` but each plugin repository's README.md is not updated from 13.2.x.
Therefore, could you update them to use `admin/plugin/` ?

**Comment by gnakagaw** [comment]
@marevol 
Hi, I'm gnakagaw, a colleagues of @Yanagi-fixstars.
Please let me explain further.

1. We can enable fess-ds-atlassian plugin via System-Plugin page in admin console. The problem has been resolved.
2. We found that several plugin's README need to be updated. They say that 
```
Installation
Download fess-ds-sample-X.X.X.jar
Copy XXX-X.X.X.jar to $FESS_HOME/app/WEB-INF/lib or /usr/share/fess/app/WEB-INF/lib
```
However, it is not valid for > fess 13.3.0. I will make another issue report.

**Comment by marevol** [comment]
> We found that several plugin's README need to be updated. 

It's for an old version.

**Comment by gnakagaw** [comment]
We got it. Thank you.
