### ISSUE TITLE
Is it possible to do searching on two FESS instances?

### ISSUE THREAD

**Issue by seppjooo** [codelibs/fess#2232]
I have two instances of FESS running on two different ports.
FESS_cluster1: localhost:8085 (Indexed documents: 1)
FESS_cluster2: localhost:8086 (Indexed documents: 2)

By default, FESS searches on the index fess.YYYYMMDD, right?
Is it possible that FESS_cluster1 can also search at the same time on the indexed documents on the index fess.YYYYMMDD of FESS_cluster2? 

See sample scenario below.
![Is Mutual Search Possible](https://user-images.githubusercontent.com/20873957/63911756-f3a5a800-ca5d-11e9-9ab3-5c27a30238a3.PNG)

I want to know if I can display the search results based on the indexed documents of FESS_cluster1 and FESS_cluster2. Is this scenario possible?

**Comment by marevol** [comment]
> By default, FESS searches on the index fess.YYYYMMDD, right?

Fess uses fess.search for searching and fess.update for indexing.

> Is it possible that FESS_cluster1 can also search at the same time on the indexed documents on the index fess.YYYYMMDD of FESS_cluster2?

Fess uses fess index on 1 elasticsearch cluster.

**Comment by seppjooo** [comment]
> Fess uses fess index on 1 elasticsearch cluster.

Is there a possibility to access the fess index of other elasticsearch cluster?

**Comment by seppjooo** [comment]
I was able to perform search on multiple clusters using remote clusters with elasticsearch cross-cluster setup. 

I also want to search multiple clusters with FESS. Is there a way on how to do this with FESS?

**Comment by marevol** [comment]
I'm not sure if alias is available for cross cluster search.

**Comment by seppjooo** [comment]
> I'm not sure if alias is available for cross cluster search.

This is my cross-cluster setup.
![image](https://user-images.githubusercontent.com/20873957/64161781-cb101a80-ce70-11e9-8d78-621d32211be3.png)

I tried assigning alias on remote cluster index but it does not let me assign it.
![image](https://user-images.githubusercontent.com/20873957/64160085-e3cb0100-ce6d-11e9-983e-b2c6cd1ecff4.png)

Does this mean that multi cluster search is not possible with FESS?

**Comment by marevol** [comment]
According to [Search multiple remote clusters](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-cross-cluster-search.html#ccs-search-multi-remote-cluster). it might work if changing `index.document.search.index` in fess_config.properties as below.

```
index.document.search.index=cluster2:fess.20190828
```

**Comment by seppjooo** [comment]
@marevol It actually works. Thank you very much!
