### ISSUE TITLE
indexing meta tags

### ISSUE THREAD

**Issue by maze13** [codelibs/fess#2237]
I crawl a site but the meta tags <meta name="description" .../> and  <meta name="keywords" .../> are not indexed and I cannot find the values when I search for it. How can I set this up?

I'm using fess 13.3

**Comment by marevol** [comment]
You can specify it in fess_config.properties by XPath:
```
crawler.document.html.content.xpath=//BODY
```

**Comment by maze13** [comment]
Thank you!
