### ISSUE TITLE
default sort order

### ISSUE THREAD

**Issue by markcamos** [codelibs/fess#2238]
If the General configuration parameter Default Sort Value is blank, what is the default search order of the results?

Also, does the number of clicks on a particular search result increase the score of that document?

**Comment by marevol** [comment]
The default is score.
You can add [ScoreFunctionBuilder](https://github.com/codelibs/fess/issues?q=addBoostFunction) in app.xml.

**Comment by marevol** [comment]
See [Similarity module](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-similarity.html#bm25).
