### ISSUE TITLE
Exclude specific URLs from results

### ISSUE THREAD

**Issue by markcamos** [codelibs/fess#2246]
I need to exclude any search results that contain http://ocvreinforcements.com 

I've added http://ocvreinforcements.com/* to Excluded URLs For Crawling and Excluded URLs For Indexing, but they still show up in search results. 

Is there a way to keep http://ocvreinforcements.com from showing up in search results?

**Comment by marevol** [comment]
`http://ocvreinforcements.com/.*`

**Comment by markcamos** [comment]
@marevol - I have these in Excluded URLs for Crawling and Excluded URLs for Indexing:
http://ocvreinforcements.com/.*
http://www.ocvreinforcements.com/.*
https://ocvreinforcements.com/.*
https://www.ocvreinforcements.com/.*

... and they still show up in the results. Do I need to add them somewhere else? Does fess need to be restarted after making these changes?

**Comment by markcamos** [comment]
![foamular](https://user-images.githubusercontent.com/5060332/64860769-1c9c7000-d5fc-11e9-9c62-7b862214dfcb.png)

**Comment by marevol** [comment]
Did you check fess-crawler.log?
You can check if they are crawled.

**Comment by markcamos** [comment]
The "Excludes" are the only thing that is in the fess-crawler.log. Is there a way to exclude these from the results, or not?

**Comment by marevol** [comment]
"Excluded URLs For Crawling" means crawler ignores URLs, so they do not show up in a search result.
Did you remove all docs in fess index before crawling?
Indexed docs are not removed until ttl is reached.

**Comment by markcamos** [comment]
Thank you for this explanation. I assumed that putting them in the exclude list would ALSO remove them from the index.

**Comment by markcamos** [comment]
What is "ttl" in this context?

**Comment by marevol** [comment]
See [Remove Documents Before](https://fess.codelibs.org/13.3/admin/general-guide.html#remove-documents-before).
