### ISSUE TITLE
Separate index for a specific crawl location

### ISSUE THREAD

**Issue by gabfields02** [codelibs/fess#2247]
The default search index and update index is fess.YYYYMMDD, right?

In my case, I wanted to create new search index and update index in FESS which I named fess_new_index. I set up my Crawl Configuration and it correctly crawled and indexed data into fess_new_index. It indexed 6 documents. However, when I perform a search, it shows a System Error.
Do I need to have FESS's mapping when creating fess_new_index? Any more idea about this so that it will not show an error? 

![FESS_10 Question](https://user-images.githubusercontent.com/55271708/65004122-df9ee900-d92d-11e9-903a-ad874d45c6fd.PNG)

Also, I tried having two update index with fess_config.properties as shown below. My goal for this is to have a separate index for a specific crawl location.
![FESS_10 Question_2](https://user-images.githubusercontent.com/55271708/65013907-75973b80-d94f-11e9-844a-7adca106f618.PNG)
However, when running FESS with this configuration, I get an error.  
Is it not possible to have two update index?

**Comment by marevol** [comment]
> Do I need to have FESS's mapping when creating fess_new_index?

Fess creates index and mappping at a startup time of Fess.

> Is it not possible to have two update index?

The number of an index for updating is only 1 index.

**Comment by seppjooo** [comment]
> The number of an index for updating is only 1 index.

Thank you for this information.


> Fess creates index and mappping at a startup time of Fess.

Would fess_new_index need to follow fess.YYYYMMDD mapping so that the indexed documents of fess_new_index can be searchable?

**Comment by gabfields02** [comment]
> The number of an index for updating is only 1 index.

Thank you for this information.

> Fess creates index and mappping at a startup time of Fess.

Would fess_new_index need to follow fess.YYYYMMDD mapping so that the indexed documents of fess_new_index can be searchable?

**Comment by marevol** [comment]
A mapping is required.

**Comment by seppjooo** [comment]
Thank you, @marevol! Will give update as soon as I can get this to work.

**Comment by gabfields02** [comment]
Thank you, @marevol! Will give update as soon as I can get this to work.

**Comment by gabfields02** [comment]
Hello @marevol,

Another question. I have this certain scenario:
I search for a certain file and it shows in the search results. After searching or clicking on that certain search result, I want to delete it from the Search Index. 
Is this possible with FESS?

**Comment by marevol** [comment]
No. For special requirements, [Commercial Support](https://www.n2sm.net/en/support/fess_support.html) supports them.

**Comment by gabfields02** [comment]
> No. For special requirements, [Commercial Support](https://www.n2sm.net/en/support/fess_support.html) supports them.

Thank you for this, @marevol.

**Comment by gabfields02** [comment]
Hello, @marevol. I have similar question again.
What about this scenario:
After clicking on a certain search result, I want to run an executable file.
Is this also a special requirement?

**Comment by marevol** [comment]
Yes.

**Comment by gabfields02** [comment]
Got it. Thank you, @marevol.
