### ISSUE TITLE
insensitive accent

### ISSUE THREAD

**Issue by rafael844** [codelibs/fess#2248]
Could someome lead me in how to use the asciifolding filter to make accent insensitive? like a search for "nao" and "não". Where and how should it configure it??
Im trying to figure it, but im starting with elasticsearch.

Thanks.

**Comment by marevol** [comment]
If you use Fess 13.3, the step is:

1. Download fess.json at [Backup](https://fess.codelibs.org/13.3/admin/backup-guide.html) page
2. Add `asciifoloding` into standard_analyzer in fess.json

```
        "standard_analyzer": {
          "type": "custom",
          "char_filter": [
            "mapping_filter"
          ],
          "tokenizer": "unigram_tokenizer",
          "filter": [
            "disable_graph",
            "asciifolding",
            "alphanum_word_filter",
```

3. Upload fess.json  at [Backup](https://fess.codelibs.org/13.3/admin/backup-guide.html) page
4. Start reindexing at [Maintenance](https://fess.codelibs.org/13.3/admin/maintenance-guide.html) page

**Comment by rafael844** [comment]
Perfect. Thanks.
