### ISSUE TITLE
Elastisearch not updated

### ISSUE THREAD

**Issue by luigigf49** [codelibs/fess#2250]
Hi Marevol,
I should interface a version of elasticsearch 5.x that I can't update otherwise I would have to upgrade the PHP application that uses this database.
Which version of Fess is compatible with Elasticsearch 5.x?

Thanks
Luigi

**Comment by marevol** [comment]
elasticsearch 5.x is EOLed.
For supported versions, see [Download](https://fess.codelibs.org/downloads.html) page.
