### ISSUE TITLE
FESS Environment Variables

### ISSUE THREAD

**Issue by gabfields02** [codelibs/fess#2252]
Hi @marevol,

I have a question about FESS's environment variables. Particularly this one.

![F_Item_11 Question](https://user-images.githubusercontent.com/55271708/65295594-6c4ae080-db94-11e9-9289-e5f440d751cd.PNG)

Is there a possibility or way to change the values for the Env Properties?

Also, there is Login functionality, but is there no Account Registration functionality in FESS?

**Comment by marevol** [comment]
They are just environment variables for your server.
I'm not sure what you want to do...

**Comment by gabfields02** [comment]
> I'm not sure what you want to do...

In separate relation to environment variables, I want to create accounts with different account types. Would it be possible with FESS?

**Comment by gabfields02** [comment]
Or is the Administrator account the only account type in FESS?

**Comment by marevol** [comment]
see #1981

**Comment by gabfields02** [comment]
@marevol Thank you. But I have another question.
I have this scenario:
I have an application that has login functionality. With FESS, I want to have feature restriction based on the login username from my application. Would this be possible with FESS?

**Comment by marevol** [comment]
Fess supports LDAP.

**Comment by gabfields02** [comment]
> Fess supports LDAP.

Does FESS also support anything else other than LDAP?

**Comment by marevol** [comment]
Azure, OpenIDConnect, SPNEGO are supported. If you need a support, please contact [Commercial Support](https://www.n2sm.net/en/support/fess_support.html).
https://github.com/codelibs/fess/blob/master/src/main/resources/fess_sso%2B%2B.xml

**Comment by gabfields02** [comment]
Thank you, @marevol!
