### ISSUE TITLE
how to see files in queue

### ISSUE THREAD

**Issue by rafael844** [codelibs/fess#2258]
Is there a way to see the files in queue? I have a folder and i noticed that its almost 7 days that the new files werent indexed. I would like to see if they are in queue to be. I noticed that  I have more than 700.00 files in queue, and its number dont decrease too much.
![Capturar](https://user-images.githubusercontent.com/31928478/65538119-0ab0ac00-dedd-11e9-931e-2ea6d26ddee9.PNG)

**Comment by marevol** [comment]
It's `.crawler.queue` index.
You can check indexed documents in it by elasticsearch query DSL.

If you stop crawler manually or the like, data in the queue remains.
To delete them, click `Clear .crawler indices` in [Maintenance](https://fess.codelibs.org/13.2/admin/maintenance-guide.html) page.
