### ISSUE TITLE
file crawling directory

### ISSUE THREAD

**Issue by heathmark012** [codelibs/fess#2267]
Hello @marevol. I want to retrieve the crawl directories of fess and use it for my application.

![Crawl Directory Question](https://user-images.githubusercontent.com/55779364/66536371-42f7f180-eb4f-11e9-94ab-6d642f068a7b.PNG)

I want to ask. From the crawling configuration, is there a way to dynamically get the list of crawling directories of fess? If yes, could the list of crawling directories be stored on a file?

**Comment by marevol** [comment]
No.

**Comment by heathmark012** [comment]
Ok thanks @marevol

**Comment by heathmark012** [comment]
Btw @marevol  would there be any other way to retrieve the crawling paths?

**Comment by marevol** [comment]
need more info...

**Comment by heathmark012** [comment]
I have an application that would need the directories crawled by FESS.
Below is a sample Crawling Configuration I have in FESS.

![CrawlDirectories](https://user-images.githubusercontent.com/55779364/67546591-5ef2ba00-f72f-11e9-91ce-f8548b94954e.PNG)

For my application, I would need to know all directories that are being crawled by FESS.

For this, I want to ask the following:
1. Could there be a physical file within FESS that I can refer to in order to know the directories crawled by FESS?
2. If the list of crawling directories is not stored on a file, is there any other way to know the directories crawled by FESS without manually checking the File Crawlers one by one?
3. Also, is there a possibility that the list of crawling directories is stored on a temporary directory?

**Comment by marevol** [comment]
Did you check fess-crawler.log?
Data is in an index in elasticsearch.

**Comment by heathmark012** [comment]
Thanks
