### ISSUE TITLE
about IndexNotFoundException[no such index

### ISSUE THREAD

**Issue by aisunny394** [codelibs/fess#2268]
Hello.
I useing Fess-13.3.1 and Elasticsearch-7.3.1 for a month.

One day, OutofMemory error was in the log.
Therefore,I changed the settings below and restarted the service.

・　「fess.in.bat」→「FESS_MAX_MEM 」
・　「fess_config.properties」→「-Xmx」、「-Xms」
※Both were set to 4GB
～～～Server Spec～～～
Physical memory：16GB
OS：Win 10 Pro
～～～～～～～～～～～

After changing the memory settings, the first restart was completed successfully and was ready for use.
After that, I tweaked the memory settings again and restarted.
Then,
On the Windows service management screen, you can see it running.
But, Could not access http: // localhost: 8080.
"404 Not Found"
I switched back the changes, but the problem didn't go away.

Please help me with causes, countermeasures, etc.
Thank you for reading.

～～～～～What I tried～～～～～
・　Stop using the external Elasticserch,
Switched to ES inside Fess.
・　Check the status with the following two commands.　※See attached file for details.
curl -XGET localhost:9200/_cat/health?v
curl localhost:9200/_cat/indices?v
・　Fess only, rebuild(Fess folder deletion & resetting)

～～～～Log overview～～～～
fess.log　※See attached file for details.
2019-10-11 09:54:00,684 [main] ERROR Failed to initialize Lasta Di.
org.lastaflute.di.exception.ContainerInitFailureException: Look! Read the message below.
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
Failed to initialize the container.
.........
[ESSR0060]Can not configure method(open) of org.codelibs.fess.es.client.FessEsClient, because [fess] IndexNotFoundException[no such index [fess]]
～～～～～～～～～～～～～～～

[191011_indecies.txt](https://github.com/codelibs/fess/files/3715776/191011_indecies.txt)
[health.txt](https://github.com/codelibs/fess/files/3715777/health.txt)
[fess.log](https://github.com/codelibs/fess/files/3715778/fess.log)

**Comment by marevol** [comment]
Where is OOM occured? It seems not to be in Fess...

**Comment by aisunny394** [comment]
Thank you for Reply.
This is the log when Fess was last running.
You can check the output of OOM.
[fess-crawler_再起動直前.log](https://github.com/codelibs/fess/files/3718184/fess-crawler_.log)
There was a problem after reboot after this log.
Prior to this, multiple OOMs were displayed from the "Fault URL" on the management screen.

Thank you.

**Comment by marevol** [comment]
I see.

> ・　「fess.in.bat」→「FESS_MAX_MEM 」

You do not need to change it.

> org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=illegal_argument_exception, reason=no write index is defined for alias [fess.update]. The write index may be explicitly disabled using is_write_index=false or the alias points to multiple indices without one being designated as a write index]

fess index seems to be broken.

**Comment by aisunny394** [comment]
What is the cause of index corruption?
This log was the first to see the error.
OOM itself was out before this.
Is there a way to fix the fess index?
I want to use it safely.

Thank you for your support.

**Comment by marevol** [comment]
[Reindex](https://fess.codelibs.org/13.4/admin/maintenance-guide.html#reindex) might fix it.

**Comment by aisunny394** [comment]
Thank you for your support.
I will study more.
