### ISSUE TITLE
Ubuntu16.04 cannot start fess.service

### ISSUE THREAD

**Issue by ZhouJiaJ** [codelibs/fess#2284]
I am on Ubuntu 16.04 and I've  installed OpenJDK 11 and elasticsearch-7.4.0.
elasticsearch.service started successfully.
But fess.service started failed and nothing in logs.
Here is my output:

root@OSS-Ubuntu-1:~# dpkg -i fess-13.4.0.deb
root@OSS-Ubuntu-1:~# systemctl start fess.service
root@OSS-Ubuntu-1:~# systemctl status fess.service 
● fess.service - Fess
   Loaded: loaded (/usr/lib/systemd/system/fess.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2019-10-23 10:26:29 CST; 2min 35s ago
     Docs: http://fess.codelibs.org/
  Process: 22122 ExecStart=/usr/share/fess/bin/fess (code=exited, status=1/FAILURE)
 Main PID: 22122 (code=exited, status=1/FAILURE)

Oct 23 10:26:29 OSS-Ubuntu-1 systemd[1]: Started Fess.
Oct 23 10:26:29 OSS-Ubuntu-1 systemd[1]: fess.service: Main process exited, code=exited, status=1/FAILURE
Oct 23 10:26:29 OSS-Ubuntu-1 systemd[1]: fess.service: Unit entered failed state.
Oct 23 10:26:29 OSS-Ubuntu-1 systemd[1]: fess.service: Failed with result 'exit-code'.

The logs are all empty.

root@OSS-Ubuntu-1:~# cat /var/log/fess/server_*
cat: '/var/log/fess/server_*': No such file or directory

Can anyone help with this?

**Comment by marevol** [comment]
Did you configure Java 11 with `update-alternatives`?

**Comment by ZhouJiaJ** [comment]
I installed Java 11 with command "ar zxvf OpenJDK11U-jdk_x64_linux_hotspot_11.0.4_11.tar.gz"

root@OSS-Ubuntu-1:~# java --version
openjdk 11.0.4 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)

**Comment by ZhouJiaJ** [comment]
I got it. It's the problem of Java Path.Thanks.
