### ISSUE TITLE
forEachOrdered() instead of forEach()

### ISSUE THREAD

**Issue by imaikazuki** [codelibs/fess#2292]
https://github.com/codelibs/fess/blob/d19f020cca1118bdfedf7c63bf950212305a3359/src/main/java/org/codelibs/fess/helper/WebFsIndexHelper.java#L278
https://github.com/codelibs/fess/blob/d19f020cca1118bdfedf7c63bf950212305a3359/src/main/java/org/codelibs/fess/helper/WebFsIndexHelper.java#L298

According to Java Stream API, [forEach()](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/stream/Stream.html#forEach(java.util.function.Consumer)) does not guarantee order. It's more safe and stable to use [forEachOrdered()](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/stream/Stream.html#forEachOrdered(java.util.function.Consumer)).

> For parallel stream pipelines, this operation does not guarantee to respect the encounter order of the stream

**Comment by marevol** [comment]
It's not parallel stream pipelines.
