### ISSUE TITLE
Errors with updated FESS source code

### ISSUE THREAD

**Issue by heathmark012** [codelibs/fess#2296]
Hello guys. I recently cloned fess with the updated one. Already imported it as a Maven project in Eclipse. However, I encountered errors. Might really need your help.

1. I get this error in several classes. Do i need to rebuild jar files for this?
`The package <package> is accessible from more than one module: <unnamed>, java.xml
`

2. Also, when running mvn:antrun (even with correct proxy settings), I get this error. The problem says something about adding cacert. Any ideas how I get to fix this?
` javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

**Comment by marevol** [comment]
What Java version do you use?

**Comment by heathmark012** [comment]
Java version "1.7.0_67"

**Comment by marevol** [comment]
See https://fess.codelibs.org/dev/getting-started.html#requirements

**Comment by heathmark012** [comment]
I now have Java 11 and Maven 3. 
Also tried changing the Compiler Compliance Level but it didn't work.

I still have the same errors. Any ideas what else I missed for the fix?

**Comment by marevol** [comment]
Do you use the latest version of eclipse?

**Comment by heathmark012** [comment]
@marevol Thanks. I think the latest version of Eclipse solved the issue.
