### ISSUE TITLE
[Windows Server]GET Office/PDF thumbnails

### ISSUE THREAD

**Issue by nakajimapanda** [codelibs/fess#2297]
Hi Author. Thank you for your great support.

I have built a Fess Server on Windows Server 2012.
Although File crawl is successful  , we cannot get thumbnails.

According the below manual, we understand Linux server can get thumbnails.
https://fess.codelibs.org/ja/13.4/config/thumbnail.html

Is it impossible to get these thumbnails on windows server even if we install imagemagick and so on?
#I installed imagemagick and set path. Although we can use convert command. it didn't work.

**Comment by marevol** [comment]
Linux environment uses [generate-thumbnail](https://github.com/codelibs/fess/blob/master/src/main/assemblies/files/generate-thumbnail).
To generate thumbnails, you need to create a script for Windows and change settings in [fess_thumbnail.xml](https://github.com/codelibs/fess/blob/master/src/main/resources/fess_thumbnail.xml).

**Comment by nakajimapanda** [comment]
Thank you for your swift reply.
I understand. I close this ticket.
