### ISSUE TITLE
The authority information of the AD group

### ISSUE THREAD

**Issue by nakajimapanda** [codelibs/fess#2302]
Hi Author. Very thanks for developing excellent system.

I would like to know about latest situation about  auth information of nested AD group.
I found this article said  Fess can handle nested AD group after FESS 12.2 version.
https://news.mynavi.jp/itsearch/article/devsoft/4569
  >Fess 12.2以降ではネストされたグループにも対応しています。

Although I tried to build  FESS 13.4.0 and I login with ldap/AD account,
all user's cannot get search results(there are no document.) even if the documents have group A permission.

Should we enable nested AD group option and so on? 
Could you tell us how to use nested AD group when we search?

(Example:Group A  has many groups.)
In this case, I hope user 1 can search documents of Group A and Group A-A .
Group A
 -- Group A-A
    --User1
    --User2....
 -- Group A-B
   --User3
    --User4...

I understand FESS did not have this function  on 10 Jan 2018.
https://github.com/codelibs/fess/issues/1428
https://github.com/codelibs/fess/issues/1561

**Comment by marevol** [comment]
Could you check if an user has expected permissions in audit.log?

**Comment by nakajimapanda** [comment]
Thank you for the response. I checked auditlog files.
It's seem to be right permission.(users have GroupA-A permission).

In addition, I confirmed some users logged in Windows OS and they can access documents of Group A permission.
 #Groupt A includes Groupe A-A and so on.

I expect latest FESS  handles nest group and users can search documents of GroupA.

What kind of causes could you think of?

**Comment by marevol** [comment]
Could you check `role` of a document in [Admin Search](https://fess.codelibs.org/13.4/admin/searchlist-guide.html) page?

**Comment by marevol** [comment]
See [Group Filter](https://fess.codelibs.org/13.4/admin/general-guide.html#id1).

**Comment by nakajimapanda** [comment]
Thank you for updating manual and the reply. I did it.
I close this question.
