### ISSUE TITLE
No description for configuring DropboxDataStore-Crawler

### ISSUE THREAD

**Issue by jobaudev** [codelibs/fess#2303]
Hi!

I have configured a DropboxDataStore-Crawler and it have access to dropbox. But there is no description for Script-Box. I want to show the name of the dropbox file in search results. My settings for Script-Box: 

url="http://localhost/"
host="localhost"
title=name
site="localhost"
last_modified=new java.util.Date()

groovy.lang.MissingPropertyException: No such property: name for class: Script1

 Please can you show an example how to set the attributes in the Script-Box?

**Comment by marevol** [comment]
Try the following settings:

Parameter
```
access_token=__your_token__
```
Script
```
url=file.url
title=file.name
content=file.contents
mimetype=file.mimetype
filetype=file.filetype
filename=file.name
content_length=file.size
last_modified=file.client_modified
```

**Comment by jobaudev** [comment]
Perfect, it works fine! Thx
