### ISSUE TITLE
Lost Indices? 

### ISSUE THREAD

**Issue by MeMeLwin** [codelibs/fess#2306]
Already crawled and perfectly worked for a while but suddenly cannot show result when searching....
Turns out the indices are lost... 
Re-crawling solved the current problem... 
But want to know the reason why indices are lost without manually deleting them...

**Comment by marevol** [comment]
Did you check [Remove Documents Before](https://fess.codelibs.org/13.4/admin/general-guide.html#remove-documents-before)?

**Comment by MeMeLwin** [comment]
General-> Remove Documents Before=3 days (default)
The window server which the fess is running was re-started due to window update...  
The indices are deleted after 3 days according to the "Remove Documents Before" setting.
I think understand the reason... 
Thank You 💃
