### ISSUE TITLE
OneNoteDataStore returns no content for notebook

### ISSUE THREAD

**Issue by jobaudev** [codelibs/fess#2313]
The crawler for OneNoteDataStore notebooks returns only metadata but no content. So no documents are added in Fess/Elasticsearch-database.

Parameter:
   tenant=xxx
   client_id=xxx
   client_secret=xxx
   site_note_crawler=true
   user_note_crawler=false
   group_note_crawler=false
Script:
   title = notebooks.name
   content = notebooks.contents
   created = notebooks.created
   last_modified = notebooks.last_modified
   url = notebooks.web_url
   role = notebooks.roles

The method page.getNextPage() in OneNoteDataStore.java:225 returns null, because the requestBuilder ist not filled in BaseColletionPage.getNextPage(). The reason is, in the response of Microsoft Graph Request the parameter 'nextLink' is not filled.

How can i get the content of notebooks and store OneNote data in fess/elasticsearch?

**Comment by marevol** [comment]
Fixed in fess-ds-office365 13.4.1.

**Comment by jobaudev** [comment]
it works fine, thanks a lot!
