### ISSUE TITLE
Elasticsearch licence policy and fess with other search engines

### ISSUE THREAD

**Issue by jobaudev** [codelibs/fess#2314]
Elasticsearch 7.4 has a hybrid license model which mixes free modules under Apache 2.0 License with  the proprietary Elastic License. So if we use Fess, we need Elastic License. Is this correct?

Q 1: Can we replace the Elasticsearch for Fess with Solr?
Q 2: Can we replace the Elasticsearch for Fess with Amazons free version of Elasticsearch 'Open Distro' (https://github.com/orgs/opendistro-for-elasticsearch/people)?
Q 3:  Is there an other Open Source alternative?

Thx a lot

**Comment by marevol** [comment]
> Q 1: Can we replace the Elasticsearch for Fess with Solr?

No.

> Q 2: Can we replace the Elasticsearch for Fess with Amazons free version of Elasticsearch 'Open Distro' (https://github.com/orgs/opendistro-for-elasticsearch/people)?

We do not test Fess on it... but I think it works.

> Q 3: Is there an other Open Source alternative?

See https://www.elastic.co/downloads/elasticsearch-oss
It includes only OSS features.

**Comment by jobaudev** [comment]
Thank you very much for the super fast response. I'm excited!
