### ISSUE TITLE
[Question]location of log files related SSO

### ISSUE THREAD

**Issue by nakajimapanda** [codelibs/fess#2318]
Hi Teams(and @marevol ). Thank you so much for supporting fess system.

I wonder if you could tell us where are SSO log files stored?
Should we change something to check any SSO setting errors?

According to the below article(it's so grateful),we confirmed we can login FESS(ver13) server with AD user.
https://news.mynavi.jp/itsearch/article/devsoft/4357

However, SSO doesn't work and we cannot find log files related SSO.
Could you tell us where are log files related SSO stored?
I would like to find root cause.

We have already done these.
 -Added SPN setting
 -Created files(krb5.conf,auth_login.conf ,fess_config.properties)
 -Checked JAVA version and client IE Settings

**Comment by marevol** [comment]
Did you change [log level](https://fess.codelibs.org/13.4/admin/general-guide.html#log-level) and then check fess.log?

**Comment by nakajimapanda** [comment]
Thank you for your swift reply.
Of course, I changed log level(ALL)   and checked fess.log .
However we couldn't find logs related SSO in fess.log?

Should we change web.xml and so on to start SSO auth?

**Comment by marevol** [comment]
Logs from JUL may not be stored at the moment.
It will be improved in a future release.

**Comment by nakajimapanda** [comment]
OK. Thank you for your response.
