### ISSUE TITLE
Thumbnail folder's are empty

### ISSUE THREAD

**Issue by ozgengures** [codelibs/fess#2324]
Hi, im crawling my website with WebDriverClient + phantomjs (because site contents filling with js). Result is perfect. But i have trouble with thumbnails (running in debug mode and i cant see any exception in logs) . "/thumbnails/etc/etc/etc" folders are created but inside is empty.
Then i tried crawling same page with default crawler(HcHttpClient) settings and thumbnails are created. 

my question is its known issue or where am i doing wrong?

**Comment by marevol** [comment]
We do not test thumbnails generation with WebDriverClient.
