### ISSUE TITLE
Change port 8080 to 80

### ISSUE THREAD

**Issue by AndresMartinezJuyar** [codelibs/fess#2325]
I can't use http acces in my site, if i don't entry for the port 8080 i can't use fess. I need your help, i'm new in fess and it configuration.

**Comment by AndresMartinezJuyar** [comment]
i can't use port 80

**Comment by marevol** [comment]
The port settings is in fess.in.[sh|bat].

**Comment by AndresMartinezJuyar** [comment]
Thanks, i know it, but change FESS_PORT=8080 to 80 and it dont work it.

**Comment by marevol** [comment]
Did you check log files? Debug level logs will be helpful.
