### ISSUE TITLE
fess duplicating content

### ISSUE THREAD

**Issue by rafael844** [codelibs/fess#2330]
Fess is duplicating all content of my folders after a while. Is there a way to stop this behavior? I set it to doesnt delete my files, but they are not being changed or anything else for being saved again.

**Comment by marevol** [comment]
need more info to reproduce it...

**Comment by rafael844** [comment]
My config and the info about one file. Tell me if more info is needed. Thank you.
![fess3](https://user-images.githubusercontent.com/31928478/70908187-5ad57100-1fe9-11ea-95a3-949f5018d47d.png)

![fess1](https://user-images.githubusercontent.com/31928478/70908193-5f018e80-1fe9-11ea-98c7-dde0bd1f41b5.png)
![fess2](https://user-images.githubusercontent.com/31928478/70908200-62951580-1fe9-11ea-80f6-21210d18b5e7.png)

**Comment by marevol** [comment]
Role 1administrator is different.
If a role is changed, Fess uses it as a different one.
