### ISSUE TITLE
Could not get Fess_crawler.log file

### ISSUE THREAD

**Issue by mizunokou520** [codelibs/fess#2335]
I am using Centos 8 to install fess 12.7 es6.8.5 JVM1.8.0_232
I did not get any error from fess in setting and I just setting simple file cralwer using file:/home/test
 and executing schedule -> Default Crawler.
I did not get any error. but when I searching some thing . There is nothing can be hit and there is no Fess_crawler.log even I set logging output to all.
Did I miss some thing?

**Comment by marevol** [comment]
If fess-crawler.log does not exist, I do not think Crawler runs.
It's better to check all log files.

**Comment by mizunokou520** [comment]
I got the reason Thank you 
I make some mistake on /etc/fess/fess_config.properties in comment out describing
