### ISSUE TITLE
score calculation unlogic and changes over time

### ISSUE THREAD

**Issue by maze13** [codelibs/fess#2336]
I crawl different domains with different crawlers (and different boost values). When I have a clean index and the crawler finished everything seems fine. That means the results with the higher boost are more relevant and have a higher score. But after some days the score seems to be calculated differently.
I found out that the score is calculated differently when using a filter or not. I made two screenshots. Each time it's a snippet of the first five results. Each time there are different sites in the results. There are always 115 results (beause of the wildcard filter).

Here you can see the results without a filter and the score like it shouldn't be. 
![score_behaviour_nofilter_blur](https://user-images.githubusercontent.com/10707490/70902054-42bb1d00-1ffc-11ea-8e24-b9d0c11075cf.png)

Here you can see the results with a filter (wildcard so the results are the same) and the score like it should be and was before the different calculation after some days. 
![score_behaviour_filter_blur](https://user-images.githubusercontent.com/10707490/70902056-42bb1d00-1ffc-11ea-9270-356efc92fbe5.png)

What causes the different calculation of the score? it is unlogical and non-transparent.

I am using fess 13.4.2.

**Comment by marevol** [comment]
See [Similarity module](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-similarity.html#bm25).
It depends on a query(filetype:* is one of queries).
