### ISSUE TITLE
wrong permissions 

### ISSUE THREAD

**Issue by AraGenji** [codelibs/fess#2338]
Hi, i have a nuber of files in a folder that inherit their permissions. But the files should not be deletable by a user so there is another rule there that denies the deletion of subfolders and files. But fess misinterprets this second rule for a complete deny of access.
![image](https://user-images.githubusercontent.com/57488201/71009454-8724e680-20ea-11ea-8d2f-72fcead5d417.png)

**Comment by marevol** [comment]
I think it does not show up at the moment. It'll be improved in a future release.

**Comment by AraGenji** [comment]
Thanks! I'm looking forward to that release.

**Comment by AraGenji** [comment]
is there a way to disable that fess gets the permissions from the filesystem?

**Comment by marevol** [comment]
It's in fess_config.properties.

    smb.role.from.file=true

**Comment by AraGenji** [comment]
Is there a way to disable this for a single Crawler?

**Comment by marevol** [comment]
This question was moved to [discuss.codelibs.org](https://discuss.codelibs.org/t/wrong-permissions/873/3).
