### ISSUE TITLE
crawled data in content are difference from fess12.3 to fess13.4

### ISSUE THREAD

**Issue by cross1154** [codelibs/fess#2360]
I did FS crawler job  with fess12.3 and fess13.4 to crawled same file(excel file),and found a little difference from [content] filed:
In fess12.3  [content] filed `"\"` is included.
In fess13.4  [content] filed `"\"` is disapeared.
Please see attached picture.
![fessVerUP](https://user-images.githubusercontent.com/12844468/72037601-ca353c80-32d9-11ea-9ab5-60e5a37c5474.jpg)

Is there something changed in  crawler function with version up?

**Comment by marevol** [comment]
What is a problem? A new version has a lot of fixes.
