### ISSUE TITLE
Can each file system crawl set encoding ? 

### ISSUE THREAD

**Issue by ji-ryoo** [codelibs/fess#2372]
hello.

I want to set the encoding for each file crawl setting.
i know default encoding is UTF-8.
So my FESS can crawl files of UTF-8 filename completely.
But it cannot crawl files of Shift-JIS filename.

ex.
org.codelibs.fess.exception.ContentNotFoundException: Not Found: file:/test/SJIS/%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD.txt

filenames has UTF-8,Shift-JIS,EUC-JP on our environment. 

Is there any way?
I didn't understand how to use configuration parameters of file crawl.

fess.version=13.4.2

**Comment by marevol** [comment]
Fess supports only UTF-8 filename.
