### ISSUE TITLE
Score Updater

### ISSUE THREAD

**Issue by maze13** [codelibs/fess#2373]
What does the Score Updater Job do? Is there a documentation?
Is there a way to see and understand the calculation of the score?

**Comment by marevol** [comment]
Score Updater updates a boost value of indexed documents to control a score value for searching them.
For example, you can boost more displayed documents with data of Google Analytics.
There is no documents for OSS at the moment...

**Comment by maze13** [comment]
Actually we don't have data from web analytics and so the boost is unaffected. Per default the Job "Score Updater" runs every hour. I have noticed that the score (boost) of documents changed between the Score Updater jobs (no other jobs, e.g. crawling jobs were running in this period of time). So back to my first question: What influences the result of the Score Updater Job? Are there any things that also influence the boost while running this job.

**Comment by marevol** [comment]
If you implements own ScoreBooster, it'll update document boost values with your own rules.

**Comment by maze13** [comment]
I didn't implement my own ScoreBooster, so the Job can be set to inactive?
As I wrote in the comment above I have noticed that the score (boost) of documents changed (only Score Updater jobs were running in this period of time!). What "job" could cause this?

**Comment by marevol** [comment]
What is changes for indexed documents? we need more details to reproduce it.

**Comment by marevol** [comment]
just in case, score is different from a boost value.

**Comment by maze13** [comment]
When I searched at different but close times the order of the documents and the score of the indexed documents changed. The boost stayed as it was set in the crawler settings. That change of the order was within two hours where only two Score Updater Jobs were running (every hour) why I thought that this was caused by the Score Updater Job.

For my understanding:
1. Score is not boost.
2. There is a job called Score Updater that updates the boost of documents (that influences the score?)
3. The job Score Updater doesn't change the boost of documents when nothing is changed of the default configuration?

**Comment by marevol** [comment]
I do not think ScoreUpdater affects the score if you do not set a custom ScoreBooster. See [ScoreUpdater](https://github.com/codelibs/fess/blob/master/src/main/java/org/codelibs/fess/score/ScoreUpdater.java). I think the cause is scheduled Merge process by elasticsearch. It changes scores by removing deleted documents.
