### ISSUE TITLE
How do I retrieve more than 10000 resultcount?

### ISSUE THREAD

**Issue by tukijaaliwa** [codelibs/fess#2379]
Hi @marevol

Is it able to get "allRecordCount" more than 10000?
Until fess ver12, allRecordCount returns over 10000, I think.

**Comment by tukijaaliwa** [comment]
I added wrong label.
Question is correct.

**Comment by marevol** [comment]
For questions, please see [discuss.codelibs.org](https://discuss.codelibs.org/c/FessEN/8).

**Comment by tukijaaliwa** [comment]
Thank you for your prompt reply.
I will try to refer to it.
