### ISSUE TITLE
question about fess's language detector

### ISSUE THREAD

**Issue by yuuiki** [codelibs/fess#2387]
Hi sorry to disturb,
I have a question about fess.
Does fess use standard analyzer for all indexed document?
or detect a proper language for a document before， and use different anaylazer for each document ?

I try fess 12.4 before, and learn about this feature from  https://github.com/codelibs/elasticsearch-langfield, but  this plugin not be used in 13.4 any more.

**Comment by marevol** [comment]
For questions, please see [discuss.codelibs.org](https://discuss.codelibs.org/c/FessEN/8).
