### ISSUE TITLE
ElasticsearchStatusException Solution?

### ISSUE THREAD

**Issue by tientmse62290** [codelibs/fess#2408]
Hi I got some problem with the log:
`

Thread Name | Crawler-KgdNXHAB3H2tRW5btIlD-1-3
-- | --
org.elasticsearch.ElasticsearchStatusException
ElasticsearchStatusException[Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]]at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177)at org.codelibs.elasticsearch.client.action.HttpAction.toElasticsearchException(HttpAction.java:138)at org.codelibs.elasticsearch.client.action.HttpSearchAction.lambda$execute$0(HttpSearchAction.java:48)at org.codelibs.curl.CurlRequest.lambda$execute$4(CurlRequest.java:220)at org.codelibs.curl.CurlRequest.lambda$connect$3(CurlRequest.java:199)at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)Suppressed: ElasticsearchException[hits is null.]... 9 moreSuppressed: org.codelibs.elasticsearch.client.action.HttpAction$CurlResponseException: {"error":{"root_cause":[],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[]},"status":503}

`
Anyone know how to fix it?

**Comment by marevol** [comment]
Please use [discuss.codelibs.org](https://discuss.codelibs.org/c/FessEN/).
