### ISSUE TITLE
In v3.6.0 created web crawler don't work

### ISSUE THREAD

**Issue by maze13** [codelibs/fess#2415]
When I create a new web crawler in fess v3.6.0, the crawler doesn't work:

> ...
> 2020-02-28 08:17:08,399 [main] INFO  Starting Crawler..
> **2020-02-28 08:17:08,438 [WebFsCrawler] INFO  No crawling target urls.**
> 2020-02-28 08:17:08,439 [main] INFO  Finished Crawler
> 2020-02-28 08:17:08,476 [main] INFO  [CRAWL INFO] CrawlerEndTime=2020-02-28T08:17:08.439+0000,CrawlerStatus=true,CrawlerStartTime=2020-02-28T08:17:08.400+0000,WebFsCrawlEndTime=2020-02-28T08:17:08.438+0000,CrawlerExecTime=40,WebFsCrawlStartTime=2020-02-28T08:17:08.423+0000
> 2020-02-28 08:17:08,482 [main] INFO  Destroyed LaContainer.

When I add the values of the web crawler to an existing web crawler (created before v3.6.0) the crawler works as expected.

**Comment by marevol** [comment]
Please use [discuss.codelibs.org](https://discuss.codelibs.org/c/FessEN/).
