### ISSUE TITLE
Unable to add labels to File Crawling

### ISSUE THREAD

**Issue by luigigf49** [codelibs/fess#2424]
Hi Marevol,

I updated my  FESS application to version 13.6 and I realized that there have been changes compared to version 12.3 regarding the definition of labels for File and Data Store crawlings.
From another user's post I realized that for Data Store crawlings I have to set up labels using scripts am I don't see how I can do the same thing with File Crawlings.

Many thanks

**Comment by marevol** [comment]
Please use [discuss.codelibs.org](https://discuss.codelibs.org/c/FessEN/).
