### ISSUE TITLE
How to open url from local file (from local disk) directly under fess and not from fileserver?

### ISSUE THREAD

**Issue by Rick978** [codelibs/fess#2429]
Hello,

after adding 3 websites, we want to search also our local files (from our local disk of pc), because we dont have something like a fileserver or that.

We used fscrawler to add data from local filesyste of Windows 10 to elasticsearch. Then we used fess-elasticsearch plugin to add them from elasticsearch into Fess. 

The result of the indexed document in fess.XXX index looks as follows: 
`{
        "_index" : "fess.20200312",
        "_type" : "_doc",
        "_id" : "97d1ee502540fe0fdd363c418a5dc159ed6d555ecf338ffcfb89b21d3180de07118864811ff4ec513e196f8e43227a2d6d3477a07ab5e31f25e07affc79625b7",
        "_score" : 1.0,
        "_source" : {
          "filetype" : "pdf",
          "expires" : "2020-03-15T07:47:55.334Z",
          "role" : [
            "1rh"
          ],
          "created" : "2018-10-04T09:04:50.000+0000",
          "click_count" : 1,
          "title" : "Exercise07.pdf",
          "doc_id" : "7a4d56589d1548af9ef8d2a3d31fb065",
          "content" : "\n\n\nPTC Academic Program \n\nHow to Model Almost Anything   164 \n \n\nConcept Development \nDESIGNING AND CREATING NEW PART GEOMETRY \n\nDesigning a New Product \nDesigning a new product allows you to be creative.",
          "url" : "file:/C:\\Users\\RH\\Downloads\\How_to_model_almost_anything\\How_to_model_almost_anything\\How_to_model_almost_anything\\Exercise07.pdf",
          "site" : "C:\\Users\\RH\\Downloads\\How_to_model_almost_anything\\How_to_model_almost_anything\\How_to_model_almost_anything\\Exercise07.pdf",
          "config_id" : "Do3efgXAB149iB2w4iXAE",
          "anchor" : "",
          "segment" : "o3efgXAB149iB2w4iXAE",
          "digest" : "",
          "boost" : "1.0",
          "favorite_count" : 0,
          "mimetype" : "application/pdf",
          "lang" : "en",
          "last_modified" : "2019-10-15T13:56:42.074+0000",
          "virtual_host" : [ ]
        }
      }`

The problem now is that it isnt possible to open the url from our local files.
![image](https://user-images.githubusercontent.com/61418116/76499967-fe46ee00-643f-11ea-80f3-9063bac73ddb.png)

If i click on the url this links tries to open:
`http://100.0.40.7:8080/go/?rt=1584000134549&docId=7d9453cc3cbd4e51bb0e8d87df1343de&queryId=072904cbebfc4e04a6d6f64388540df5&order=0`

There I received an error that the page isnt available.

Is there a way to open this url:
`file:/C:\\Users\\RH\\Downloads\\How_to_model_almost_anything\\How_to_model_almost_anything\\How_to_model_almost_anything\\Exercise07.pdf` from local files directly?

Thanks.

**Comment by marevol** [comment]
Please use [discuss.codelibs.org](https://discuss.codelibs.org/c/FessEN/).

**Comment by Rick978** [comment]
I will do, thanks.
