### ISSUE TITLE
The search result of the user who belongs to Domain Users and the file access result of that user are different.

### ISSUE THREAD

**Issue by GodPhwng** [codelibs/fess#2446]
Fess Version : Fess 13.6.3

■Fess Administrator Guide LDAP Setting
Account Filter : (&(objectClass=user)(sAMAccountName=%s))
Group Filter : 
memberOf : memberOf

When a user who belongs to a domain user logs in, the "Domain Users" group authority cannot be obtained.
As a result, the accessible files do not appear in the search results.
The cause is expected to be as follows.
https://social.technet.microsoft.com/Forums/exchange/ja-JP/3d8583fe-eddc-4dcc-9f28-d818f8cc81c0/memberof-domain-users-?forum=winserver8

Please tell me how to resolve.
Also, can it be solved by modifying the Fess side?

I need you help.

**Comment by marevol** [comment]
Please use [discuss.codelibs.org](https://discuss.codelibs.org/c/FessEN/).

**Comment by GodPhwng** [comment]
Thank you!
