### ISSUE TITLE
Docker restart not working

### ISSUE THREAD

**Issue by flozi00** [codelibs/fess#2475]
(_Please see [discuss.codelibs.org](https://discuss.codelibs.org/c/FessEN/8) before filing a bug._)

**Describe the bug**
After restarting the docker container, the elasticsearch is not reachable anymore

**To Reproduce**
Install the docker container, then just reload / restart it.

**Expected behavior**
The whole server restarts correctly
**Screenshots**

**Environment (please complete the following information):**
ubuntu, plesk docker extension

**Comment by marevol** [comment]
Please use [discuss.codelibs.org](https://discuss.codelibs.org/c/FessEN/).
