### ISSUE TITLE
"Please advise on access for SAML protected sites from search engine crawl process"

### ISSUE THREAD

**Issue by lewisdonofrio** [codelibs/fess#2482]
I have many sites (129+) behind SAML authentication and so far I can only perhaps 'ask' webmasters to enable NTML or just make a copy (excludes CMS) of the site and lock it down to ip's and leave it open to unauthenticated users but that seems like a lot to ask with more and more sites that seem to forget about the issues that using JavaScript navigation causes to things like search engines and non-browsers (wget/curl) access.

**Comment by marevol** [comment]
Please use [discuss.codelibs.org](https://discuss.codelibs.org/c/FessEN/).
