### ISSUE TITLE
sun.jnu.encoding

### ISSUE THREAD

**Issue by koichi-ueno** [codelibs/fess#2509]
(_Please use [discuss.codelibs.org](https://discuss.codelibs.org/c/FessEN/8) before filing a bug._)

**Describe the bug**
On Ubuntu 20.04 Server (default-jdk), see System Property
sun.jnu.encoding=ANSI_X3.4-1968
On Ubuntu 18.04 Server (default-jdk), see System Property
sun.jnu.encoding=UTF-8

**To Reproduce**
Install Ubuntu 20.04 Server
set locale to LANG=ja_JP.UTF-8
install default-jdk
install elasticsearch 7.9.3-amd64
install fess 13.9.3

**Expected behavior**
System Property: sun.jnu.encoding=UTF-8

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.1 Server

**Additional context**

**Comment by marevol** [comment]
What version is Java? Please check fess.log.

**Comment by koichi-ueno** [comment]
Ubuntu 20.04 default-jdk -> the version is 11.
sorry, I already delete 20.04 and install 18.04 fess is very good running on 18.04.

**Comment by marevol** [comment]
I need more info...
How do you check the value?

**Comment by koichi-ueno** [comment]
I checked the value on web browser.
-> System Information -> System Property

**Comment by marevol** [comment]
What is a problem in this setting?
I do not think sun.jnu.encoding affects Fess.

**Comment by koichi-ueno** [comment]
In this setting, crawler is fail in path with japanese character.

**Comment by marevol** [comment]
I tried Fess 13.10 on Azure(Canonical:0001-com-ubuntu-server-focal:20_04-lts-gen2latest image) with default-jdk, but it was not reproduced...
It is sun.jnu.encoding=UTF-8.

**Comment by koichi-ueno** [comment]
OK. It's may not Fess problem, and will be OS setting problem.
I'll try 20.04 in time.
Thank you !

**Comment by koichi-ueno** [comment]
I tried again and get same result.
sun.jnu.encoding=ANSI_X3.4-1968
/var/log/fess/fess.log
---------------------------------------
nothing wrote. size=0.
---------------------------------------

/var/log/fess/server_0.log
---------------------------------------
Jan 26, 2021 5:59:14 AM org.dbflute.tomcat.logging.BootLogger info
INFO: ...Booting the Tomcat: port=8080 contextPath=
Jan 26, 2021 5:59:14 AM org.dbflute.tomcat.logging.BootLogger info
INFO: ...Reflecting configuration to server: config=[tomcat_config.properties]
Jan 26, 2021 5:59:14 AM org.dbflute.tomcat.logging.BootLogger info
INFO:  tomcat.URIEncoding = UTF-8
Jan 26, 2021 5:59:14 AM org.dbflute.tomcat.logging.BootLogger info
INFO:  tomcat.useBodyEncodingForURI = true
Jan 26, 2021 5:59:15 AM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-8080"]
Jan 26, 2021 5:59:15 AM org.apache.catalina.core.StandardService startInternal
INFO: Starting service [Tomcat]
Jan 26, 2021 5:59:15 AM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet engine: [Apache Tomcat/9.0.41]
Jan 26, 2021 5:59:15 AM org.dbflute.tomcat.logging.BootLogger info
INFO: ...Initializing webapp of default web.xml with JSP (the servlet found)
Jan 26, 2021 5:59:16 AM org.apache.catalina.startup.ContextConfig getDefaultWebXmlFragment
INFO: No global web.xml found
Jan 26, 2021 5:59:27 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-nio-8080"]
Jan 26, 2021 5:59:27 AM org.dbflute.tomcat.logging.BootLogger info
INFO: Boot successful: url -> http://localhost:8080
---------------------------------------

**Comment by koichi-ueno** [comment]
on ubuntu 20.04.1 KVM virtual-machine
elasticsearch-7.10.2
fess-13.10.2

**Comment by koichi-ueno** [comment]
Property of BUGREPORT
----------------------------------------------------
file.separator=/
file.encoding=UTF-8
java.runtime.version=11.0.9.1+1-Ubuntu-0ubuntu1.20.04
java.vm.info=mixed mode, sharing
java.vm.name=OpenJDK 64-Bit Server VM
java.vm.vendor=Ubuntu
java.vm.version=11.0.9.1+1-Ubuntu-0ubuntu1.20.04
os.arch=amd64
os.name=Linux
os.version=5.4.0-64-generic
user.country=US
user.language=en
user.timezone=Etc/UTC

**Comment by marevol** [comment]
We have no plan to fix this problem because it's not reproduced. Please add the setting to your environment. You can add them to /etc/fess/fess_config.properties and /usr/share/fess/bin/fess.

**Comment by koichi-ueno** [comment]
solved ! The problem is environment.
on initial install,
# locale -a
C
C.UTF-8
ja_JP.utf8
POSIX
---> not exist en_US.UTF-8
when add to locale-gen file, sun.jnu.encoding is set collectly!
Thank you very much.
