### ISSUE TITLE
Reset Password 

### ISSUE THREAD

**Issue by scheiblr** [codelibs/fess#2515]
Hi, 

I found an answered issue how to reset the admin password for older fess versions (#921, #1520), but it doesn't work with fess 13.
How is that possible, if the admin password got lost?

**Comment by marevol** [comment]
Please use [discuss.codelibs.org](https://discuss.codelibs.org/c/FessEN/).

**Comment by scheiblr** [comment]
Thanks, opened an issue here: https://discuss.codelibs.org/t/reset-admin-password/1429
