### ISSUE TITLE
SSL Verification fails

### ISSUE THREAD

**Issue by davidhoelzel** [codelibs/fess#2516]
Imported a Certificate into Java Cert-Store for a site to be crawled.
Connection is successful when testing with https://confluence.atlassian.com/kb/files/779355358/779355357/1/1441897666313/SSLPoke.class:
`root@6998c5fc5f35:/usr/share/fess# java SSLPoke www.my-domain.com 443
Successfully connected`

Nevertheless, FESS still complains about the certificate:
` Failed to access to https://www.my-domain.com/; I/O exception(PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target): https:///www.my-domain.com/en-us/; I/O exception(PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target): https:///www.my-domain.com/en-us/; I/O exception(PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target): https:///www.my-domain.com/en-us/; I/O exception(PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target): https:///www.my-domain.com/en-us/; I/O exception(PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target): https:///www.my-domain.com/en-us/`

Before importing the certificate into to cert-store of Java, Java had the same error.

Seems like FESS is using some different mechanic to establish an SSL Connection. Is there any way to solve this?

**Comment by marevol** [comment]
Please use [discuss.codelibs.org](https://discuss.codelibs.org/c/FessEN/).

**Comment by etlweather** [comment]
If anybody else arrives here to find a solution, you can find it here: https://discuss.codelibs.org/t/how-to-crawl-site-with-self-signed-cert/1495/3
