### ISSUE TITLE
I want .html file after crawling Data Store(DBMS).

### ISSUE THREAD

**Issue by Black-20191211** [codelibs/fess#2528]
But, html file isn't create.
I attached fess-crawler.log and picture of config, searched result.

Please teach me how to do.

![20210210](https://user-images.githubusercontent.com/58764902/107469430-10c82b00-6bad-11eb-90b3-819dad3d480d.png)
![Data_Store_Crawling_Configuration](https://user-images.githubusercontent.com/58764902/107469434-11f95800-6bad-11eb-9f02-51178ee94804.PNG)
[fess-crawler.log](https://github.com/codelibs/fess/files/5956044/fess-crawler.log)

**Comment by marevol** [comment]
Please use [discuss.codelibs.org](https://discuss.codelibs.org/c/fessen/).
