### ISSUE TITLE
Request *** does not support having a body

### ISSUE THREAD

**Issue by tobiasschaeferptb** [codelibs/fess#2539]
Hello,

I have a fresh installed Fess 13.10.4 with Elasticsearch 7.11.1.
When I try to delete or optimize or do any other operation on the fess index I get this error:
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "request [POST /fess.20210305/_forcemerge] does not support having a body"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "request [POST /fess.20210305/_forcemerge] does not support having a body"
  },
  "status": 400
}
I think this is caused by a change of the API of elasticsearch with version 7.11.
Have a look at this issue https://github.com/elastic/elasticsearch/issues/69532

Best regards,
Tobias

**Comment by marevol** [comment]
Thank you for the info, but Fess 13.10 does not support elasticsearch 7.11.
