### ISSUE TITLE
Thumbnail files in /tmp folder

### ISSUE THREAD

**Issue by tobiasschaeferptb** [codelibs/fess#2543]
Hello,

I noticed that the thumbnail generator creates many files in the /tmp folder but doesn't delete them afterwards.
Is it possible that FESS takes care of deleting those unnecessary files?

Best regards,
Tobias Schaefer

**Comment by marevol** [comment]
Please use [discuss.codelibs.org](https://discuss.codelibs.org/c/fessen/).
