### ISSUE TITLE
Exclude pages from being indexed

### ISSUE THREAD

**Issue by Anders-Bergqvist** [codelibs/fess#2607]
Hi!

I've tried to exclude all pages with paging such as `https://www.oru.se/english/news/?page=4`
I've put java regexp in "Excluded URLs For Indexing" and tried:
`.*\?page=\d{1,4}$` 

Is that correct and how can i see if that worked. In `crawler.log` I can only see "Excluded URL:" and thats the url:s in "Excluded from crawling not excluded from indexing, right?

**Comment by marevol** [comment]
Please use https://discuss.codelibs.org/c/FessEN/
