### ISSUE TITLE
Create Label

### ISSUE THREAD

**Issue by sweetyblack000** [codelibs/fess#2656]
Hello,
I want to create new label for thai language using unicode, but fess label support Value must match "^[a-zA-Z0-9_]+$" missing \ for unicode support.
Example word โทรศัพท์ is \u0e42\u0e17\u0e23\u0e28\u0e31\u0e1e\u0e17\u0e4c

Could you suggest me ?

**Comment by marevol** [comment]
https://discuss.codelibs.org/c/fessen/
