### ISSUE TITLE
Web Crawling issue

### ISSUE THREAD

**Issue by vinothitg** [codelibs/fess#2724]
Hi Team,

I have created web crawl for this website `https://jinfo-test.jnn-planet.com/jnnservices/servlet/jnninfo/login`

Below configuration was configured by me.
Web Crawl:
![image](https://user-images.githubusercontent.com/127812592/224881647-104d71af-4cba-4672-85c4-640cedbcf2e7.png)
![image](https://user-images.githubusercontent.com/127812592/224881734-e7ae959f-6ac7-42f1-ae04-cab7a42d80c9.png)

Web Authentication:
![image](https://user-images.githubusercontent.com/127812592/224881857-851bac86-f0c4-4671-a37b-5d04a54bcdb0.png)

I received only below result.
![image](https://user-images.githubusercontent.com/127812592/224882024-94bb64e8-78fb-44ea-956d-3ff5cad64bdf.png)

Please advice this is correct configuration, I can`t crawl inside website. please advice.

**Comment by marevol** [comment]
I think it's a problem about the configuration.

**Comment by vinothitg** [comment]
Could you please correct the configuration. I follow the same procedure using this link `https://fess.codelibs.org/9.1/admin/webCrawlingConfig-guide.html`. please advice.

**Comment by vinothitg** [comment]
[fess-crawler (9).log](https://github.com/codelibs/fess/files/10975543/fess-crawler.9.log)
Attached log file also.
