### ISSUE TITLE
DO NOT CREATE ME

### ISSUE THREAD

**Issue by robin-human** [codelibs/fess#2741]
HI,this is a exciting project , I have been used the custorm field successful,it works very well ,then I want to copy the custom field message to the "content" ,it dosen't work .

the doc.json writed like this :
![image](https://user-images.githubusercontent.com/9818879/235442700-c760abe9-7246-4f5a-87dc-fe8cb1e0cf9d.png)
the fess.config.properties writed like this :
![image](https://user-images.githubusercontent.com/9818879/235443347-f76e0de2-ac97-477e-98ed-345c8ccb9521.png)

Following the author's [advice(),](https://discuss.codelibs.org/t/custom-field-and-doc-boost/1844/2) I changed the above configuration and restarted Fess, but it still couldn't work properly. This problem has been bothering me for more than two days. I kept trying and searched through the Fess forum, but there is little information on this topic. Up until now, I have not been able to solve it and I am looking forward to the author's help. Thank you very much!

the author's another advice:
1)Add a custom field to [doc.json 4](https://github.com/codelibs/fess/blob/fess-14.2.0/src/main/resources/fess_indices/fess/doc.json)
2) Reindex on [Maintenace](https://fess.codelibs.org/14.2/admin/maintenance-guide.html) page
3) Add the field name to [query.additional.search.fields](https://github.com/codelibs/fess/issues/new?assignees=&labels=&template=question.md&title=DO+NOT+CREATE+ME#L449) in fess_config.properties
4) Restart Fess

the Fess forum's subject about this ,but it doesn't work.
[](https://discuss.codelibs.org/t/question-additional-content-for-search-term/847)

I need your help ,thans a lot !

**Comment by marevol** [comment]
Please use forum.
