### ISSUE TITLE
WebCrawler returns no results

### ISSUE THREAD

**Issue by andionita** [codelibs/fess#2773]
Dear FESS-developers/-users,

I have just started using version 14.10 and cannot get any results from the web crawler. Please see my crawler configuration below.

![fess_crawler_config](https://github.com/codelibs/fess/assets/29715624/89108651-319a-4623-9668-bb5a8df44d3e)

Under System Infos > Crawling Infos > Session-ID there are no results listed. fess-crawler.log does not offer any further hints. 

`{"@timestamp":"2023-10-13T10:33:41.588Z","log.level": "INFO","message":"Target URL: https://press.un.org/en/content/press-release", "ecs.version": "1.2.0","service.name":"fess","event.dataset":"crawler","process.thread.name":"WebFsCrawler","log.logger":"org.codelibs.fess.helper.WebFsIndexHelper"}

{"@timestamp":"2023-10-13T10:33:41.589Z","log.level": "INFO","message":"Included URL: https://press\\.un\\.org/en/2023/\\w+\\.doc\\.htm", "ecs.version": "1.2.0","service.name":"fess","event.dataset":"crawler","process.thread.name":"WebFsCrawler","log.logger":"org.codelibs.fess.helper.WebFsIndexHelper"}

{"@timestamp":"2023-10-13T10:33:41.590Z","log.level": "INFO","message":"Excluded URL: (?i).*(css|js|jpeg|jpg|gif|png|bmp|wmv|xml|ico|exe)", "ecs.version": "1.2.0","service.name":"fess","event.dataset":"crawler","process.thread.name":"WebFsCrawler","log.logger":"org.codelibs.fess.helper.WebFsIndexHelper"}
`
I carefully read through the documentation and some other related issues, but that did not help. Do have any ideas about what is going wrong? Any help would be appreciated. 

Thank you in advance

Andrei

**Comment by marevol** [comment]
Please use https://discuss.codelibs.org/c/fessen/

**Comment by andionita** [comment]
Thank you for the hint. Moved question here
https://discuss.codelibs.org/t/webcrawler-returns-no-results/2269 

[fess-crawler.log](https://github.com/codelibs/fess/files/12895350/fess-crawler.log)
