### ISSUE TITLE
管理UIにアクセスしてもページが開きません

### ISSUE THREAD

**Issue by terufu** [codelibs/fess#2781]
初めてFessの環境構築をしているところです。
「素早く Fess に触れてみたい人向け」という事で、下記サイトから環境の構築を試みました。
https://fess.codelibs.org/ja/quick-start.html

ところが、上記ページの上から順に設定しているのですが、「管理 UI にアクセス」のところで、下記URLが開かず困っています。
http://localhost:8080/admin

外部にはつながっていないローカルPCで試しています。
Apacheは、いつも使用しているXAMPPで起動していて、Fess以外の他のWEBサイトは開くので、起動中なのは間違いないです。

私は開発ではなく営業なので、XAMPPも詳しくなくデフォルトのままで使用しています。
各サイトのフォルダは、htdocsの直下にあるので、Fessも同様にしました。
ただ、気になるのはFessフォルダの中には、index.html 等に相当するファイルがありません。
フォルダ構成が間違っているのでしょうか。
ご教授いただけますと幸いです。

**Comment by marevol** [comment]
Please use https://discuss.codelibs.org/
