### ISSUE TITLE
Broken dashboard layout (elasticsearch-kopf) in IE11

### ISSUE THREAD

**Issue by kitakita** [codelibs/fess#348]
Server: Windows 10 with JDK8u66
Client: Windows 10
Browser: IE11

IE11 の場合、以下のようにダッシュボードの kopf の部分で CSS が読み込まれていないように見えます（開発者ツールで見るとスタイルの項目が空っぽでした）。Edge や Google Chrome では正常に表示されました。

個別に立てた elasticsearch に kopf プラグインを入れた場合は IE11 でも正常に表示されるので、FESS 側で何か起きているのでは無いかと思っています。

![default](https://cloud.githubusercontent.com/assets/207338/12225754/a44b16ce-b854-11e5-9cc3-780f65555a81.PNG)

補足ですが、開発者ツールで当該 CSS `kopf.css` の通信状態を見ると、サーバーから 200 OK で返却されているものの、応答の Body が空になっていました（以下図）。
しかし、対象の URL を IE11 で直接叩くと、CSS の内容が表示されます。

![2](https://cloud.githubusercontent.com/assets/207338/12225826/23630330-b856-11e5-984b-3e9daf399953.PNG)

**Comment by marevol** [comment]
It will be fixed in GA release.
