### ISSUE TITLE
#index docs decreasing after adding/starting crawler (jobs)

### ISSUE THREAD

**Issue by zopyx** [codelibs/fess#418]
I had about 1.8 million docs indexed. I added two more web crawlers and related crawl jobs. Checking the dashboard revealed that the number of indexed docs went down to 600.000 items...what is happening here?

**Comment by marevol** [comment]
In General page, you can set document TTL at Remove Documents Before field.
If removing TTL, set it to -1.

**Comment by attibalazs** [comment]
Hi, i checked the help for the ,"Remove Documents Before" field i`m not exactly sure what this means.
The help states only: "Days which old documents are removed." Can you provide more detail please?

**Comment by marevol** [comment]
It's TTL for documents.
If indexed documents is not updated, they are removed.
