### ISSUE TITLE
Is there a docker image of fess?

### ISSUE THREAD

**Issue by kujiy** [codelibs/fess#424]
Hi. I'd like to try using fess but don't have enough time to make an environment.
Is there a useful docker image which has all required softwares of fess?

**Comment by marevol** [comment]
We are working on this task now.
We will provide it in the near future...

**Comment by monaka** [comment]
Yesterday I run Fess in Docker. https://github.com/monami-ya/fess/tree/docker
Hope it helps you.

**Comment by kujiy** [comment]
Thanks @monaka, I'll try with that :grinning:

**Comment by nullpos** [comment]
Hi @kujiy . This is their official docker image on Docker hub :) 
https://hub.docker.com/r/codelibs/fess/

**Comment by kujiy** [comment]
@nullpos Thank you so much! I will change our base image to yours!

And sorry for my late @monaka, your image helped us a lot. We've been using fess for five months and my team members really likes it. We will keep using fess with our core service. Fess is awesome!!
