### ISSUE TITLE
How to restore settings via Web UI?

### ISSUE THREAD

**Issue by monaka** [codelibs/fess#428]
My Fess's version is 10.0.2.
I see how to get setting backups via Web console.
But I failed to find the page for restore them.
Where Is the page for restoring?

**Comment by marevol** [comment]
At the moment, Restore UI does not exist.
We will provide it in the future release.
Backup file is a bulk json file for Elasticsearch.
So, you can use Elasticsearch's Bulk API:
https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html
For example, 

    curl -XPOST localhost:9201/_bulk -d @fess_config.json

**Comment by monaka** [comment]
It's enough convenient for me using Bulk API.
Thank you for your support.  I close this issue.
