### ISSUE TITLE
Custom language support

### ISSUE THREAD

**Issue by andreierdoss** [codelibs/fess#489]
Hello,

How can I customize Fess to index correctly Romanian language sites? I would like to replace the Japanese specific files with the Romanian ones.

Thank you

**Comment by marevol** [comment]
Please see https://github.com/codelibs/fess#localization

**Comment by andreierdoss** [comment]
Thank you for the response. 

What would I have to do for Kuromoji equivalent?

Where is the synonyms dictionary being used?

**Comment by marevol** [comment]
> What would I have to do for Kuromoji equivalent?

Analyzers for each languages affect search quality.
For reference to create an analyzer, Solr uses https://github.com/apache/lucene-solr/blob/master/solr/example/files/conf/managed-schema
You can create the analyzer definition from Solr's one.

> Where is the synonyms dictionary being used?

synonym data is in .configsync index.

**Comment by andreierdoss** [comment]
I want to use the Romanian Elasticsearch's analyzer. How do I configure this?

**Comment by marevol** [comment]
Analyzer: https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-analyzers.html
synonym file: https://www.elastic.co/guide/en/elasticsearch/reference/2.3/analysis-synonym-tokenfilter.html#_solr_synonyms

**Comment by andreierdoss** [comment]
Thank you. I updated fess.json and also doc.json for Romanian. Does this look ok? Am I missing something?

https://gist.github.com/andreierdoss/a601d20bd14207f9f6f314f47297d6a5

**Comment by andreierdoss** [comment]
I edited doc.json and fess.json files as you see above (https://gist.github.com/andreierdoss/a601d20bd14207f9f6f314f47297d6a5), but these changes are not reflected in the fess index. How would I go about making these changes take effect?

**Comment by marevol** [comment]
The index is created at startup phase if it does not exist.
So, please delete old fess index.
