### ISSUE TITLE
Fess fails after first request is sent

### ISSUE THREAD

**Issue by mprpic** [codelibs/fess#499]
Hi! I wanted to try out Fess so I installed it on a Fedora VM along with elasticsearch (all according to your instructions in the docs), started it and the request to reach localhost:8080/admin would just time out. After that, the service reported the following error:

    May 06 13:40:30 example.com fess[20800]: Caused by: java.lang.ClassNotFoundException: Illegal access: this web application instance has been stopped already. Could not load [org.elasticsearch.transport.TransportService$TimeoutInfoHolder]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
    May 06 13:40:30 example.com fess[20800]: at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1343)
    May 06 13:40:30 example.com fess[20800]: at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1206)
    May 06 13:40:30 example.com fess[20800]: at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1167)

Here is a paste of the fess.log file entry: https://paste.fedoraproject.org/363380/ and something also seems to fail and get logged in elasticsearch.log: https://paste.fedoraproject.org/363385/. I'm using:

    $ rpm -q fess
    fess-10.0.3-1.noarch
    $ rpm -q elasticsearch
    elasticsearch-2.3.2-1.noarch

Any ideas what my be wrong with my setup? Thanks!

**Comment by marevol** [comment]
Please use elasticsearch 2.2.x.
Fess 10.1 will support elasticsearch 2.3.x.
