### ISSUE TITLE
proxy setting

### ISSUE THREAD

**Issue by ndrwchn** [codelibs/fess#511]
Hi,

I always got 'connection refused'. If Fess behind proxy server, is it necessary to setup proxy? Or it is ok to use OS's setting as default?

Thanks!

**Comment by ndrwchn** [comment]
log:

org.codelibs.fess.crawler.exception.CrawlingAccessException: Connection time out(Connect to xx.xx.com:80 [xx.xx.com/xx.xx.xx.xx] failed: Connection refused: connect): http://xx.xx.com/search/
at org.codelibs.fess.crawler.client.http.HcHttpClient.processHttpMethod(HcHttpClient.java:745)

**Comment by marevol** [comment]
Could you put the following settings to Config Parameters for Crawling Config?

    client.proxyHost=hostname
    client.proxyPort=1234

http://fess.codelibs.org/10.0/admin/webconfig-guide.html#config-parameters

**Comment by ndrwchn** [comment]
Thanks a lot!

**Comment by marevol** [comment]
Yes.
