### ISSUE TITLE
crawler is blocked port 80 but 443

### ISSUE THREAD

**Issue by ndrwchn** [codelibs/fess#521]
It seems weird to me. Once crawlering a certain website, like http://xxx.xxx.com/, no indexing result. However, using https://xxx.xxx.com/, no issue. By using curl to test, port 80 bounces 'connection refused', 443 is OK. Both 80 and 443 are OK in browser.

My question is how this happened? It seems block FESS in firewall not by TCP port, but by app name? What's robot name for FESS?

**Comment by marevol** [comment]
Changing user-agent on web crawling config, it may work.
http://fess.codelibs.org/10.0/admin/webconfig-guide.html#user-agent

**Comment by attibalazs** [comment]
Can you share an example of how to configure the Data Store crawler, in the help pages in the screenshots the configuration parameters are blank.
