### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by nvoleau** [codelibs/fess#522]
Hi,
i crawl filesystem and my file have special caractère like like this : "d**é**cale" and when i serach this document in my résult page I have "D**Ã©**cale"
I think it's because my filename are in iso-8859-1.
Any workaround ?

**Comment by marevol** [comment]
- What is a kind of file? Is it .txt?
- What is the encoding? The default encoding of Fess is UTF-8.

**Comment by nvoleau** [comment]
All files... and i have the problem only with the name of the file. For example i have a file wich name is : Formation enrichissement Art - Reprise des données enrichissement.ppt and all "é" are encode Ã©

**Comment by marevol** [comment]
Can I find the file on the web? I'd like to reproduce it.

**Comment by nvoleau** [comment]
Non but you cal create excel file and name the file "Reprise des données enrichissement.ppt"
In the result page : 
`<c:forEach var="doc" varStatus="s" items="${documentItems}">
				<li id="result${s.index}">
					<h3 class="title ellipsis">
						<a class="link" href="${doc.urlLink}" data-uri="${doc.urlLink}"
							data-id="${doc.doc_id}" data-order="${s.index}"><c:forTokens var="p" items="${doc.urlLink}" delims="/" varStatus="vs">
 <c:if test="${vs.last}">${p}</c:if>
</c:forTokens></a>`

**Comment by marevol** [comment]
Not reproduced on Fess/MacOS.
Is your environment on Windows?

**Comment by nvoleau** [comment]
Windows

**Comment by marevol** [comment]
Hmm... not reproduced on Windows.
fess.in.bat contains the following encoding setting.

    set JAVA_OPTS=%JAVA_OPTS% -Dfile.encoding=UTF-8

Therefore, I think it works if it's encoded by UTF-8.
