### ISSUE TITLE
Separate index for each crawling job

### ISSUE THREAD

**Issue by AdeelIlyas2014** [codelibs/fess#528]
Is there a way I can create separate index other than "fess" default index for each separate crawling job i.e 1. for Crawling Confluence, 2. for Crawing Wordpress blogs, 3. for Crawing Forums etc so on ?

**Comment by marevol** [comment]
How about label feature?
http://fess.codelibs.org/10.0/admin/labeltype-guide.html

**Comment by AdeelIlyas2014** [comment]
Thanks for help. Fortunately I have already started using it. but a question as I  lready indexed good amount of urls without label. Now when I edited the web crawling config and added label for it the results won't show in search with label based search. Could you tell me is there a way I could apply label to the already/exiisting crawled indexes? or need to run the indexing again ?

**Comment by AdeelIlyas2014** [comment]
Thanks for help. Fortunately I have already started using it. but a question as I  already indexed good amount of urls without label. Now when I edited the web crawling config and added label for it the results won't show in search with label based search. Could you tell me is there a way I could apply label to the already/exiisting crawled indexes? (through any way like query etc) or need to run the crawling job again with label?

Your help will be really appreciated. Thanks

**Comment by marevol** [comment]
> need to run the crawling job again with label?
You need to run it again and also disable "Check Last Modified".
http://fess.codelibs.org/10.0/admin/general-guide.html

**Comment by AdeelIlyas2014** [comment]
@marevol Thank you man. really appreciated!
