### ISSUE TITLE
How to configure an external elasticsearch server?

### ISSUE THREAD

**Issue by marfago** [codelibs/fess#552]
Is it possible to use an external elasticsearch server instead of the embedded one?

**Comment by marevol** [comment]
Yes. RPM distribution uses an external elasticsearch by default.
To use it, please set the following environment variable.

    export ES_HTTP_URL=http://localhost:9200
    export ES_TRANSPORT_URL=localhost:9300

**Comment by marfago** [comment]
Thank you.
