### ISSUE TITLE
FESS cluster

### ISSUE THREAD

**Issue by marfago** [codelibs/fess#553]
Is it possible to build up a cluster of many different instances of FESS server?

**Comment by marevol** [comment]
To construct Fess/Elasticsearch cluster, please use external elasticsearch cluster.

    Users <-> Load Balancer(use sticky session) <-> Fess instances <-> Elasticsearch Cluster

**Comment by adamclayton** [comment]
Just wondering if you have two or more instances of fess server connecting to the elasticsearch cluster then which fess instance would be doing crawling and other background jobs? Trying to think of how jobs in Fess are scheduled/coordinated in this configuration.

**Comment by marevol** [comment]
To specify a job for each Fess instances, "Target name" is available in fess_config.properties as below:

    scheduler.target.name=

For examples, you can set a host name to scheduler.target.name.
For Job setting, [Target configuration](http://fess.codelibs.org/11.0/admin/scheduler-guide.html#target) is in Scheduler page.

**Comment by julianopcardoso** [comment]
I need to do that.
So, let me see if I understood.

Example:
I have Server1 and Server2 (both Fess server).
I have the Index_Crawler_Job.
Only the Server2 will run the Index_Crawler_Job.

Will the target name be the same in both servers at scheduler.target.name=Server2  and Target = Server2 (Target Configuration) ?

**Comment by julianopcardoso** [comment]
Please help me with this question.

Thanks in advance.
