### ISSUE TITLE
IndexUpdater delay

### ISSUE THREAD

**Issue by marfago** [codelibs/fess#556]
I noticed that the IndexUpdater updates index in average every 5 seconds, and the number of documents in foss index is very much smaller than teh number in .crawler index. Also the load in average is 50%, so I would like to reduce time delay for IndexUpdater for a faster indexing. Is there any way to to do that?

**Comment by marevol** [comment]
Please check interval time and change the number of threads.
http://fess.codelibs.org/10.1/admin/webconfig-guide.html#interval-time

**Comment by marfago** [comment]
Interval time is already 0 but indexer starts every 5 seconds. Any other suggestion?

**Comment by marevol** [comment]
Ah, it's in fess_config.properties

    indexer.webfs.commit.margin.time=5000
