### ISSUE TITLE
Multi-Tenancy support

### ISSUE THREAD

**Issue by AdeelIlyas2014** [codelibs/fess#561]
Hi, 

Does FESS support Multi-tenancy somehow?. In UI particularly, so that single instance can be used for multiple sites (domains pointing to it) with each having different look and feel i.e Logo, Page Design etc. How can we achieve that? 2nd question, can we configure multiple Fess instances on single server? How can I change the port of Fess server If I want to run second on the same server.?

I appreciate your cooperation.

**Comment by marevol** [comment]
> Does FESS support Multi-tenancy somehow?

No, Fess does not support multi-tenancy.

> can we configure multiple Fess instances on single server? 

Yes. We recommend this way.
A port setting is in bin/fess.in.sh

    FESS_JAVA_OPTS="$FESS_JAVA_OPTS -Dfess.port=8080"

If you want to use external elasticsearch cluster, put the following settings to fess.in.sh

    ES_HTTP_URL=http://localhost:9200
    ES_TRANSPORT_URL=localhost:9300
    FESS_DICTIONARY_PATH=/var/lib/elasticsearch/config/

and also, if you want to use specific index, change them in fess_config.properties.

    index.document.search.index=fess
    index.document.update.index=fess
