### ISSUE TITLE
Add crawler.ignore.robots.txt=false to fess_config.properties

### ISSUE THREAD

**Issue by marevol** [codelibs/fess#568]

**Comment by Tpev** [comment]
@marevol  Hello, do you have any ETA for the ignore.robots function ? Or do you have any workarround for previous version ? Thanks

**Comment by marevol** [comment]
To disable robots.txt, put the following settings to config parameters: http://fess.codelibs.org/10.1/admin/webconfig-guide.html#config-parameters

    client.robotsTxtEnabled=false
