### ISSUE TITLE
Indexing Metadata, JSON and XML

### ISSUE THREAD

**Issue by willparkinson** [codelibs/fess#574]
Hello

Is there a way currently in Fess to index file metadata (HTML metadata in particular)?  Also, is there a method to index XML and JSON feeds?

Thanks!

Will

**Comment by marevol** [comment]
> Is there a way currently in Fess to index file metadata (HTML metadata in particular)?

The following xpath setting is in app/WEB-INF/classes/fess_confing.properties:

    crawler.document.html.content.xpath=//BODY

> Also, is there a method to index XML and JSON feeds?

No, it's not supported at the moment.
