### ISSUE TITLE
MS SQL Support

### ISSUE THREAD

**Issue by TheCodeGnome** [codelibs/fess#597]
The readme states that database crawling is included. I'm wondering, is MS SQL supported? Need an explicit answer as part of a feature review.

**Comment by marevol** [comment]
Database Crawling depends on JDBC driver.
It works if JDBC driver is available.

**Comment by attibalazs** [comment]
Can you share an example of how to configure the Data Store crawler, in the help pages in the screenshots the configuration parameters are blank.
