### ISSUE TITLE
Append Params to URL is not add search words

### ISSUE THREAD

**Issue by ma2tani** [codelibs/fess#615]
To Reproduce.
1. To index pdf files
2. Append Params to URL is Enable (Admin General Configuration)
3. Search in "pdf Lorem"
Result:
"http://localhost:8080/go/?rt=1...abridgement...&hash=%23search%3D#search="

Expected Behavior:
'http://localhost:8080/go/?rt=1...abridgement...&hash=%23search%3D#search="pdf Lorem"'

**Comment by marevol** [comment]
@ma2tani 
Not reproduced. Expected url is:
http://localhost:8080/go/?rt=1...abridgement...&hash=%23search%3D%2522pdf%20Lorem%2522
/go does not contain #search=...
