### ISSUE TITLE
Trouble starting Fess from source

### ISSUE THREAD

**Issue by attibalazs** [codelibs/fess#631]
I'm having some trouble starting it up from the source code, i get the following errors:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/dbflute/tomcat/TomcatBoot
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:123)
Caused by: java.lang.ClassNotFoundException: org.dbflute.tomcat.TomcatBoot
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true -Dhttp.auth.preference=ntlm

```

Or if I try debugging i get this:
```
Connected to the target VM, address: '127.0.0.1:61072', transport: 'socket'
Disconnected from the target VM, address: '127.0.0.1:61072', transport: 'socket'
Error: Could not find or load main class org.codelibs.fess.FessBoot
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true -Dhttp.auth.preference=ntlm
```

**Comment by marevol** [comment]
Run mvn package before starting FessBoot.

**Comment by attibalazs** [comment]
The mvn package ran succesfully. However I`m trying to run based on the sourced code from IntelliJ IDEA. 
Following the documentation:

> Launch org.codelibs.fess.FessBoot as Debug mode and then access to http://localhost:8080/

**Comment by marevol** [comment]
To run on IDEA, could you remove provided scope of tomcat-boot and tomcat-jasper in pom.xml?

https://github.com/codelibs/fess/blob/master/pom.xml#L1251

**Comment by attibalazs** [comment]
Hi thanks for that! I updated the pom.xml and now I`m on to the next error. I spent some time searching the web and trying to figure it out but i`m stuck again. 

The following jar files seem to be missing, and i can`t get Maven/IDEA to download them:
Do these have to be installed manually or is it just my environment that`s not configured properly?

java.io.FileNotFoundException:
.m2/repository/xalan/xalan/2.7.2/xercesImpl.jar
m2/repository/xalan/xalan/2.7.2/xml-apis.jar
.m2\repository\xalan\xalan\2.7.2\serializer.jar
.m2\repository\com\drewnoakes\metadata-extractor\2.8.1\xmpcore-5.1.2.jar
.m2\repository\com\github\junrar\junrar\0.7\commons-logging-api-1.1.jar
.m2\repository\com\github\junrar\junrar\0.7\commons-vfs2-2.0.jar
.m2\repository\com\github\junrar\junrar\0.7\commons-logging-1.1.1.jar
.m2\repository\com\github\junrar\junrar\0.7\maven-scm-api-1.4.jar 
.m2\repository\com\github\junrar\junrar\0.7\plexus-utils-1.5.6.jar 
.m2\repository\com\github\junrar\junrar\0.7\maven-scm-provider-svnexe-1.4.jar 
.m2\repository\com\github\junrar\junrar\0.7\maven-scm-provider-svn-commons-1.4.jar 
.m2\repository\com\github\junrar\junrar\0.7\regexp-1.3.jar
.m2\repository\org\apache\opennlp\opennlp-tools\1.5.3\opennlp-maxent-3.0.3.jar
.m2\repository\org\apache\opennlp\opennlp-tools\1.5.3\jwnl-1.3.3.jar
.m2\repository\edu\ucar\netcdf4\4.5.5\cdm-4.5.5.jar
.m2\repository\edu\ucar\netcdf4\4.5.5\udunits-4.5.5.jar
.m2\repository\edu\ucar\netcdf4\4.5.5\httpservices-4.5.5.jar
.m2\repository\edu\ucar\netcdf4\4.5.5\httpclient-4.2.6.jar 
.m2\repository\edu\ucar\netcdf4\4.5.5\commons-logging-1.1.1.jar 
.m2\repository\edu\ucar\netcdf4\4.5.5\commons-codec-1.6.jar
.m2\repository\edu\ucar\netcdf4\4.5.5\httpmime-4.2.6.jar
.m2\repository\edu\ucar\netcdf4\4.5.5\httpcore-4.2.5.jar
.m2\repository\edu\ucar\netcdf4\4.5.5\jcl-over-slf4j-1.7.7.jar
.m2\repository\edu\ucar\netcdf4\4.5.5\joda-time-2.2.jar
.m2\repository\edu\ucar\netcdf4\4.5.5\jdom2-2.0.4.jar 

... and many more

**Comment by marevol** [comment]
Run mvn package, and then dependencies are downloaded.

**Comment by attibalazs** [comment]
I did run mvn package see above also. When i run mvn package it build with success. When i build for debug i get errors of missing packages.

**Comment by marevol** [comment]
Please check Local Repository in Preference -> Build,Execution,Deployment -> Build Tools -> Maven.
I think it's a general problem about IDEA/Maven, not Fess...

**Comment by attibalazs** [comment]
I managed to successfully build the solution this morning. I think the issue was that the corporate proxy was blocking some of the domains you referenced. I used a different connection and it all started working. I could build for debug using IntelliJ and also package the release with Maven. Thanks for your support.
