### ISSUE TITLE
Datastore crawler example

### ISSUE THREAD

**Issue by attibalazs** [codelibs/fess#633]
hi, do you have some examples on how to set up a datastore crawler. i would like to crawl an MS Sql server database. The documentation is a bit light: http://fess.codelibs.org/10.1/admin/dataconfig-guide.html

many thanks

**Comment by attibalazs** [comment]
Can you share an example of how to configure the Data Store crawler, in the help pages in the screenshots the configuration parameters are blank.

**Comment by marevol** [comment]
See http://fess.codelibs.org/10.2/admin/dataconfig-guide.html#databasedatastore
