### ISSUE TITLE
Specify Label search on /json/ webservice

### ISSUE THREAD

**Issue by AdeelIlyas2014** [codelibs/fess#646]
How I can specify the fields.label to search for only label related documents in /json/ provided webservice?

**Comment by AdeelIlyas2014** [comment]
I have got it working as following:

q=(sponsoring)%20AND%20label:"blogs"

Let me know if there can be any improvement in it. Thanks

**Comment by marevol** [comment]
field.label is a request parameter.

     q=sponsoring&fields.label=blogs

**Comment by AdeelIlyas2014** [comment]
Sorry it was not working your suggested way. Please check again - there must be some bug then

**Comment by AdeelIlyas2014** [comment]
For search ui it is a request parameter but for json service it is not. I checked your code of [QueryStringBuilder.java](https://github.com/codelibs/fess/blob/master/src/main/java/org/codelibs/fess/util/QueryStringBuilder.java). It is also saying same.

**Comment by marevol** [comment]
It works. The source code is [here](https://github.com/codelibs/fess/blob/master/src/main/java/org/codelibs/fess/api/json/JsonApiManager.java#L736).

    curl "http://search.n2sm.co.jp/json/?q=fess"
    curl "http://search.n2sm.co.jp/json/?q=fess&fields.label=lucene"
