### ISSUE TITLE
 add thumbnail

### ISSUE THREAD

**Issue by MajidSafari** [codelibs/fess#658]
how i can  add thumbnail image ?????

**Comment by marevol** [comment]
If phantomjs is installed in your environment and Thumbnail View is enalbed on General Config page, thumbnail images will be displayed.
In not Unix environment, a path for phantomjs (${path}/phantomjs) needs to be changed in app/WEB-INF/classes/fess_thumbnail.xml.

**Comment by Stepanov-Sergey** [comment]
It may be enough to register phantomjs:
windows7,10 CMD
SET path = C: \ pathtophantomjs\;% path%
SET phantomjs = C: \ pathtophantomjs\phantomjs;% path%

**Comment by Stepanov-Sergey** [comment]
fess 10.2.1+phantomjs+windows10 works fine, it is necessary to register as I said,
