### ISSUE TITLE
Is there any configuration of index file

### ISSUE THREAD

**Issue by albertgu2016** [codelibs/fess#663]
Hi
 Is FESS suport place index data in other computer not local?

**Comment by marevol** [comment]
Index data is managed by elasticsearch.
Fess is able to use external elasticsearch cluster.

http://fess.codelibs.org/10.2/install/install.html

**Comment by albertgu2016** [comment]
Hi marevol,
 I am using fess-10.0.0 in Windows and instlled elasticsearch-2.4.0 by RPM command in Linux, and I tried the method in your url, the 3rd line of this command below is strange, it point to windows URL of elasticsearch, and The method doesn't work? Is there anything wrong?
set FESS_PARAMS=%FESS_PARAMS% -Dfess.es.http_address=http://localhost:9200
set FESS_PARAMS=%FESS_PARAMS% -Dfess.es.transport_addresses=localhost:9300
set FESS_PARAMS=%FESS_PARAMS% -Dfess.dictionary.path="c:/<elasticsearch-<version>/data/"

**Comment by marevol** [comment]
For a remote elasticsearch on Linux, these settings are on Windows:

    set FESS_PARAMS=%FESS_PARAMS% -Dfess.es.http_address=http://LINUXSERVERNAME:9200
    set FESS_PARAMS=%FESS_PARAMS% -Dfess.es.transport_addresses=LINUXSERVERNAME:9300
    set FESS_PARAMS=%FESS_PARAMS% -Dfess.dictionary.path="/var/lib/elasticsearch/config/"
