### ISSUE TITLE
hi , NOINDEX

### ISSUE THREAD

**Issue by MajidSafari** [codelibs/fess#665]
<META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW">

hi how to config , no  Crawling page if noindex ????

**Comment by marevol** [comment]
Need more info.

**Comment by MajidSafari** [comment]
i want when page has meta noindex Crawling skip page 

but now in ver 10.2 not working

**Comment by marevol** [comment]
noindex of meta tag is not supported at the moment.
Our current release supports robots.txt.
For meta tag, we will support it in the future release.

**Comment by MajidSafari** [comment]
tax pleas add in ver 10.3
