### ISSUE TITLE
Is there a setting for max length ?

### ISSUE THREAD

**Issue by attibalazs** [codelibs/fess#667]
I am getting the following exceptions when crawling files org.codelibs.fess.crawler.exception.MaxLengthExceededException

is there some setting where i can increase the max length ?

**Comment by marevol** [comment]
The setting is in app/WEB-INF/classes/crawler/contentLength.xml.

    <property name="defaultMaxLength">10485760</property>

**Comment by attibalazs** [comment]
Thanks i have increased it to 100MB, fingers crossed.
