### ISSUE TITLE
FESS does not search the URL by default?

### ISSUE THREAD

**Issue by attibalazs** [codelibs/fess#668]
When indexing files/documents the Url is important. The folder structure and file name can have valuable information. By default fess only searches the document content. Is there a way to add the url to the default search without explicitly specifying it like Url:Test ?

**Comment by marevol** [comment]
See http://fess.codelibs.org/10.2/user/search-field.html

**Comment by attibalazs** [comment]
I knew about those options. Thanks.

I was just wandering if it possible to make it search both on the content and on the url without the url: . For an index which has files this is useful. Searching for files based on the file name and folder names is something users ask for.
