### ISSUE TITLE
Why are dates saved as numbers ?

### ISSUE THREAD

**Issue by attibalazs** [codelibs/fess#669]
I noticed that some dates are saved as numbers. I want to use Kibana to look at the indexes and do some analytics on them but the dates show up as numbers. I am looking at the .crawler index where dates are stored in the epoch format as numbers.

I noticed you are displaying the dates correctly in FESS, is this related to elastic search or the way fess saves the data ?

>  "status": 9999,
>                "httpStatusCode": 200,
>                "method": "GET",
>                "mimeType": "text/plain",
>                **"createTime": 1471282801243,**
>                "executionTime": 23,
>                "contentLength": 219,
>                **"lastModified": 1340626665470**

**Comment by marevol** [comment]
It's a specification for Fess.
We do not expect data in .crawler index is displayed on Kibana.
