### ISSUE TITLE
How can i upgrade to the latest version?

### ISSUE THREAD

**Issue by attibalazs** [codelibs/fess#670]
How can i upgrade to the latest version of FESS or move my index and configurations to the latest version ?

**Comment by marevol** [comment]
See http://fess.codelibs.org/10.2/admin/upgrade-guide.html

**Comment by attibalazs** [comment]
Thought you want to know, the image link is broken on the upgrade documentation page see attached:

![fess_broken_image_link](https://cloud.githubusercontent.com/assets/1638454/18348450/4b11d444-75c3-11e6-8d9e-5aa5120173af.png)
