### ISSUE TITLE
hi , Data Store Crawling

### ISSUE THREAD

**Issue by MajidSafari** [codelibs/fess#677]
hi

 in Data Store Crawling

how to connect to sql server 2014 ,???

**Comment by marevol** [comment]
See http://fess.codelibs.org/10.2/admin/dataconfig-guide.html#databasedatastore
and put JAR file of JDBC driver for SQL server to app/WEB-INF/lib.

**Comment by MajidSafari** [comment]
hi , i see that  but ,

**Comment by MajidSafari** [comment]
i cant set parameters to connect to sql  ?????

can you example how to config parameters and sctipt

**Comment by marevol** [comment]
The parameter is settings for DB, and the script is mappings between SQL results and indexed document.
