### ISSUE TITLE
video, and image , content

### ISSUE THREAD

**Issue by MajidSafari** [codelibs/fess#678]
plz , support in content

**Comment by marevol** [comment]
Need more info...

**Comment by MajidSafari** [comment]
search video and image ? in fess

**Comment by marevol** [comment]
It depends on Apache Tika.

**Comment by Stepanov-Sergey** [comment]
Apache Tika  supports fb2 format, but does not display search results. It is necessary to do additional configuration FESS? Tika also supports the PDF format and I scan a lot of documents, but displayed few files...

**Comment by marevol** [comment]
Please check fess-crawler.log.

**Comment by Stepanov-Sergey** [comment]
I found in the log file. I had to read Custom facets #555. Thanks!
