### ISSUE TITLE
Not working on our Elasticsearch 2.4.0 cluster

### ISSUE THREAD

**Issue by bryan-vest** [codelibs/fess#680]
I used the .deb to install fess-10.2.0, followed the rest of the instructions. fess loads and does not show any errors in the log but our elastic cluster does not show any fess indices and going to http://our.server:8080 the page just sits at loading and never loads.

I have changed the settings in /usr/share/fess/bin/fess.in.sh, tried localhost and the fqdn of the server. Same result.

I tried it with the zip/bin on another server and that comes right up as long as it is using its own es server.

**Comment by ma2tani** [comment]
I could not reproduce it. Could you check log files in /var/log/fess and /var/log/elasticsearch directories?

http://fess.codelibs.org/10.2/install/install.html

I installed the following plugins: 
- /usr/share/elasticsearch/bin/plugin install org.codelibs/elasticsearch-analysis-fess/2.4.0
- /usr/share/elasticsearch/bin/plugin install org.codelibs/elasticsearch-analysis-ja/2.4.0
- /usr/share/elasticsearch/bin/plugin install org.codelibs/elasticsearch-analysis-synonym/2.4.0
- /usr/share/elasticsearch/bin/plugin install org.codelibs/elasticsearch-configsync/2.4.0
- /usr/share/elasticsearch/bin/plugin install org.codelibs/elasticsearch-dataformat/2.4.0
- /usr/share/elasticsearch/bin/plugin install org.codelibs/elasticsearch-langfield/2.4.0
- /usr/share/elasticsearch/bin/plugin install http://maven.codelibs.org/archive/elasticsearch/plugin/kopf/elasticsearch-kopf-2.0.1.0.zip

**Comment by bryan-vest** [comment]
I had two issues. I had installed the wrong version of plugins. I uninstalled them and installed the ones listed above. I also had a permission error on the dictionary folder. Working fine now.
