### ISSUE TITLE
exclude form crawler 

### ISSUE THREAD

**Issue by MajidSafari** [codelibs/fess#681]
hi , 

i want sub domains exclude form crawler  , ?

plz help me !!

**Comment by ma2tani** [comment]
Could you provide examples, please?

**Comment by MajidSafari** [comment]
this true ?
![screenshot 6](https://cloud.githubusercontent.com/assets/5099564/18502486/b1564ea8-7a6c-11e6-882c-80fbdb84b64b.png)

**Comment by ma2tani** [comment]
set to "Excluded URLs For Crawling".
http://www.kanoon.ir/main/.*
http://www.kanoon.ir/site/.*
