### ISSUE TITLE
Lost configuration / data on my fess instance

### ISSUE THREAD

**Issue by attibalazs** [codelibs/fess#688]
Hi, i lost all the configurations and data i had indexed on my fess instance.
Not sure what happened is there a way to debug this ? Happened on version 10.2, has this happened to you, is this a bug?

**Comment by marevol** [comment]
See log files in logs directory.
Configuration data is in data/<cluster name> directory.
If you change cluster name for elasticsearch, you need to change data directory.

**Comment by attibalazs** [comment]
that might have been the cause i did change the cluster name. Thanks a lot for the quick answer.

**Comment by abhilashbolla-innoplexus** [comment]
What is the location of the data directory?

**Comment by marevol** [comment]
The location is es/data or /var/lib/elasticsearch.
