### ISSUE TITLE
xmlrpc Auth question

### ISSUE THREAD

**Issue by bryan-vest** [codelibs/fess#689]
We are attempting to have fess index our internal wiki. The wiki runs on OSX server which I think I have traced to using xmlrpc for authentication. I have tried every auth method offered and none of them work. Does anyone have any tips on getting fess to auth with xmlrpc?

**Comment by marevol** [comment]
Currently, Fess supports BASIC/DIGEST/NTLM authentication.
I do not think it's the above one, so it might work if you set Cookie header of logged-in session to Request Header for the Crawling Configuration.

**Comment by bryan-vest** [comment]
I have been digging in the server code, which is all written in python to see exactly what it wants in the header. If I have success I will post the required header information to make this work.

**Comment by bryan-vest** [comment]
This wiki server uses a two stage authentication that I could not get to work. So I took another route, I NFS mounted the path to the wiki files to the FESS server and used path mapping to change it back to an https:// instead of file:// so far seems to be working fine.

**Comment by bryan-vest** [comment]
Since we are reading the files directly one of the things it wants to put in every search result link is "/js/jquery-1.7.2.min.js wiki_entry " I read through the documentation and can not find if there is a setting to tell it not to include that line in the link.

**Comment by marevol** [comment]
How about modifying search result page in admin design page?
