### ISSUE TITLE
If the coding on the scanned pages is not defined, FESS can display wrong coding

### ISSUE THREAD

**Issue by Stepanov-Sergey** [codelibs/fess#694]
For example page is created in the Windows-1251, but does not have the appropriate tag, and FESS is trying to bring in UTF8 encoding

**Comment by marevol** [comment]
Fess uses a charset info of a meta tag.
The default is UTF-8 if it's not specified.
If you want to change it, add charsetName to apps/WEB-INF/classes/crawler/transformer.xml:

```
...
        <component name="fessXpathTransformer" class="org.codelibs.fess.crawler.transformer.FessXpathTransformer" instance="singleton">
                <property name="charsetName">"Windows-1251"</property>
...
```
