### ISSUE TITLE
Database changes

### ISSUE THREAD

**Issue by chankrisna** [codelibs/fess#743]
Hi Fess Author,

i found in doc of version 9.4 is allow to change Database from H2 to other. and i try to change to Postgresql by change config in dbflute_fess but doesn't work. Is it possible to change database in version 10.2 ?

**Comment by marevol** [comment]
Fess 10.x does not need any databases.

**Comment by chankrisna** [comment]
Is it possible or not if I want to put user into postgresql . do you have any clue for do that ?

**Comment by marevol** [comment]
Fess 10 contains no DB. User information is in elasticsearch, LDAP/AD or OpenIDConect. DB is not supported.

**Comment by chankrisna** [comment]
Thank you for support, I have own oauth2 service so how to integrate with fess as login with oauth2.

**Comment by marevol** [comment]
OAuth2 is Authorization, not Authentication.
Fess supports only authentication system at the moment.
Therefore, OAuth is not supported.

**Comment by chankrisna** [comment]
does fess can support login with facebook or google plus? if have please provide me some example.

**Comment by marevol** [comment]
To support them, we need to create SsoAuthenticator implementation, like oic.OpenIdConnectAuthenticator.

https://github.com/codelibs/fess/tree/master/src/main/java/org/codelibs/fess/sso

**Comment by chankrisna** [comment]
Yes, Thank you so much. i will try.
