### ISSUE TITLE
Unable to crawl SSL pages

### ISSUE THREAD

**Issue by kotesh** [codelibs/fess#753]
I am trying to crawl an https:// site but seems FESS crawler is failing with below error.

org.codelibs.fess.crawler.exception.CrawlingAccessException: I/O exception(handshake alert:  unrecognized_name):
javax.net.ssl.SSLProtocolException

I tried to disable SNI support by setting below configuration in fess.in.sh 
java -Djsse.enableSNIExtension=false

**Comment by marevol** [comment]
The configuration depends on your servers for crawling.
I will not add it to Fess as a default configuration.

**Comment by kotesh** [comment]
Thanks for the response. After setting  java -Djsse.enableSNIExtension=false in fess.in.sh also I am still getting the same error. 
How can i enable SSL Crawling for my server

**Comment by marevol** [comment]
How about adding it to fess_config.properties, not fess.in.sh, as below:

```
# JVM options
jvm.crawler.options=\
-Djsse.enableSNIExtension=false\n\
-Djava.awt.headless=true\n\
-server\n\
...
```

**Comment by kotesh** [comment]
Unable to build the package. Seems some of the dependencies are not resolving properly. Deleted the below jar and and tried but still unable to run mvn package.
Is there any Java/Maven version dependencies. 

Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.2:enforce (enforce-maven) on project fess: Execution enforce-maven of goal org.apache.maven.plugins:maven-enforcer-plugin:1.2:enforce failed: A required class was missing while executing org.apache.maven.plugins:maven-enforcer-plugin:1.2:enforce: org/apache/maven/enforcer/rule/api/EnforcerRuleException

**Comment by marevol** [comment]
My environment is below.
```
$ java -version
java version "1.8.0_102"
$ mvn --version
Apache Maven 3.3.1
```

However, jvm.crawler.options is just a configuration.
So, repackaging is not needed.

**Comment by kotesh** [comment]
Thank you. Now I am able to crawl SSL sites
