### ISSUE TITLE
How to change analyzer settings

### ISSUE THREAD

**Issue by MajidSafari** [codelibs/fess#757]
hi

my language is Persian how config analyzer persian

and how add list stop word ?

**Comment by marevol** [comment]
Please see persian_analyzer in src/main/resources/fess_indices/fess.json.
If you change fess.json, fess.* index needs to be deleted before starting Fess.
For analyzer settings, see https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-analyzers.html
