### ISSUE TITLE
how add stopword

### ISSUE THREAD

**Issue by MajidSafari** [codelibs/fess#763]
i change in fess.json

```
  "persian_stop": {
      "type":       "stop",
      "stopwords_path":  "${fess.dictionary.path}fa/stopwords.txt"
    },
```

is work ?

**Comment by marevol** [comment]
I think it works.

**Comment by MajidSafari** [comment]
it not work plz help

**Comment by marevol** [comment]
Need more info...
Could you provide steps you executed?

**Comment by Stepanov-Sergey** [comment]
possible problem in the encoding of the text. what encoding should be for stopwords?
