### ISSUE TITLE
Support auto boost h1 h2 h3

### ISSUE THREAD

**Issue by MajidSafari** [codelibs/fess#774]
Support auto boust h1 h2 h3

**Comment by marevol** [comment]
Need more info...

**Comment by MajidSafari** [comment]
when in page some element  for example 

<h1>
<h2>

this element important in seo  ,

i want  text in this tag increase Boost ,

**Comment by marevol** [comment]
I'll support it in the future release.

**Comment by MajidSafari** [comment]
FESS 10.3 final, releases date ?

**Comment by marevol** [comment]
We have a plan to release 10.3 at the end of this month.
