### ISSUE TITLE
dont index text in tag hidden

### ISSUE THREAD

**Issue by MajidSafari** [codelibs/fess#775]
plz add 

if tag is hidden not 

<h1 class='hiddin'>text</h>

**Comment by marevol** [comment]
Could you provide more details?

**Comment by cernadasjuan** [comment]
Is there a way to configure the crawler to not index hidden content (elements with classes with property display:none)?

For example, it indexed this:
<div class="asa.portlet" id="asa.portlet.Z7_814CHK41K8RQC0ABSTSS85H6I3" style="display:none;">
<span class="asa.portlet.id">Z7_814CHK41K8RQC0ABSTSS85H6I3</span>
</div>

Thanks!
