### ISSUE TITLE
Add ImageUrl field

### ISSUE THREAD

**Issue by MajidSafari** [codelibs/fess#779]
can you add in field ,

**Comment by marevol** [comment]
Need more info...

**Comment by MajidSafari** [comment]
i use data store in Fees , i have image url from in my  content

 but

ImageUrl field not exist in Fess ,

or 

web crawling read from meta tag

meta property="image" content="http://img.kanoon.ir/Images/kanoon.jpg" 

and store in ImageUrl for **thumb image**

**Comment by marevol** [comment]
If you want to add additional field, insert the following configuration into app/WEB-INF/classes/crawler/transformer.xml. I think image_url field is added to fess index.

```
                <postConstruct name="addFieldRule">
                        <arg>"image_url"</arg>
                        <arg>"//META[@ property =\"image\"]/@content"</arg>
                </postConstruct>
```

**Comment by MajidSafari** [comment]
WOW ....

I loved Fess

**Comment by MajidSafari** [comment]
and i can use in web store this field  ?

**Comment by marevol** [comment]
Yes. It works on Web Crawling configuration.

If you want to use image_url in JSP file, you also need to modify fess_config.properties.

    query.additional.response.fields=image_url

**Comment by MajidSafari** [comment]
how add this fields in json callback in FEss

**Comment by marevol** [comment]
As for 10.2, it's in app/WEB-INF/classes/app.xml.

        <component name="queryHelper" class="org.codelibs.fess.helper.QueryHelper">
                <property name="apiResponseFields">["content_description",
                    "content_title",
                    "site_path",
                    "url_link",
                    "_id",
                    "doc_id",
                    "boost",
                    "content_length",
                    "host",
                    "site",
                    "last_modified",
                    "timestamp",
                    "mimetype",
                    "filetype",
                    "filename",
                    "created",
                    "title",
                    "digest",
                    "url",
                    "image_url"]</property>


In 10.3, it'll be in fess_config.properties.

    query.additional.api.response.fields=image_url

**Comment by MajidSafari** [comment]
hi , 
Now i can use image_url , but i can't update records in Administrator, because my some records have image and some records have not image and i get Exception for Update records .

**Comment by marevol** [comment]
Need more details.

**Comment by MajidSafari** [comment]
i add additional fields=image_url in crawler

some pages not exist META[@ property =\"image\"]/@content"

now in Administrator in url /admin/searchlist/ 

![screenshot 2](https://cloud.githubusercontent.com/assets/5099564/21003307/e2a35382-bd3f-11e6-9cde-199e5ecf83c6.png)

when click in update  ... 
I see

**System Error
Contact the Site Administrator.**

**Comment by marevol** [comment]
I see.
Additional field editing is not supported at the moment.
We will support it in the next release.

**Comment by MajidSafari** [comment]
i don't want  editing in Additional field

**Comment by MajidSafari** [comment]
how now

Fix
System Error
Contact the Site Administrator.

??

**Comment by MajidSafari** [comment]
when not exist image_url

System Error
Contact the Site Administrator.



when  exist image_url , is work
![screenshot 3](https://cloud.githubusercontent.com/assets/5099564/21003697/0abb7406-bd42-11e6-803d-36cc669474c1.png)
