### ISSUE TITLE
How to exclude files on File Crawling

### ISSUE THREAD

**Issue by con-jr** [codelibs/fess#783]
Hi, can I have a sample on how to exclude a file in the File Crawling Configuration?

For example I want to exclude a .config file in a folder. I set up the crawl path in file:///C:/sitefolder/Media, and all the sub-folders in this directory can be indexed, except for the web.config file   (i.e.:  file:///C:/sitefolder/Media/web.config). Thanks

**Comment by marevol** [comment]
If you want to exclude all .config file, "Excluded Paths For Crawling" is as below:

    .*\.config

**Comment by con-jr** [comment]
Hi, thanks marevol. It works, but may I ask, how do I delete the previously indexed data? 

In order to make that work, I have to delete the whole fess folder, extract and run the fess.bin and do the scheduler again. 

Updating the configuration settings and starting the scheduler does not seem to removed the previously indexed files/pages. Thanks again.

**Comment by marevol** [comment]
Indexed documents have TTL.
They will be removed after specified days.
http://fess.codelibs.org/10.2/admin/general-guide.html#remove-documents-before

**Comment by con-jr** [comment]
Ok, thanks for the quick response.
