### ISSUE TITLE
How to use labels properly?

### ISSUE THREAD

**Issue by Ozius** [codelibs/fess#784]
Hi,

I am configuring some labels to search only on a subgroup of indexed pages.

I need to assign a label to all the pages in a certain folder, for example: http://www.example.org/folder/

I tried to put in "Included Paths" different formats but nothing appears to work properly, all the indexed pages has the label assigned, not only the pages in that folder.

Included Paths format is a java regex? I tried with:

^http://www.example.org/folder/
^http://www.example.org/folder/.*
http://www.example.org/folder/.*

Is the label functionality working fine? or I am configuring it wrongly?

Thanks!

**Comment by marevol** [comment]
Included Paths format is Java regex.
The setting for http://www.example.org/folder/.* assigns a label to pages under http://www.example.org/folder/ including sub directories.
If you selected a label in web crawling config page, ALL pages is assigned to the label.

**Comment by Ozius** [comment]
I have selected the label in web crawling config... :(

A reindex is necessary to update the label assigment?

**Comment by marevol** [comment]
Yes. Reindex is needed to update labels.

**Comment by Ozius** [comment]
Ok! Thanks!
