### ISSUE TITLE
add sitemap.xml

### ISSUE THREAD

**Issue by MajidSafari** [codelibs/fess#786]
how to do ?

**Comment by marevol** [comment]
sitemap.xml is supported.

**Comment by MajidSafari** [comment]
< link rel="sitemap" href="http://www.kanoon.ir/site/sitemap.xml" />

i want this link add in head, FESS read it ?

**Comment by marevol** [comment]
Fess Crawler does not check a link tag for sitemap.
It will be supported in a future release.
