### ISSUE TITLE
How to set replica configuration

### ISSUE THREAD

**Issue by kotesh** [codelibs/fess#793]
I am running with FESS with default configurations. I noticed that the crawling index "fess.date" doesn't have any replica nodes. How can a define the replica nodes for crawling index.

**Comment by kotesh** [comment]
Through kopf admin UI, I am able to edit the settings for this index. But would like to if there is any other configuration to override the default values for replica

**Comment by marevol** [comment]
If you want to use replica nodes, an external elasticsearch cluster is needed.
See http://fess.codelibs.org/10.2/install/install.html
