### ISSUE TITLE
Force interface language

### ISSUE THREAD

**Issue by Ozius** [codelibs/fess#794]
Hi,

My website is translated into two languages, spanish and basque. I am trying to personalize the fess search interface with my website design.

I created the localized version of fess_label_xx.properties for spanish and basque languages and the interface is translated into spanish correctly.

There is any method to force the interface language to use? an url parameter or something? I need to show the search engine in spanish or basque depends on the language you are in.

Thanks!

**Comment by marevol** [comment]
Currently, it depends on only browser's preferred language.
To change it by a request parameter will be supported in the future release...

**Comment by marevol** [comment]
In Fess 10.3, browser_lang parameter is available.
To change a language, access to localhost:8080/?browser_lang=en

**Comment by Ozius** [comment]
Thanks @marevol for the fast implementation.

I am trying it but I have a problem, with en, ja, ko and ru languages is working fine but I created fess_label_es.properties with spanish localization at app\WEB-INF\classes and when trying to open the browser interface with "?browser_lang=es" is showing the default english version.

I need to adjust some configuration file?

**Comment by Ozius** [comment]
Oh sorry, I need to create fess_label_es and fess_message_es files to work properly.

Thank you!!
