### ISSUE TITLE
Web crawler indexing html comments - fess 10.3.0

### ISSUE THREAD

**Issue by Ozius** [codelibs/fess#798]
Hi,

I installed 10.3.0 version and configured the crawler to index all my website.

I launched the crawler and I'm seeing some strange results. The crawler is indexing the html comments content and it's showing them on the results.

On 10.2.2 version this is not happening, the crawler ignored the comments tags.

How can I fix it? Is a configuration problem?

**Comment by marevol** [comment]
Fixed in #799
