### ISSUE TITLE
Error creating fess user on Linux Mint

### ISSUE THREAD

**Issue by beezdul** [codelibs/fess#800]
Here is the console output I'm getting using the .deb release.

/tmp $ sudo dpkg -i fess-10.3.0.deb 
(Reading database ... 311366 files and directories currently installed.)
Preparing to unpack fess-10.3.0.deb ...
Creating fess user...Option d is ambiguous (debug, disabled-login, disabled-password)
adduser [--home DIR] [--shell SHELL] [--no-create-home] [--uid ID]
[--firstuid ID] [--lastuid ID] [--gecos GECOS] [--ingroup GROUP | --gid ID]
[--disabled-password] [--disabled-login] [--encrypt-home] USER
   Add a normal user

adduser --system [--home DIR] [--shell SHELL] [--no-create-home] [--uid ID]
[--gecos GECOS] [--group | --ingroup GROUP | --gid ID] [--disabled-password]
[--disabled-login] USER
   Add a system user

adduser --group [--gid ID] GROUP
addgroup [--gid ID] GROUP
   Add a user group

addgroup --system [--gid ID] GROUP
   Add a system group

adduser USER GROUP
   Add an existing user to an existing group

general options:
  --quiet | -q      don't give process information to stdout
  --force-badname   allow usernames which do not match the
                    NAME_REGEX[_SYSTEM] configuration variable
  --extrausers      uses extra users as the database
  --help | -h       usage message
  --version | -v    version number and copyright
  --conf | -c FILE  use FILE as configuration file

dpkg: error processing archive fess-10.3.0.deb (--install):
 subprocess new pre-installation script returned error exit status 1
Errors were encountered while processing:
 fess-10.3.0.deb

**Comment by marevol** [comment]
Filed #801.
We will fix it this week...
