### ISSUE TITLE
increase view count and like count by json

### ISSUE THREAD

**Issue by MajidSafari** [codelibs/fess#805]
i use json Fess ,

how use viewcount and like ,  by json  ?

**Comment by marevol** [comment]
What is viewcount?

**Comment by MajidSafari** [comment]
/go/?rt=1480841350604&docId=91c5e21c833f4fc2b078e3ea5df1435a&queryId=ee2b3e998bf24cc0b626f4fe30abb2d8&order=4

**Comment by MajidSafari** [comment]
when i click link in fess

**Comment by MajidSafari** [comment]
increase  
![screenshot](https://cloud.githubusercontent.com/assets/5099564/20865056/41e5c32e-ba1c-11e6-9efe-c0a3933048a2.png)

**Comment by marevol** [comment]
go link is not supported on JSON response.
It'll be supported in the future release...

**Comment by lethanh603Imlv** [comment]
hi marevol
i am using fess version 11.2.1
Was labels.search_click_count supported by JSON-response?

**Comment by marevol** [comment]
Set the following setting in fess_config.properties.
```
query.additional.api.response.fields=favorite_count
```
