### ISSUE TITLE
Is Crawl Scheduler automatic?

### ISSUE THREAD

**Issue by con-jr** [codelibs/fess#807]
Hi,  I have a File Crawler task/job which crawls and indexed the files in a certain folder. Do I need to run the job again if I upload a new file in the directory? I uploaded a new file and it is not returned in the search results. 

Can I also ask if there's a way to remove the indexed item in the search result quickly without waiting for the "Remove Documents Before" to take effect?

 Thanks

**Comment by marevol** [comment]
Yes. You need to run crawler job when files are updated.
Enabling incremental crawling, deleted files will be removed at the crawling time.
http://fess.codelibs.org/10.3/admin/general-guide.html#check-last-modified

**Comment by con-jr** [comment]
Thanks @marevol . Can I also ask how to change the language of Fess admin? Currently the menu labels are in English, is there a way or an option to change it to Japanese? Thanks
