### ISSUE TITLE
Label for url

### ISSUE THREAD

**Issue by MajidSafari** [codelibs/fess#809]
i want  if url like www,kanoon.ir/book/564

into other Label 

![screenshot 1](https://cloud.githubusercontent.com/assets/5099564/20934655/21398454-bbf1-11e6-9f93-8c3019878cc9.png)

?????????

**Comment by marevol** [comment]
Need more details...

**Comment by MajidSafari** [comment]
i need to category my result using label on urls , but i can see another url in my result 
for example i need to search of this folder kanoon.ir/book/ but my result from kanoon.ir/book/ and kanoon.ir/writers/ 


how can i create a label of my  urls ?

**Comment by marevol** [comment]
Please check the following:

- Do not set labels in the web crawling setting
- Set .\*kanoon.ir/book/.\* to Included Paths

**Comment by MajidSafari** [comment]
tanx its work
