### ISSUE TITLE
unicode

### ISSUE THREAD

**Issue by MajidSafari** [codelibs/fess#810]
main url 
http://www.kanoon.ir/Amoozesh/Video/5-1-43607-1/مقدمات-چهارم-انسانی-تاریخ‌شناسی-چهارم-دبیرستان-انسانی

when click in fess , and /go/

![untitled](https://cloud.githubusercontent.com/assets/5099564/20938524/b193fbce-bc00-11e6-8f8a-a9ad99eb8513.png)

**Comment by marevol** [comment]
I'll look into this problem and fix it in a next release.
