### ISSUE TITLE
how add mapping

### ISSUE THREAD

**Issue by MajidSafari** [codelibs/fess#815]
how add mapping  ? for Persian language

![screenshot 4](https://cloud.githubusercontent.com/assets/5099564/21016638/93772e00-bd7b-11e6-9236-5373a5955756.png)

**Comment by marevol** [comment]
Please modify app/WEB-INF/classes/fess_indices/fess.json before starting Fess.
For analyzer, see https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-analyzers.html
