### ISSUE TITLE
Does the use of plugins for Elasticsearch prevent the use of the AWS Elasticsearch product?

### ISSUE THREAD

**Issue by pcolmer** [codelibs/fess#816]
Hi

If I've understood the documentation correctly, I have to install some plugins onto the Elasticsearch instance in order for Fess to work. Is that correct? If so, I'm presuming that this means that Fess cannot be used with the AWS Elasticsearch product since that is a managed platform, i.e. I don't have direct access to it to install bits.

Regards

Philip

**Comment by marevol** [comment]
To extend Elasticsearch, plugins needs to be installed.
