### ISSUE TITLE
How to ignore URLs that have dynamic parts (i.e. ?)

### ISSUE THREAD

**Issue by pcolmer** [codelibs/fess#820]
One of our web sites makes extensive use of ? to pass parameters in the URLs. This, however, seems to result in the same page being crawled & indexed multiple times.

Is there a way to tell fess to ignore any URL that has a ? in it? I'm guessing that the excluded URLs field can be used for this but I wanted to check ...

Thanks.

**Comment by pcolmer** [comment]
I *think* I can use something like this:

https://wiki.linaro.org/.*\?.*

**Comment by marevol** [comment]
Please use Excluded URLs.

**Comment by pcolmer** [comment]
Thank you.
