### ISSUE TITLE
How to change a mapping char filter

### ISSUE THREAD

**Issue by MajidSafari** [codelibs/fess#821]
don't work  "mappings": [ "\\u200C=> "] 

i want  u200C like space

help me

**Comment by marevol** [comment]
Need more details.
To change analyzer/mapping, fess index needs to be deleted and created.

**Comment by MajidSafari** [comment]
when change  analyzer/mapping must delete index ???

**Comment by marevol** [comment]
Yes. 
Index setting/mapping is applied at index creation time.
Basically, index setting/mapping cannot be changed(some of them can be changed).
This is specification of Elasticsearch, not Fess.
