### ISSUE TITLE
Analyze contents for a specific language

### ISSUE THREAD

**Issue by MajidSafari** [codelibs/fess#823]
who set "قلمچی" =>"قلم چی"

**Comment by marevol** [comment]
It depends on an analyzer setting for your language.

**Comment by MajidSafari** [comment]
can you help me how config ?

**Comment by MajidSafari** [comment]
hi
i want use 

Analyzer for Persian.

https://lucene.apache.org/core/6_0_0/analyzers-common/org/apache/lucene/analysis/fa/package-summary.html

how i can ???

**Comment by marevol** [comment]
I have already provided info, see #757 and #815.
I cannot read Persian. So please provide a more explanation about your problem.
