### ISSUE TITLE
Formatting Synonyms

### ISSUE THREAD

**Issue by MajidSafari** [codelibs/fess#848]
Hi again 
i tried to add Synonyms in dictionary, for single part words like "test=>exam" it works fine but for more than one part words with spaces like "online test=>exam" it doesn't work. 
the line for this rule in the "synonym.txt" is: 
online exam,online test=>exam

did i do something wrong ?

**Comment by marevol** [comment]
If you use standard tokenizer and synonym token filter, standard tokenizer is divides "online test" into online and test. So, "online test" does not match in synonym token filter.
I think it works if using ngram_synonym tokenizer .
https://github.com/codelibs/elasticsearch-analysis-synonym

**Comment by MajidSafari** [comment]
hi

i add this code in fess.json

>  "tokenizer": {
        "2gram_synonym":{
            "type":"ngram_synonym",
            "n":"2",
            "synonyms_path":"${fess.dictionary.path}synonym.txt"}
     }

and

> "persian_analyzer": {
          "type": "custom",
          "tokenizer": "2gram_synonym",
          "char_filter": [ "zero_width_spaces" ],
          "filter": [
            "truncate20_filter",
            "lowercase",
            "arabic_normalization",
            "persian_normalization",
            "persian_stop"          
          ]
        },

but not working

plz help me

**Comment by marevol** [comment]
Did you re-create fess index?

**Comment by MajidSafari** [comment]
yes

**Comment by marevol** [comment]
Hmm...
This is not Fess problem.
To solve it, I think that enough knowledge for Lucene analysis is needed...

**Comment by MajidSafari** [comment]
@marevol  

i cannot solve  this , plz help to me ,

sample code or something more  ,

**Comment by marevol** [comment]
I have no time to support a specific issue other than Fess...
If you need a quick support, please contact Commercial Support: http://www.n2sm.net/en/support/fess_support.html

**Comment by MajidSafari** [comment]
Ok tnx

**Comment by MajidSafari** [comment]
i solved 
by 

> "persian_analyzer": {
          "type": "custom",
          "tokenizer": "unigram_synonym_tokenizer",
          "char_filter": [ "zero_width_spaces" ],
          "filter": [
            "truncate20_filter",
            "lowercase",
            "arabic_normalization",
            "persian_normalization",
            "persian_stop"
          ]
        },

exam => online test its work 

but online test => exam  not working

i try to solve this , tanx
