### ISSUE TITLE
Go link in json

### ISSUE THREAD

**Issue by MajidSafari** [codelibs/fess#856]
when use json result  and Go link 

/go/?rt=0&docId=2260983c3fe44002afd8fc13fa48874c&queryId=61205333c3a64b268e3c914a50d04fe7

userSessionId is null so click log not loging

`
final String userSessionId = userInfoHelper.getUserCode();
            if (userSessionId != null) `

**Comment by marevol** [comment]
userSessionId requires HTTP session.

**Comment by MajidSafari** [comment]
when use json , not exist userSessionId  in json result like queryId

**Comment by MajidSafari** [comment]
@marevol help me ??

**Comment by marevol** [comment]
This issue will be fixed in next release.
userCode parameter will be added.

**Comment by MajidSafari** [comment]
tanx @marevol
