### ISSUE TITLE
Dashboard does not display when using proxy

### ISSUE THREAD

**Issue by asiral** [codelibs/fess#865]
When running Apache as a proxy for FESS (see https://github.com/codelibs/fess/issues/834), everything works fine except for the dashboard (/admin/dashboard/).  The HTML is loaded as text on the page.  The only difference I can see in the request is that with Apache, a Content-type header of text/plain is sent and that without Apache, no Content-type is sent.  This is for Dashboard template (e.g. /admin/server_25d8e0d0e93e48de99d371c696d634ac/_plugin/kopf/).

In the meantime, I have added the directive: DefaultType text/html and this resolves the problem.  But I believe the larger issue may be that the original content-type is not communicated in the response from FESS when Apache proxies a request.

**Comment by marevol** [comment]
The workaround is 

    DefaultType None
