### ISSUE TITLE
ElasticCloud

### ISSUE THREAD

**Issue by huntercarter** [codelibs/fess#876]
Hi, is it possible to use FESS with an ElasticSearch server _other_ than the bundled one? I would love to use Fess on ElasticCloud (https://www.elastic.co/cloud) however I don't see any options for indexing to a remote install of ElasticSearch. I thought perhaps it would be possible to do this by dumping a backup to S3, however it appears that the repository creation tools under "snapshot" are also not working. 

Any advice would be appreciated. Thanks!

**Comment by marevol** [comment]
>  is it possible to use FESS with an ElasticSearch server other than the bundled one?

Yes. Please see http://fess.codelibs.org/10.3/install/install.html
We recommend remote elasticsearch cluster for production use.

For ElasticCloud, I'm not sure if it works with Fess because Fess requires Elasticsearch plugins.

>  it would be possible to do this by dumping a backup to S3

Bundled elasticsearch does not contain S3 plugin.

**Comment by huntercarter** [comment]
Which plugins does FESS require? ElasticCloud supports several:
https://www.elastic.co/guide/en/cloud/current/official-plugins.html

If you do not recommend ElasticCloud, what kind of deployment do you recommend? AWS?

**Comment by marevol** [comment]
Any environments are okay if plugins are able to be installed.

**Comment by huntercarter** [comment]
@marevol  thanks for the quick responses. I have another follow up question for you:

I am trying to set up FESS to communicate with a local ElasticSearch. I installed via the .zip in the link you provided, my ElasticSearch instance is running on default ports, and I added this bit from the link you provided:

> For Unix environment, they are in fess-<version>/bin/fess.in.sh.

```
ES_HTTP_URL=http://localhost:9200
ES_TRANSPORT_URL=localhost:9300
FESS_DICTIONARY_PATH=/var/lib/elasticsearch/config/
```

The server fails to start. I suspect the path in the DOCS may not be relevant to my directory structure. I am on Mac OSX. Any ideas what I'm missing here?

**Comment by marevol** [comment]
Please set configsync.config_path in elasticsearch.yml

    configsync.config_path: <elasticsearch_home>/data/config

and then set FESS_DICTIONARY_PATH as below:

    FESS_DICTIONARY_PATH=<elasticsearch_home>/data/config

<elasticsearch_home> is an installed directory of elasticsearch.

**Comment by epalorleant** [comment]
Hello,
Is that possible to use FESS with a TLS secured Elasticsearch cluster ?
Thanks.
