### ISSUE TITLE
Created 0 thumbnail files

### ISSUE THREAD

**Issue by FaKod** [codelibs/fess#884]
No thumbnails are generated with default settings using Docker Version codelibs/fess:latest

Job "Thumbnail Generator" is running, but returns "Created 0 thumbnail files"

What am I doing wrong?

**Comment by marevol** [comment]
Thumbnail feature requires photomjs command.
I do not think Docker image contains it.
So, the current Docker image does not support it.
Any contribution is welcome :)

**Comment by FaKod** [comment]
ok, so there just has to be the phantomjs binary somewhere in PATH?

**Comment by marevol** [comment]
Yes.

**Comment by FaKod** [comment]
Hmm, installed it, basically using this: https://gist.github.com/ianchen06/db12a2ecc7f1218f8e7e

but no effect (things like `phantomjs hello.js` are working)
Did not restart FESS

**Comment by marevol** [comment]
Fess checks if phantomjs command exists on startup.

**Comment by FaKod** [comment]
added a [PR](https://github.com/codelibs/docker-fess/pull/3) to docker-fess
