### ISSUE TITLE
Reload synonyms_path File Dynamically

### ISSUE THREAD

**Issue by MajidSafari** [codelibs/fess#900]
hi , i use this code

how can Reload Dynamically ???

```
{
    "index" : {
        "analysis" : {
            "analyzer" : {
                "synonym" : {
                    "tokenizer" : "whitespace",
                    "filter" : ["synonym"]
               }
            },
            "filter" : {
                "synonym" : {
                    "type" : "synonym",
                    "synonyms_path" : "analysis/synonym.txt"
                }
            }
        }
    }
}
```

**Comment by marevol** [comment]
Synonym filter provided by elastic does not reload a synonym file dynamically.
Fess uses https://github.com/codelibs/elasticsearch-analysis-synonym

**Comment by MajidSafari** [comment]
i want use  "tokenizer" : "whitespace",

like 
https://github.com/bells/elasticsearch-analysis-dynamic-synonym

**Comment by marevol** [comment]
We provide "type":"synonym_filter" as TokenFilter in elasticsearch-analysis-synonym.

**Comment by MajidSafari** [comment]
tanks
