### ISSUE TITLE
sitemapindex

### ISSUE THREAD

**Issue by MajidSafari** [codelibs/fess#904]
i add this sitemap , but fess  this url add in result search
http://www.kanoon.ir/sitemap_article.xml?page=1

`<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<sitemap>
<loc>http://www.kanoon.ir/sitemap_article.xml?page=1</loc>
<lastmod>2017-02-23T00:00:00+03:30</lastmod>
</sitemap>
<sitemap>
<loc>http://www.kanoon.ir/sitemap_article.xml?page=2</loc>
<lastmod>2017-02-23T00:00:00+03:30</lastmod>
</sitemap>
</sitemapindex>`

**Comment by marevol** [comment]
The url pattern of sitemap is in rule.xml
```
<arg>"http[s]?:.*sitemap[^/]*.xml$|http[s]?:.*sitemap[^/]*.gz$|http[s]?:.*sitemap[^/]*.txt$"</arg>
```

If you want to use other urls, modify the above pattern.
