### ISSUE TITLE
fess suggestions

### ISSUE THREAD

**Issue by AdeelIlyas2014** [codelibs/fess#919]
Currently suggest? returns like:

{"response":{"version":11.1,"status":0,"result":{"took":"11","total":"3","num":"3","hits":[{"text":"cells","tags":["yahoo_buzzlog","others","lucene"],"roles":["Rguest"],"fields":["content"]},{"text":"cellsi","tags":["others"],"roles":["Rguest"],"fields":["content"]},{"text":"cells.length","tags":["others"],"roles":["Rguest"],"fields":["content"]}]}}}

I want to exclude roles field from the response. 

http://search.n2sm.co.jp/suggest?callback=jQuery21409240452003414692_1489048094096&query=cells&fields=_default%2Ccontent%2Ctitle&num=20&_=1489048094097

Please suggest how can I do it, any parameter need to etc. Regards

**Comment by marevol** [comment]
No parameter at the moment...
We will fix it in the next release.
