### ISSUE TITLE
How to reset admin password?

### ISSUE THREAD

**Issue by MichaelHierweck** [codelibs/fess#921]
How can I reset a lost admin password in FESS 10.x?

I tried to push the data from fess_user.bulk to ES:

`curl -XPUT  'http://127.0.0.1:9201/.fess_user/user/YWRtaW4=' -d '{ "password" : "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918", "surname" : "admin", "roles" : [ "YWRtaW4=", "Z3Vlc3Q=" ], "name" : "admin" }'`

The data object was updated successfully. I hoped this would reenable admin/admin. But the login still failes.

Thanks in advance.

**Comment by marevol** [comment]
Please try to upload app/WEB-INF/classes/fess_indeices/.fess_user/user.bulk on [Admin Backup page](http://fess.codelibs.org/11.0/admin/backup-guide.html).

**Comment by marevol** [comment]
Oh, you cannot login as admin... try:

    curl -XPOST localhost:9201/_bulk --data-binary @app/WEB-INF/classes/fess_indeices/.fess_user/user.bulk

**Comment by MichaelHierweck** [comment]
Thanks. Works great.
