### ISSUE TITLE
Using PHP for programming

### ISSUE THREAD

**Issue by pinhao1994** [codelibs/fess#926]
Dear Fess,

I am newbie of Fess
I want to use PHP to program my user website
currently, I understand that I could receive search result by "http://Fess.example/json/?q=word"
and getting suggest by "http://Fess.example/suggest/?query=word&field="_default,content,title"&num=10"

I am wondering that how can I get "popular words" in a similar way
Is there any parameter for me to set in the URL

Moreover, it seems that Additional Word and Bad Word do not work well
for example I have "As soon as possible", "ASAP","{role}guest,{role}admin,{user}admin" ,"" , "100.0" in Additional Word, but when I type ASAP, I cannot get "As soon as possible"
besides, I have some stop words such as "about", "am" in Bad Word, but the suggest still show out those words

thx,
hope to hear ur reply ASAP

**Comment by marevol** [comment]
> I am wondering that how can I get "popular words" in a similar way

    http://<Server Name>/json/?type=popularword

> for example I have "As soon as possible", "ASAP","{role}guest,{role}admin,{user}admin" ,"" , "100.0" in Additional Word, but when I type ASAP, I cannot get "As soon as possible"

The added word may be normalized. It will be improved in next release.

**Comment by pinhao1994** [comment]
thank u very much for ur answer
God Bless Fess !!!!
