### ISSUE TITLE
org.codelibs.fess.crawler.exception.MaxLengthExceededException

### ISSUE THREAD

**Issue by jdeathe** [codelibs/fess#929]
Where can the MaxLength configuration value be set? I want to allow for larger PDF documents in this instance.

**Comment by marevol** [comment]
The configuration is in app/WEB-INF/classes/crawler/contentlength.xml:

    <property name="defaultMaxLength">10485760</property>

**Comment by jdeathe** [comment]
Thanks @marevol :)
