### ISSUE TITLE
Backup Support

### ISSUE THREAD

**Issue by AdeelIlyas2014** [codelibs/fess#933]
Hi,

I am wondering, does fess support any backup support for the indexed data? /es. 

Like I want to keep last 7 days backup of indexed data (fess). So I could restore to any required. 

Please confirm.

Please share best ways for doing this with fess indexed data.

Thank you.

**Comment by marevol** [comment]
For Index backup, see [Elasticsearch Snapshot/Restore](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/modules-snapshots.html).
Index name for Fess is fess.yyyyMMdd.
