### ISSUE TITLE
Access Token Usage

### ISSUE THREAD

**Issue by jdeathe** [codelibs/fess#936]
- I have created a role named `internal`.
- I have a Label with Permissions: `{role}internal`.
- I have a Web Crawler with Permissions: `{role}internal` that has added content to the index. Documents in the index have the role `Rinternal` and have been assigned the appropriate Labels.
- I have created an Access Token with Name `internal`, Permissions `{role}internal`, Parameter Name `internal_token`, Expired `2018-01-01T00:00:00` and Token `l8aOrF3pzXKJOxaJgpgekE7QGWvo1SEFMhb8IukuMNLU3eDAdxfM30sGhTMI`.

How can I use this token to query the API?

I thought it would be something like:
```
curl -H "Authorization: internal_token l8aOrF3pzXKJOxaJgpgekE7QGWvo1SEFMhb8IukuMNLU3eDAdxfM30sGhTMI" http://localhost:8080/json/\?q\=test
```

**Comment by marevol** [comment]
Could you try:

    curl -H "Authorization: l8aOrF3pzXKJOxaJgpgekE7QGWvo1SEFMhb8IukuMNLU3eDAdxfM30sGhTMI" http://localhost:8080/json/\?q\=test

**Comment by jdeathe** [comment]
@marevol - Yes! That works.
