### ISSUE TITLE
configure with mod_osso / Single Signon

### ISSUE THREAD

**Issue by adamclayton** [codelibs/fess#940]
Can Fess can be configured to work with Apache OHS/mod_osso and Oracle Single Signon so that logins will bypass the default Fess login page while showing the userid of the SSO account will show in the top right corner?

I'm guessing I will need to setup a reverse proxy in Apache OHS but still need to work out on how to pass the cookie info across to Fess.

**Comment by marevol** [comment]
Fess does not support mod_osso at the moment.
To support it, creating [SsoAuthenticator](https://github.com/codelibs/fess/blob/master/src/main/java/org/codelibs/fess/sso/SsoAuthenticator.java) implementation for mod_osso, I think it works.
