### ISSUE TITLE
API to add new crawlers?

### ISSUE THREAD

**Issue by comschmid** [codelibs/fess#942]
I tested Fess 11.0.1 (well done!) and looked through the documentation but didn't find an answer to my question: is there an API available or planned that programmatically allows to add/remove crawlers?

Thank you for any pointers!

**Comment by marevol** [comment]
Admin API will be introduced in Fess 11.1.
For current versions, configurations are in .fess_config index of elasticsearch.
To modify configuration with API, elasticsearch REST API is available.

**Comment by comschmid** [comment]
Great, looking forward to Fess 11.1! 
Thank you for this wonderful piece of software!

**Comment by abolotnov** [comment]
I have the same question for version 12.4 - looks like the admin API is not yet available and the crawler configuration is no longer stored in elastic index? Is there a way to manage crawlers programmatically in 12.4? Thanks!

**Comment by marevol** [comment]
It's available in Fess 12.
See [I/F doc](https://fess.codelibs.org/lastadoc-fess.html#.api.admin.scheduler.::index).
