### ISSUE TITLE
Installed following the installation guide, but no response from http://localhost:8080/

### ISSUE THREAD

**Issue by riceming** [codelibs/fess#954]
Installed both Elasticsearch 5.3 and Fess 11.0 follow the guide 
http://fess.codelibs.org/11.0/install/install.html

Elasticsearch seems working fine with correct response from http://localhost:9200/

But Fess is not responding http://localhost:8080/

/var/log/fess/fess.log has the below lines
2017-03-30 14:17:00,123 [localhost-startStop-1] ERROR Failed to initialize Lasta Di.
org.lastaflute.di.exception.ContainerInitFailureException: Look! Read the message below.
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
Failed to initialize the container.

[Path]
esclient.xml

[Namespace]
null

[Included by]
esflute_config.xml
esflute_user.xml
esflute_log.xml
* * * * * * * * * */

what is the cause of the problem? and how to fix it?

**Comment by marevol** [comment]
Fess 11.0 supports Elasticsearch 5.0 to 5.2.
Elasticsearch 5.3 will be supported in Fess 11.1.

**Comment by riceming** [comment]
reinstalled elasticsearch 5.2.0 and fess 11.0.1 , still no luck.

any hints?

**Comment by marevol** [comment]
What is the stacktraces?

**Comment by riceming** [comment]
only these lines in server_0.log

Mar 30, 2017 3:13:53 PM org.dbflute.tomcat.logging.BootLogger info
INFO: ...Booting the Tomcat: port=8080 contextPath=
Mar 30, 2017 3:13:53 PM org.dbflute.tomcat.logging.BootLogger info
INFO: ...Reflecting configuration to server: tomcat_config.properties
Mar 30, 2017 3:13:53 PM org.dbflute.tomcat.logging.BootLogger info
INFO:  tomcat.URIEncoding = UTF-8
Mar 30, 2017 3:13:53 PM org.dbflute.tomcat.logging.BootLogger info
INFO:  tomcat.useBodyEncodingForURI = true
Mar 30, 2017 3:13:54 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-8080"]
Mar 30, 2017 3:13:54 PM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
INFO: Using a shared selector for servlet write/read
Mar 30, 2017 3:13:54 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Tomcat
Mar 30, 2017 3:13:54 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/8.5.6
Mar 30, 2017 3:13:54 PM org.dbflute.tomcat.logging.BootLogger info
INFO: ...Initializing webapp of default web.xml with JSP (the servlet found)
Mar 30, 2017 3:13:54 PM org.apache.catalina.startup.ContextConfig getDefaultWebXmlFragment
INFO: No global web.xml found
Mar 30, 2017 3:13:55 PM org.apache.jasper.servlet.TldScanner scanJars
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Mar 30, 2017 3:24:11 PM org.apache.catalina.util.SessionIdGeneratorBase createSecureRandom
INFO: Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [616,521] milliseconds.
Mar 30, 2017 3:24:32 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler [http-nio-8080]
Mar 30, 2017 3:24:32 PM org.dbflute.tomcat.logging.BootLogger info
INFO: Boot successful: url -> http://localhost:8080

fess.log is empty, strange

where should I look up for more debug info?

**Comment by marevol** [comment]
> INFO: Boot successful: url -> http://localhost:8080

It seems to work...
Stopping Java processes for both Fess and Elasticsearch and deleting log files, and then starts Elasticsearch and Fess.

**Comment by riceming** [comment]
thanks marevol, it worked.  it was my fault, tomcat takes time to bootup, after a while, i can access to the dashboard.  thanks a lot again.
