### ISSUE TITLE
Error reading link without filename

### ISSUE THREAD

**Issue by riceming** [codelibs/fess#956]
When a web page (http://www.abc.com/test.php) consists a link without filename like <a href="?year=2016">2016</a>, normal browser will able to append the current url (http://www.abc.com/test.php?year=2016), but fess crawler wont (http://www.abc.com/?year=2016)

Hope this will be fixed in next version.

**Comment by marevol** [comment]
Fess crawls links for <a> tags, could you check if <a> tag is correct?

**Comment by riceming** [comment]
Let me rewrite my question, forgot to style the code.

For a webpage (http://www.abc.com/test.php), if there is a link in page:
`<a href="?year=2016">2016</a>`
Normal browser will prepend the filename test.php and open as http://www.abc.com/test.php?year=2016

But Fess crawler will not prepend the filename and open as http://www.abc.com/?year=2016
which is not the correct url

**Comment by marevol** [comment]
It's not reproduced...
Putting `<a href="?abc=123">?abc=123</a>`, `http://...?abc=123` is crawled.
Does test.php contain <link rel="canonical"... ?

**Comment by riceming** [comment]
No, the page does not have canonical value

**Comment by riceming** [comment]
tested with <link rel="canonical" href="http://www.abc.com/test.php">

`<html>
<head>
	<link rel="canonical" href="http://www.abc.com/test.php">
</head>
<body>

<a href="?year=2016">2016</a>
<a href="?year=2015">2015</a>
<a href="?year=2014">2014</a>
<a href="?year=2013">2013</a>
</body>
</html>
`

still crawling http://www.abc.com/?year=2016, not http://www.abc.com/test.php?year=2016

**Comment by marevol** [comment]
If "http://www.abc.com/test.php?year=2016" page contains <link rel="canonical"..., the page is not indexed. To disable canonical attribute, set the following setting to empty in fess_config.properties.

    crawler.document.html.cannonical.xpath=
