### ISSUE TITLE
Crawling urls that include space characters?

### ISSUE THREAD

**Issue by jbogal** [codelibs/fess#982]
Will FESS crawl and index a url that contains a space character? Thank you for your time.

**Comment by marevol** [comment]
A space character is %20.

**Comment by jbogal** [comment]
Thank you for the reply.
Yes, in a properly-escaped url, a space character will be replaced with %20. However, will FESS crawl urls not have not been properly escaped (or urlencoded)? Many urls in the pages I'm trying to crawl and index have not been properly escaped.

**Comment by marevol** [comment]
Please check fess-crawler.log. Crawled urls are listed.

**Comment by jbogal** [comment]
According to fess-crawler.log, there are ignored urls that have unencoded spaces in them. However, they could be ignored for other reasons, because the log does not say why they were ignored.
Is there a way to make fess crawl urls that contain unencoded spaces, and if so, how?
Thanks again.

**Comment by marevol** [comment]
Fess ignores url with unencoded space characters in href attribute as an invalid url.
It will be supported in next release.

**Comment by jbogal** [comment]
Thank you very much for the reply, and thank you for adding this feature.
