### ISSUE TITLE
Programmatically updating search results

### ISSUE THREAD

**Issue by micakovic** [codelibs/fess#983]
When performing search queries in Fess web app, results are built with href links that look like this (example values):
```
<a class="link" href="/go/?rt=1491302202658&amp;docId=c684b94fac6b42c4b01dbfa7e1c046e2&amp;queryId=be33a1e17ced43c1b236d1d37e8c59a7&amp;order=0" data-uri="..." data-id="c684b94fac6b42c4b01dbfa7e1c046e2" data-order="0">...</a>
```
These values can be obtained from the response object when performing json queries:
```
docId
queryId
data-order
```
These are not part of the response object:
```
rt
data-id
```
In order to increase scoring when building custom views which are not part of the Fess user interface, one would have to construct build links using the same scheme, right? Clicking on those links would take the user to the Fess server, then immediately redirect to the requested page, while other bits of the business logic such as increasing the score value for the clicked link are performed by Fess. If this is correct, how can the 'rt' field, which seems to be obligatory, be obtained when working with json?

Alternatively, is there another way of programmatically updating the backend with the number of clicks, or the number of likes, so that clicks on interfaces which are independent of the Fess web app are also accounted for?

**Comment by marevol** [comment]
data-id is docId.
rt is query request time(unix time), it means when do you send the query, so it's managed in your application.

Currently, click count is one of sort orders, and it does not affect scoring. (but it might be changed in the future release)

click count is in fess.YYYYMMDD index. To modify it, please send update requests to elasticsearch.

**Comment by marevol** [comment]
It might be implemented as one of Admin API in Fess 11.1...

**Comment by efridge** [comment]
I'd love to see this feature as well.  We are adapting FESS to be a site search and I'd like to see the user click actions able to feed back into the search engine through the API.  This way, the popularity of a document on our site can be used to influence its relevance.

**Comment by marevol** [comment]
It will be in Fess 11.2...

**Comment by micakovic** [comment]
I'm curious: did this feature make it into 11.2 or 11.2.1?

**Comment by marevol** [comment]
[Admin API](https://github.com/codelibs/fess/blob/master/src/main/java/org/codelibs/fess/app/web/api/admin/searchlist/ApiAdminSearchlistAction.java) supports it, but there is no document at the moment...
