### ISSUE TITLE
Searching by field

### ISSUE THREAD

**Issue by qmaxquique** [codelibs/fess#989]
Perhaps this is a silly question, but how do I search by field? 

For instance, I want to narrow down my searches by host/site, I was trying to do this:
`curl http://localhost:8081/json -d"q=about&facet.field=site&facet.query=\"www.example.com\""`

But l get "Invalid facet field: site"

Thanks!

**Comment by marevol** [comment]
Supported fields are [here](https://github.com/codelibs/fess/blob/fess-11.0.1/src/main/java/org/codelibs/fess/helper/QueryHelper.java#L205). (site is not in that as default)
To add site, modify fess_config.properties as below:

    query.additional.facet.fields=site

**Comment by qmaxquique** [comment]
Thank you!
